//! Arabic. Right to left; Latin digits, as CLDR's default for `ar`. No short
//! vowels or shadda: the atlases bake no combining marks. Labels have no case.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "حطم الكون",
        ContinueJourney => "متابعة الرحلة",
        NewJourney => "رحلة جديدة",
        SectorSelect => "اختيار القطاع",
        ContinueDetail => "{0} · {1}",
        StatMedals => "الميداليات",
        StatBest => "الأفضل",
        ActionServe => "إطلاق",
        ActionRelease => "إفلات",
        ActionSelect => "اختيار",
        ActionResume => "استئناف",
        ActionBack => "رجوع",
        Fullscreen => "ملء الشاشة",
        SectorsHeading => "القطاعات",
        PracticeNote => "جولات التدريب لا تغير رحلتك",
        MedalClear => "اجتياز",
        MedalClean => "بلا خسارة",
        MedalSwift => "سريع",
        PlaySector => "العب القطاع {0}",
        UnlockHint => "أكمل القطاع {0} لفتحه",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · القطاع {1}",
        Paused => "إيقاف مؤقت",
        RetrySector => "إعادة القطاع",
        MainMenu => "القائمة الرئيسية",
        JourneyComplete => "اكتملت الرحلة",
        OneMoreOrbit => "مدار آخر؟",
        StatPoints => "النقاط",
        SectorClear => "اكتمل القطاع",
        StatTime => "الوقت",
        StatBonus => "مكافأة",
        StatChain => "السلسلة",
        ExtraLife => "اكتمل الفصل · +1 حياة",
        NextSector => "القطاع التالي",
        BackToSectors => "العودة إلى القطاعات",
        SaveFailed => "تعذر حفظ التقدم",
        PerfTitle => "الأداء / المعالج",
        HelpResume => "تابع من حيث توقفت",
        HelpRetry => "ابدأ من نقطة حفظ القطاع",
        HelpMainMenu => "رحلتك محفوظة",
        HelpSectors => "تدرب على أي قطاع مفتوح",
        HelpNewJourney => "ابدأ من القطاع 01 · الميداليات تبقى",
        Settings => "الإعدادات",
        HelpSettings => "الصوت، العرض، اللغة",
        SettingSound => "الصوت",
        SettingVolume => "مستوى الصوت",
        SettingDisplay => "العرض",
        SettingLanguage => "اللغة",
        DisplayWindow => "نافذة",
        LanguageSystem => "النظام",
        ActionAdjust => "ضبط",
        KeySpace => "مسافة",
        KeyEsc => "Esc",
        SectorsOf => "القطاعات: {0} من {1}",
        TargetBest => "{0} · الأفضل {1}",
        LifeGained => "+1 حياة",
        PresenceMenus => "في القوائم",
        PresenceJourney => "القطاع {0} · {1}",
        PresencePractice => "يتدرب في القطاع {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "الفجر",
            Chapter::BlueHour => "الساعة الزرقاء",
            Chapter::Afterlight => "الشفق",
        },
        PowerName(p) => match p {
            Power::Wide => "عريض",
            Power::Slow => "بطيء",
            Power::Multi => "كرات متعددة",
            Power::Anchor => "مرساة",
            Power::Phase => "طور",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("متابعة"),
        UnlockHint => Some("مقفل"),
        RetrySector => Some("إعادة"),
        MainMenu => Some("القائمة"),
        NewJourney => Some("جديدة"),
        SectorSelect => Some("القطاعات"),
        NextSector => Some("التالي"),
        BackToSectors => Some("القطاعات"),
        Settings => Some("خيارات"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("استئناف"),
        PlaySector => Some("العب {0}"),
        ActionServe => Some("إطلاق"),
        ActionRelease => Some("إفلات"),
        ActionSelect => Some("اختيار"),
        ActionBack => Some("رجوع"),
        ActionAdjust => Some("ضبط"),
        StatBest => Some("الأفضل"),
        StatMedals => Some("ميداليات"),
        SectorsHeading => Some("القطاعات"),
        SaveFailed => Some("لم يحفظ"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("مسافة"),
        HelpResume => Some("عودة إلى اللعب"),
        HelpRetry => Some("من نقطة الحفظ"),
        HelpMainMenu => Some("محفوظة"),
        HelpSectors => Some("تدريب القطاعات"),
        HelpNewJourney => Some("من القطاع 01"),
        HelpSettings => Some("الصوت، العرض"),
        SettingSound => Some("الصوت"),
        SettingVolume => Some("الصوت"),
        SettingDisplay => Some("العرض"),
        SettingLanguage => Some("اللغة"),
        DisplayWindow => Some("نافذة"),
        Fullscreen => Some("كاملة"),
        LanguageSystem => Some("النظام"),
        ExtraLife => Some("+1 حياة"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("القطاع {1}"),
        JourneyComplete => Some("اكتملت"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "الضوء الأول",
    "أقمار صناعية",
    "انسياب",
    "رنين",
    "منشور",
    "تداخل",
    "التيار الساحب",
    "طلوع القمر",
    "وهج الغروب",
    "اختلاف المنظر",
    "مستعر أعظم",
    "العودة",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "الضوء الأول",
    "أقمار",
    "انسياب",
    "رنين",
    "منشور",
    "تداخل",
    "التيار",
    "القمر",
    "الوهج",
    "المنظر",
    "مستعر أعظم",
    "العودة",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} عريض و{icon:slow} بطيء: التقط الكبسولات المتساقطة",
    "{icon:anchor} مرساة: التقط الكرة، صوب، ثم أطلقها",
    "النوى الكهرمانية: كل انفجار يصل إلى جيرانه الأربعة",
    "النوى المتجاورة تنقل التفاعل",
    "{icon:multi} كرات متعددة: ثلاث كرات، فتحة واحدة",
    "افتح طريقا عبر خطي المرحلات",
    "اخترق الجيوب خلف الدروع",
    "اتبع المرحل حول المركز المفتوح",
    "{icon:phase} طور: ثلاث ملامسات للطوب بلا ارتداد",
    "اخترق القشرة ثم أشعل المسار الداخلي",
    "التقط كرة عائدة بينما تواصل الكرات الأخرى",
    "مدار أخير: اجعل كل فتحة مهمة",
];
