//! Bulgarian. Informal *ти*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Разбий космоса",
        ContinueJourney => "Продължи пътешествието",
        NewJourney => "Ново пътешествие",
        SectorSelect => "Избор на сектор",
        ContinueDetail => "{0} · {1}",
        StatMedals => "МЕДАЛИ",
        StatBest => "РЕКОРД",
        ActionServe => "Старт",
        ActionRelease => "Пусни",
        ActionSelect => "Избери",
        ActionResume => "Продължи",
        ActionBack => "Назад",
        Fullscreen => "Цял екран",
        SectorsHeading => "Сектори",
        PracticeNote => "Тренировките не променят пътешествието ти",
        MedalClear => "ПРЕМИНАТ",
        MedalClean => "БЕЗУПРЕЧЕН",
        MedalSwift => "БЪРЗ",
        PlaySector => "Играй сектор {0}",
        UnlockHint => "Премини сектор {0}, за да отключиш",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · СЕКТОР {1}",
        Paused => "Пауза",
        RetrySector => "Сектора отново",
        MainMenu => "Главно меню",
        JourneyComplete => "Пътят завърши",
        OneMoreOrbit => "Още една орбита?",
        StatPoints => "ТОЧКИ",
        SectorClear => "Секторът е преминат",
        StatTime => "ВРЕМЕ",
        StatBonus => "БОНУС",
        StatChain => "ВЕРИГА",
        ExtraLife => "Главата завърши · +1 живот",
        NextSector => "Следващ сектор",
        BackToSectors => "Към секторите",
        SaveFailed => "Напредъкът не можа да се запази",
        PerfTitle => "Производителност / CPU",
        HelpResume => "Продължи оттам, където спря",
        HelpRetry => "Започни от контролната точка на сектора",
        HelpMainMenu => "Пътешествието ти е запазено",
        HelpSectors => "Тренирай във всеки отворен сектор",
        HelpNewJourney => "Отначало от сектор 01 · медалите остават",
        Settings => "Настройки",
        HelpSettings => "Звук, екран, език",
        SettingSound => "Звук",
        SettingVolume => "Сила на звука",
        SettingDisplay => "Екран",
        SettingLanguage => "Език",
        DisplayWindow => "Прозорец",
        LanguageSystem => "Системен",
        ActionAdjust => "Промени",
        KeySpace => "Интервал",
        KeyEsc => "Esc",
        SectorsOf => "{0} от {1} сектора",
        TargetBest => "{0} · рекорд {1}",
        LifeGained => "+1 живот",
        PresenceMenus => "В менютата",
        PresenceJourney => "Сектор {0} · {1}",
        PresencePractice => "Тренира сектор {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ЗОРА",
            Chapter::BlueHour => "СИН ЧАС",
            Chapter::Afterlight => "ЗДРАЧ",
        },
        PowerName(p) => match p {
            Power::Wide => "ШИРОКО",
            Power::Slow => "БАВНО",
            Power::Multi => "МУЛТИТОПКА",
            Power::Anchor => "КОТВА",
            Power::Phase => "ФАЗА",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Продължи"),
        UnlockHint => Some("Заключен"),
        RetrySector => Some("Отново"),
        MainMenu => Some("Меню"),
        NewJourney => Some("Ново"),
        SectorSelect => Some("Сектори"),
        NextSector => Some("Напред"),
        BackToSectors => Some("Сектори"),
        Settings => Some("Опции"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Продължи"),
        PlaySector => Some("Играй {0}"),
        ActionServe => Some("Старт"),
        ActionRelease => Some("Пусни"),
        ActionSelect => Some("Избери"),
        ActionBack => Some("Назад"),
        ActionAdjust => Some("Промени"),
        StatBest => Some("РЕКОРД"),
        StatMedals => Some("МЕДАЛИ"),
        SectorsHeading => Some("Сектори"),
        SaveFailed => Some("Не е запазено"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Интервал"),
        HelpResume => Some("Обратно в играта"),
        HelpRetry => Some("От контролната точка"),
        HelpMainMenu => Some("Пътят е запазен"),
        HelpSectors => Some("Тренировка"),
        HelpNewJourney => Some("От сектор 01"),
        HelpSettings => Some("Звук, екран"),
        SettingSound => Some("Звук"),
        SettingVolume => Some("Сила"),
        SettingDisplay => Some("Екран"),
        SettingLanguage => Some("Език"),
        DisplayWindow => Some("Прозорец"),
        Fullscreen => Some("Цял"),
        LanguageSystem => Some("Система"),
        ExtraLife => Some("+1 живот"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("СЕКТОР {1}"),
        JourneyComplete => Some("Завърши"),
        SectorClear => Some("Преминат"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Първа светлина",
    "Спътници",
    "Въздушна следа",
    "Резонанс",
    "Призма",
    "Преливане",
    "Подводно течение",
    "Изгрев на луната",
    "Отблясък",
    "Паралакс",
    "Свръхнова",
    "Завръщане",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Първа светлина",
    "Спътници",
    "Следа",
    "Резонанс",
    "Призма",
    "Преливане",
    "Течение",
    "Луна",
    "Отблясък",
    "Паралакс",
    "Свръхнова",
    "Завръщане",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Широко и {icon:slow} Бавно: хващай падащите капсули",
    "{icon:anchor} Котва: хвани топката, прицели се и я пусни",
    "Кехлибарени ядра: всеки взрив достига четирите съседни",
    "Съседните ядра пренасят реакцията",
    "{icon:multi} Мултитопка: три топки, един отвор",
    "Отвори път през двете релейни линии",
    "Пробий до джобовете зад бронята",
    "Следвай релето около откритата среда",
    "{icon:phase} Фаза: три удара в тухли без отскок",
    "Пробий черупката, после запали вътрешния път",
    "Хвани връщаща се топка, докато другите летят",
    "Последна орбита: всеки отвор е важен",
];
