//! Czech. Informal *ty*; hints read "action: keys", which keeps them short;
//! labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Rozbij vesmír",
        ContinueJourney => "Pokračovat v cestě",
        NewJourney => "Nová cesta",
        SectorSelect => "Výběr sektoru",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDAILE",
        StatBest => "REKORD",
        ActionServe => "Podat",
        ActionRelease => "Uvolnit",
        ActionSelect => "Vybrat",
        ActionResume => "Pokračovat",
        ActionBack => "Zpět",
        Fullscreen => "Celá obrazovka",
        SectorsHeading => "Sektory",
        PracticeNote => "Tréninky tvou cestu nikdy nezmění",
        MedalClear => "SPLNĚNO",
        MedalClean => "BEZ ZTRÁT",
        MedalSwift => "RYCHLE",
        PlaySector => "Hrát sektor {0}",
        UnlockHint => "Odemkneš dokončením sektoru {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pozastaveno",
        RetrySector => "Opakovat sektor",
        MainMenu => "Hlavní nabídka",
        JourneyComplete => "Cesta dokončena",
        OneMoreOrbit => "Ještě jeden oběh?",
        StatPoints => "BODY",
        SectorClear => "Sektor dokončen",
        StatTime => "ČAS",
        StatBonus => "BONUS",
        StatChain => "ŘETĚZ",
        ExtraLife => "Kapitola dokončena · +1 život",
        NextSector => "Další sektor",
        BackToSectors => "Zpět k sektorům",
        SaveFailed => "Postup se nepodařilo uložit",
        PerfTitle => "Výkon / CPU",
        HelpResume => "Pokračuj od místa přerušení",
        HelpRetry => "Znovu od kontrolního bodu sektoru",
        HelpMainMenu => "Tvá cesta je uložena",
        HelpSectors => "Trénuj kterýkoli otevřený sektor",
        HelpNewJourney => "Znovu od sektoru 01 · medaile zůstanou",
        Settings => "Nastavení",
        HelpSettings => "Zvuk, obraz, jazyk",
        SettingSound => "Zvuk",
        SettingVolume => "Hlasitost",
        SettingDisplay => "Obraz",
        SettingLanguage => "Jazyk",
        DisplayWindow => "Okno",
        LanguageSystem => "Systémový",
        ActionAdjust => "Upravit",
        SettingEffects => "Efekty",
        SettingContrast => "Kontrast",
        LookStandard => "Standardní",
        EffectsReduced => "Omezené",
        ContrastHigh => "Vysoký",
        KeySpace => "Mezerník",
        KeyEsc => "Esc",
        SectorsOf => "{0} z {1} sektorů",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 život",
        PresenceMenus => "V nabídkách",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Trénuje sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ÚSVIT",
            Chapter::Morning => "RÁNO",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "ZLATÁ HODINKA",
            Chapter::Afterlight => "SOUMRAK",
            Chapter::BlueHour => "MODRÁ HODINKA",
            Chapter::Eclipse => "ZATMĚNÍ",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "ŠIROKÁ",
            Power::Slow => "POMALÁ",
            Power::Multi => "MULTIMÍČEK",
            Power::Anchor => "KOTVA",
            Power::Phase => "FÁZE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Pokračovat"),
        UnlockHint => Some("Zamčeno"),
        RetrySector => Some("Znovu"),
        MainMenu => Some("Nabídka"),
        NewJourney => Some("Nová"),
        SectorSelect => Some("Sektory"),
        NextSector => Some("Další"),
        BackToSectors => Some("Sektory"),
        Settings => Some("Volby"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Dál"),
        PlaySector => Some("Hrát {0}"),
        ActionServe => Some("Podat"),
        ActionRelease => Some("Pustit"),
        ActionSelect => Some("Vybrat"),
        ActionBack => Some("Zpět"),
        ActionAdjust => Some("Změnit"),
        SettingEffects => Some("Efekty"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Běžné"),
        EffectsReduced => Some("Méně"),
        ContrastHigh => Some("Vysoký"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDAILE"),
        SectorsHeading => Some("Sektory"),
        SaveFailed => Some("Neuloženo"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Mezera"),
        HelpResume => Some("Zpět do hry"),
        HelpRetry => Some("Od kontrolního bodu"),
        HelpMainMenu => Some("Cesta uložena"),
        HelpSectors => Some("Trénink sektorů"),
        HelpNewJourney => Some("Od sektoru 01"),
        HelpSettings => Some("Zvuk, obraz"),
        SettingSound => Some("Zvuk"),
        SettingVolume => Some("Hlasitost"),
        SettingDisplay => Some("Obraz"),
        SettingLanguage => Some("Jazyk"),
        DisplayWindow => Some("Okno"),
        Fullscreen => Some("Celá"),
        LanguageSystem => Some("Systém"),
        ExtraLife => Some("+1 život"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Dokončeno"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "První světlo",
    "Unášení",
    "Obzor",
    "Záblesk",
    "Skřivan",
    "Lucerny",
    "Příliv",
    "Východ slunce",
    "Satelity",
    "Rosný bod",
    "Clona",
    "Ambit",
    "Klenák",
    "Sluneční hodiny",
    "Dírka",
    "Růžice větrů",
    "Úplav",
    "Vlákno",
    "Poledník",
    "Kaskáda",
    "Prolínání",
    "Serpentiny",
    "Slunovrat",
    "Rezonance",
    "Hranol",
    "Plástev",
    "Mořská tříšť",
    "Spodní proud",
    "Žně",
    "Kaleidoskop",
    "Tapiserie",
    "Dlouhé stíny",
    "Dosvit",
    "Kukla",
    "Geoda",
    "Paralaxa",
    "Citadela",
    "Nautilus",
    "Nešpory",
    "Supernova",
    "Východ měsíce",
    "Šero",
    "Světlo lampy",
    "Světlušky",
    "Maják",
    "Nokturno",
    "Hluboké pole",
    "Souhvězdí",
    "Polostín",
    "Metronom",
    "Koróna",
    "Syzygie",
    "Pulsar",
    "Závěrka",
    "Umbra",
    "Totalita",
    "Sluneční vítr",
    "Polární záře",
    "Stuhy",
    "Polární noc",
    "Katedrála",
    "Třpyt",
    "Singularita",
    "Návrat domů",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "První světlo",
    "Unášení",
    "Obzor",
    "Záblesk",
    "Skřivan",
    "Lucerny",
    "Příliv",
    "Slunce",
    "Satelity",
    "Rosa",
    "Clona",
    "Ambit",
    "Klenák",
    "Hodiny",
    "Dírka",
    "Růžice",
    "Úplav",
    "Vlákno",
    "Poledník",
    "Kaskáda",
    "Prolínání",
    "Serpentiny",
    "Slunovrat",
    "Rezonance",
    "Hranol",
    "Plástev",
    "Tříšť",
    "Proud",
    "Žně",
    "Kaleido",
    "Tapiserie",
    "Stíny",
    "Dosvit",
    "Kukla",
    "Geoda",
    "Paralaxa",
    "Citadela",
    "Nautilus",
    "Nešpory",
    "Supernova",
    "Měsíc",
    "Šero",
    "Lampa",
    "Světlušky",
    "Maják",
    "Nokturno",
    "Hlubina",
    "Hvězdy",
    "Polostín",
    "Metronom",
    "Koróna",
    "Syzygie",
    "Pulsar",
    "Závěrka",
    "Umbra",
    "Totalita",
    "Vítr",
    "Záře",
    "Stuhy",
    "Polární noc",
    "Katedrála",
    "Třpyt",
    "Singularita",
    "Návrat",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Široká: chyť padající kapsli",
    "{icon:slow} Pomalá: chyť ji a míček zvolní",
    "Naváděj: okraje pálky pošlou míček do stran",
    "Osamělé jiskry: pronásleduj každou",
    "Pošli míček nahoru otevřenými křídly",
    "Vyčisti každou lucernu zespodu",
    "Plav se na vlně: odrážej od bočních stěn",
    "Odštipuj slunce zespodu, řadu po řadě",
    "{icon:anchor} Kotva: chyť míček, zamiř a pusť ho",
    "Pancéřové cihly snesou dva zásahy: hlídej okraje",
    "{icon:anchor} Zamiř skrz mezeru ve zdi",
    "Jediné dveře: pošli míček na nádvoří",
    "Vyraz klenák a oblouk se otevře",
    "Čti úhly: každý stín je jeden odpal",
    "{icon:anchor} Jedna úzká dírka: drž, zamiř, pusť",
    "Každá světová strana vede k srdci",
    "Jantarová jádra: každý výbuch zasáhne čtyři sousedy",
    "Dotkni se vlákna kdekoli: hoří oběma směry",
    "Rozděl pole podél poledníku",
    "Spusť kaskádu z kteréhokoli konce",
    "Otevři cestu skrz obě řady relé",
    "Tři řady relé: každá jeden čistý odpal",
    "Prstenec hoří celý: najdi cestu k jeho okraji",
    "Sousední jádra šíří reakci dál",
    "{icon:multi} Multimíček: tři míčky, jeden průchod",
    "Jádro v každé buňce: rozlom je",
    "Tříšť všude: vypusť tři míčky",
    "Proraž se do kapes za pancířem",
    "Plné pole: {icon:multi} Multimíček ho rychle vyčistí",
    "Zrcadla všude: rozbij jednu stranu, pak její dvojče",
    "Zatáhni za jednu nit a tkanina se rozpáře",
    "Proraž podlahu a zapal dlouhou zápalnou šňůru",
    "{icon:phase} Fáze: tři zásahy cihel bez odrazu",
    "{icon:phase} Fáze proklouzne skořápkou až k jádru",
    "Rozlom geodu a její krystaly se rozsvítí",
    "Proraž skořápku, pak zapal vnitřní trasu",
    "Vstup branou, nebo skrz zeď s {icon:phase} Fází",
    "Do spirály: vnější závit se rozsvítí první",
    "Tři zvony: zazvoň na každý zespodu",
    "Chyť vracející se míček, zatímco ostatní letí",
    "Sleduj relé kolem volného středu",
    "Světlo mizí: nauč se pole, dokud můžeš",
    "Ve tmě nesou světlo míček a pálka",
    "Světlušky: jádra září i ve tmě",
    "Přejeď světlem pálky přes pobřeží",
    "Víc míčků, víc světla: {icon:multi} Multimíček",
    "Hluboké pole: každá slabá tečka je cihla",
    "Spoj hvězdy: ty jasné jsou jádra",
    "Brány slábnou v rytmu: počkej na mezeru",
    "Tik, tak: brány drží čas",
    "Koróna se otevírá v rytmu: udeř dovnitř",
    "Přízračná brána vyvzdoruje výbuch: načasuj jiskru",
    "Pulsar: rychlé údery, rychlé ruce",
    "Závěrka se na chvíli otevře: buď připraven",
    "Napůl ve stínu: strana s branami drží rytmus",
    "Zažehni slunce, dokud je měsíc pevný",
    "Vítr vane jedním směrem: pluj s ním k jádrům",
    "Závěsy světla: smeť je {icon:multi} Multimíčkem",
    "Každá stuha je přivázaná k bráně: přeřízni obě poloviny",
    "Dlouhá noc: miř podle světla, které neseš",
    "Dveřmi dovnitř a nahoru k rozetě",
    "Všechno najednou: sleduj jádra",
    "Udeř do prstence, když brány ztuhnou",
    "Poslední oběh: využij každý průchod",
];
