//! Czech. Informal *ty*; hints read "action: keys", which keeps them short;
//! labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Rozbij vesmír",
        ContinueJourney => "Pokračovat v cestě",
        NewJourney => "Nová cesta",
        SectorSelect => "Výběr sektoru",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDAILE",
        StatBest => "REKORD",
        ActionServe => "Podat",
        ActionRelease => "Uvolnit",
        ActionSelect => "Vybrat",
        ActionResume => "Pokračovat",
        ActionBack => "Zpět",
        Fullscreen => "Celá obrazovka",
        SectorsHeading => "Sektory",
        PracticeNote => "Tréninky tvou cestu nikdy nezmění",
        MedalClear => "SPLNĚNO",
        MedalClean => "BEZ ZTRÁT",
        MedalSwift => "RYCHLE",
        PlaySector => "Hrát sektor {0}",
        UnlockHint => "Odemkneš dokončením sektoru {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pozastaveno",
        RetrySector => "Opakovat sektor",
        MainMenu => "Hlavní nabídka",
        JourneyComplete => "Cesta dokončena",
        OneMoreOrbit => "Ještě jeden oběh?",
        StatPoints => "BODY",
        SectorClear => "Sektor dokončen",
        StatTime => "ČAS",
        StatBonus => "BONUS",
        StatChain => "ŘETĚZ",
        ExtraLife => "Kapitola dokončena · +1 život",
        NextSector => "Další sektor",
        BackToSectors => "Zpět k sektorům",
        SaveFailed => "Postup se nepodařilo uložit",
        PerfTitle => "Výkon / CPU",
        HelpResume => "Pokračuj od místa přerušení",
        HelpRetry => "Znovu od kontrolního bodu sektoru",
        HelpMainMenu => "Tvá cesta je uložena",
        HelpSectors => "Trénuj kterýkoli otevřený sektor",
        HelpNewJourney => "Znovu od sektoru 01 · medaile zůstanou",
        Settings => "Nastavení",
        HelpSettings => "Zvuk, obraz, jazyk",
        SettingSound => "Zvuk",
        SettingVolume => "Hlasitost",
        SettingDisplay => "Obraz",
        SettingLanguage => "Jazyk",
        DisplayWindow => "Okno",
        LanguageSystem => "Systémový",
        ActionAdjust => "Upravit",
        KeySpace => "Mezerník",
        KeyEsc => "Esc",
        SectorsOf => "{0} z {1} sektorů",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 život",
        PresenceMenus => "V nabídkách",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Trénuje sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ÚSVIT",
            Chapter::BlueHour => "MODRÁ HODINKA",
            Chapter::Afterlight => "SOUMRAK",
        },
        PowerName(p) => match p {
            Power::Wide => "ŠIROKÁ",
            Power::Slow => "POMALÁ",
            Power::Multi => "MULTIMÍČEK",
            Power::Anchor => "KOTVA",
            Power::Phase => "FÁZE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Pokračovat"),
        UnlockHint => Some("Zamčeno"),
        RetrySector => Some("Znovu"),
        MainMenu => Some("Nabídka"),
        NewJourney => Some("Nová"),
        SectorSelect => Some("Sektory"),
        NextSector => Some("Další"),
        BackToSectors => Some("Sektory"),
        Settings => Some("Volby"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Dál"),
        PlaySector => Some("Hrát {0}"),
        ActionServe => Some("Podat"),
        ActionRelease => Some("Pustit"),
        ActionSelect => Some("Vybrat"),
        ActionBack => Some("Zpět"),
        ActionAdjust => Some("Změnit"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDAILE"),
        SectorsHeading => Some("Sektory"),
        SaveFailed => Some("Neuloženo"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Mezera"),
        HelpResume => Some("Zpět do hry"),
        HelpRetry => Some("Od kontrolního bodu"),
        HelpMainMenu => Some("Cesta uložena"),
        HelpSectors => Some("Trénink sektorů"),
        HelpNewJourney => Some("Od sektoru 01"),
        HelpSettings => Some("Zvuk, obraz"),
        SettingSound => Some("Zvuk"),
        SettingVolume => Some("Hlasitost"),
        SettingDisplay => Some("Obraz"),
        SettingLanguage => Some("Jazyk"),
        DisplayWindow => Some("Okno"),
        Fullscreen => Some("Celá"),
        LanguageSystem => Some("Systém"),
        ExtraLife => Some("+1 život"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Dokončeno"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "První světlo",
    "Satelity",
    "Úplav",
    "Rezonance",
    "Hranol",
    "Prolínání",
    "Spodní proud",
    "Východ měsíce",
    "Dosvit",
    "Paralaxa",
    "Supernova",
    "Návrat domů",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "První světlo",
    "Satelity",
    "Úplav",
    "Rezonance",
    "Hranol",
    "Prolínání",
    "Proud",
    "Měsíc",
    "Dosvit",
    "Paralaxa",
    "Supernova",
    "Návrat",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Široká a {icon:slow} Pomalá: chytej padající kapsle",
    "{icon:anchor} Kotva: chyť míček, zamiř a pusť ho",
    "Jantarová jádra: každý výbuch zasáhne čtyři sousedy",
    "Sousední jádra šíří reakci dál",
    "{icon:multi} Multimíček: tři míčky, jeden průchod",
    "Otevři cestu skrz obě řady relé",
    "Proraž se do kapes za pancířem",
    "Sleduj relé kolem volného středu",
    "{icon:phase} Fáze: tři zásahy cihel bez odrazu",
    "Proraž skořápku, pak zapal vnitřní trasu",
    "Chyť vracející se míček, zatímco ostatní letí",
    "Poslední oběh: využij každý průchod",
];
