//! Danish. Informal *du*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Knus kosmos",
        ContinueJourney => "Fortsæt rejsen",
        NewJourney => "Ny rejse",
        SectorSelect => "Vælg sektor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALJER",
        StatBest => "REKORD",
        ActionServe => "Serv",
        ActionRelease => "Slip",
        ActionSelect => "Vælg",
        ActionResume => "Genoptag",
        ActionBack => "Tilbage",
        Fullscreen => "Fuld skærm",
        SectorsHeading => "Sektorer",
        PracticeNote => "Træning ændrer aldrig din rejse",
        MedalClear => "KLARET",
        MedalClean => "FEJLFRI",
        MedalSwift => "HURTIG",
        PlaySector => "Spil sektor {0}",
        UnlockHint => "Gennemfør sektor {0} for at låse op",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pause",
        RetrySector => "Prøv sektoren igen",
        MainMenu => "Hovedmenu",
        JourneyComplete => "Rejsen er fuldført",
        OneMoreOrbit => "Én bane til?",
        StatPoints => "POINT",
        SectorClear => "Sektor klaret",
        StatTime => "TID",
        StatBonus => "BONUS",
        StatChain => "KÆDE",
        ExtraLife => "Kapitel fuldført · +1 liv",
        NextSector => "Næste sektor",
        BackToSectors => "Tilbage til sektorer",
        SaveFailed => "Fremskridt kunne ikke gemmes",
        PerfTitle => "Ydeevne / CPU",
        HelpResume => "Fortsæt, hvor du slap",
        HelpRetry => "Start forfra fra sektorens checkpoint",
        HelpMainMenu => "Din rejse er gemt",
        HelpSectors => "Træn i en åben sektor",
        HelpNewJourney => "Forfra fra sektor 01 · medaljer bevares",
        Settings => "Indstillinger",
        HelpSettings => "Lyd, skærm, sprog",
        SettingSound => "Lyd",
        SettingVolume => "Lydstyrke",
        SettingDisplay => "Skærm",
        SettingLanguage => "Sprog",
        DisplayWindow => "Vindue",
        LanguageSystem => "System",
        ActionAdjust => "Justér",
        SettingEffects => "Effekter",
        SettingContrast => "Kontrast",
        LookStandard => "Standard",
        EffectsReduced => "Reduceret",
        ContrastHigh => "Høj",
        KeySpace => "Mellemrum",
        KeyEsc => "Esc",
        SectorsOf => "{0} af {1} sektorer",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 liv",
        PresenceMenus => "I menuerne",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Træner sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAGGRY",
            Chapter::BlueHour => "BLÅ TIME",
            Chapter::Afterlight => "EFTERLYS",
        },
        PowerName(p) => match p {
            Power::Wide => "BRED",
            Power::Slow => "LANGSOM",
            Power::Multi => "MULTIBOLD",
            Power::Anchor => "ANKER",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Fortsæt"),
        UnlockHint => Some("Låst"),
        RetrySector => Some("Prøv igen"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Ny"),
        SectorSelect => Some("Sektorer"),
        NextSector => Some("Næste"),
        BackToSectors => Some("Sektorer"),
        Settings => Some("Valg"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Fortsæt"),
        PlaySector => Some("Spil {0}"),
        ActionServe => Some("Serv"),
        ActionRelease => Some("Slip"),
        ActionSelect => Some("Vælg"),
        ActionBack => Some("Tilbage"),
        ActionAdjust => Some("Justér"),
        SettingEffects => Some("Effekter"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Færre"),
        ContrastHigh => Some("Høj"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDALJER"),
        SectorsHeading => Some("Sektorer"),
        SaveFailed => Some("Ikke gemt"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Mellemrum"),
        HelpResume => Some("Tilbage til spillet"),
        HelpRetry => Some("Fra checkpointet"),
        HelpMainMenu => Some("Rejsen er gemt"),
        HelpSectors => Some("Træn sektorer"),
        HelpNewJourney => Some("Fra sektor 01"),
        HelpSettings => Some("Lyd, skærm"),
        SettingSound => Some("Lyd"),
        SettingVolume => Some("Lydstyrke"),
        SettingDisplay => Some("Skærm"),
        SettingLanguage => Some("Sprog"),
        DisplayWindow => Some("Vindue"),
        Fullscreen => Some("Fuld"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 liv"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Fuldført"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Første lys",
    "Satellitter",
    "Slipstrøm",
    "Resonans",
    "Prisme",
    "Overtoning",
    "Understrøm",
    "Måneopgang",
    "Efterglød",
    "Parallakse",
    "Supernova",
    "Hjemkomst",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Første lys",
    "Satellitter",
    "Slipstrøm",
    "Resonans",
    "Prisme",
    "Overtoning",
    "Understrøm",
    "Måne",
    "Efterglød",
    "Parallakse",
    "Supernova",
    "Hjemkomst",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Bred og {icon:slow} Langsom: grib de faldende kapsler",
    "{icon:anchor} Anker: grib bolden, sigt, og slip den",
    "Ravkerner: hver eksplosion rammer de fire naboer",
    "Nabokerner fører reaktionen videre",
    "{icon:multi} Multibold: tre bolde, én åbning",
    "Åbn en vej gennem de to relælinjer",
    "Bryd ind i lommerne bag panseret",
    "Følg relæet rundt om den åbne midte",
    "{icon:phase} Fase: tre klodsramninger uden at prelle af",
    "Gennembryd skallen, og antænd så den indre rute",
    "Grib en returbold, mens de andre fortsætter",
    "En sidste bane: få hver åbning til at tælle",
];
