//! Danish. Informal *du*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Knus kosmos",
        ContinueJourney => "Fortsæt rejsen",
        NewJourney => "Ny rejse",
        SectorSelect => "Vælg sektor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALJER",
        StatBest => "REKORD",
        ActionServe => "Serv",
        ActionRelease => "Slip",
        ActionSelect => "Vælg",
        ActionResume => "Genoptag",
        ActionBack => "Tilbage",
        Fullscreen => "Fuld skærm",
        SectorsHeading => "Sektorer",
        PracticeNote => "Træning ændrer aldrig din rejse",
        MedalClear => "KLARET",
        MedalClean => "FEJLFRI",
        MedalSwift => "HURTIG",
        PlaySector => "Spil sektor {0}",
        UnlockHint => "Gennemfør sektor {0} for at låse op",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pause",
        RetrySector => "Prøv sektoren igen",
        MainMenu => "Hovedmenu",
        JourneyComplete => "Rejsen er fuldført",
        OneMoreOrbit => "Én bane til?",
        StatPoints => "POINT",
        SectorClear => "Sektor klaret",
        StatTime => "TID",
        StatBonus => "BONUS",
        StatChain => "KÆDE",
        ExtraLife => "Kapitel fuldført · +1 liv",
        NextSector => "Næste sektor",
        BackToSectors => "Tilbage til sektorer",
        SaveFailed => "Fremskridt kunne ikke gemmes",
        PerfTitle => "Ydeevne / CPU",
        HelpResume => "Fortsæt, hvor du slap",
        HelpRetry => "Start forfra fra sektorens checkpoint",
        HelpMainMenu => "Din rejse er gemt",
        HelpSectors => "Træn i en åben sektor",
        HelpNewJourney => "Forfra fra sektor 01 · medaljer bevares",
        Settings => "Indstillinger",
        HelpSettings => "Lyd, skærm, sprog",
        SettingSound => "Lyd",
        SettingVolume => "Lydstyrke",
        SettingDisplay => "Skærm",
        SettingLanguage => "Sprog",
        DisplayWindow => "Vindue",
        LanguageSystem => "System",
        ActionAdjust => "Justér",
        SettingEffects => "Effekter",
        SettingContrast => "Kontrast",
        LookStandard => "Standard",
        EffectsReduced => "Reduceret",
        ContrastHigh => "Høj",
        KeySpace => "Mellemrum",
        KeyEsc => "Esc",
        SectorsOf => "{0} af {1} sektorer",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 liv",
        PresenceMenus => "I menuerne",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Træner sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAGGRY",
            Chapter::Morning => "MORGEN",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "GYLDEN TIME",
            Chapter::Afterlight => "EFTERLYS",
            Chapter::BlueHour => "BLÅ TIME",
            Chapter::Eclipse => "FORMØRKELSE",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "BRED",
            Power::Slow => "LANGSOM",
            Power::Multi => "MULTIBOLD",
            Power::Anchor => "ANKER",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Fortsæt"),
        UnlockHint => Some("Låst"),
        RetrySector => Some("Prøv igen"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Ny"),
        SectorSelect => Some("Sektorer"),
        NextSector => Some("Næste"),
        BackToSectors => Some("Sektorer"),
        Settings => Some("Valg"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Fortsæt"),
        PlaySector => Some("Spil {0}"),
        ActionServe => Some("Serv"),
        ActionRelease => Some("Slip"),
        ActionSelect => Some("Vælg"),
        ActionBack => Some("Tilbage"),
        ActionAdjust => Some("Justér"),
        SettingEffects => Some("Effekter"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Færre"),
        ContrastHigh => Some("Høj"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDALJER"),
        SectorsHeading => Some("Sektorer"),
        SaveFailed => Some("Ikke gemt"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Mellemrum"),
        HelpResume => Some("Tilbage til spillet"),
        HelpRetry => Some("Fra checkpointet"),
        HelpMainMenu => Some("Rejsen er gemt"),
        HelpSectors => Some("Træn sektorer"),
        HelpNewJourney => Some("Fra sektor 01"),
        HelpSettings => Some("Lyd, skærm"),
        SettingSound => Some("Lyd"),
        SettingVolume => Some("Lydstyrke"),
        SettingDisplay => Some("Skærm"),
        SettingLanguage => Some("Sprog"),
        DisplayWindow => Some("Vindue"),
        Fullscreen => Some("Fuld"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 liv"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Fuldført"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Første lys",
    "Drift",
    "Horisont",
    "Glimt",
    "Lærke",
    "Lanterner",
    "Tidevand",
    "Solopgang",
    "Satellitter",
    "Dugpunkt",
    "Blænde",
    "Kloster",
    "Slutsten",
    "Solur",
    "Nålehul",
    "Vindrose",
    "Slipstrøm",
    "Glødetråd",
    "Meridian",
    "Kaskade",
    "Overtoning",
    "Hårnålesving",
    "Solhverv",
    "Resonans",
    "Prisme",
    "Vokskage",
    "Skumsprøjt",
    "Understrøm",
    "Høst",
    "Kaleidoskop",
    "Gobelin",
    "Lange skygger",
    "Efterglød",
    "Puppe",
    "Geode",
    "Parallakse",
    "Citadel",
    "Nautilus",
    "Aftensang",
    "Supernova",
    "Måneopgang",
    "Tusmørke",
    "Lampelys",
    "Ildfluer",
    "Fyrtårn",
    "Nocturne",
    "Dybfelt",
    "Stjernebillede",
    "Halvskygge",
    "Metronom",
    "Korona",
    "Syzygi",
    "Pulsar",
    "Lukker",
    "Umbra",
    "Totalitet",
    "Solvind",
    "Nordlys",
    "Bånd",
    "Polarnat",
    "Katedral",
    "Glimmer",
    "Singularitet",
    "Hjemkomst",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Første lys",
    "Drift",
    "Horisont",
    "Glimt",
    "Lærke",
    "Lanterner",
    "Tidevand",
    "Sol",
    "Satellitter",
    "Dugpunkt",
    "Blænde",
    "Kloster",
    "Slutsten",
    "Solur",
    "Nålehul",
    "Vindrose",
    "Slipstrøm",
    "Tråd",
    "Meridian",
    "Kaskade",
    "Overtoning",
    "Hårnål",
    "Solhverv",
    "Resonans",
    "Prisme",
    "Voks",
    "Skumsprøjt",
    "Understrøm",
    "Høst",
    "Kaleido",
    "Gobelin",
    "Skygger",
    "Efterglød",
    "Puppe",
    "Geode",
    "Parallakse",
    "Citadel",
    "Nautilus",
    "Aftensang",
    "Supernova",
    "Måne",
    "Tusmørke",
    "Lampelys",
    "Ildfluer",
    "Fyrtårn",
    "Nocturne",
    "Dybfelt",
    "Stjerner",
    "Halvskygge",
    "Metronom",
    "Korona",
    "Syzygi",
    "Pulsar",
    "Lukker",
    "Umbra",
    "Totalitet",
    "Solvind",
    "Nordlys",
    "Bånd",
    "Polarnat",
    "Katedral",
    "Glimmer",
    "Singularitet",
    "Hjemkomst",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Bred: grib den faldende kapsel",
    "{icon:slow} Langsom: grib den, og bolden tager det roligt",
    "Styr: battets kanter sender bolden bredt ud",
    "Enlige gnister: jag hver eneste",
    "Send bolden op ad de åbne fløje",
    "Ryd hver lanterne nedefra",
    "Rid på dønningen: spil af mod sidevæggene",
    "Hug solen væk nedefra, række for række",
    "{icon:anchor} Anker: grib bolden, sigt, og slip den",
    "Panserklodser tager to slag: pas på kanterne",
    "{icon:anchor} Sigt gennem hullet i muren",
    "Kun én dør: send bolden ind i gården",
    "Slå slutstenen ud, og buen står åben",
    "Læs vinklerne: hver skygge er et skud",
    "{icon:anchor} Ét smalt nålehul: hold, sigt, slip",
    "Hvert verdenshjørne fører til hjertet",
    "Ravkerner: hver eksplosion rammer de fire naboer",
    "Rør glødetråden et vilkårligt sted: den brænder begge veje",
    "Del banen langs meridianen",
    "Start kaskaden i begge ender",
    "Åbn en vej gennem de to relælinjer",
    "Tre relælinjer: ét rent skud til hver",
    "Ringen brænder helt: find en vej til kanten",
    "Nabokerner fører reaktionen videre",
    "{icon:multi} Multibold: tre bolde, én åbning",
    "En kerne i hver celle: knæk dem op",
    "Sprøjt overalt: slip tre bolde løs",
    "Bryd ind i lommerne bag panseret",
    "Fuld bane: {icon:multi} Multibold rydder den hurtigt",
    "Spejle overalt: bryd den ene side, så dens tvilling",
    "Træk i én tråd, og vævningen går op",
    "Bryd gennem gulvet og tænd den lange lunte",
    "{icon:phase} Fase: tre klodsramninger uden at prelle af",
    "{icon:phase} Fase glider gennem skallen til kernen",
    "Knæk en geode, og dens krystaller lyser op",
    "Gennembryd skallen, og antænd så den indre rute",
    "Ind ad porten, eller gennem muren med {icon:phase} Fase",
    "Spiral indad: den yderste vinding lyser først",
    "Tre klokker: ring på hver nedefra",
    "Grib en returbold, mens de andre fortsætter",
    "Følg relæet rundt om den åbne midte",
    "Lyset forsvinder: lær banen, mens du kan",
    "I mørket bærer din bold og dit bat lyset",
    "Ildfluer: kernerne gløder selv i mørket",
    "Fej batets lys hen over kysten",
    "Flere bolde, mere lys: {icon:multi} Multibold",
    "Dybfelt: hver svag plet er en klods",
    "Forbind stjernerne: de klare er kerner",
    "Porte blegner i takt: vent på åbningen",
    "Tik, tak: portene holder takten",
    "Koronaen åbner i takt: ram indeni",
    "En spøgelsesport ryster en eksplosion af sig: tim gnisten",
    "En pulsar: hurtige slag, hurtige hænder",
    "Lukkeren åbner et øjeblik: vær klar",
    "Halvt i skygge: portsiden holder takten",
    "Tænd solen, mens månen er fast",
    "Vinden blæser kun én vej: rid med den til kernerne",
    "Lysgardiner: fej dem væk med {icon:multi} Multibold",
    "Hvert bånd er bundet til en port: skær begge halvdele over",
    "Den lange nat: sigt efter det lys, du bærer",
    "Ind ad dørene, op til rosevinduet",
    "Alt på én gang: hold øje med kernerne",
    "Ram ringen, når portene bliver faste",
    "En sidste bane: få hver åbning til at tælle",
];
