//! German. Informal *du*, as games address players. Labels in capitals:
//! a label never contains ß, which has no capital form here; the table
//! tests check that every label is already upper case.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Zerbrich den Kosmos",
        ContinueJourney => "Reise fortsetzen",
        NewJourney => "Neue Reise",
        SectorSelect => "Sektorauswahl",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDAILLEN",
        StatBest => "BESTWERT",
        ActionServe => "Starten",
        ActionRelease => "Lösen",
        ActionSelect => "Auswählen",
        ActionResume => "Fortsetzen",
        ActionBack => "Zurück",
        Fullscreen => "Vollbild",
        SectorsHeading => "Sektoren",
        PracticeNote => "Üben verändert deine Reise nie",
        MedalClear => "GESCHAFFT",
        MedalClean => "MAKELLOS",
        MedalSwift => "FLINK",
        PlaySector => "Sektor {0} spielen",
        UnlockHint => "Zum Freischalten Sektor {0} abschließen",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pausiert",
        RetrySector => "Sektor wiederholen",
        MainMenu => "Hauptmenü",
        JourneyComplete => "Reise abgeschlossen",
        OneMoreOrbit => "Noch eine Runde?",
        StatPoints => "PUNKTE",
        SectorClear => "Sektor geschafft",
        StatTime => "ZEIT",
        StatBonus => "BONUS",
        StatChain => "KETTE",
        ExtraLife => "Kapitel abgeschlossen · +1 Leben",
        NextSector => "Nächster Sektor",
        BackToSectors => "Zurück zu den Sektoren",
        SaveFailed => "Fortschritt konnte nicht gespeichert werden",
        PerfTitle => "Leistung / CPU",
        HelpResume => "Mach da weiter, wo du warst",
        HelpRetry => "Ab dem Kontrollpunkt des Sektors neu starten",
        HelpMainMenu => "Deine Reise ist gespeichert",
        HelpSectors => "Übe jeden offenen Sektor",
        HelpNewJourney => "Neu ab Sektor 01 · Medaillen bleiben",
        Settings => "Einstellungen",
        HelpSettings => "Ton, Anzeige, Sprache",
        SettingSound => "Ton",
        SettingVolume => "Lautstärke",
        SettingDisplay => "Anzeige",
        SettingLanguage => "Sprache",
        DisplayWindow => "Fenster",
        LanguageSystem => "System",
        ActionAdjust => "Anpassen",
        KeySpace => "Leertaste",
        KeyEsc => "Esc",
        SectorsOf => "{0} von {1} Sektoren",
        TargetBest => "{0} · Bestzeit {1}",
        LifeGained => "+1 Leben",
        PresenceMenus => "Im Menü",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Übt Sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "MORGENGRAUEN",
            Chapter::BlueHour => "BLAUE STUNDE",
            Chapter::Afterlight => "ABENDGLUT",
        },
        PowerName(p) => match p {
            Power::Wide => "BREIT",
            Power::Slow => "LANGSAM",
            Power::Multi => "MULTIBALL",
            Power::Anchor => "ANKER",
            Power::Phase => "PHASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Weiter"),
        UnlockHint => Some("Gesperrt"),
        RetrySector => Some("Wiederholen"),
        MainMenu => Some("Menü"),
        NewJourney => Some("Neu"),
        SectorSelect => Some("Sektoren"),
        NextSector => Some("Weiter"),
        BackToSectors => Some("Sektoren"),
        Settings => Some("Optionen"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Weiter"),
        PlaySector => Some("Sektor {0}"),
        ActionServe => Some("Start"),
        ActionRelease => Some("Lösen"),
        ActionSelect => Some("Wählen"),
        ActionBack => Some("Zurück"),
        ActionAdjust => Some("Ändern"),
        StatBest => Some("BESTWERT"),
        StatMedals => Some("MEDAILLEN"),
        SectorsHeading => Some("Sektoren"),
        SaveFailed => Some("Nicht gespeichert"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Leer"),
        HelpResume => Some("Zurück ins Spiel"),
        HelpRetry => Some("Ab dem Kontrollpunkt"),
        HelpMainMenu => Some("Reise gespeichert"),
        HelpSectors => Some("Sektoren üben"),
        HelpNewJourney => Some("Ab Sektor 01"),
        HelpSettings => Some("Ton, Anzeige"),
        SettingSound => Some("Ton"),
        SettingVolume => Some("Lautstärke"),
        SettingDisplay => Some("Anzeige"),
        SettingLanguage => Some("Sprache"),
        DisplayWindow => Some("Fenster"),
        Fullscreen => Some("Voll"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 Leben"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Erstes Licht",
    "Satelliten",
    "Windschatten",
    "Resonanz",
    "Prisma",
    "Überblendung",
    "Sog",
    "Mondaufgang",
    "Nachglühen",
    "Parallaxe",
    "Supernova",
    "Heimkehr",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Erstes Licht",
    "Satelliten",
    "Windschatten",
    "Resonanz",
    "Prisma",
    "Blende",
    "Sog",
    "Mond",
    "Nachglühen",
    "Parallaxe",
    "Supernova",
    "Heimkehr",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Breit und {icon:slow} Langsam: Fang die fallenden Kapseln",
    "{icon:anchor} Anker: Ball fangen, zielen, dann loslassen",
    "Bernsteinkerne: Jede Explosion trifft ihre vier Nachbarn",
    "Benachbarte Kerne tragen die Kettenreaktion weiter",
    "{icon:multi} Multiball: drei Bälle, eine Öffnung",
    "Öffne einen Weg durch die beiden Relaislinien",
    "Brich in die Taschen hinter der Panzerung ein",
    "Folge dem Relais um die offene Mitte",
    "{icon:phase} Phase: drei Steintreffer ohne Abprall",
    "Durchbrich die Hülle, dann zünde den inneren Weg",
    "Fang einen Ball, während die anderen weiterfliegen",
    "Ein letzter Orbit: Jede Öffnung zählt",
];
