//! German. Informal *du*, as games address players. Labels in capitals:
//! a label never contains ß, which has no capital form here; the table
//! tests check that every label is already upper case.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Zerbrich den Kosmos",
        ContinueJourney => "Reise fortsetzen",
        NewJourney => "Neue Reise",
        SectorSelect => "Sektorauswahl",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDAILLEN",
        StatBest => "BESTWERT",
        ActionServe => "Starten",
        ActionRelease => "Lösen",
        ActionSelect => "Auswählen",
        ActionResume => "Fortsetzen",
        ActionBack => "Zurück",
        Fullscreen => "Vollbild",
        SectorsHeading => "Sektoren",
        PracticeNote => "Üben verändert deine Reise nie",
        MedalClear => "GESCHAFFT",
        MedalClean => "MAKELLOS",
        MedalSwift => "FLINK",
        PlaySector => "Sektor {0} spielen",
        UnlockHint => "Zum Freischalten Sektor {0} abschließen",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pausiert",
        RetrySector => "Sektor wiederholen",
        MainMenu => "Hauptmenü",
        JourneyComplete => "Reise abgeschlossen",
        OneMoreOrbit => "Noch eine Runde?",
        StatPoints => "PUNKTE",
        SectorClear => "Sektor geschafft",
        StatTime => "ZEIT",
        StatBonus => "BONUS",
        StatChain => "KETTE",
        ExtraLife => "Kapitel abgeschlossen · +1 Leben",
        NextSector => "Nächster Sektor",
        BackToSectors => "Zurück zu den Sektoren",
        SaveFailed => "Fortschritt konnte nicht gespeichert werden",
        PerfTitle => "Leistung / CPU",
        HelpResume => "Mach da weiter, wo du warst",
        HelpRetry => "Ab dem Kontrollpunkt des Sektors neu starten",
        HelpMainMenu => "Deine Reise ist gespeichert",
        HelpSectors => "Übe jeden offenen Sektor",
        HelpNewJourney => "Neu ab Sektor 01 · Medaillen bleiben",
        Settings => "Einstellungen",
        HelpSettings => "Ton, Anzeige, Sprache",
        SettingSound => "Ton",
        SettingVolume => "Lautstärke",
        SettingDisplay => "Anzeige",
        SettingLanguage => "Sprache",
        DisplayWindow => "Fenster",
        LanguageSystem => "System",
        ActionAdjust => "Anpassen",
        SettingEffects => "Effekte",
        SettingContrast => "Kontrast",
        LookStandard => "Standard",
        EffectsReduced => "Reduziert",
        ContrastHigh => "Hoch",
        KeySpace => "Leertaste",
        KeyEsc => "Esc",
        SectorsOf => "{0} von {1} Sektoren",
        TargetBest => "{0} · Bestzeit {1}",
        LifeGained => "+1 Leben",
        PresenceMenus => "Im Menü",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Übt Sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "MORGENGRAUEN",
            Chapter::Morning => "MORGEN",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "GOLDENE STUNDE",
            Chapter::Afterlight => "ABENDGLUT",
            Chapter::BlueHour => "BLAUE STUNDE",
            Chapter::Eclipse => "FINSTERNIS",
            Chapter::Aurora => "POLARLICHT",
        },
        PowerName(p) => match p {
            Power::Wide => "BREIT",
            Power::Slow => "LANGSAM",
            Power::Multi => "MULTIBALL",
            Power::Anchor => "ANKER",
            Power::Phase => "PHASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Weiter"),
        UnlockHint => Some("Gesperrt"),
        RetrySector => Some("Wiederholen"),
        MainMenu => Some("Menü"),
        NewJourney => Some("Neu"),
        SectorSelect => Some("Sektoren"),
        NextSector => Some("Weiter"),
        BackToSectors => Some("Sektoren"),
        Settings => Some("Optionen"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Weiter"),
        PlaySector => Some("Sektor {0}"),
        ActionServe => Some("Start"),
        ActionRelease => Some("Lösen"),
        ActionSelect => Some("Wählen"),
        ActionBack => Some("Zurück"),
        ActionAdjust => Some("Ändern"),
        StatBest => Some("BESTWERT"),
        StatMedals => Some("MEDAILLEN"),
        SectorsHeading => Some("Sektoren"),
        SaveFailed => Some("Nicht gespeichert"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Leer"),
        HelpResume => Some("Zurück ins Spiel"),
        HelpRetry => Some("Ab dem Kontrollpunkt"),
        HelpMainMenu => Some("Reise gespeichert"),
        HelpSectors => Some("Sektoren üben"),
        HelpNewJourney => Some("Ab Sektor 01"),
        HelpSettings => Some("Ton, Anzeige"),
        SettingSound => Some("Ton"),
        SettingVolume => Some("Lautstärke"),
        SettingDisplay => Some("Anzeige"),
        SettingLanguage => Some("Sprache"),
        DisplayWindow => Some("Fenster"),
        Fullscreen => Some("Voll"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 Leben"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        SettingEffects => Some("Effekte"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Wenig"),
        ContrastHigh => Some("Hoch"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Erstes Licht",
    "Dahintreiben",
    "Horizont",
    "Glimmen",
    "Lerche",
    "Laternen",
    "Gezeiten",
    "Sonnenaufgang",
    "Satelliten",
    "Taupunkt",
    "Apertur",
    "Kreuzgang",
    "Schlussstein",
    "Sonnenuhr",
    "Nadelöhr",
    "Windrose",
    "Windschatten",
    "Glühfaden",
    "Meridian",
    "Kaskade",
    "Überblendung",
    "Serpentine",
    "Sonnenwende",
    "Resonanz",
    "Prisma",
    "Wabe",
    "Gischt",
    "Sog",
    "Ernte",
    "Kaleidoskop",
    "Gobelin",
    "Lange Schatten",
    "Nachglühen",
    "Kokon",
    "Geode",
    "Parallaxe",
    "Zitadelle",
    "Nautilus",
    "Vesper",
    "Supernova",
    "Mondaufgang",
    "Zwielicht",
    "Lampenlicht",
    "Glühwürmchen",
    "Leuchtturm",
    "Nocturne",
    "Tiefenfeld",
    "Sternbild",
    "Halbschatten",
    "Metronom",
    "Korona",
    "Syzygie",
    "Pulsar",
    "Verschluss",
    "Umbra",
    "Totalität",
    "Sonnenwind",
    "Nordlicht",
    "Bänder",
    "Polarnacht",
    "Kathedrale",
    "Flirren",
    "Singularität",
    "Heimkehr",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Erstes Licht",
    "Treiben",
    "Horizont",
    "Glimmen",
    "Lerche",
    "Laternen",
    "Gezeiten",
    "Sonne",
    "Satelliten",
    "Taupunkt",
    "Apertur",
    "Kreuzgang",
    "Schlussstein",
    "Sonnenuhr",
    "Nadelöhr",
    "Windrose",
    "Windschatten",
    "Faden",
    "Meridian",
    "Kaskade",
    "Blende",
    "Serpentine",
    "Sonnenwende",
    "Resonanz",
    "Prisma",
    "Wabe",
    "Gischt",
    "Sog",
    "Ernte",
    "Kaleido",
    "Gobelin",
    "Schatten",
    "Nachglühen",
    "Kokon",
    "Geode",
    "Parallaxe",
    "Zitadelle",
    "Nautilus",
    "Vesper",
    "Supernova",
    "Mond",
    "Zwielicht",
    "Lampenlicht",
    "Glühwürmer",
    "Leuchtturm",
    "Nocturne",
    "Tiefenfeld",
    "Sternbild",
    "Halbschatten",
    "Metronom",
    "Korona",
    "Syzygie",
    "Pulsar",
    "Verschluss",
    "Umbra",
    "Totalität",
    "Sonnenwind",
    "Nordlicht",
    "Bänder",
    "Polarnacht",
    "Kathedrale",
    "Flirren",
    "Singularität",
    "Heimkehr",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Breit: fang die fallende Kapsel",
    "{icon:slow} Langsam: fang sie, und der Ball wird gemächlicher",
    "Lenke: die Kanten des Schlägers schicken den Ball weit",
    "Einzelne Funken: jag jeden einzeln",
    "Schick den Ball durch die offenen Flügel nach oben",
    "Räum jede Laterne von unten ab",
    "Reite die Dünung: spiel über die Seitenwände",
    "Hack die Sonne von unten ab, Reihe um Reihe",
    "{icon:anchor} Anker: Ball fangen, zielen, dann loslassen",
    "Gepanzerte Steine brauchen zwei Treffer: achte auf die Ränder",
    "{icon:anchor} Ziele durch die Lücke in der Wand",
    "Nur eine Tür: schick den Ball in den Innenhof",
    "Schlag den Schlussstein heraus, und der Bogen ist offen",
    "Lies die Winkel: jeder Schatten ist ein Schuss",
    "{icon:anchor} Ein schmales Nadelöhr: halten, zielen, loslassen",
    "Jede Himmelsrichtung führt ins Herz",
    "Bernsteinkerne: Jede Explosion trifft ihre vier Nachbarn",
    "Berühr den Glühfaden irgendwo: er brennt in beide Richtungen",
    "Teile das Feld entlang des Meridians",
    "Starte die Kaskade an einem der beiden Enden",
    "Öffne einen Weg durch die beiden Relaislinien",
    "Drei Relaislinien: je ein sauberer Schuss",
    "Der Ring brennt ganz: finde einen Weg an seinen Rand",
    "Benachbarte Kerne tragen die Kettenreaktion weiter",
    "{icon:multi} Multiball: drei Bälle, eine Öffnung",
    "Ein Kern in jeder Zelle: brich sie auf",
    "Gischt überall: lass drei Bälle los",
    "Brich in die Taschen hinter der Panzerung ein",
    "Volles Feld: {icon:multi} Multiball räumt es schnell ab",
    "Spiegel überall: brich eine Seite, dann ihren Zwilling",
    "Zieh an einem Faden, und das Gewebe löst sich",
    "Brich durch den Boden und zünde die lange Lunte",
    "{icon:phase} Phase: drei Steintreffer ohne Abprall",
    "{icon:phase} Phase gleitet durch die Hülle bis zum Kern",
    "Knack eine Geode, und ihre Kristalle leuchten auf",
    "Durchbrich die Hülle, dann zünde den inneren Weg",
    "Durchs Tor hinein, oder durch die Wand mit {icon:phase} Phase",
    "Spiral nach innen: die äußere Windung leuchtet zuerst",
    "Drei Glocken: läute jede von unten",
    "Fang einen Ball, während die anderen weiterfliegen",
    "Folge dem Relais um die offene Mitte",
    "Das Licht schwindet: lerne das Feld, solange du kannst",
    "Im Dunkeln tragen Ball und Schläger das Licht",
    "Glühwürmchen: die Kerne leuchten auch im Dunkeln",
    "Streif mit dem Licht des Schlägers über die Küste",
    "Mehr Bälle, mehr Licht: {icon:multi} Multiball",
    "Tiefenfeld: jeder blasse Punkt ist ein Stein",
    "Verbinde die Sterne: die hellen sind Kerne",
    "Tore verblassen im Takt: warte auf die Lücke",
    "Tick, tack: die Tore halten den Takt",
    "Die Korona öffnet sich im Takt: triff hinein",
    "Ein Geistertor steckt Explosionen weg: zünd den Funken im richtigen Moment",
    "Ein Pulsar: schnelle Schläge, schnelle Hände",
    "Der Verschluss öffnet sich kurz: sei bereit",
    "Halb im Schatten: die Torseite hält den Takt",
    "Zünde die Sonne, solange der Mond fest ist",
    "Der Wind weht nur in eine Richtung: reite ihn zu den Kernen",
    "Lichtvorhänge: fege sie mit {icon:multi} Multiball ab",
    "Jedes Band hängt an einem Tor: durchtrenne beide Hälften",
    "Die lange Nacht: ziele nach dem Licht, das du trägst",
    "Durch die Tore hinein, hoch zur Rosette",
    "Alles auf einmal: achte auf die Kerne",
    "Triff den Ring, wenn die Tore fest werden",
    "Ein letzter Orbit: Jede Öffnung zählt",
];
