//! German. Informal *du*, as games address players. Labels in capitals:
//! a label never contains ß, which has no capital form here; the table
//! tests check that every label is already upper case.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Zerbrich den Kosmos",
        ContinueJourney => "Reise fortsetzen",
        NewJourney => "Neue Reise",
        SectorSelect => "Sektorauswahl",
        ContinueDetail => "Sektor {0} · {1} · {2}",
        StatSectors => "SEKTOREN",
        StatMedals => "MEDAILLEN",
        StatBest => "BESTWERT",
        Fraction => "{0} / {1}",
        KeysMove => "Maus oder Pfeiltasten zum Bewegen",
        KeysServe => "Leertaste oder Klick zum Starten",
        KeysPause => "Esc zum Pausieren",
        KeysRelease => "Klick oder Leertaste zum Lösen",
        KeysBrowse => "Pfeiltasten zum Blättern",
        KeysPlay => "Eingabe zum Spielen",
        KeysBack => "Esc zum Zurückgehen",
        PadMove => "Stick oder Steuerkreuz zum Bewegen",
        PadBrowse => "Steuerkreuz zum Blättern",
        ActionServe => "Starten",
        ActionPause => "Pause",
        ActionRelease => "Lösen",
        ActionSelect => "Auswählen",
        ActionResume => "Fortsetzen",
        ActionPlay => "Spielen",
        ActionBack => "Zurück",
        SoundOn => "Ton an",
        SoundOff => "Ton aus",
        Volume => "Lautstärke {0}",
        Fullscreen => "Vollbild",
        SectorsHeading => "Sektoren",
        PracticeNote => "Übungsrunden verändern deine Reise nie",
        MedalClear => "GESCHAFFT",
        MedalClean => "MAKELLOS",
        MedalSwift => "FLINK",
        MedalClearHow => "Sektor abschließen",
        MedalCleanHow => "Kein Leben verlieren",
        PlaySector => "Sektor {0} spielen",
        SwiftWithin => "Unter {0} abschließen",
        UnlockHint => "Zum Freischalten Sektor {0} abschließen",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pausiert",
        RetrySector => "Sektor wiederholen",
        MainMenu => "Hauptmenü",
        JourneyComplete => "Reise abgeschlossen",
        OneMoreOrbit => "Noch eine Runde?",
        StatPoints => "PUNKTE",
        SectorClear => "Sektor geschafft",
        StatTime => "ZEIT",
        StatBonus => "BONUS",
        StatChain => "KETTE",
        ExtraLife => "Kapitel abgeschlossen · +1 Leben",
        NextSector => "Nächster Sektor",
        BackToSectors => "Zurück zu den Sektoren",
        SaveFailed => "Fortschritt konnte nicht gespeichert werden",
        PerfTitle => "Leistung / CPU",
        HelpResume => "Mach da weiter, wo du warst",
        HelpRetry => "Ab dem Kontrollpunkt des Sektors neu starten",
        HelpMainMenu => "Deine Reise ist gespeichert",
        HelpSectors => "Übe jeden offenen Sektor",
        HelpNewJourney => "Neu ab Sektor 01 · Medaillen bleiben",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "MORGENGRAUEN",
            Chapter::BlueHour => "BLAUE STUNDE",
            Chapter::Afterlight => "ABENDGLUT",
        },
        PowerName(p) => match p {
            Power::Wide => "Breit",
            Power::Slow => "Langsam",
            Power::Multi => "Multiball",
            Power::Anchor => "Anker",
            Power::Phase => "Phase",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1} · {2}"),
        ContinueJourney => Some("Weiter"),
        SwiftWithin => Some("Unter {0}"),
        UnlockHint => Some("Gesperrt"),
        RetrySector => Some("Wiederholen"),
        MainMenu => Some("Menü"),
        NewJourney => Some("Neu"),
        SectorSelect => Some("Sektoren"),
        NextSector => Some("Weiter"),
        BackToSectors => Some("Sektoren"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Erstes Licht",
    "Satelliten",
    "Windschatten",
    "Resonanz",
    "Prisma",
    "Überblendung",
    "Sog",
    "Mondaufgang",
    "Nachglühen",
    "Parallaxe",
    "Supernova",
    "Heimkehr",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Breit und {icon:slow} Langsam: Fang die fallenden Kapseln",
    "{icon:anchor} Anker: Ball fangen, zielen, dann loslassen",
    "Bernsteinkerne: Jede Explosion trifft ihre vier Nachbarn",
    "Benachbarte Kerne tragen die Kettenreaktion weiter",
    "{icon:multi} Multiball: drei Bälle, eine Öffnung",
    "Öffne einen Weg durch die beiden Relaislinien",
    "Brich in die Taschen hinter der Panzerung ein",
    "Folge dem Relais um die offene Mitte",
    "{icon:phase} Phase: drei Steintreffer ohne Abprall",
    "Durchbrich die Hülle, dann zünde den inneren Weg",
    "Fang einen Ball, während die anderen weiterfliegen",
    "Ein letzter Orbit: Jede Öffnung zählt",
];
