//! Greek. Informal second person; labels in capitals without accents, as
//! Greek sets all-caps text. The question mark is ";" (U+037E normalizes to it).
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Σπάσε το σύμπαν",
        ContinueJourney => "Συνέχεια ταξιδιού",
        NewJourney => "Νέο ταξίδι",
        SectorSelect => "Επιλογή τομέα",
        ContinueDetail => "{0} · {1}",
        StatMedals => "ΜΕΤΑΛΛΙΑ",
        StatBest => "ΡΕΚΟΡ",
        ActionServe => "Σερβίς",
        ActionRelease => "Απελευθέρωση",
        ActionSelect => "Επιλογή",
        ActionResume => "Συνέχεια",
        ActionBack => "Πίσω",
        Fullscreen => "Πλήρης οθόνη",
        SectorsHeading => "Τομείς",
        PracticeNote => "Η εξάσκηση δεν αλλάζει ποτέ το ταξίδι σου",
        MedalClear => "ΟΛΟΚΛΗΡΩΣΗ",
        MedalClean => "ΑΨΟΓΑ",
        MedalSwift => "ΤΑΧΥΤΗΤΑ",
        PlaySector => "Παίξε τον τομέα {0}",
        UnlockHint => "Ολοκλήρωσε τον τομέα {0} για ξεκλείδωμα",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · ΤΟΜΕΑΣ {1}",
        Paused => "Σε παύση",
        RetrySector => "Τομέας ξανά",
        MainMenu => "Κύριο μενού",
        JourneyComplete => "Τέλος ταξιδιού",
        OneMoreOrbit => "Άλλη μία τροχιά;",
        StatPoints => "ΠΟΝΤΟΙ",
        SectorClear => "Τομέας ολοκληρώθηκε",
        StatTime => "ΧΡΟΝΟΣ",
        StatBonus => "ΜΠΟΝΟΥΣ",
        StatChain => "ΑΛΥΣΙΔΑ",
        ExtraLife => "Τέλος κεφαλαίου · +1 ζωή",
        NextSector => "Επόμενος τομέας",
        BackToSectors => "Πίσω στους τομείς",
        SaveFailed => "Η πρόοδος δεν αποθηκεύτηκε",
        PerfTitle => "Επιδόσεις / CPU",
        HelpResume => "Συνέχισε από εκεί που σταμάτησες",
        HelpRetry => "Από το σημείο ελέγχου του τομέα",
        HelpMainMenu => "Το ταξίδι σου αποθηκεύτηκε",
        HelpSectors => "Εξάσκηση σε ανοιχτούς τομείς",
        HelpNewJourney => "Από τον τομέα 01 · τα μετάλλια μένουν",
        Settings => "Ρυθμίσεις",
        HelpSettings => "Ήχος, οθόνη, γλώσσα",
        SettingSound => "Ήχος",
        SettingVolume => "Ένταση",
        SettingDisplay => "Οθόνη",
        SettingLanguage => "Γλώσσα",
        DisplayWindow => "Παράθυρο",
        LanguageSystem => "Συστήματος",
        ActionAdjust => "Ρύθμιση",
        SettingEffects => "Εφέ",
        SettingContrast => "Αντίθεση",
        LookStandard => "Τυπικό",
        EffectsReduced => "Μειωμένα",
        ContrastHigh => "Υψηλή",
        KeySpace => "Διάστημα",
        KeyEsc => "Esc",
        SectorsOf => "{0} από {1} τομείς",
        TargetBest => "{0} · ρεκόρ {1}",
        LifeGained => "+1 ζωή",
        PresenceMenus => "Στα μενού",
        PresenceJourney => "Τομέας {0} · {1}",
        PresencePractice => "Εξάσκηση στον τομέα {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ΑΥΓΗ",
            Chapter::BlueHour => "ΜΠΛΕ ΩΡΑ",
            Chapter::Afterlight => "ΛΥΚΟΦΩΣ",
        },
        PowerName(p) => match p {
            Power::Wide => "ΦΑΡΔΥ",
            Power::Slow => "ΑΡΓΟ",
            Power::Multi => "ΠΟΛΛΕΣ ΜΠΑΛΕΣ",
            Power::Anchor => "ΑΓΚΥΡΑ",
            Power::Phase => "ΦΑΣΗ",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Συνέχεια"),
        UnlockHint => Some("Κλειδωμένο"),
        RetrySector => Some("Ξανά"),
        MainMenu => Some("Μενού"),
        NewJourney => Some("Νέο"),
        SectorSelect => Some("Τομείς"),
        NextSector => Some("Επόμενος"),
        BackToSectors => Some("Τομείς"),
        Settings => Some("Επιλογές"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Συνέχεια"),
        PlaySector => Some("Παίξε {0}"),
        ActionServe => Some("Σερβίς"),
        ActionRelease => Some("Άφησε"),
        ActionSelect => Some("Επιλογή"),
        ActionBack => Some("Πίσω"),
        ActionAdjust => Some("Ρύθμιση"),
        SettingEffects => Some("Εφέ"),
        SettingContrast => Some("Αντίθεση"),
        LookStandard => Some("Τυπικό"),
        EffectsReduced => Some("Λιγότερα"),
        ContrastHigh => Some("Υψηλή"),
        StatBest => Some("ΡΕΚΟΡ"),
        StatMedals => Some("ΜΕΤΑΛΛΙΑ"),
        SectorsHeading => Some("Τομείς"),
        SaveFailed => Some("Δεν αποθηκεύτηκε"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Κενό"),
        HelpResume => Some("Πίσω στο παιχνίδι"),
        HelpRetry => Some("Από το σημείο ελέγχου"),
        HelpMainMenu => Some("Αποθηκεύτηκε"),
        HelpSectors => Some("Εξάσκηση"),
        HelpNewJourney => Some("Από τον τομέα 01"),
        HelpSettings => Some("Ήχος, οθόνη"),
        SettingSound => Some("Ήχος"),
        SettingVolume => Some("Ένταση"),
        SettingDisplay => Some("Οθόνη"),
        SettingLanguage => Some("Γλώσσα"),
        DisplayWindow => Some("Παράθυρο"),
        Fullscreen => Some("Πλήρης"),
        LanguageSystem => Some("Σύστημα"),
        ExtraLife => Some("+1 ζωή"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("ΤΟΜΕΑΣ {1}"),
        JourneyComplete => Some("Τέλος"),
        SectorClear => Some("Ολοκληρώθηκε"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Πρώτο φως",
    "Δορυφόροι",
    "Ρεύμα έλξης",
    "Συντονισμός",
    "Πρίσμα",
    "Διασταύρωση",
    "Υπόρρευμα",
    "Ανατολή σελήνης",
    "Απόλαμψη",
    "Παράλλαξη",
    "Σουπερνόβα",
    "Επιστροφή",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Πρώτο φως",
    "Δορυφόροι",
    "Ρεύμα",
    "Συντονισμός",
    "Πρίσμα",
    "Διασταύρωση",
    "Υπόρρευμα",
    "Σελήνη",
    "Απόλαμψη",
    "Παράλλαξη",
    "Σουπερνόβα",
    "Επιστροφή",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Φαρδύ και {icon:slow} Αργό: πιάσε τις κάψουλες που πέφτουν",
    "{icon:anchor} Άγκυρα: πιάσε την μπάλα, σημάδεψε και άφησέ τη",
    "Κεχριμπαρένιοι πυρήνες: κάθε έκρηξη φτάνει τους τέσσερις γείτονες",
    "Οι γειτονικοί πυρήνες μεταφέρουν την αντίδραση",
    "{icon:multi} Πολλαπλή μπάλα: τρεις μπάλες, ένα άνοιγμα",
    "Άνοιξε δρόμο μέσα από τις δύο γραμμές αναμεταδοτών",
    "Μπες στις κοιλότητες πίσω από τη θωράκιση",
    "Ακολούθησε τον αναμεταδότη γύρω από το ανοιχτό κέντρο",
    "{icon:phase} Φάση: τρεις επαφές με τούβλα χωρίς αναπήδηση",
    "Τρύπησε το κέλυφος και άναψε την εσωτερική διαδρομή",
    "Πιάσε μια μπάλα που επιστρέφει ενώ οι άλλες συνεχίζουν",
    "Μία τελευταία τροχιά: αξιοποίησε κάθε άνοιγμα",
];
