//! English, the source. Labels are authored in capitals, headings and
//! actions in sentence case, sector names in title case.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Break the cosmos",
        ContinueJourney => "Continue journey",
        NewJourney => "New journey",
        SectorSelect => "Sector select",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALS",
        StatBest => "BEST",
        ActionServe => "Serve",
        ActionRelease => "Release",
        ActionSelect => "Select",
        ActionResume => "Resume",
        ActionBack => "Back",
        Fullscreen => "Fullscreen",
        SectorsHeading => "Sectors",
        PracticeNote => "Practice never changes your journey",
        MedalClear => "CLEAR",
        MedalClean => "CLEAN",
        MedalSwift => "SWIFT",
        PlaySector => "Play sector {0}",
        UnlockHint => "Clear sector {0} to unlock",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTOR {1}",
        Paused => "Paused",
        RetrySector => "Retry sector",
        MainMenu => "Main menu",
        JourneyComplete => "Journey complete",
        OneMoreOrbit => "One more orbit?",
        StatPoints => "POINTS",
        SectorClear => "Sector clear",
        StatTime => "TIME",
        StatBonus => "BONUS",
        StatChain => "CHAIN",
        ExtraLife => "Chapter complete · +1 life",
        NextSector => "Next sector",
        BackToSectors => "Back to sectors",
        SaveFailed => "Progress could not be saved",
        PerfTitle => "Performance / CPU",
        HelpResume => "Pick up where you left off",
        HelpRetry => "Restart from the sector checkpoint",
        HelpMainMenu => "Your journey is saved",
        HelpSectors => "Practice any open sector",
        HelpNewJourney => "Start again from sector 01 · medals stay",
        Settings => "Settings",
        HelpSettings => "Sound, display, language",
        SettingSound => "Sound",
        SettingVolume => "Volume",
        SettingDisplay => "Display",
        SettingLanguage => "Language",
        DisplayWindow => "Window",
        LanguageSystem => "System",
        ActionAdjust => "Adjust",
        SettingEffects => "Effects",
        SettingContrast => "Contrast",
        LookStandard => "Standard",
        EffectsReduced => "Reduced",
        ContrastHigh => "High",
        KeySpace => "Space",
        KeyEsc => "Esc",
        SectorsOf => "{0} of {1} sectors",
        TargetBest => "{0} · best {1}",
        LifeGained => "+1 life",
        PresenceMenus => "In menus",
        PresenceJourney => "Sector {0} · {1}",
        PresencePractice => "Practicing sector {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAYBREAK",
            Chapter::Morning => "MORNING",
            Chapter::Zenith => "ZENITH",
            Chapter::GoldenHour => "GOLDEN HOUR",
            Chapter::Afterlight => "AFTERLIGHT",
            Chapter::BlueHour => "BLUE HOUR",
            Chapter::Eclipse => "ECLIPSE",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "WIDE",
            Power::Slow => "SLOW",
            Power::Multi => "MULTIBALL",
            Power::Anchor => "ANCHOR",
            Power::Phase => "PHASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continue"),
        UnlockHint => Some("Locked"),
        RetrySector => Some("Retry"),
        MainMenu => Some("Menu"),
        NewJourney => Some("New"),
        SectorSelect => Some("Sectors"),
        NextSector => Some("Next"),
        BackToSectors => Some("Sectors"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Resume"),
        PlaySector => Some("Play {0}"),
        Settings => Some("Options"),
        ActionServe => Some("Serve"),
        ActionRelease => Some("Release"),
        ActionSelect => Some("Select"),
        ActionBack => Some("Back"),
        ActionAdjust => Some("Adjust"),
        StatBest => Some("BEST"),
        StatMedals => Some("MEDALS"),
        SectorsHeading => Some("Sectors"),
        SaveFailed => Some("Not saved"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Space"),
        HelpResume => Some("Back to play"),
        HelpRetry => Some("From the checkpoint"),
        HelpMainMenu => Some("Journey saved"),
        HelpSectors => Some("Practice sectors"),
        HelpNewJourney => Some("From sector 01"),
        HelpSettings => Some("Sound, display"),
        SettingSound => Some("Sound"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Display"),
        SettingLanguage => Some("Language"),
        DisplayWindow => Some("Window"),
        Fullscreen => Some("Full"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 life"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SECTOR {1}"),
        JourneyComplete => Some("Complete"),
        SettingEffects => Some("Effects"),
        SettingContrast => Some("Contrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Low"),
        ContrastHigh => Some("High"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "First Light",
    "Drift",
    "Horizon",
    "Glimmer",
    "Skylark",
    "Lanterns",
    "Tidewater",
    "Sunrise",
    "Satellites",
    "Dewpoint",
    "Aperture",
    "Cloister",
    "Keystone",
    "Sundial",
    "Pinhole",
    "Windrose",
    "Slipstream",
    "Filament",
    "Meridian",
    "Cascade",
    "Crossfade",
    "Switchback",
    "Solstice",
    "Resonance",
    "Prism",
    "Honeycomb",
    "Spindrift",
    "Undertow",
    "Harvest",
    "Kaleidoscope",
    "Tapestry",
    "Long Shadows",
    "Afterglow",
    "Chrysalis",
    "Geode",
    "Parallax",
    "Citadel",
    "Nautilus",
    "Vespers",
    "Supernova",
    "Moonrise",
    "Gloaming",
    "Lamplight",
    "Fireflies",
    "Lighthouse",
    "Nocturne",
    "Deep Field",
    "Constellation",
    "Penumbra",
    "Metronome",
    "Corona",
    "Syzygy",
    "Pulsar",
    "Shutter",
    "Umbra",
    "Totality",
    "Solar Wind",
    "Borealis",
    "Ribbons",
    "Polar Night",
    "Cathedral",
    "Shimmer",
    "Singularity",
    "Homecoming",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "First Light",
    "Drift",
    "Horizon",
    "Glimmer",
    "Skylark",
    "Lanterns",
    "Tidewater",
    "Sunrise",
    "Satellites",
    "Dewpoint",
    "Aperture",
    "Cloister",
    "Keystone",
    "Sundial",
    "Pinhole",
    "Windrose",
    "Slipstream",
    "Filament",
    "Meridian",
    "Cascade",
    "Crossfade",
    "Switchback",
    "Solstice",
    "Resonance",
    "Prism",
    "Honeycomb",
    "Spindrift",
    "Undertow",
    "Harvest",
    "Kaleido",
    "Tapestry",
    "Shadows",
    "Afterglow",
    "Chrysalis",
    "Geode",
    "Parallax",
    "Citadel",
    "Nautilus",
    "Vespers",
    "Supernova",
    "Moonrise",
    "Gloaming",
    "Lamplight",
    "Fireflies",
    "Lighthouse",
    "Nocturne",
    "Deep Field",
    "Stars",
    "Penumbra",
    "Metronome",
    "Corona",
    "Syzygy",
    "Pulsar",
    "Shutter",
    "Umbra",
    "Totality",
    "Solar Wind",
    "Borealis",
    "Ribbons",
    "Polar Night",
    "Cathedral",
    "Shimmer",
    "Singularity",
    "Homecoming",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Wide: catch the falling capsule",
    "{icon:slow} Slow: catch it and the ball eases off",
    "Steer: the paddle's edges send the ball wide",
    "Lone sparks: chase each one down",
    "Send the ball up the open wings",
    "Clear each lantern from below",
    "Ride the swell: bank shots off the side walls",
    "Chip the sun away from below, row by row",
    "{icon:anchor} Anchor: catch the ball, aim, then release it",
    "Armored bricks take two hits: watch the rims",
    "{icon:anchor} Aim through the gap in the wall",
    "One door in: send the ball into the courtyard",
    "Knock out the keystone and the arch is open",
    "Read the angles: each shadow is a shot",
    "{icon:anchor} One narrow pinhole: hold, aim, release",
    "Every point of the compass leads to the heart",
    "Amber cores: each blast reaches its four neighbors",
    "Touch the filament anywhere: it burns both ways",
    "Split the field down the meridian",
    "Start the cascade at either end",
    "Open a route through the two relay lines",
    "Three relay lines: one clean shot each",
    "The ring burns whole: find a way to its edge",
    "Neighboring cores carry the reaction",
    "{icon:multi} Multiball: three balls, one opening",
    "A core in every cell: crack them open",
    "Spray everywhere: let three balls loose",
    "Break into the pockets behind the armor",
    "A full field: {icon:multi} Multiball reaps it fast",
    "Mirrors everywhere: break one side, then its twin",
    "Pull one thread and the weave comes loose",
    "Break through the floor and light the long fuse",
    "{icon:phase} Phase: three brick contacts without a bounce",
    "{icon:phase} Phase slips through the shell to the core",
    "Crack a geode and its crystals light up",
    "Pierce the shell, then ignite the inner route",
    "In by the gate, or through the wall with {icon:phase} Phase",
    "Spiral in: the outer coil lights first",
    "Three bells: ring each one from beneath",
    "Catch a return while the other balls keep going",
    "Follow the relay around the open center",
    "Light is leaving: learn the field while you can",
    "In the dark, your ball and keel carry the light",
    "Fireflies: the cores glow even in the dark",
    "Sweep the keel's light across the coast",
    "More balls, more light: {icon:multi} Multiball",
    "Deep field: every faint speck is a brick",
    "Join the stars: the bright ones are cores",
    "Gates fade on a beat: wait for the gap",
    "Tick, tock: the gates keep time",
    "The corona opens on the beat: strike inside",
    "A ghost gate shrugs off a blast: time the spark",
    "A pulsar: quick beats, quick hands",
    "The shutter opens for a moment: be ready",
    "Half in shadow: the gated side keeps time",
    "Ignite the sun while the moon is solid",
    "The wind runs one way: ride it to the cores",
    "Curtains of light: sweep them with {icon:multi} Multiball",
    "Each ribbon is tied with a gate: cut both halves",
    "The long night: aim by the light you carry",
    "In through the doors, up to the rose window",
    "Everything at once: watch the cores",
    "Strike the ring as the gates turn solid",
    "One last orbit: make each opening count",
];
