//! English, the source. Labels are authored in capitals, headings and
//! actions in sentence case, sector names in title case.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Break the cosmos",
        ContinueJourney => "Continue journey",
        NewJourney => "New journey",
        SectorSelect => "Sector select",
        SavedAt => "Saved at sector {0} · {1}",
        JourneyIntro => "Twelve sectors across three chapters",
        StatSectors => "SECTORS",
        StatMedals => "MEDALS",
        StatBest => "BEST",
        Fraction => "{0} / {1}",
        KeysMove => "Mouse or arrow keys to move",
        KeysServe => "Space or click to serve",
        KeysPause => "Esc to pause",
        KeysRelease => "Click or Space to release",
        KeysBrowse => "Arrow keys to browse",
        KeysPlay => "Enter to play",
        KeysBack => "Esc to go back",
        KeysContinue => "Enter or click to continue",
        PadMove => "Stick or D-pad to move",
        PadBrowse => "D-pad to browse",
        ActionServe => "Serve",
        ActionPause => "Pause",
        ActionRelease => "Release",
        ActionSelect => "Select",
        ActionResume => "Resume",
        ActionRetry => "Retry",
        ActionPlay => "Play",
        ActionBack => "Back",
        ActionContinue => "Continue",
        SoundOn => "Sound on",
        SoundOff => "Sound off",
        Volume => "Volume {0}",
        Fullscreen => "Fullscreen",
        SectorsHeading => "Sectors",
        PracticeNote => "Practice runs never change your journey",
        NoTime => "--:--",
        SwiftTarget => "Swift target {0}",
        BestTime => "Best {0}",
        MedalClear => "CLEAR",
        MedalClean => "CLEAN",
        MedalSwift => "SWIFT",
        MedalClearHow => "Finish the sector",
        MedalCleanHow => "Lose no lives",
        MedalSwiftHow => "Beat the target time",
        PlaySector => "Play sector {0}",
        ClearPreviousFirst => "Clear the previous sector first",
        Score => "SCORE",
        Lives => "LIVES",
        SectorNumber => "SECTOR {0}",
        PracticeNumber => "PRACTICE {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTOR {1}",
        Paused => "Paused",
        RetrySector => "Retry sector",
        MainMenu => "Main menu",
        RetryNote => "Retry restarts from the checkpoint",
        JourneyComplete => "Journey complete",
        OneMoreOrbit => "One more orbit?",
        StatPoints => "POINTS",
        ProgressSaved => "Your progress is saved",
        SectorClear => "Sector clear",
        StatTime => "TIME",
        StatBonus => "BONUS",
        StatBestChain => "BEST CHAIN",
        ExtraLife => "Chapter complete · extra life",
        NextSector => "Next sector",
        BackToSectors => "Back to sectors",
        SaveFailed => "Progress could not be saved",
        PerfTitle => "Performance / CPU",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAYBREAK",
            Chapter::BlueHour => "BLUE HOUR",
            Chapter::Afterlight => "AFTERLIGHT",
        },
        PowerName(p) => match p {
            Power::Wide => "Wide",
            Power::Slow => "Slow",
            Power::Multi => "Multiball",
            Power::Anchor => "Anchor",
            Power::Phase => "Phase",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueJourney => Some("Continue"),
        ClearPreviousFirst => Some("Locked"),
        StatBestChain => Some("CHAIN"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "First Light",
    "Satellites",
    "Slipstream",
    "Resonance",
    "Prism",
    "Crossfade",
    "Undertow",
    "Moonrise",
    "Afterglow",
    "Parallax",
    "Supernova",
    "Homecoming",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Wide and {icon:slow} Slow: catch the falling capsules",
    "{icon:anchor} Anchor: catch the ball, aim, then release it",
    "Amber cores: each blast reaches its four neighbors",
    "Neighboring cores carry the reaction",
    "{icon:multi} Multiball: three balls, one opening",
    "Open a route through the two relay lines",
    "Break into the pockets behind the armor",
    "Follow the relay around the open center",
    "{icon:phase} Phase: three brick contacts without a bounce",
    "Pierce the shell, then ignite the inner route",
    "Catch a return while the other balls keep going",
    "One last orbit: make each opening count",
];
