//! English, the source. Labels are authored in capitals, headings and
//! actions in sentence case, sector names in title case.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Break the cosmos",
        ContinueJourney => "Continue journey",
        NewJourney => "New journey",
        SectorSelect => "Sector select",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALS",
        StatBest => "BEST",
        ActionServe => "Serve",
        ActionRelease => "Release",
        ActionSelect => "Select",
        ActionResume => "Resume",
        ActionBack => "Back",
        Fullscreen => "Fullscreen",
        SectorsHeading => "Sectors",
        PracticeNote => "Practice never changes your journey",
        MedalClear => "CLEAR",
        MedalClean => "CLEAN",
        MedalSwift => "SWIFT",
        PlaySector => "Play sector {0}",
        UnlockHint => "Clear sector {0} to unlock",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTOR {1}",
        Paused => "Paused",
        RetrySector => "Retry sector",
        MainMenu => "Main menu",
        JourneyComplete => "Journey complete",
        OneMoreOrbit => "One more orbit?",
        StatPoints => "POINTS",
        SectorClear => "Sector clear",
        StatTime => "TIME",
        StatBonus => "BONUS",
        StatChain => "CHAIN",
        ExtraLife => "Chapter complete · +1 life",
        NextSector => "Next sector",
        BackToSectors => "Back to sectors",
        SaveFailed => "Progress could not be saved",
        PerfTitle => "Performance / CPU",
        HelpResume => "Pick up where you left off",
        HelpRetry => "Restart from the sector checkpoint",
        HelpMainMenu => "Your journey is saved",
        HelpSectors => "Practice any open sector",
        HelpNewJourney => "Start again from sector 01 · medals stay",
        Settings => "Settings",
        HelpSettings => "Sound, display, language",
        SettingSound => "Sound",
        SettingVolume => "Volume",
        SettingDisplay => "Display",
        SettingLanguage => "Language",
        DisplayWindow => "Window",
        LanguageSystem => "System",
        ActionAdjust => "Adjust",
        KeySpace => "Space",
        KeyEsc => "Esc",
        SectorsOf => "{0} of {1} sectors",
        TargetBest => "{0} · best {1}",
        LifeGained => "+1 life",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAYBREAK",
            Chapter::BlueHour => "BLUE HOUR",
            Chapter::Afterlight => "AFTERLIGHT",
        },
        PowerName(p) => match p {
            Power::Wide => "WIDE",
            Power::Slow => "SLOW",
            Power::Multi => "MULTIBALL",
            Power::Anchor => "ANCHOR",
            Power::Phase => "PHASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continue"),
        UnlockHint => Some("Locked"),
        RetrySector => Some("Retry"),
        MainMenu => Some("Menu"),
        NewJourney => Some("New"),
        SectorSelect => Some("Sectors"),
        NextSector => Some("Next"),
        BackToSectors => Some("Sectors"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "First Light",
    "Satellites",
    "Slipstream",
    "Resonance",
    "Prism",
    "Crossfade",
    "Undertow",
    "Moonrise",
    "Afterglow",
    "Parallax",
    "Supernova",
    "Homecoming",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Wide and {icon:slow} Slow: catch the falling capsules",
    "{icon:anchor} Anchor: catch the ball, aim, then release it",
    "Amber cores: each blast reaches its four neighbors",
    "Neighboring cores carry the reaction",
    "{icon:multi} Multiball: three balls, one opening",
    "Open a route through the two relay lines",
    "Break into the pockets behind the armor",
    "Follow the relay around the open center",
    "{icon:phase} Phase: three brick contacts without a bounce",
    "Pierce the shell, then ignite the inner route",
    "Catch a return while the other balls keep going",
    "One last orbit: make each opening count",
];
