//! Spanish as written in Spain. Informal *tú*; labels in capitals with
//! accents kept (RÉCORD).
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Rompe el cosmos",
        ContinueJourney => "Continuar viaje",
        NewJourney => "Nuevo viaje",
        SectorSelect => "Elegir sector",
        ContinueDetail => "Sector {0} · {1} · {2}",
        StatSectors => "SECTORES",
        StatMedals => "MEDALLAS",
        StatBest => "RÉCORD",
        Fraction => "{0} / {1}",
        KeysMove => "Ratón o flechas para moverte",
        KeysServe => "Espacio o clic para sacar",
        KeysPause => "Esc para pausar",
        KeysRelease => "Clic o Espacio para soltar",
        KeysBrowse => "Flechas para recorrer",
        KeysPlay => "Intro para jugar",
        KeysBack => "Esc para volver",
        PadMove => "Stick o cruceta para moverte",
        PadBrowse => "Cruceta para recorrer",
        ActionServe => "Sacar",
        ActionPause => "Pausa",
        ActionRelease => "Soltar",
        ActionSelect => "Elegir",
        ActionResume => "Reanudar",
        ActionPlay => "Jugar",
        ActionBack => "Volver",
        Fullscreen => "Pantalla completa",
        SectorsHeading => "Sectores",
        PracticeNote => "Las partidas de práctica nunca cambian tu viaje",
        MedalClear => "SUPERADO",
        MedalClean => "IMPECABLE",
        MedalSwift => "VELOZ",
        MedalClearHow => "Completa el sector",
        MedalCleanHow => "No pierdas vidas",
        PlaySector => "Jugar sector {0}",
        SwiftWithin => "Completa en menos de {0}",
        UnlockHint => "Supera el sector {0} para desbloquearlo",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTOR {1}",
        Paused => "En pausa",
        RetrySector => "Reintentar sector",
        MainMenu => "Menú principal",
        JourneyComplete => "Viaje completado",
        OneMoreOrbit => "¿Otra órbita?",
        StatPoints => "PUNTOS",
        SectorClear => "Sector superado",
        StatTime => "TIEMPO",
        StatBonus => "BONIFICACIÓN",
        StatChain => "CADENA",
        ExtraLife => "Capítulo completado · +1 vida",
        NextSector => "Siguiente sector",
        BackToSectors => "Volver a los sectores",
        SaveFailed => "No se pudo guardar el progreso",
        PerfTitle => "Rendimiento / CPU",
        HelpResume => "Sigue donde lo dejaste",
        HelpRetry => "Vuelve al punto de control del sector",
        HelpMainMenu => "Tu viaje está guardado",
        HelpSectors => "Practica cualquier sector abierto",
        HelpNewJourney => "Empieza de nuevo en el sector 01 · las medallas se quedan",
        Settings => "Ajustes",
        HelpSettings => "Sonido, pantalla, idioma",
        SettingSound => "Sonido",
        SettingVolume => "Volumen",
        SettingDisplay => "Pantalla",
        SettingLanguage => "Idioma",
        DisplayWindow => "Ventana",
        LanguageSystem => "Sistema",
        ActionAdjust => "Ajustar",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "AMANECER",
            Chapter::BlueHour => "HORA AZUL",
            Chapter::Afterlight => "OCASO",
        },
        PowerName(p) => match p {
            Power::Wide => "Ancho",
            Power::Slow => "Lento",
            Power::Multi => "Multibola",
            Power::Anchor => "Ancla",
            Power::Phase => "Fase",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1} · {2}"),
        ContinueJourney => Some("Continuar"),
        SwiftWithin => Some("Menos de {0}"),
        UnlockHint => Some("Bloqueado"),
        RetrySector => Some("Reintentar"),
        MainMenu => Some("Menú"),
        NewJourney => Some("Nuevo"),
        SectorSelect => Some("Sectores"),
        NextSector => Some("Siguiente"),
        BackToSectors => Some("Sectores"),
        StatBonus => Some("BONO"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Primera luz",
    "Satélites",
    "Estela",
    "Resonancia",
    "Prisma",
    "Fundido",
    "Resaca",
    "Salida de la luna",
    "Resplandor",
    "Paralaje",
    "Supernova",
    "Regreso",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Ancho y {icon:slow} Lento: atrapa las cápsulas que caen",
    "{icon:anchor} Ancla: atrapa la bola, apunta y suéltala",
    "Núcleos ámbar: cada explosión alcanza a sus cuatro vecinos",
    "Los núcleos vecinos propagan la reacción",
    "{icon:multi} Multibola: tres bolas, una abertura",
    "Abre una ruta entre las dos líneas de relés",
    "Entra en los huecos tras el blindaje",
    "Sigue el relé alrededor del centro abierto",
    "{icon:phase} Fase: tres contactos con ladrillos sin rebotar",
    "Perfora la coraza y luego enciende la ruta interior",
    "Atrapa una bola mientras las demás siguen en juego",
    "Una última órbita: que cada abertura cuente",
];
