//! Spanish as written in Spain. Informal *tú*; labels in capitals with
//! accents kept (RÉCORD).
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Rompe el cosmos",
        ContinueJourney => "Continuar viaje",
        NewJourney => "Nuevo viaje",
        SectorSelect => "Elegir sector",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALLAS",
        StatBest => "RÉCORD",
        ActionServe => "Sacar",
        ActionRelease => "Soltar",
        ActionSelect => "Elegir",
        ActionResume => "Reanudar",
        ActionBack => "Volver",
        Fullscreen => "Pantalla completa",
        SectorsHeading => "Sectores",
        PracticeNote => "Practicar nunca cambia tu viaje",
        MedalClear => "SUPERADO",
        MedalClean => "IMPECABLE",
        MedalSwift => "VELOZ",
        PlaySector => "Jugar sector {0}",
        UnlockHint => "Supera el sector {0} para desbloquearlo",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTOR {1}",
        Paused => "En pausa",
        RetrySector => "Reintentar sector",
        MainMenu => "Menú principal",
        JourneyComplete => "Viaje completado",
        OneMoreOrbit => "¿Otra órbita?",
        StatPoints => "PUNTOS",
        SectorClear => "Sector superado",
        StatTime => "TIEMPO",
        StatBonus => "BONIFICACIÓN",
        StatChain => "CADENA",
        ExtraLife => "Capítulo completado · +1 vida",
        NextSector => "Siguiente sector",
        BackToSectors => "Volver a los sectores",
        SaveFailed => "No se pudo guardar el progreso",
        PerfTitle => "Rendimiento / CPU",
        HelpResume => "Sigue donde lo dejaste",
        HelpRetry => "Vuelve al punto de control del sector",
        HelpMainMenu => "Tu viaje está guardado",
        HelpSectors => "Practica cualquier sector abierto",
        HelpNewJourney => "Empieza de nuevo en el sector 01 · las medallas se quedan",
        Settings => "Ajustes",
        HelpSettings => "Sonido, pantalla, idioma",
        SettingSound => "Sonido",
        SettingVolume => "Volumen",
        SettingDisplay => "Pantalla",
        SettingLanguage => "Idioma",
        DisplayWindow => "Ventana",
        LanguageSystem => "Sistema",
        ActionAdjust => "Ajustar",
        KeySpace => "Espacio",
        KeyEsc => "Esc",
        SectorsOf => "{0} de {1} sectores",
        TargetBest => "{0} · récord {1}",
        LifeGained => "+1 vida",
        PresenceMenus => "En los menús",
        PresenceJourney => "Sector {0} · {1}",
        PresencePractice => "Practicando el sector {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "AMANECER",
            Chapter::BlueHour => "HORA AZUL",
            Chapter::Afterlight => "OCASO",
        },
        PowerName(p) => match p {
            Power::Wide => "ANCHO",
            Power::Slow => "LENTO",
            Power::Multi => "MULTIBOLA",
            Power::Anchor => "ANCLA",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continuar"),
        UnlockHint => Some("Bloqueado"),
        RetrySector => Some("Reintentar"),
        MainMenu => Some("Menú"),
        NewJourney => Some("Nuevo"),
        SectorSelect => Some("Sectores"),
        NextSector => Some("Siguiente"),
        BackToSectors => Some("Sectores"),
        StatBonus => Some("BONO"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Seguir"),
        PlaySector => Some("Jugar {0}"),
        Settings => Some("Ajustes"),
        ActionServe => Some("Sacar"),
        ActionRelease => Some("Soltar"),
        ActionSelect => Some("Elegir"),
        ActionBack => Some("Volver"),
        ActionAdjust => Some("Ajustar"),
        StatBest => Some("RÉCORD"),
        StatMedals => Some("MEDALLAS"),
        SectorsHeading => Some("Sectores"),
        SaveFailed => Some("Sin guardar"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Espacio"),
        HelpResume => Some("Volver al juego"),
        HelpRetry => Some("Desde el punto de control"),
        HelpMainMenu => Some("Viaje guardado"),
        HelpSectors => Some("Practicar sectores"),
        HelpNewJourney => Some("Desde el sector 01"),
        HelpSettings => Some("Sonido, pantalla"),
        SettingSound => Some("Sonido"),
        SettingVolume => Some("Volumen"),
        SettingDisplay => Some("Pantalla"),
        SettingLanguage => Some("Idioma"),
        DisplayWindow => Some("Ventana"),
        Fullscreen => Some("Completa"),
        LanguageSystem => Some("Sistema"),
        ExtraLife => Some("+1 vida"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SECTOR {1}"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Primera luz",
    "Satélites",
    "Estela",
    "Resonancia",
    "Prisma",
    "Fundido",
    "Resaca",
    "Salida de la luna",
    "Resplandor",
    "Paralaje",
    "Supernova",
    "Regreso",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Primera luz",
    "Satélites",
    "Estela",
    "Resonancia",
    "Prisma",
    "Fundido",
    "Resaca",
    "Luna",
    "Resplandor",
    "Paralaje",
    "Supernova",
    "Regreso",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Ancho y {icon:slow} Lento: atrapa las cápsulas que caen",
    "{icon:anchor} Ancla: atrapa la bola, apunta y suéltala",
    "Núcleos ámbar: cada explosión alcanza a sus cuatro vecinos",
    "Los núcleos vecinos propagan la reacción",
    "{icon:multi} Multibola: tres bolas, una abertura",
    "Abre una ruta entre las dos líneas de relés",
    "Entra en los huecos tras el blindaje",
    "Sigue el relé alrededor del centro abierto",
    "{icon:phase} Fase: tres contactos con ladrillos sin rebotar",
    "Perfora la coraza y luego enciende la ruta interior",
    "Atrapa una bola mientras las demás siguen en juego",
    "Una última órbita: que cada abertura cuente",
];
