//! Finnish. Hints read "action: keys", which keeps them short; labels in
//! capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Murskaa kosmos",
        ContinueJourney => "Jatka matkaa",
        NewJourney => "Uusi matka",
        SectorSelect => "Valitse sektori",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MITALIT",
        StatBest => "ENNÄTYS",
        ActionServe => "Syötä",
        ActionRelease => "Vapauta",
        ActionSelect => "Valitse",
        ActionResume => "Jatka",
        ActionBack => "Takaisin",
        Fullscreen => "Koko näyttö",
        SectorsHeading => "Sektorit",
        PracticeNote => "Harjoittelu ei koskaan muuta matkaasi",
        MedalClear => "LÄPI",
        MedalClean => "PUHDAS",
        MedalSwift => "NOPEA",
        PlaySector => "Pelaa sektori {0}",
        UnlockHint => "Avaa läpäisemällä sektori {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTORI {1}",
        Paused => "Tauko",
        RetrySector => "Sektori uudelleen",
        MainMenu => "Päävalikko",
        JourneyComplete => "Matka päättyi",
        OneMoreOrbit => "Vielä yksi kierros?",
        StatPoints => "PISTEET",
        SectorClear => "Sektori läpäisty",
        StatTime => "AIKA",
        StatBonus => "BONUS",
        StatChain => "KETJU",
        ExtraLife => "Luku läpäisty · +1 elämä",
        NextSector => "Seuraava sektori",
        BackToSectors => "Takaisin sektoreihin",
        SaveFailed => "Edistymistä ei voitu tallentaa",
        PerfTitle => "Suorituskyky / CPU",
        HelpResume => "Jatka siitä, mihin jäit",
        HelpRetry => "Aloita sektorin tarkistuspisteestä",
        HelpMainMenu => "Matkasi on tallennettu",
        HelpSectors => "Harjoittele mitä tahansa avointa sektoria",
        HelpNewJourney => "Alusta sektorista 01 · mitalit säilyvät",
        Settings => "Asetukset",
        HelpSettings => "Ääni, näyttö, kieli",
        SettingSound => "Ääni",
        SettingVolume => "Äänenvoimakkuus",
        SettingDisplay => "Näyttö",
        SettingLanguage => "Kieli",
        DisplayWindow => "Ikkuna",
        LanguageSystem => "Järjestelmä",
        ActionAdjust => "Säädä",
        SettingEffects => "Tehosteet",
        SettingContrast => "Kontrasti",
        LookStandard => "Vakio",
        EffectsReduced => "Vähennetty",
        ContrastHigh => "Korkea",
        KeySpace => "Välilyönti",
        KeyEsc => "Esc",
        SectorsOf => "{0}/{1} sektoria",
        TargetBest => "{0} · paras {1}",
        LifeGained => "+1 elämä",
        PresenceMenus => "Valikoissa",
        PresenceJourney => "Sektori {0} · {1}",
        PresencePractice => "Harjoittelee sektoria {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "AAMUNKOITTO",
            Chapter::BlueHour => "SININEN HETKI",
            Chapter::Afterlight => "ILTAHÄMÄRÄ",
        },
        PowerName(p) => match p {
            Power::Wide => "LEVEÄ",
            Power::Slow => "HIDAS",
            Power::Multi => "MONIPALLO",
            Power::Anchor => "ANKKURI",
            Power::Phase => "VAIHE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Jatka"),
        UnlockHint => Some("Lukittu"),
        RetrySector => Some("Uudelleen"),
        MainMenu => Some("Valikko"),
        NewJourney => Some("Uusi"),
        SectorSelect => Some("Sektorit"),
        NextSector => Some("Seuraava"),
        BackToSectors => Some("Sektorit"),
        Settings => Some("Asetukset"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Jatka"),
        PlaySector => Some("Pelaa {0}"),
        ActionServe => Some("Syötä"),
        ActionRelease => Some("Vapauta"),
        ActionSelect => Some("Valitse"),
        ActionBack => Some("Takaisin"),
        ActionAdjust => Some("Säädä"),
        SettingEffects => Some("Tehosteet"),
        SettingContrast => Some("Kontrasti"),
        LookStandard => Some("Vakio"),
        EffectsReduced => Some("Vähemmän"),
        ContrastHigh => Some("Korkea"),
        StatBest => Some("ENNÄTYS"),
        StatMedals => Some("MITALIT"),
        SectorsHeading => Some("Sektorit"),
        SaveFailed => Some("Ei tallennettu"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Väli"),
        HelpResume => Some("Takaisin peliin"),
        HelpRetry => Some("Tarkistuspisteestä"),
        HelpMainMenu => Some("Matka tallennettu"),
        HelpSectors => Some("Harjoittele"),
        HelpNewJourney => Some("Sektorista 01"),
        HelpSettings => Some("Ääni, näyttö"),
        SettingSound => Some("Ääni"),
        SettingVolume => Some("Voimakkuus"),
        SettingDisplay => Some("Näyttö"),
        SettingLanguage => Some("Kieli"),
        DisplayWindow => Some("Ikkuna"),
        Fullscreen => Some("Koko"),
        LanguageSystem => Some("Järjestelmä"),
        ExtraLife => Some("+1 elämä"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTORI {1}"),
        JourneyComplete => Some("Päättyi"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Ensivalo",
    "Satelliitit",
    "Imuvirta",
    "Resonanssi",
    "Prisma",
    "Ristihäivytys",
    "Pohjavirta",
    "Kuunnousu",
    "Jälkihehku",
    "Parallaksi",
    "Supernova",
    "Kotiinpaluu",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Ensivalo",
    "Satelliitit",
    "Imuvirta",
    "Resonanssi",
    "Prisma",
    "Häivytys",
    "Pohjavirta",
    "Kuunnousu",
    "Jälkihehku",
    "Parallaksi",
    "Supernova",
    "Kotiinpaluu",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Leveä ja {icon:slow} Hidas: nappaa putoavat kapselit",
    "{icon:anchor} Ankkuri: nappaa pallo, tähtää ja vapauta",
    "Meripihkaytimet: räjähdys osuu neljään naapuriin",
    "Vierekkäiset ytimet välittävät reaktion",
    "{icon:multi} Monipallo: kolme palloa, yksi aukko",
    "Avaa reitti kahden välityslinjan läpi",
    "Murtaudu panssarin takaisiin taskuihin",
    "Seuraa välitystä avoimen keskustan ympäri",
    "{icon:phase} Vaihe: kolme tiiliosumaa ilman kimpoamista",
    "Läpäise kuori ja sytytä sitten sisäreitti",
    "Nappaa palaava pallo muiden lentäessä",
    "Viimeinen kierros: hyödynnä jokainen aukko",
];
