//! Finnish. Hints read "action: keys", which keeps them short; labels in
//! capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Murskaa kosmos",
        ContinueJourney => "Jatka matkaa",
        NewJourney => "Uusi matka",
        SectorSelect => "Valitse sektori",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MITALIT",
        StatBest => "ENNÄTYS",
        ActionServe => "Syötä",
        ActionRelease => "Vapauta",
        ActionSelect => "Valitse",
        ActionResume => "Jatka",
        ActionBack => "Takaisin",
        Fullscreen => "Koko näyttö",
        SectorsHeading => "Sektorit",
        PracticeNote => "Harjoittelu ei koskaan muuta matkaasi",
        MedalClear => "LÄPI",
        MedalClean => "PUHDAS",
        MedalSwift => "NOPEA",
        PlaySector => "Pelaa sektori {0}",
        UnlockHint => "Avaa läpäisemällä sektori {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTORI {1}",
        Paused => "Tauko",
        RetrySector => "Sektori uudelleen",
        MainMenu => "Päävalikko",
        JourneyComplete => "Matka päättyi",
        OneMoreOrbit => "Vielä yksi kierros?",
        StatPoints => "PISTEET",
        SectorClear => "Sektori läpäisty",
        StatTime => "AIKA",
        StatBonus => "BONUS",
        StatChain => "KETJU",
        ExtraLife => "Luku läpäisty · +1 elämä",
        NextSector => "Seuraava sektori",
        BackToSectors => "Takaisin sektoreihin",
        SaveFailed => "Edistymistä ei voitu tallentaa",
        PerfTitle => "Suorituskyky / CPU",
        HelpResume => "Jatka siitä, mihin jäit",
        HelpRetry => "Aloita sektorin tarkistuspisteestä",
        HelpMainMenu => "Matkasi on tallennettu",
        HelpSectors => "Harjoittele mitä tahansa avointa sektoria",
        HelpNewJourney => "Alusta sektorista 01 · mitalit säilyvät",
        Settings => "Asetukset",
        HelpSettings => "Ääni, näyttö, kieli",
        SettingSound => "Ääni",
        SettingVolume => "Äänenvoimakkuus",
        SettingDisplay => "Näyttö",
        SettingLanguage => "Kieli",
        DisplayWindow => "Ikkuna",
        LanguageSystem => "Järjestelmä",
        ActionAdjust => "Säädä",
        SettingEffects => "Tehosteet",
        SettingContrast => "Kontrasti",
        LookStandard => "Vakio",
        EffectsReduced => "Vähennetty",
        ContrastHigh => "Korkea",
        KeySpace => "Välilyönti",
        KeyEsc => "Esc",
        SectorsOf => "{0}/{1} sektoria",
        TargetBest => "{0} · paras {1}",
        LifeGained => "+1 elämä",
        PresenceMenus => "Valikoissa",
        PresenceJourney => "Sektori {0} · {1}",
        PresencePractice => "Harjoittelee sektoria {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "AAMUNKOITTO",
            Chapter::Morning => "AAMU",
            Chapter::Zenith => "HUIPPU",
            Chapter::GoldenHour => "KULTAINEN HETKI",
            Chapter::Afterlight => "ILTAHÄMÄRÄ",
            Chapter::BlueHour => "SININEN HETKI",
            Chapter::Eclipse => "PIMENNYS",
            Chapter::Aurora => "REVONTULET",
        },
        PowerName(p) => match p {
            Power::Wide => "LEVEÄ",
            Power::Slow => "HIDAS",
            Power::Multi => "MONIPALLO",
            Power::Anchor => "ANKKURI",
            Power::Phase => "VAIHE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Jatka"),
        UnlockHint => Some("Lukittu"),
        RetrySector => Some("Uudelleen"),
        MainMenu => Some("Valikko"),
        NewJourney => Some("Uusi"),
        SectorSelect => Some("Sektorit"),
        NextSector => Some("Seuraava"),
        BackToSectors => Some("Sektorit"),
        Settings => Some("Asetukset"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Jatka"),
        PlaySector => Some("Pelaa {0}"),
        ActionServe => Some("Syötä"),
        ActionRelease => Some("Vapauta"),
        ActionSelect => Some("Valitse"),
        ActionBack => Some("Takaisin"),
        ActionAdjust => Some("Säädä"),
        SettingEffects => Some("Tehosteet"),
        SettingContrast => Some("Kontrasti"),
        LookStandard => Some("Vakio"),
        EffectsReduced => Some("Vähemmän"),
        ContrastHigh => Some("Korkea"),
        StatBest => Some("ENNÄTYS"),
        StatMedals => Some("MITALIT"),
        SectorsHeading => Some("Sektorit"),
        SaveFailed => Some("Ei tallennettu"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Väli"),
        HelpResume => Some("Takaisin peliin"),
        HelpRetry => Some("Tarkistuspisteestä"),
        HelpMainMenu => Some("Matka tallennettu"),
        HelpSectors => Some("Harjoittele"),
        HelpNewJourney => Some("Sektorista 01"),
        HelpSettings => Some("Ääni, näyttö"),
        SettingSound => Some("Ääni"),
        SettingVolume => Some("Voimakkuus"),
        SettingDisplay => Some("Näyttö"),
        SettingLanguage => Some("Kieli"),
        DisplayWindow => Some("Ikkuna"),
        Fullscreen => Some("Koko"),
        LanguageSystem => Some("Järjestelmä"),
        ExtraLife => Some("+1 elämä"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTORI {1}"),
        JourneyComplete => Some("Päättyi"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Ensivalo",
    "Ajelehtiminen",
    "Horisontti",
    "Tuike",
    "Leivo",
    "Lyhdyt",
    "Vuorovesi",
    "Auringonnousu",
    "Satelliitit",
    "Kastepiste",
    "Aukko",
    "Luostari",
    "Huippukivi",
    "Aurinkokello",
    "Neulanreikä",
    "Tuuliruusu",
    "Imuvirta",
    "Hehkulanka",
    "Meridiaani",
    "Kaskadi",
    "Ristihäivytys",
    "Serpentiini",
    "Päivänseisaus",
    "Resonanssi",
    "Prisma",
    "Mehiläiskenno",
    "Meriroiske",
    "Pohjavirta",
    "Sato",
    "Kaleidoskooppi",
    "Kuvakudos",
    "Pitkät varjot",
    "Jälkihehku",
    "Kotelo",
    "Geodi",
    "Parallaksi",
    "Linnake",
    "Nautilus",
    "Iltarukous",
    "Supernova",
    "Kuunnousu",
    "Hämärä",
    "Lampunvalo",
    "Tulikärpäset",
    "Majakka",
    "Nokturni",
    "Syväkenttä",
    "Tähtikuvio",
    "Puolivarjo",
    "Metronomi",
    "Korona",
    "Syzygia",
    "Pulsari",
    "Suljin",
    "Umbra",
    "Täydellisyys",
    "Aurinkotuuli",
    "Pohjanvalo",
    "Nauhat",
    "Napayö",
    "Katedraali",
    "Kimallus",
    "Singulariteetti",
    "Kotiinpaluu",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Ensivalo",
    "Ajelehti",
    "Horisontti",
    "Tuike",
    "Leivo",
    "Lyhdyt",
    "Vuorovesi",
    "Aurinko",
    "Satelliitit",
    "Kastepiste",
    "Aukko",
    "Luostari",
    "Huippukivi",
    "Aurinkokello",
    "Neulanreikä",
    "Tuuliruusu",
    "Imuvirta",
    "Lanka",
    "Meridiaani",
    "Kaskadi",
    "Häivytys",
    "Serpentiini",
    "Seisaus",
    "Resonanssi",
    "Prisma",
    "Kenno",
    "Roiske",
    "Pohjavirta",
    "Sato",
    "Kaleido",
    "Kuvakudos",
    "Varjot",
    "Jälkihehku",
    "Kotelo",
    "Geodi",
    "Parallaksi",
    "Linnake",
    "Nautilus",
    "Iltarukous",
    "Supernova",
    "Kuunnousu",
    "Hämärä",
    "Lampunvalo",
    "Tulikärpäset",
    "Majakka",
    "Nokturni",
    "Syväkenttä",
    "Tähdet",
    "Puolivarjo",
    "Metronomi",
    "Korona",
    "Syzygia",
    "Pulsari",
    "Suljin",
    "Umbra",
    "Täydellisyys",
    "Aurinkotuuli",
    "Pohjanvalo",
    "Nauhat",
    "Napayö",
    "Katedraali",
    "Kimallus",
    "Singulariteetti",
    "Kotiinpaluu",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Leveä: nappaa putoava kapseli",
    "{icon:slow} Hidas: nappaa se, niin pallo rauhoittuu",
    "Ohjaa: mailan reunat lähettävät pallon sivuille",
    "Yksittäiset kipinät: jahtaa jokainen",
    "Lähetä pallo ylös avoimia siipiä pitkin",
    "Tyhjennä jokainen lyhty alhaalta",
    "Ratsasta aallolla: kimmota sivuseinistä",
    "Louhi aurinkoa alhaalta, rivi riviltä",
    "{icon:anchor} Ankkuri: nappaa pallo, tähtää ja vapauta",
    "Panssaroidut tiilet kestävät kaksi osumaa: varo reunoja",
    "{icon:anchor} Tähtää muurin aukosta",
    "Vain yksi ovi: lähetä pallo sisäpihalle",
    "Kaada huippukivi, niin kaari aukeaa",
    "Lue kulmat: jokainen varjo on laukaus",
    "{icon:anchor} Yksi kapea neulanreikä: pidä, tähtää, vapauta",
    "Jokainen ilmansuunta johtaa sydämeen",
    "Meripihkaytimet: räjähdys osuu neljään naapuriin",
    "Kosketa hehkulankaa mistä tahansa: se palaa molempiin suuntiin",
    "Jaa kenttä meridiaania pitkin",
    "Käynnistä kaskadi kummasta päästä tahansa",
    "Avaa reitti kahden välityslinjan läpi",
    "Kolme välityslinjaa: yksi puhdas laukaus kullekin",
    "Rengas palaa kokonaan: etsi reitti sen reunalle",
    "Vierekkäiset ytimet välittävät reaktion",
    "{icon:multi} Monipallo: kolme palloa, yksi aukko",
    "Ydin jokaisessa kennossa: murra ne auki",
    "Roiskeita joka puolella: päästä kolme palloa irti",
    "Murtaudu panssarin takaisiin taskuihin",
    "Täysi kenttä: {icon:multi} Monipallo putsaa sen nopeasti",
    "Peilejä kaikkialla: riko yksi puoli, sitten sen kaksonen",
    "Vedä yhdestä langasta, niin kudos purkautuu",
    "Murra lattia läpi ja sytytä pitkä sytytyslanka",
    "{icon:phase} Vaihe: kolme tiiliosumaa ilman kimpoamista",
    "{icon:phase} Vaihe liukuu kuoren läpi ytimeen",
    "Murra geodi, niin sen kiteet syttyvät",
    "Läpäise kuori ja sytytä sitten sisäreitti",
    "Porttia pitkin sisään tai muurin läpi {icon:phase} Vaiheella",
    "Kierrä sisäänpäin: uloin kierros syttyy ensin",
    "Kolme kelloa: soita jokaista alhaalta",
    "Nappaa palaava pallo muiden lentäessä",
    "Seuraa välitystä avoimen keskustan ympäri",
    "Valo katoaa: opettele kenttä, kun vielä ehdit",
    "Pimeässä pallosi ja mailasi kantavat valoa",
    "Tulikärpäset: ytimet hehkuvat pimeässäkin",
    "Pyyhkäise mailan valo rannikon yli",
    "Lisää palloja, lisää valoa: {icon:multi} Monipallo",
    "Syväkenttä: jokainen himmeä piste on tiili",
    "Yhdistä tähdet: kirkkaat ovat ytimiä",
    "Portit himmenevät tahdissa: odota aukkoa",
    "Tik, tak: portit pitävät tahtia",
    "Korona aukeaa tahdissa: iske sisään",
    "Aaveportti ravistaa räjähdyksen pois: ajoita kipinä",
    "Pulsari: nopeat iskut, nopeat kädet",
    "Suljin aukeaa hetkeksi: ole valmis",
    "Puoliksi varjossa: porttipuoli pitää tahdin",
    "Sytytä aurinko, kun kuu on kiinteä",
    "Tuuli puhaltaa yhteen suuntaan: ratsasta sillä ytimille",
    "Valoverhot: pyyhi ne pois {icon:multi} Monipallolla",
    "Jokainen nauha on sidottu porttiin: katkaise molemmat puolikkaat",
    "Pitkä yö: tähtää kantamasi valon mukaan",
    "Ovista sisään ja ylös ruusuikkunalle",
    "Kaikki kerralla: tarkkaile ytimiä",
    "Iske renkaaseen, kun portit muuttuvat kiinteiksi",
    "Viimeinen kierros: hyödynnä jokainen aukko",
];
