//! French. Labels in capitals with accents kept (MÉDAILLES); a no-break
//! space before `:` and a narrow one before `?`, as French typography sets them.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Brisez le cosmos",
        ContinueJourney => "Poursuivre le voyage",
        NewJourney => "Nouveau voyage",
        SectorSelect => "Choix du secteur",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MÉDAILLES",
        StatBest => "RECORD",
        ActionServe => "Servir",
        ActionRelease => "Relâcher",
        ActionSelect => "Choisir",
        ActionResume => "Reprendre",
        ActionBack => "Retour",
        Fullscreen => "Plein écran",
        SectorsHeading => "Secteurs",
        PracticeNote => "L’entraînement ne modifie jamais votre voyage",
        MedalClear => "RÉUSSI",
        MedalClean => "SANS PERTE",
        MedalSwift => "RAPIDE",
        PlaySector => "Jouer le secteur {0}",
        UnlockHint => "Terminez le secteur {0} pour le débloquer",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTEUR {1}",
        Paused => "Pause",
        RetrySector => "Recommencer le secteur",
        MainMenu => "Menu principal",
        JourneyComplete => "Voyage terminé",
        OneMoreOrbit => "Encore une orbite\u{202f}?",
        StatPoints => "POINTS",
        SectorClear => "Secteur terminé",
        StatTime => "TEMPS",
        StatBonus => "BONUS",
        StatChain => "CHAÎNE",
        ExtraLife => "Chapitre terminé · +1 vie",
        NextSector => "Secteur suivant",
        BackToSectors => "Retour aux secteurs",
        SaveFailed => "Impossible de sauvegarder la progression",
        PerfTitle => "Performances / CPU",
        HelpResume => "Reprenez là où vous en étiez",
        HelpRetry => "Repartir du point de contrôle du secteur",
        HelpMainMenu => "Votre voyage est sauvegardé",
        HelpSectors => "Entraînez-vous sur un secteur ouvert",
        HelpNewJourney => "Recommencer au secteur 01 · les médailles restent",
        Settings => "Paramètres",
        HelpSettings => "Son, affichage, langue",
        SettingSound => "Son",
        SettingVolume => "Volume",
        SettingDisplay => "Affichage",
        SettingLanguage => "Langue",
        DisplayWindow => "Fenêtre",
        LanguageSystem => "Système",
        ActionAdjust => "Régler",
        SettingEffects => "Effets",
        SettingContrast => "Contraste",
        LookStandard => "Standard",
        EffectsReduced => "Réduits",
        ContrastHigh => "Élevé",
        KeySpace => "Espace",
        KeyEsc => "Échap",
        SectorsOf => "{0} secteurs sur {1}",
        TargetBest => "{0} · record {1}",
        LifeGained => "+1 vie",
        PresenceMenus => "Dans les menus",
        PresenceJourney => "Secteur {0} · {1}",
        PresencePractice => "Entraînement, secteur {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "AUBE",
            Chapter::Morning => "MATIN",
            Chapter::Zenith => "ZÉNITH",
            Chapter::GoldenHour => "HEURE DORÉE",
            Chapter::Afterlight => "CRÉPUSCULE",
            Chapter::BlueHour => "HEURE BLEUE",
            Chapter::Eclipse => "ÉCLIPSE",
            Chapter::Aurora => "AURORE",
        },
        PowerName(p) => match p {
            Power::Wide => "LARGE",
            Power::Slow => "LENT",
            Power::Multi => "MULTIBALLE",
            Power::Anchor => "ANCRE",
            Power::Phase => "PHASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continuer"),
        UnlockHint => Some("Verrouillé"),
        RetrySector => Some("Recommencer"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nouveau"),
        SectorSelect => Some("Secteurs"),
        NextSector => Some("Suivant"),
        BackToSectors => Some("Secteurs"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Reprendre"),
        PlaySector => Some("Jouer {0}"),
        Settings => Some("Options"),
        ActionServe => Some("Servir"),
        ActionRelease => Some("Lâcher"),
        ActionSelect => Some("Choisir"),
        ActionBack => Some("Retour"),
        ActionAdjust => Some("Régler"),
        StatBest => Some("RECORD"),
        StatMedals => Some("MÉDAILLES"),
        SectorsHeading => Some("Secteurs"),
        SaveFailed => Some("Non sauvegardé"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Espace"),
        HelpResume => Some("Retour au jeu"),
        HelpRetry => Some("Depuis le point de contrôle"),
        HelpMainMenu => Some("Voyage sauvegardé"),
        HelpSectors => Some("Entraînement"),
        HelpNewJourney => Some("Depuis le secteur 01"),
        HelpSettings => Some("Son, affichage"),
        SettingSound => Some("Son"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Affichage"),
        SettingLanguage => Some("Langue"),
        DisplayWindow => Some("Fenêtre"),
        Fullscreen => Some("Plein"),
        LanguageSystem => Some("Système"),
        ExtraLife => Some("+1 vie"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SECTEUR {1}"),
        SettingEffects => Some("Effets"),
        SettingContrast => Some("Contraste"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Moins"),
        ContrastHigh => Some("Élevé"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Première lueur",
    "Dérive",
    "Horizon",
    "Miroitement",
    "Alouette",
    "Lanternes",
    "Marée",
    "Lever du soleil",
    "Satellites",
    "Point de rosée",
    "Ouverture",
    "Cloître",
    "Clé de voûte",
    "Cadran solaire",
    "Sténopé",
    "Rose des vents",
    "Sillage",
    "Filament",
    "Méridien",
    "Cascade",
    "Fondu enchaîné",
    "Lacets",
    "Solstice",
    "Résonance",
    "Prisme",
    "Alvéoles",
    "Embruns",
    "Contre-courant",
    "Moisson",
    "Kaléidoscope",
    "Tapisserie",
    "Longues ombres",
    "Rémanence",
    "Chrysalide",
    "Géode",
    "Parallaxe",
    "Citadelle",
    "Nautilus",
    "Vêpres",
    "Supernova",
    "Lever de lune",
    "Entre chien et loup",
    "Lueur de lampe",
    "Lucioles",
    "Phare",
    "Nocturne",
    "Champ profond",
    "Constellation",
    "Pénombre",
    "Métronome",
    "Couronne solaire",
    "Syzygie",
    "Pulsar",
    "Obturateur",
    "Umbra",
    "Totalité",
    "Vent solaire",
    "Aurore boréale",
    "Rubans",
    "Nuit polaire",
    "Cathédrale",
    "Chatoiement",
    "Singularité",
    "Retour",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Lueur",
    "Dérive",
    "Horizon",
    "Miroitement",
    "Alouette",
    "Lanternes",
    "Marée",
    "Soleil",
    "Satellites",
    "Rosée",
    "Ouverture",
    "Cloître",
    "Clé",
    "Cadran",
    "Sténopé",
    "Rose",
    "Sillage",
    "Filament",
    "Méridien",
    "Cascade",
    "Fondu",
    "Lacets",
    "Solstice",
    "Résonance",
    "Prisme",
    "Alvéoles",
    "Embruns",
    "Ressac",
    "Moisson",
    "Kaléido",
    "Tapisserie",
    "Ombres",
    "Rémanence",
    "Chrysalide",
    "Géode",
    "Parallaxe",
    "Citadelle",
    "Nautilus",
    "Vêpres",
    "Supernova",
    "Lune",
    "Brune",
    "Lampe",
    "Lucioles",
    "Phare",
    "Nocturne",
    "Champ profond",
    "Étoiles",
    "Pénombre",
    "Métronome",
    "Couronne",
    "Syzygie",
    "Pulsar",
    "Obturateur",
    "Umbra",
    "Totalité",
    "Vent",
    "Boréale",
    "Rubans",
    "Nuit polaire",
    "Cathédrale",
    "Chatoiement",
    "Singularité",
    "Retour",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Large\u{a0}: attrapez la capsule qui tombe",
    "{icon:slow} Lent\u{a0}: attrapez-la et la balle ralentit",
    "Dirigez\u{a0}: les bords de la raquette envoient la balle au large",
    "Étincelles isolées\u{a0}: traquez-les une à une",
    "Envoyez la balle dans les ailes dégagées",
    "Dégagez chaque lanterne par en dessous",
    "Suivez la houle\u{a0}: jouez les rebonds sur les murs latéraux",
    "Grignotez le soleil par en dessous, rangée après rangée",
    "{icon:anchor} Ancre\u{a0}: attrapez la balle, visez, puis relâchez-la",
    "Les briques blindées encaissent deux coups\u{a0}: surveillez les bords",
    "{icon:anchor} Visez à travers la brèche du mur",
    "Une seule porte\u{a0}: envoyez la balle dans la cour",
    "Faites sauter la clé de voûte et l’arche s’ouvre",
    "Lisez les angles\u{a0}: chaque ombre est un tir",
    "{icon:anchor} Un seul sténopé étroit\u{a0}: retenez, visez, relâchez",
    "Chaque point cardinal mène au cœur",
    "Noyaux ambrés\u{a0}: chaque explosion touche ses quatre voisins",
    "Touchez le filament n’importe où\u{a0}: il brûle dans les deux sens",
    "Coupez le terrain le long du méridien",
    "Lancez la cascade par l’une ou l’autre extrémité",
    "Ouvrez une voie à travers les deux lignes de relais",
    "Trois lignes de relais\u{a0}: un tir net pour chacune",
    "L’anneau brûle en entier\u{a0}: trouvez un chemin jusqu’à son bord",
    "Les noyaux voisins propagent la réaction",
    "{icon:multi} Multiballe\u{a0}: trois balles, une seule ouverture",
    "Un noyau dans chaque alvéole\u{a0}: fendez-les",
    "Des embruns partout\u{a0}: lâchez trois balles",
    "Percez jusqu’aux poches derrière le blindage",
    "Terrain plein\u{a0}: {icon:multi} Multiballe le nettoie vite",
    "Des miroirs partout\u{a0}: brisez un côté, puis son jumeau",
    "Tirez sur un fil et la trame se défait",
    "Percez le sol et allumez la longue mèche",
    "{icon:phase} Phase\u{a0}: trois contacts de brique sans rebond",
    "{icon:phase} Phase traverse la coque jusqu’au noyau",
    "Fendez une géode et ses cristaux s’illuminent",
    "Percez la coque, puis allumez la voie intérieure",
    "Entrez par la porte, ou à travers le mur avec {icon:phase} Phase",
    "En spirale\u{a0}: la boucle extérieure s’allume d’abord",
    "Trois cloches\u{a0}: faites sonner chacune par en dessous",
    "Rattrapez une balle pendant que les autres continuent",
    "Suivez le relais autour du centre dégagé",
    "La lumière décline\u{a0}: apprenez le terrain tant que vous le pouvez",
    "Dans le noir, votre balle et votre raquette portent la lumière",
    "Lucioles\u{a0}: les noyaux brillent même dans le noir",
    "Balayez la côte de la lumière de la raquette",
    "Plus de balles, plus de lumière\u{a0}: {icon:multi} Multiballe",
    "Champ profond\u{a0}: chaque point pâle est une brique",
    "Reliez les étoiles\u{a0}: les plus brillantes sont des noyaux",
    "Les portes s’effacent en rythme\u{a0}: attendez l’ouverture",
    "Tic, tac\u{a0}: les portes battent la mesure",
    "La couronne s’ouvre en rythme\u{a0}: frappez à l’intérieur",
    "Une porte fantôme encaisse l’explosion\u{a0}: soignez le timing",
    "Un pulsar\u{a0}: rythme vif, mains vives",
    "L’obturateur s’ouvre un instant\u{a0}: soyez prêt",
    "À moitié dans l’ombre\u{a0}: le côté à portes bat la mesure",
    "Allumez le soleil tant que la lune est pleine",
    "Le vent souffle dans un seul sens\u{a0}: suivez-le jusqu’aux noyaux",
    "Rideaux de lumière\u{a0}: balayez-les avec {icon:multi} Multiballe",
    "Chaque ruban tient à une porte\u{a0}: coupez les deux moitiés",
    "La longue nuit\u{a0}: visez à la lumière que vous portez",
    "Entrez par les portes, montez jusqu’à la rosace",
    "Tout à la fois\u{a0}: surveillez les noyaux",
    "Frappez l’anneau quand les portes se solidifient",
    "Une dernière orbite\u{a0}: chaque ouverture compte",
];
