//! French. Labels in capitals with accents kept (MÉDAILLES); a no-break
//! space before `:` and a narrow one before `?`, as French typography sets them.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Brisez le cosmos",
        ContinueJourney => "Poursuivre le voyage",
        NewJourney => "Nouveau voyage",
        SectorSelect => "Choix du secteur",
        ContinueDetail => "Secteur {0} · {1} · {2}",
        StatSectors => "SECTEURS",
        StatMedals => "MÉDAILLES",
        StatBest => "RECORD",
        Fraction => "{0} / {1}",
        KeysMove => "Souris ou flèches pour se déplacer",
        KeysServe => "Espace ou clic pour servir",
        KeysPause => "Échap pour la pause",
        KeysRelease => "Clic ou Espace pour relâcher",
        KeysBrowse => "Flèches pour parcourir",
        KeysPlay => "Entrée pour jouer",
        KeysBack => "Échap pour revenir",
        KeysContinue => "Entrée ou clic pour continuer",
        PadMove => "Stick ou croix pour se déplacer",
        PadBrowse => "Croix pour parcourir",
        ActionServe => "Servir",
        ActionPause => "Pause",
        ActionRelease => "Relâcher",
        ActionSelect => "Choisir",
        ActionResume => "Reprendre",
        ActionRetry => "Réessayer",
        ActionPlay => "Jouer",
        ActionBack => "Retour",
        ActionContinue => "Continuer",
        SoundOn => "Son activé",
        SoundOff => "Son coupé",
        Volume => "Volume {0}",
        Fullscreen => "Plein écran",
        SectorsHeading => "Secteurs",
        PracticeNote => "L’entraînement ne modifie jamais votre voyage",
        NoTime => "--:--",
        SwiftTarget => "Temps cible {0}",
        BestTime => "Record {0}",
        MedalClear => "RÉUSSI",
        MedalClean => "SANS PERTE",
        MedalSwift => "RAPIDE",
        MedalClearHow => "Terminer le secteur",
        MedalCleanHow => "Ne perdre aucune vie",
        MedalSwiftHow => "Battre le temps cible",
        PlaySector => "Jouer le secteur {0}",
        ClearPreviousFirst => "Terminez d’abord le secteur précédent",
        Score => "SCORE",
        Lives => "VIES",
        SectorNumber => "SECTEUR {0}",
        PracticeNumber => "ENTRAÎNEMENT {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTEUR {1}",
        Paused => "Pause",
        RetrySector => "Recommencer le secteur",
        MainMenu => "Menu principal",
        RetryNote => "Recommencer repart du point de contrôle",
        JourneyComplete => "Voyage terminé",
        OneMoreOrbit => "Encore une orbite\u{202f}?",
        StatPoints => "POINTS",
        ProgressSaved => "Votre progression est sauvegardée",
        SectorClear => "Secteur terminé",
        StatTime => "TEMPS",
        StatBonus => "BONUS",
        StatBestChain => "CHAÎNE MAX",
        ExtraLife => "Chapitre terminé · vie supplémentaire",
        NextSector => "Secteur suivant",
        BackToSectors => "Retour aux secteurs",
        SaveFailed => "Impossible de sauvegarder la progression",
        PerfTitle => "Performances / CPU",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "AUBE",
            Chapter::BlueHour => "HEURE BLEUE",
            Chapter::Afterlight => "CRÉPUSCULE",
        },
        PowerName(p) => match p {
            Power::Wide => "Large",
            Power::Slow => "Lent",
            Power::Multi => "Multiballe",
            Power::Anchor => "Ancre",
            Power::Phase => "Phase",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1} · {2}"),
        ContinueJourney => Some("Continuer"),
        ClearPreviousFirst => Some("Verrouillé"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Première lueur",
    "Satellites",
    "Sillage",
    "Résonance",
    "Prisme",
    "Fondu enchaîné",
    "Contre-courant",
    "Lever de lune",
    "Rémanence",
    "Parallaxe",
    "Supernova",
    "Retour",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Large et {icon:slow} Lent\u{a0}: attrapez les capsules qui tombent",
    "{icon:anchor} Ancre\u{a0}: attrapez la balle, visez, puis relâchez-la",
    "Noyaux ambrés\u{a0}: chaque explosion touche ses quatre voisins",
    "Les noyaux voisins propagent la réaction",
    "{icon:multi} Multiballe\u{a0}: trois balles, une seule ouverture",
    "Ouvrez une voie à travers les deux lignes de relais",
    "Percez jusqu’aux poches derrière le blindage",
    "Suivez le relais autour du centre dégagé",
    "{icon:phase} Phase\u{a0}: trois contacts de brique sans rebond",
    "Percez la coque, puis allumez la voie intérieure",
    "Rattrapez une balle pendant que les autres continuent",
    "Une dernière orbite\u{a0}: chaque ouverture compte",
];
