//! French. Labels in capitals with accents kept (MÉDAILLES); a no-break
//! space before `:` and a narrow one before `?`, as French typography sets them.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Brisez le cosmos",
        ContinueJourney => "Poursuivre le voyage",
        NewJourney => "Nouveau voyage",
        SectorSelect => "Choix du secteur",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MÉDAILLES",
        StatBest => "RECORD",
        ActionServe => "Servir",
        ActionRelease => "Relâcher",
        ActionSelect => "Choisir",
        ActionResume => "Reprendre",
        ActionBack => "Retour",
        Fullscreen => "Plein écran",
        SectorsHeading => "Secteurs",
        PracticeNote => "L’entraînement ne modifie jamais votre voyage",
        MedalClear => "RÉUSSI",
        MedalClean => "SANS PERTE",
        MedalSwift => "RAPIDE",
        PlaySector => "Jouer le secteur {0}",
        UnlockHint => "Terminez le secteur {0} pour le débloquer",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTEUR {1}",
        Paused => "Pause",
        RetrySector => "Recommencer le secteur",
        MainMenu => "Menu principal",
        JourneyComplete => "Voyage terminé",
        OneMoreOrbit => "Encore une orbite\u{202f}?",
        StatPoints => "POINTS",
        SectorClear => "Secteur terminé",
        StatTime => "TEMPS",
        StatBonus => "BONUS",
        StatChain => "CHAÎNE",
        ExtraLife => "Chapitre terminé · +1 vie",
        NextSector => "Secteur suivant",
        BackToSectors => "Retour aux secteurs",
        SaveFailed => "Impossible de sauvegarder la progression",
        PerfTitle => "Performances / CPU",
        HelpResume => "Reprenez là où vous en étiez",
        HelpRetry => "Repartir du point de contrôle du secteur",
        HelpMainMenu => "Votre voyage est sauvegardé",
        HelpSectors => "Entraînez-vous sur un secteur ouvert",
        HelpNewJourney => "Recommencer au secteur 01 · les médailles restent",
        Settings => "Paramètres",
        HelpSettings => "Son, affichage, langue",
        SettingSound => "Son",
        SettingVolume => "Volume",
        SettingDisplay => "Affichage",
        SettingLanguage => "Langue",
        DisplayWindow => "Fenêtre",
        LanguageSystem => "Système",
        ActionAdjust => "Régler",
        KeySpace => "Espace",
        KeyEsc => "Échap",
        SectorsOf => "{0} secteurs sur {1}",
        TargetBest => "{0} · record {1}",
        LifeGained => "+1 vie",
        PresenceMenus => "Dans les menus",
        PresenceJourney => "Secteur {0} · {1}",
        PresencePractice => "Entraînement, secteur {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "AUBE",
            Chapter::BlueHour => "HEURE BLEUE",
            Chapter::Afterlight => "CRÉPUSCULE",
        },
        PowerName(p) => match p {
            Power::Wide => "LARGE",
            Power::Slow => "LENT",
            Power::Multi => "MULTIBALLE",
            Power::Anchor => "ANCRE",
            Power::Phase => "PHASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continuer"),
        UnlockHint => Some("Verrouillé"),
        RetrySector => Some("Recommencer"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nouveau"),
        SectorSelect => Some("Secteurs"),
        NextSector => Some("Suivant"),
        BackToSectors => Some("Secteurs"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Reprendre"),
        PlaySector => Some("Jouer {0}"),
        Settings => Some("Options"),
        ActionServe => Some("Servir"),
        ActionRelease => Some("Lâcher"),
        ActionSelect => Some("Choisir"),
        ActionBack => Some("Retour"),
        ActionAdjust => Some("Régler"),
        StatBest => Some("RECORD"),
        StatMedals => Some("MÉDAILLES"),
        SectorsHeading => Some("Secteurs"),
        SaveFailed => Some("Non sauvegardé"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Espace"),
        HelpResume => Some("Retour au jeu"),
        HelpRetry => Some("Depuis le point de contrôle"),
        HelpMainMenu => Some("Voyage sauvegardé"),
        HelpSectors => Some("Entraînement"),
        HelpNewJourney => Some("Depuis le secteur 01"),
        HelpSettings => Some("Son, affichage"),
        SettingSound => Some("Son"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Affichage"),
        SettingLanguage => Some("Langue"),
        DisplayWindow => Some("Fenêtre"),
        Fullscreen => Some("Plein"),
        LanguageSystem => Some("Système"),
        ExtraLife => Some("+1 vie"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SECTEUR {1}"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Première lueur",
    "Satellites",
    "Sillage",
    "Résonance",
    "Prisme",
    "Fondu enchaîné",
    "Contre-courant",
    "Lever de lune",
    "Rémanence",
    "Parallaxe",
    "Supernova",
    "Retour",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Lueur",
    "Satellites",
    "Sillage",
    "Résonance",
    "Prisme",
    "Fondu",
    "Ressac",
    "Lune",
    "Rémanence",
    "Parallaxe",
    "Supernova",
    "Retour",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Large et {icon:slow} Lent\u{a0}: attrapez les capsules qui tombent",
    "{icon:anchor} Ancre\u{a0}: attrapez la balle, visez, puis relâchez-la",
    "Noyaux ambrés\u{a0}: chaque explosion touche ses quatre voisins",
    "Les noyaux voisins propagent la réaction",
    "{icon:multi} Multiballe\u{a0}: trois balles, une seule ouverture",
    "Ouvrez une voie à travers les deux lignes de relais",
    "Percez jusqu’aux poches derrière le blindage",
    "Suivez le relais autour du centre dégagé",
    "{icon:phase} Phase\u{a0}: trois contacts de brique sans rebond",
    "Percez la coque, puis allumez la voie intérieure",
    "Rattrapez une balle pendant que les autres continuent",
    "Une dernière orbite\u{a0}: chaque ouverture compte",
];
