//! Hungarian. Informal *te*; hints read "action: keys". Ordinal sector
//! numbers take a period (`03. szektor`); labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Zúzd szét a kozmoszt",
        ContinueJourney => "Utazás folytatása",
        NewJourney => "Új utazás",
        SectorSelect => "Szektorválasztás",
        ContinueDetail => "{0} · {1}",
        StatMedals => "ÉRMEK",
        StatBest => "REKORD",
        ActionServe => "Indítás",
        ActionRelease => "Elengedés",
        ActionSelect => "Kiválasztás",
        ActionResume => "Folytatás",
        ActionBack => "Vissza",
        Fullscreen => "Teljes képernyő",
        SectorsHeading => "Szektorok",
        PracticeNote => "A gyakorlás sosem változtat az utazásodon",
        MedalClear => "TELJESÍTVE",
        MedalClean => "HIBÁTLAN",
        MedalSwift => "VILLÁM",
        PlaySector => "{0}. szektor indítása",
        UnlockHint => "Nyitás: teljesítsd a(z) {0}. szektort",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · {1}. SZEKTOR",
        Paused => "Szünet",
        RetrySector => "Szektor újra",
        MainMenu => "Főmenü",
        JourneyComplete => "Utazás teljesítve",
        OneMoreOrbit => "Még egy kör?",
        StatPoints => "PONTOK",
        SectorClear => "Szektor teljesítve",
        StatTime => "IDŐ",
        StatBonus => "BÓNUSZ",
        StatChain => "LÁNC",
        ExtraLife => "Fejezet teljesítve · +1 élet",
        NextSector => "Következő szektor",
        BackToSectors => "Vissza a szektorokhoz",
        SaveFailed => "Az előrehaladást nem sikerült menteni",
        PerfTitle => "Teljesítmény / CPU",
        HelpResume => "Folytasd ott, ahol abbahagytad",
        HelpRetry => "Újra a szektor ellenőrzőpontjától",
        HelpMainMenu => "Az utazásod mentve",
        HelpSectors => "Gyakorolj bármely nyitott szektorban",
        HelpNewJourney => "Újra a 01. szektortól · az érmek maradnak",
        Settings => "Beállítások",
        HelpSettings => "Hang, kijelző, nyelv",
        SettingSound => "Hang",
        SettingVolume => "Hangerő",
        SettingDisplay => "Kijelző",
        SettingLanguage => "Nyelv",
        DisplayWindow => "Ablak",
        LanguageSystem => "Rendszer",
        ActionAdjust => "Állítás",
        KeySpace => "Szóköz",
        KeyEsc => "Esc",
        SectorsOf => "{0}/{1} szektor",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 élet",
        PresenceMenus => "A menükben",
        PresenceJourney => "{0}. szektor · {1}",
        PresencePractice => "Gyakorol: {0}. szektor · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "HAJNAL",
            Chapter::BlueHour => "KÉK ÓRA",
            Chapter::Afterlight => "ALKONY",
        },
        PowerName(p) => match p {
            Power::Wide => "SZÉLES",
            Power::Slow => "LASSÚ",
            Power::Multi => "TÖBBLABDA",
            Power::Anchor => "HORGONY",
            Power::Phase => "FÁZIS",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Folytatás"),
        UnlockHint => Some("Zárolva"),
        RetrySector => Some("Újra"),
        MainMenu => Some("Menü"),
        NewJourney => Some("Új"),
        SectorSelect => Some("Szektorok"),
        NextSector => Some("Tovább"),
        BackToSectors => Some("Szektorok"),
        Settings => Some("Opciók"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Folytatás"),
        PlaySector => Some("{0}. szektor"),
        ActionServe => Some("Indítás"),
        ActionRelease => Some("Elenged"),
        ActionSelect => Some("Választ"),
        ActionBack => Some("Vissza"),
        ActionAdjust => Some("Állítás"),
        StatBest => Some("REKORD"),
        StatMedals => Some("ÉRMEK"),
        SectorsHeading => Some("Szektorok"),
        SaveFailed => Some("Nincs mentve"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Szóköz"),
        HelpResume => Some("Vissza a játékba"),
        HelpRetry => Some("Ellenőrzőponttól"),
        HelpMainMenu => Some("Utazás mentve"),
        HelpSectors => Some("Gyakorlás"),
        HelpNewJourney => Some("A 01. szektortól"),
        HelpSettings => Some("Hang, kijelző"),
        SettingSound => Some("Hang"),
        SettingVolume => Some("Hangerő"),
        SettingDisplay => Some("Kijelző"),
        SettingLanguage => Some("Nyelv"),
        DisplayWindow => Some("Ablak"),
        Fullscreen => Some("Teljes"),
        LanguageSystem => Some("Rendszer"),
        ExtraLife => Some("+1 élet"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("{1}. SZEKTOR"),
        JourneyComplete => Some("Teljesítve"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Első fény",
    "Műholdak",
    "Szélárnyék",
    "Rezonancia",
    "Prizma",
    "Áttűnés",
    "Örvény",
    "Holdkelte",
    "Utófény",
    "Parallaxis",
    "Szupernóva",
    "Hazatérés",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Első fény",
    "Műholdak",
    "Szélárnyék",
    "Rezonancia",
    "Prizma",
    "Áttűnés",
    "Örvény",
    "Holdkelte",
    "Utófény",
    "Parallaxis",
    "Szupernóva",
    "Hazatérés",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Széles és {icon:slow} Lassú: kapd el a hulló kapszulákat",
    "{icon:anchor} Horgony: kapd el a labdát, célozz, majd engedd el",
    "Borostyánmagok: minden robbanás eléri a négy szomszédot",
    "A szomszédos magok továbbviszik a reakciót",
    "{icon:multi} Többlabda: három labda, egy rés",
    "Nyiss utat a két reléláncon át",
    "Törj be a páncél mögötti zsebekbe",
    "Kövesd a relét a nyitott közép körül",
    "{icon:phase} Fázis: három téglaérintés visszapattanás nélkül",
    "Törd át a héjat, aztán gyújtsd be a belső utat",
    "Kapj el egy visszatérő labdát, amíg a többi repül",
    "Egy utolsó kör: használj ki minden rést",
];
