//! Hungarian. Informal *te*; hints read "action: keys". Ordinal sector
//! numbers take a period (`03. szektor`); labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Zúzd szét a kozmoszt",
        ContinueJourney => "Utazás folytatása",
        NewJourney => "Új utazás",
        SectorSelect => "Szektorválasztás",
        ContinueDetail => "{0} · {1}",
        StatMedals => "ÉRMEK",
        StatBest => "REKORD",
        ActionServe => "Indítás",
        ActionRelease => "Elengedés",
        ActionSelect => "Kiválasztás",
        ActionResume => "Folytatás",
        ActionBack => "Vissza",
        Fullscreen => "Teljes képernyő",
        SectorsHeading => "Szektorok",
        PracticeNote => "A gyakorlás sosem változtat az utazásodon",
        MedalClear => "TELJESÍTVE",
        MedalClean => "HIBÁTLAN",
        MedalSwift => "VILLÁM",
        PlaySector => "{0}. szektor indítása",
        UnlockHint => "Nyitás: teljesítsd a(z) {0}. szektort",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · {1}. SZEKTOR",
        Paused => "Szünet",
        RetrySector => "Szektor újra",
        MainMenu => "Főmenü",
        JourneyComplete => "Utazás teljesítve",
        OneMoreOrbit => "Még egy kör?",
        StatPoints => "PONTOK",
        SectorClear => "Szektor teljesítve",
        StatTime => "IDŐ",
        StatBonus => "BÓNUSZ",
        StatChain => "LÁNC",
        ExtraLife => "Fejezet teljesítve · +1 élet",
        NextSector => "Következő szektor",
        BackToSectors => "Vissza a szektorokhoz",
        SaveFailed => "Az előrehaladást nem sikerült menteni",
        PerfTitle => "Teljesítmény / CPU",
        HelpResume => "Folytasd ott, ahol abbahagytad",
        HelpRetry => "Újra a szektor ellenőrzőpontjától",
        HelpMainMenu => "Az utazásod mentve",
        HelpSectors => "Gyakorolj bármely nyitott szektorban",
        HelpNewJourney => "Újra a 01. szektortól · az érmek maradnak",
        Settings => "Beállítások",
        HelpSettings => "Hang, kijelző, nyelv",
        SettingSound => "Hang",
        SettingVolume => "Hangerő",
        SettingDisplay => "Kijelző",
        SettingLanguage => "Nyelv",
        DisplayWindow => "Ablak",
        LanguageSystem => "Rendszer",
        ActionAdjust => "Állítás",
        SettingEffects => "Effektek",
        SettingContrast => "Kontraszt",
        LookStandard => "Normál",
        EffectsReduced => "Csökkentett",
        ContrastHigh => "Magas",
        KeySpace => "Szóköz",
        KeyEsc => "Esc",
        SectorsOf => "{0}/{1} szektor",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 élet",
        PresenceMenus => "A menükben",
        PresenceJourney => "{0}. szektor · {1}",
        PresencePractice => "Gyakorol: {0}. szektor · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "HAJNAL",
            Chapter::Morning => "REGGEL",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "ARANYÓRA",
            Chapter::Afterlight => "ALKONY",
            Chapter::BlueHour => "KÉK ÓRA",
            Chapter::Eclipse => "FOGYATKOZÁS",
            Chapter::Aurora => "AURÓRA",
        },
        PowerName(p) => match p {
            Power::Wide => "SZÉLES",
            Power::Slow => "LASSÚ",
            Power::Multi => "TÖBBLABDA",
            Power::Anchor => "HORGONY",
            Power::Phase => "FÁZIS",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Folytatás"),
        UnlockHint => Some("Zárolva"),
        RetrySector => Some("Újra"),
        MainMenu => Some("Menü"),
        NewJourney => Some("Új"),
        SectorSelect => Some("Szektorok"),
        NextSector => Some("Tovább"),
        BackToSectors => Some("Szektorok"),
        Settings => Some("Opciók"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Folytatás"),
        PlaySector => Some("{0}. szektor"),
        ActionServe => Some("Indítás"),
        ActionRelease => Some("Elenged"),
        ActionSelect => Some("Választ"),
        ActionBack => Some("Vissza"),
        ActionAdjust => Some("Állítás"),
        SettingEffects => Some("Effektek"),
        SettingContrast => Some("Kontraszt"),
        LookStandard => Some("Normál"),
        EffectsReduced => Some("Kevesebb"),
        ContrastHigh => Some("Magas"),
        StatBest => Some("REKORD"),
        StatMedals => Some("ÉRMEK"),
        SectorsHeading => Some("Szektorok"),
        SaveFailed => Some("Nincs mentve"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Szóköz"),
        HelpResume => Some("Vissza a játékba"),
        HelpRetry => Some("Ellenőrzőponttól"),
        HelpMainMenu => Some("Utazás mentve"),
        HelpSectors => Some("Gyakorlás"),
        HelpNewJourney => Some("A 01. szektortól"),
        HelpSettings => Some("Hang, kijelző"),
        SettingSound => Some("Hang"),
        SettingVolume => Some("Hangerő"),
        SettingDisplay => Some("Kijelző"),
        SettingLanguage => Some("Nyelv"),
        DisplayWindow => Some("Ablak"),
        Fullscreen => Some("Teljes"),
        LanguageSystem => Some("Rendszer"),
        ExtraLife => Some("+1 élet"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("{1}. SZEKTOR"),
        JourneyComplete => Some("Teljesítve"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Első fény",
    "Sodródás",
    "Látóhatár",
    "Villanás",
    "Pacsirta",
    "Lámpások",
    "Dagály",
    "Napkelte",
    "Műholdak",
    "Harmatpont",
    "Rekesz",
    "Kolostor",
    "Zárókő",
    "Napóra",
    "Tűlyuk",
    "Szélrózsa",
    "Szélárnyék",
    "Izzószál",
    "Délkör",
    "Zuhatag",
    "Áttűnés",
    "Szerpentin",
    "Napforduló",
    "Rezonancia",
    "Prizma",
    "Méhsejt",
    "Tajték",
    "Örvény",
    "Aratás",
    "Kaleidoszkóp",
    "Kárpit",
    "Hosszú árnyak",
    "Utófény",
    "Báb",
    "Geoda",
    "Parallaxis",
    "Fellegvár",
    "Nautilus",
    "Vecsernye",
    "Szupernóva",
    "Holdkelte",
    "Szürkület",
    "Lámpafény",
    "Szentjánosbogarak",
    "Világítótorony",
    "Noktürn",
    "Mélyég",
    "Csillagkép",
    "Félárnyék",
    "Metronóm",
    "Korona",
    "Szizigia",
    "Pulsar",
    "Zár",
    "Umbra",
    "Teljesség",
    "Napszél",
    "Sarki fény",
    "Szalagok",
    "Sarki éjszaka",
    "Katedrális",
    "Csillámlás",
    "Szingularitás",
    "Hazatérés",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Első fény",
    "Sodródás",
    "Látóhatár",
    "Villanás",
    "Pacsirta",
    "Lámpások",
    "Dagály",
    "Napkelte",
    "Műholdak",
    "Harmat",
    "Rekesz",
    "Kolostor",
    "Zárókő",
    "Napóra",
    "Tűlyuk",
    "Szélrózsa",
    "Szélárnyék",
    "Szál",
    "Délkör",
    "Zuhatag",
    "Áttűnés",
    "Szerpentin",
    "Napforduló",
    "Rezonancia",
    "Prizma",
    "Méhsejt",
    "Tajték",
    "Örvény",
    "Aratás",
    "Kaleido",
    "Kárpit",
    "Árnyak",
    "Utófény",
    "Báb",
    "Geoda",
    "Parallaxis",
    "Fellegvár",
    "Nautilus",
    "Vecsernye",
    "Szupernóva",
    "Holdkelte",
    "Szürkület",
    "Lámpafény",
    "Bogarak",
    "Torony",
    "Noktürn",
    "Mélyég",
    "Csillagok",
    "Félárnyék",
    "Metronóm",
    "Korona",
    "Szizigia",
    "Pulsar",
    "Zár",
    "Umbra",
    "Teljesség",
    "Napszél",
    "Fény",
    "Szalagok",
    "Sarki éj",
    "Katedrális",
    "Csillám",
    "Szingularitás",
    "Hazatérés",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Széles: kapd el a hulló kapszulát",
    "{icon:slow} Lassú: kapd el, és a labda lelassul",
    "Irányíts: az ütő szélei szélesen lövik el a labdát",
    "Magányos szikrák: vadászd le mindet",
    "Küldd a labdát felfelé a nyitott szárnyakon",
    "Tisztítsd meg alulról az összes lámpást",
    "Lovagold meg a hullámot: pattintsd az oldalfalakról",
    "Faragd a napot alulról, sorról sorra",
    "{icon:anchor} Horgony: kapd el a labdát, célozz, majd engedd el",
    "A páncélozott téglák két találatot bírnak: figyeld a széleket",
    "{icon:anchor} Célozz a fal résén át",
    "Egyetlen ajtó: küldd a labdát az udvarba",
    "Üsd ki a zárókövet, és az ív megnyílik",
    "Olvasd a szögeket: minden árnyék egy lövés",
    "{icon:anchor} Egyetlen keskeny tűlyuk: tartsd, célozz, engedd el",
    "Minden égtáj a szívhez vezet",
    "Borostyánmagok: minden robbanás eléri a négy szomszédot",
    "Érintsd meg az izzószálat bárhol: mindkét irányba ég",
    "Oszd ketté a mezőt a délkör mentén",
    "Indítsd a zuhatagot bármelyik végén",
    "Nyiss utat a két reléláncon át",
    "Három relésor: soronként egy tiszta lövés",
    "A gyűrű egészében ég: találd meg az utat a pereméig",
    "A szomszédos magok továbbviszik a reakciót",
    "{icon:multi} Többlabda: három labda, egy rés",
    "Mag minden cellában: törd fel őket",
    "Tajték mindenütt: szabadíts el három labdát",
    "Törj be a páncél mögötti zsebekbe",
    "Teli mező: a {icon:multi} Többlabda gyorsan letarolja",
    "Tükrök mindenütt: törd az egyik oldalt, aztán az ikerpárját",
    "Húzz meg egy szálat, és szétfeslik a szövet",
    "Törj át a padlón, és gyújtsd meg a hosszú kanócot",
    "{icon:phase} Fázis: három téglaérintés visszapattanás nélkül",
    "{icon:phase} Fázis átsiklik a héjon egészen a magig",
    "Törj fel egy geodát, és kristályai felizzanak",
    "Törd át a héjat, aztán gyújtsd be a belső utat",
    "Be a kapun, vagy át a falon {icon:phase} Fázissal",
    "Spirálisan befelé: a külső menet gyullad ki először",
    "Három harang: üss meg mindet alulról",
    "Kapj el egy visszatérő labdát, amíg a többi repül",
    "Kövesd a relét a nyitott közép körül",
    "A fény elmegy: tanuld meg a mezőt, amíg tudod",
    "A sötétben a labdád és az ütőd viszi a fényt",
    "Szentjánosbogarak: a magok a sötétben is izzanak",
    "Söpörd végig az ütő fényét a parton",
    "Több labda, több fény: {icon:multi} Többlabda",
    "Mélyég: minden halvány pötty egy tégla",
    "Kösd össze a csillagokat: a fényesek magok",
    "A kapuk ütemre halványulnak: várd meg a rést",
    "Tik-tak: a kapuk tartják az időt",
    "A korona ütemre nyílik: ütés befelé",
    "A szellemkapu lerázza a robbanást: időzítsd a szikrát",
    "Egy pulsar: gyors ütemek, gyors kezek",
    "A zár egy pillanatra kinyílik: légy készen",
    "Félig árnyékban: a kapus oldal tartja az ütemet",
    "Gyújtsd be a napot, amíg a hold szilárd",
    "A szél egy irányba fúj: lovagold meg a magokig",
    "Fényfüggönyök: söpörd le őket {icon:multi} Többlabdával",
    "Minden szalag egy kapuhoz van kötve: vágd el mindkét felét",
    "A hosszú éjszaka: a hordozott fény szerint célozz",
    "Be az ajtókon, fel a rózsaablakhoz",
    "Minden egyszerre: figyeld a magokat",
    "Üsd a gyűrűt, amikor a kapuk szilárddá válnak",
    "Egy utolsó kör: használj ki minden rést",
];
