//! Indonesian. Informal *-mu*, as Indonesian games address players; labels
//! in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Hancurkan kosmos",
        ContinueJourney => "Lanjutkan perjalanan",
        NewJourney => "Perjalanan baru",
        SectorSelect => "Pilih sektor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALI",
        StatBest => "REKOR",
        ActionServe => "Servis",
        ActionRelease => "Lepas",
        ActionSelect => "Pilih",
        ActionResume => "Lanjutkan",
        ActionBack => "Kembali",
        Fullscreen => "Layar penuh",
        SectorsHeading => "Sektor",
        PracticeNote => "Latihan tidak pernah mengubah perjalananmu",
        MedalClear => "TUNTAS",
        MedalClean => "BERSIH",
        MedalSwift => "KILAT",
        PlaySector => "Mainkan sektor {0}",
        UnlockHint => "Selesaikan sektor {0} untuk membuka",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Dijeda",
        RetrySector => "Ulangi sektor",
        MainMenu => "Menu utama",
        JourneyComplete => "Perjalanan selesai",
        OneMoreOrbit => "Satu orbit lagi?",
        StatPoints => "POIN",
        SectorClear => "Sektor tuntas",
        StatTime => "WAKTU",
        StatBonus => "BONUS",
        StatChain => "RANTAI",
        ExtraLife => "Bab selesai · +1 nyawa",
        NextSector => "Sektor berikutnya",
        BackToSectors => "Kembali ke sektor",
        SaveFailed => "Kemajuan tidak dapat disimpan",
        PerfTitle => "Performa / CPU",
        HelpResume => "Lanjutkan dari posisi terakhir",
        HelpRetry => "Mulai lagi dari titik simpan sektor",
        HelpMainMenu => "Perjalananmu tersimpan",
        HelpSectors => "Latihan di sektor mana pun yang terbuka",
        HelpNewJourney => "Mulai lagi dari sektor 01 · medali tetap",
        Settings => "Pengaturan",
        HelpSettings => "Suara, layar, bahasa",
        SettingSound => "Suara",
        SettingVolume => "Volume",
        SettingDisplay => "Layar",
        SettingLanguage => "Bahasa",
        DisplayWindow => "Jendela",
        LanguageSystem => "Sistem",
        ActionAdjust => "Atur",
        SettingEffects => "Efek",
        SettingContrast => "Kontras",
        LookStandard => "Standar",
        EffectsReduced => "Dikurangi",
        ContrastHigh => "Tinggi",
        KeySpace => "Spasi",
        KeyEsc => "Esc",
        SectorsOf => "{0} dari {1} sektor",
        TargetBest => "{0} · rekor {1}",
        LifeGained => "+1 nyawa",
        PresenceMenus => "Di menu",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Berlatih sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "FAJAR",
            Chapter::Morning => "PAGI",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "JAM EMAS",
            Chapter::Afterlight => "SENJA",
            Chapter::BlueHour => "JAM BIRU",
            Chapter::Eclipse => "GERHANA",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "LEBAR",
            Power::Slow => "LAMBAT",
            Power::Multi => "MULTIBOLA",
            Power::Anchor => "JANGKAR",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Lanjutkan"),
        UnlockHint => Some("Terkunci"),
        RetrySector => Some("Ulangi"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Baru"),
        SectorSelect => Some("Sektor"),
        NextSector => Some("Lanjut"),
        BackToSectors => Some("Sektor"),
        Settings => Some("Opsi"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Lanjut"),
        PlaySector => Some("Main {0}"),
        ActionServe => Some("Servis"),
        ActionRelease => Some("Lepas"),
        ActionSelect => Some("Pilih"),
        ActionBack => Some("Kembali"),
        ActionAdjust => Some("Atur"),
        SettingEffects => Some("Efek"),
        SettingContrast => Some("Kontras"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Sedikit"),
        ContrastHigh => Some("Tinggi"),
        StatBest => Some("REKOR"),
        StatMedals => Some("MEDALI"),
        SectorsHeading => Some("Sektor"),
        SaveFailed => Some("Tidak tersimpan"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spasi"),
        HelpResume => Some("Kembali bermain"),
        HelpRetry => Some("Dari titik simpan"),
        HelpMainMenu => Some("Tersimpan"),
        HelpSectors => Some("Latihan sektor"),
        HelpNewJourney => Some("Dari sektor 01"),
        HelpSettings => Some("Suara, layar"),
        SettingSound => Some("Suara"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Layar"),
        SettingLanguage => Some("Bahasa"),
        DisplayWindow => Some("Jendela"),
        Fullscreen => Some("Penuh"),
        LanguageSystem => Some("Sistem"),
        ExtraLife => Some("+1 nyawa"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Selesai"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Cahaya Pertama",
    "Hanyut",
    "Cakrawala",
    "Kerlip",
    "Branjangan",
    "Lentera",
    "Air Pasang",
    "Matahari Terbit",
    "Satelit",
    "Titik Embun",
    "Apertur",
    "Biara",
    "Batu Kunci",
    "Jam Matahari",
    "Lubang Jarum",
    "Mawar Angin",
    "Arus Seret",
    "Filamen",
    "Meridian",
    "Kaskade",
    "Silang Pudar",
    "Tikungan Tajam",
    "Solstis",
    "Resonansi",
    "Prisma",
    "Sarang Lebah",
    "Percik Ombak",
    "Arus Bawah",
    "Panen",
    "Kaleidoskop",
    "Permadani",
    "Bayang Panjang",
    "Pendar Senja",
    "Kepompong",
    "Geode",
    "Paralaks",
    "Benteng",
    "Nautilus",
    "Vesper",
    "Supernova",
    "Bulan Terbit",
    "Remang-remang",
    "Cahaya Lampu",
    "Kunang-kunang",
    "Mercusuar",
    "Nokturne",
    "Medan Dalam",
    "Rasi Bintang",
    "Penumbra",
    "Metronom",
    "Korona",
    "Sizigi",
    "Pulsar",
    "Rana",
    "Umbra",
    "Totalitas",
    "Angin Surya",
    "Borealis",
    "Pita",
    "Malam Kutub",
    "Katedral",
    "Kemilau",
    "Singularitas",
    "Pulang",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Cahaya",
    "Hanyut",
    "Cakrawala",
    "Kerlip",
    "Branjangan",
    "Lentera",
    "Pasang",
    "Mentari",
    "Satelit",
    "Embun",
    "Apertur",
    "Biara",
    "Kunci",
    "Jam",
    "Lubang",
    "Mawar",
    "Arus Seret",
    "Filamen",
    "Meridian",
    "Kaskade",
    "Pudar",
    "Tikungan",
    "Solstis",
    "Resonansi",
    "Prisma",
    "Sarang",
    "Percik",
    "Arus Bawah",
    "Panen",
    "Kaleido",
    "Permadani",
    "Bayang",
    "Pendar",
    "Kepompong",
    "Geode",
    "Paralaks",
    "Benteng",
    "Nautilus",
    "Vesper",
    "Supernova",
    "Bulan Terbit",
    "Remang",
    "Lampu",
    "Kunang",
    "Mercusuar",
    "Nokturne",
    "Dalam",
    "Bintang",
    "Penumbra",
    "Metronom",
    "Korona",
    "Sizigi",
    "Pulsar",
    "Rana",
    "Umbra",
    "Totalitas",
    "Angin",
    "Borealis",
    "Pita",
    "Malam",
    "Katedral",
    "Kemilau",
    "Singularitas",
    "Pulang",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Lebar: tangkap kapsul yang jatuh",
    "{icon:slow} Lambat: tangkap, dan bola melambat",
    "Arahkan: tepi dayung melontarkan bola ke samping",
    "Percikan api sendirian: kejar satu per satu",
    "Kirim bola naik lewat sayap yang terbuka",
    "Bersihkan setiap lentera dari bawah",
    "Tunggangi ombak: pantulkan dari dinding samping",
    "Pahat matahari dari bawah, baris demi baris",
    "{icon:anchor} Jangkar: tangkap bola, bidik, lalu lepaskan",
    "Bata berlapis baja butuh dua pukulan: awasi tepinya",
    "{icon:anchor} Bidik lewat celah di dinding",
    "Satu pintu saja: kirim bola ke halaman dalam",
    "Hancurkan batu kunci dan lengkungnya terbuka",
    "Baca sudutnya: setiap bayangan adalah satu tembakan",
    "{icon:anchor} Satu lubang sempit: tahan, bidik, lepaskan",
    "Setiap arah mata angin menuju jantung",
    "Inti amber: setiap ledakan mengenai empat tetangganya",
    "Sentuh filamen di mana saja: ia terbakar ke dua arah",
    "Belah medan di sepanjang meridian",
    "Mulai kaskade dari kedua ujung mana pun",
    "Buka jalan melewati dua jalur relai",
    "Tiga jalur relai: satu tembakan bersih tiap jalur",
    "Cincin terbakar utuh: cari jalan ke tepinya",
    "Inti yang bertetangga meneruskan reaksi",
    "{icon:multi} Multibola: tiga bola, satu celah",
    "Satu inti di tiap sel: pecahkan semuanya",
    "Percikan di mana-mana: lepaskan tiga bola",
    "Tembus ke kantong di balik lapisan baja",
    "Medan penuh: {icon:multi} Multibola membersihkannya cepat",
    "Cermin di mana-mana: pecahkan satu sisi, lalu kembarannya",
    "Tarik satu benang dan anyamannya terurai",
    "Tembus lantai dan nyalakan sumbu panjang",
    "{icon:phase} Fase: tiga sentuhan bata tanpa memantul",
    "{icon:phase} Fase menembus cangkang sampai ke inti",
    "Pecahkan geode dan kristalnya menyala",
    "Tembus cangkangnya, lalu nyalakan rute dalam",
    "Masuk lewat gerbang, atau tembus dinding dengan {icon:phase} Fase",
    "Berputar ke dalam: lilitan terluar menyala duluan",
    "Tiga lonceng: bunyikan satu per satu dari bawah",
    "Tangkap bola yang kembali selagi bola lain terus melaju",
    "Ikuti relai mengitari bagian tengah yang terbuka",
    "Cahaya memudar: pelajari medan selagi bisa",
    "Dalam gelap, bola dan dayungmu membawa cahaya",
    "Kunang-kunang: inti bersinar bahkan dalam gelap",
    "Sapukan cahaya dayung ke seluruh pantai",
    "Lebih banyak bola, lebih banyak cahaya: {icon:multi} Multibola",
    "Medan dalam: setiap titik redup adalah bata",
    "Hubungkan bintang: yang terang adalah inti",
    "Gerbang memudar mengikuti irama: tunggu celahnya",
    "Tik, tok: gerbang menjaga waktu",
    "Korona terbuka mengikuti irama: pukul ke dalam",
    "Gerbang hantu menepis ledakan: atur waktu percikannya",
    "Sebuah pulsar: irama cepat, tangan cepat",
    "Rana terbuka sesaat: bersiaplah",
    "Setengah dalam bayangan: sisi bergerbang menjaga irama",
    "Nyalakan matahari selagi bulan padat",
    "Angin bertiup satu arah: tunggangi sampai ke inti",
    "Tirai cahaya: sapu dengan {icon:multi} Multibola",
    "Setiap pita terikat pada gerbang: putuskan kedua bagiannya",
    "Malam yang panjang: bidik dengan cahaya yang kamu bawa",
    "Masuk lewat pintu, naik ke jendela mawar",
    "Semua sekaligus: awasi intinya",
    "Pukul cincin saat gerbang menjadi padat",
    "Orbit terakhir: manfaatkan setiap celah",
];
