//! Indonesian. Informal *-mu*, as Indonesian games address players; labels
//! in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Hancurkan kosmos",
        ContinueJourney => "Lanjutkan perjalanan",
        NewJourney => "Perjalanan baru",
        SectorSelect => "Pilih sektor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALI",
        StatBest => "REKOR",
        ActionServe => "Servis",
        ActionRelease => "Lepas",
        ActionSelect => "Pilih",
        ActionResume => "Lanjutkan",
        ActionBack => "Kembali",
        Fullscreen => "Layar penuh",
        SectorsHeading => "Sektor",
        PracticeNote => "Latihan tidak pernah mengubah perjalananmu",
        MedalClear => "TUNTAS",
        MedalClean => "BERSIH",
        MedalSwift => "KILAT",
        PlaySector => "Mainkan sektor {0}",
        UnlockHint => "Selesaikan sektor {0} untuk membuka",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Dijeda",
        RetrySector => "Ulangi sektor",
        MainMenu => "Menu utama",
        JourneyComplete => "Perjalanan selesai",
        OneMoreOrbit => "Satu orbit lagi?",
        StatPoints => "POIN",
        SectorClear => "Sektor tuntas",
        StatTime => "WAKTU",
        StatBonus => "BONUS",
        StatChain => "RANTAI",
        ExtraLife => "Bab selesai · +1 nyawa",
        NextSector => "Sektor berikutnya",
        BackToSectors => "Kembali ke sektor",
        SaveFailed => "Kemajuan tidak dapat disimpan",
        PerfTitle => "Performa / CPU",
        HelpResume => "Lanjutkan dari posisi terakhir",
        HelpRetry => "Mulai lagi dari titik simpan sektor",
        HelpMainMenu => "Perjalananmu tersimpan",
        HelpSectors => "Latihan di sektor mana pun yang terbuka",
        HelpNewJourney => "Mulai lagi dari sektor 01 · medali tetap",
        Settings => "Pengaturan",
        HelpSettings => "Suara, layar, bahasa",
        SettingSound => "Suara",
        SettingVolume => "Volume",
        SettingDisplay => "Layar",
        SettingLanguage => "Bahasa",
        DisplayWindow => "Jendela",
        LanguageSystem => "Sistem",
        ActionAdjust => "Atur",
        SettingEffects => "Efek",
        SettingContrast => "Kontras",
        LookStandard => "Standar",
        EffectsReduced => "Dikurangi",
        ContrastHigh => "Tinggi",
        KeySpace => "Spasi",
        KeyEsc => "Esc",
        SectorsOf => "{0} dari {1} sektor",
        TargetBest => "{0} · rekor {1}",
        LifeGained => "+1 nyawa",
        PresenceMenus => "Di menu",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Berlatih sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "FAJAR",
            Chapter::BlueHour => "JAM BIRU",
            Chapter::Afterlight => "SENJA",
        },
        PowerName(p) => match p {
            Power::Wide => "LEBAR",
            Power::Slow => "LAMBAT",
            Power::Multi => "MULTIBOLA",
            Power::Anchor => "JANGKAR",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Lanjutkan"),
        UnlockHint => Some("Terkunci"),
        RetrySector => Some("Ulangi"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Baru"),
        SectorSelect => Some("Sektor"),
        NextSector => Some("Lanjut"),
        BackToSectors => Some("Sektor"),
        Settings => Some("Opsi"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Lanjut"),
        PlaySector => Some("Main {0}"),
        ActionServe => Some("Servis"),
        ActionRelease => Some("Lepas"),
        ActionSelect => Some("Pilih"),
        ActionBack => Some("Kembali"),
        ActionAdjust => Some("Atur"),
        SettingEffects => Some("Efek"),
        SettingContrast => Some("Kontras"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Sedikit"),
        ContrastHigh => Some("Tinggi"),
        StatBest => Some("REKOR"),
        StatMedals => Some("MEDALI"),
        SectorsHeading => Some("Sektor"),
        SaveFailed => Some("Tidak tersimpan"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spasi"),
        HelpResume => Some("Kembali bermain"),
        HelpRetry => Some("Dari titik simpan"),
        HelpMainMenu => Some("Tersimpan"),
        HelpSectors => Some("Latihan sektor"),
        HelpNewJourney => Some("Dari sektor 01"),
        HelpSettings => Some("Suara, layar"),
        SettingSound => Some("Suara"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Layar"),
        SettingLanguage => Some("Bahasa"),
        DisplayWindow => Some("Jendela"),
        Fullscreen => Some("Penuh"),
        LanguageSystem => Some("Sistem"),
        ExtraLife => Some("+1 nyawa"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Selesai"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Cahaya Pertama",
    "Satelit",
    "Arus Seret",
    "Resonansi",
    "Prisma",
    "Silang Pudar",
    "Arus Bawah",
    "Bulan Terbit",
    "Pendar Senja",
    "Paralaks",
    "Supernova",
    "Pulang",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Cahaya",
    "Satelit",
    "Arus Seret",
    "Resonansi",
    "Prisma",
    "Pudar",
    "Arus Bawah",
    "Bulan Terbit",
    "Pendar",
    "Paralaks",
    "Supernova",
    "Pulang",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Lebar dan {icon:slow} Lambat: tangkap kapsul yang jatuh",
    "{icon:anchor} Jangkar: tangkap bola, bidik, lalu lepaskan",
    "Inti amber: setiap ledakan mengenai empat tetangganya",
    "Inti yang bertetangga meneruskan reaksi",
    "{icon:multi} Multibola: tiga bola, satu celah",
    "Buka jalan melewati dua jalur relai",
    "Tembus ke kantong di balik lapisan baja",
    "Ikuti relai mengitari bagian tengah yang terbuka",
    "{icon:phase} Fase: tiga sentuhan bata tanpa memantul",
    "Tembus cangkangnya, lalu nyalakan rute dalam",
    "Tangkap bola yang kembali selagi bola lain terus melaju",
    "Orbit terakhir: manfaatkan setiap celah",
];
