//! Italian. Informal *tu*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Spezza il cosmo",
        ContinueJourney => "Continua il viaggio",
        NewJourney => "Nuovo viaggio",
        SectorSelect => "Scegli settore",
        ContinueDetail => "Settore {0} · {1} · {2}",
        StatSectors => "SETTORI",
        StatMedals => "MEDAGLIE",
        StatBest => "RECORD",
        Fraction => "{0} / {1}",
        KeysMove => "Mouse o frecce per muoverti",
        KeysServe => "Spazio o clic per lanciare",
        KeysPause => "Esc per la pausa",
        KeysRelease => "Clic o Spazio per rilasciare",
        KeysBrowse => "Frecce per scorrere",
        KeysPlay => "Invio per giocare",
        KeysBack => "Esc per tornare indietro",
        KeysContinue => "Invio o clic per continuare",
        PadMove => "Levetta o croce per muoverti",
        PadBrowse => "Croce direzionale per scorrere",
        ActionServe => "Lancia",
        ActionPause => "Pausa",
        ActionRelease => "Rilascia",
        ActionSelect => "Seleziona",
        ActionResume => "Riprendi",
        ActionRetry => "Riprova",
        ActionPlay => "Gioca",
        ActionBack => "Indietro",
        ActionContinue => "Continua",
        SoundOn => "Audio attivo",
        SoundOff => "Audio disattivato",
        Volume => "Volume {0}",
        Fullscreen => "Schermo intero",
        SectorsHeading => "Settori",
        PracticeNote => "Gli allenamenti non cambiano mai il tuo viaggio",
        NoTime => "--:--",
        SwiftTarget => "Tempo obiettivo {0}",
        BestTime => "Migliore {0}",
        MedalClear => "SUPERATO",
        MedalClean => "PERFETTO",
        MedalSwift => "RAPIDO",
        MedalClearHow => "Completa il settore",
        MedalCleanHow => "Non perdere vite",
        MedalSwiftHow => "Batti il tempo obiettivo",
        PlaySector => "Gioca il settore {0}",
        ClearPreviousFirst => "Completa prima il settore precedente",
        Score => "PUNTI",
        Lives => "VITE",
        SectorNumber => "SETTORE {0}",
        PracticeNumber => "ALLENAMENTO {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SETTORE {1}",
        Paused => "In pausa",
        RetrySector => "Riprova il settore",
        MainMenu => "Menu principale",
        RetryNote => "Riprova riparte dal checkpoint",
        JourneyComplete => "Viaggio completato",
        OneMoreOrbit => "Un’altra orbita?",
        StatPoints => "PUNTI",
        ProgressSaved => "I tuoi progressi sono salvati",
        SectorClear => "Settore completato",
        StatTime => "TEMPO",
        StatBonus => "BONUS",
        StatBestChain => "CATENA MAX",
        ExtraLife => "Capitolo completato · vita extra",
        NextSector => "Settore successivo",
        BackToSectors => "Torna ai settori",
        SaveFailed => "Impossibile salvare i progressi",
        PerfTitle => "Prestazioni / CPU",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ALBA",
            Chapter::BlueHour => "ORA BLU",
            Chapter::Afterlight => "CREPUSCOLO",
        },
        PowerName(p) => match p {
            Power::Wide => "Largo",
            Power::Slow => "Lento",
            Power::Multi => "Multipalla",
            Power::Anchor => "Ancora",
            Power::Phase => "Fase",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1} · {2}"),
        ContinueJourney => Some("Continua"),
        ClearPreviousFirst => Some("Bloccato"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Prima luce",
    "Satelliti",
    "Scia",
    "Risonanza",
    "Prisma",
    "Dissolvenza",
    "Risacca",
    "Sorgere della luna",
    "Bagliore",
    "Parallasse",
    "Supernova",
    "Ritorno",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Largo e {icon:slow} Lento: prendi le capsule che cadono",
    "{icon:anchor} Ancora: prendi la palla, mira e poi rilasciala",
    "Nuclei ambra: ogni esplosione raggiunge i suoi quattro vicini",
    "I nuclei vicini propagano la reazione",
    "{icon:multi} Multipalla: tre palle, un’apertura",
    "Apri un varco tra le due linee di relè",
    "Entra nelle sacche dietro la corazza",
    "Segui il relè intorno al centro aperto",
    "{icon:phase} Fase: tre contatti con i mattoni senza rimbalzo",
    "Perfora il guscio, poi accendi il percorso interno",
    "Prendi una palla mentre le altre continuano",
    "Un’ultima orbita: fai contare ogni apertura",
];
