//! Italian. Informal *tu*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Spezza il cosmo",
        ContinueJourney => "Continua il viaggio",
        NewJourney => "Nuovo viaggio",
        SectorSelect => "Scegli settore",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDAGLIE",
        StatBest => "RECORD",
        ActionServe => "Lancia",
        ActionRelease => "Rilascia",
        ActionSelect => "Seleziona",
        ActionResume => "Riprendi",
        ActionBack => "Indietro",
        Fullscreen => "Schermo intero",
        SectorsHeading => "Settori",
        PracticeNote => "L’allenamento non cambia mai il tuo viaggio",
        MedalClear => "SUPERATO",
        MedalClean => "PERFETTO",
        MedalSwift => "RAPIDO",
        PlaySector => "Gioca il settore {0}",
        UnlockHint => "Completa il settore {0} per sbloccarlo",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SETTORE {1}",
        Paused => "In pausa",
        RetrySector => "Riprova il settore",
        MainMenu => "Menu principale",
        JourneyComplete => "Viaggio completato",
        OneMoreOrbit => "Un’altra orbita?",
        StatPoints => "PUNTI",
        SectorClear => "Settore completato",
        StatTime => "TEMPO",
        StatBonus => "BONUS",
        StatChain => "CATENA",
        ExtraLife => "Capitolo completato · +1 vita",
        NextSector => "Settore successivo",
        BackToSectors => "Torna ai settori",
        SaveFailed => "Impossibile salvare i progressi",
        PerfTitle => "Prestazioni / CPU",
        HelpResume => "Riprendi da dove eri rimasto",
        HelpRetry => "Riparti dal checkpoint del settore",
        HelpMainMenu => "Il tuo viaggio è salvato",
        HelpSectors => "Allenati in un settore aperto",
        HelpNewJourney => "Ricomincia dal settore 01 · le medaglie restano",
        Settings => "Impostazioni",
        HelpSettings => "Audio, schermo, lingua",
        SettingSound => "Audio",
        SettingVolume => "Volume",
        SettingDisplay => "Schermo",
        SettingLanguage => "Lingua",
        DisplayWindow => "Finestra",
        LanguageSystem => "Sistema",
        ActionAdjust => "Regola",
        KeySpace => "Spazio",
        KeyEsc => "Esc",
        SectorsOf => "{0} settori su {1}",
        TargetBest => "{0} · record {1}",
        LifeGained => "+1 vita",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ALBA",
            Chapter::BlueHour => "ORA BLU",
            Chapter::Afterlight => "CREPUSCOLO",
        },
        PowerName(p) => match p {
            Power::Wide => "LARGO",
            Power::Slow => "LENTO",
            Power::Multi => "MULTIPALLA",
            Power::Anchor => "ANCORA",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continua"),
        UnlockHint => Some("Bloccato"),
        RetrySector => Some("Riprova"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nuovo"),
        SectorSelect => Some("Settori"),
        NextSector => Some("Avanti"),
        BackToSectors => Some("Settori"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Riprendi"),
        PlaySector => Some("Gioca {0}"),
        Settings => Some("Opzioni"),
        ActionServe => Some("Lancia"),
        ActionRelease => Some("Rilascia"),
        ActionSelect => Some("Scegli"),
        ActionBack => Some("Indietro"),
        ActionAdjust => Some("Regola"),
        StatBest => Some("RECORD"),
        StatMedals => Some("MEDAGLIE"),
        SectorsHeading => Some("Settori"),
        SaveFailed => Some("Non salvato"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spazio"),
        HelpResume => Some("Torna a giocare"),
        HelpRetry => Some("Dal checkpoint"),
        HelpMainMenu => Some("Viaggio salvato"),
        HelpSectors => Some("Allenati nei settori"),
        HelpNewJourney => Some("Dal settore 01"),
        HelpSettings => Some("Audio, schermo"),
        SettingSound => Some("Audio"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Schermo"),
        SettingLanguage => Some("Lingua"),
        DisplayWindow => Some("Finestra"),
        Fullscreen => Some("Intero"),
        LanguageSystem => Some("Sistema"),
        ExtraLife => Some("+1 vita"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SETTORE {1}"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Prima luce",
    "Satelliti",
    "Scia",
    "Risonanza",
    "Prisma",
    "Dissolvenza",
    "Risacca",
    "Sorgere della luna",
    "Bagliore",
    "Parallasse",
    "Supernova",
    "Ritorno",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Prima luce",
    "Satelliti",
    "Scia",
    "Risonanza",
    "Prisma",
    "Dissolvenza",
    "Risacca",
    "Luna",
    "Bagliore",
    "Parallasse",
    "Supernova",
    "Ritorno",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Largo e {icon:slow} Lento: prendi le capsule che cadono",
    "{icon:anchor} Ancora: prendi la palla, mira e poi rilasciala",
    "Nuclei ambra: ogni esplosione raggiunge i suoi quattro vicini",
    "I nuclei vicini propagano la reazione",
    "{icon:multi} Multipalla: tre palle, un’apertura",
    "Apri un varco tra le due linee di relè",
    "Entra nelle sacche dietro la corazza",
    "Segui il relè intorno al centro aperto",
    "{icon:phase} Fase: tre contatti con i mattoni senza rimbalzo",
    "Perfora il guscio, poi accendi il percorso interno",
    "Prendi una palla mentre le altre continuano",
    "Un’ultima orbita: fai contare ogni apertura",
];
