//! Italian. Informal *tu*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Spezza il cosmo",
        ContinueJourney => "Continua il viaggio",
        NewJourney => "Nuovo viaggio",
        SectorSelect => "Scegli settore",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDAGLIE",
        StatBest => "RECORD",
        ActionServe => "Lancia",
        ActionRelease => "Rilascia",
        ActionSelect => "Seleziona",
        ActionResume => "Riprendi",
        ActionBack => "Indietro",
        Fullscreen => "Schermo intero",
        SectorsHeading => "Settori",
        PracticeNote => "L’allenamento non cambia mai il tuo viaggio",
        MedalClear => "SUPERATO",
        MedalClean => "PERFETTO",
        MedalSwift => "RAPIDO",
        PlaySector => "Gioca il settore {0}",
        UnlockHint => "Completa il settore {0} per sbloccarlo",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SETTORE {1}",
        Paused => "In pausa",
        RetrySector => "Riprova il settore",
        MainMenu => "Menu principale",
        JourneyComplete => "Viaggio completato",
        OneMoreOrbit => "Un’altra orbita?",
        StatPoints => "PUNTI",
        SectorClear => "Settore completato",
        StatTime => "TEMPO",
        StatBonus => "BONUS",
        StatChain => "CATENA",
        ExtraLife => "Capitolo completato · +1 vita",
        NextSector => "Settore successivo",
        BackToSectors => "Torna ai settori",
        SaveFailed => "Impossibile salvare i progressi",
        PerfTitle => "Prestazioni / CPU",
        HelpResume => "Riprendi da dove eri rimasto",
        HelpRetry => "Riparti dal checkpoint del settore",
        HelpMainMenu => "Il tuo viaggio è salvato",
        HelpSectors => "Allenati in un settore aperto",
        HelpNewJourney => "Ricomincia dal settore 01 · le medaglie restano",
        Settings => "Impostazioni",
        HelpSettings => "Audio, schermo, lingua",
        SettingSound => "Audio",
        SettingVolume => "Volume",
        SettingDisplay => "Schermo",
        SettingLanguage => "Lingua",
        DisplayWindow => "Finestra",
        LanguageSystem => "Sistema",
        ActionAdjust => "Regola",
        SettingEffects => "Effetti",
        SettingContrast => "Contrasto",
        LookStandard => "Standard",
        EffectsReduced => "Ridotti",
        ContrastHigh => "Alto",
        KeySpace => "Spazio",
        KeyEsc => "Esc",
        SectorsOf => "{0} settori su {1}",
        TargetBest => "{0} · record {1}",
        LifeGained => "+1 vita",
        PresenceMenus => "Nei menu",
        PresenceJourney => "Settore {0} · {1}",
        PresencePractice => "In allenamento, settore {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ALBA",
            Chapter::Morning => "MATTINO",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "ORA D’ORO",
            Chapter::Afterlight => "CREPUSCOLO",
            Chapter::BlueHour => "ORA BLU",
            Chapter::Eclipse => "ECLISSI",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "LARGO",
            Power::Slow => "LENTO",
            Power::Multi => "MULTIPALLA",
            Power::Anchor => "ANCORA",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continua"),
        UnlockHint => Some("Bloccato"),
        RetrySector => Some("Riprova"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nuovo"),
        SectorSelect => Some("Settori"),
        NextSector => Some("Avanti"),
        BackToSectors => Some("Settori"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Riprendi"),
        PlaySector => Some("Gioca {0}"),
        Settings => Some("Opzioni"),
        ActionServe => Some("Lancia"),
        ActionRelease => Some("Rilascia"),
        ActionSelect => Some("Scegli"),
        ActionBack => Some("Indietro"),
        ActionAdjust => Some("Regola"),
        StatBest => Some("RECORD"),
        StatMedals => Some("MEDAGLIE"),
        SectorsHeading => Some("Settori"),
        SaveFailed => Some("Non salvato"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spazio"),
        HelpResume => Some("Torna a giocare"),
        HelpRetry => Some("Dal checkpoint"),
        HelpMainMenu => Some("Viaggio salvato"),
        HelpSectors => Some("Allenati nei settori"),
        HelpNewJourney => Some("Dal settore 01"),
        HelpSettings => Some("Audio, schermo"),
        SettingSound => Some("Audio"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Schermo"),
        SettingLanguage => Some("Lingua"),
        DisplayWindow => Some("Finestra"),
        Fullscreen => Some("Intero"),
        LanguageSystem => Some("Sistema"),
        ExtraLife => Some("+1 vita"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SETTORE {1}"),
        SettingEffects => Some("Effetti"),
        SettingContrast => Some("Contrasto"),
        LookStandard => Some("Normale"),
        EffectsReduced => Some("Meno"),
        ContrastHigh => Some("Alto"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Prima luce",
    "Deriva",
    "Orizzonte",
    "Barlume",
    "Allodola",
    "Lanterne",
    "Marea",
    "Sorgere del sole",
    "Satelliti",
    "Punto di rugiada",
    "Apertura",
    "Chiostro",
    "Chiave di volta",
    "Meridiana",
    "Foro stenopeico",
    "Rosa dei venti",
    "Scia",
    "Filamento",
    "Meridiano",
    "Cascata",
    "Dissolvenza",
    "Tornanti",
    "Solstizio",
    "Risonanza",
    "Prisma",
    "Alveare",
    "Spruzzi",
    "Risacca",
    "Raccolto",
    "Caleidoscopio",
    "Arazzo",
    "Ombre lunghe",
    "Bagliore",
    "Crisalide",
    "Geode",
    "Parallasse",
    "Cittadella",
    "Nautilo",
    "Vespri",
    "Supernova",
    "Sorgere della luna",
    "Imbrunire",
    "Luce di lampada",
    "Lucciole",
    "Faro",
    "Notturno",
    "Campo profondo",
    "Costellazione",
    "Penombra",
    "Metronomo",
    "Corona",
    "Sizigia",
    "Pulsar",
    "Otturatore",
    "Umbra",
    "Totalità",
    "Vento solare",
    "Borealis",
    "Nastri",
    "Notte polare",
    "Cattedrale",
    "Scintillio",
    "Singolarità",
    "Ritorno",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Prima luce",
    "Deriva",
    "Orizzonte",
    "Barlume",
    "Allodola",
    "Lanterne",
    "Marea",
    "Sole",
    "Satelliti",
    "Rugiada",
    "Apertura",
    "Chiostro",
    "Chiave",
    "Meridiana",
    "Stenopeico",
    "Rosa",
    "Scia",
    "Filamento",
    "Meridiano",
    "Cascata",
    "Dissolvenza",
    "Tornanti",
    "Solstizio",
    "Risonanza",
    "Prisma",
    "Alveare",
    "Spruzzi",
    "Risacca",
    "Raccolto",
    "Caleido",
    "Arazzo",
    "Ombre",
    "Bagliore",
    "Crisalide",
    "Geode",
    "Parallasse",
    "Cittadella",
    "Nautilo",
    "Vespri",
    "Supernova",
    "Luna",
    "Imbrunire",
    "Lampada",
    "Lucciole",
    "Faro",
    "Notturno",
    "Campo profondo",
    "Stelle",
    "Penombra",
    "Metronomo",
    "Corona",
    "Sizigia",
    "Pulsar",
    "Otturatore",
    "Umbra",
    "Totalità",
    "Vento",
    "Borealis",
    "Nastri",
    "Notte polare",
    "Cattedrale",
    "Scintillio",
    "Singolarità",
    "Ritorno",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Largo: prendi la capsula che cade",
    "{icon:slow} Lento: prendila e la palla rallenta",
    "Guida: i bordi della racchetta mandano la palla di lato",
    "Scintille isolate: dai la caccia a ognuna",
    "Manda la palla su per le ali aperte",
    "Libera ogni lanterna dal basso",
    "Cavalca l’onda: rimbalza sulle pareti laterali",
    "Scheggia il sole dal basso, riga dopo riga",
    "{icon:anchor} Ancora: prendi la palla, mira e poi rilasciala",
    "I mattoni corazzati reggono due colpi: occhio ai bordi",
    "{icon:anchor} Mira attraverso il varco nel muro",
    "Una sola porta: manda la palla nel cortile",
    "Abbatti la chiave di volta e l’arco si apre",
    "Leggi gli angoli: ogni ombra è un tiro",
    "{icon:anchor} Un solo foro stretto: tieni, mira, rilascia",
    "Ogni punto cardinale porta al cuore",
    "Nuclei ambra: ogni esplosione raggiunge i suoi quattro vicini",
    "Tocca il filamento ovunque: brucia in entrambe le direzioni",
    "Dividi il campo lungo il meridiano",
    "Avvia la cascata da una delle due estremità",
    "Apri un varco tra le due linee di relè",
    "Tre linee di relè: un tiro pulito per ciascuna",
    "L’anello brucia intero: trova una via fino al suo bordo",
    "I nuclei vicini propagano la reazione",
    "{icon:multi} Multipalla: tre palle, un’apertura",
    "Un nucleo in ogni cella: spaccale",
    "Spruzzi ovunque: libera tre palle",
    "Entra nelle sacche dietro la corazza",
    "Campo pieno: {icon:multi} Multipalla lo ripulisce in fretta",
    "Specchi ovunque: rompi un lato, poi il suo gemello",
    "Tira un filo e la trama si scioglie",
    "Sfonda il pavimento e accendi la lunga miccia",
    "{icon:phase} Fase: tre contatti con i mattoni senza rimbalzo",
    "{icon:phase} Fase attraversa il guscio fino al nucleo",
    "Spacca una geode e i suoi cristalli si accendono",
    "Perfora il guscio, poi accendi il percorso interno",
    "Entra dal portale, o attraverso il muro con {icon:phase} Fase",
    "A spirale: la spira esterna si accende per prima",
    "Tre campane: suona ognuna dal basso",
    "Prendi una palla mentre le altre continuano",
    "Segui il relè intorno al centro aperto",
    "La luce se ne va: impara il campo finché puoi",
    "Al buio, palla e racchetta portano la luce",
    "Lucciole: i nuclei brillano anche al buio",
    "Spazza la costa con la luce della racchetta",
    "Più palle, più luce: {icon:multi} Multipalla",
    "Campo profondo: ogni puntino debole è un mattone",
    "Unisci le stelle: le più luminose sono nuclei",
    "I portali svaniscono a tempo: aspetta il varco",
    "Tic, tac: i portali tengono il tempo",
    "La corona si apre a tempo: colpisci dentro",
    "Un portale fantasma ignora l’esplosione: calcola la scintilla",
    "Una pulsar: battiti rapidi, mani rapide",
    "L’otturatore si apre un istante: sii pronto",
    "Metà in ombra: il lato dei portali tiene il tempo",
    "Accendi il sole finché la luna è solida",
    "Il vento soffia in una sola direzione: seguilo fino ai nuclei",
    "Tende di luce: spazzale con {icon:multi} Multipalla",
    "Ogni nastro è legato a un portale: taglia entrambe le metà",
    "La lunga notte: mira con la luce che porti",
    "Entra dalle porte, sali al rosone",
    "Tutto insieme: tieni d’occhio i nuclei",
    "Colpisci l’anello quando i portali si solidificano",
    "Un’ultima orbita: fai contare ogni apertura",
];
