//! Japanese. Polite plain style for notes, terse imperatives for tips;
//! full-width punctuation (：・？) and a space between Japanese and Latin.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "宇宙を打ち砕け",
        ContinueJourney => "旅を続ける",
        NewJourney => "新しい旅",
        SectorSelect => "セクター選択",
        ContinueDetail => "セクター {0}・{1}・{2}",
        StatSectors => "セクター",
        StatMedals => "メダル",
        StatBest => "ベスト",
        Fraction => "{0} / {1}",
        KeysMove => "マウスまたは矢印キーで移動",
        KeysServe => "スペースまたはクリックでサーブ",
        KeysPause => "Esc で一時停止",
        KeysRelease => "クリックまたはスペースでリリース",
        KeysBrowse => "矢印キーで選択",
        KeysPlay => "Enter でプレイ",
        KeysBack => "Esc で戻る",
        KeysContinue => "Enter またはクリックで次へ",
        PadMove => "スティックまたは十字キーで移動",
        PadBrowse => "十字キーで選択",
        ActionServe => "サーブ",
        ActionPause => "一時停止",
        ActionRelease => "リリース",
        ActionSelect => "決定",
        ActionResume => "再開",
        ActionRetry => "リトライ",
        ActionPlay => "プレイ",
        ActionBack => "戻る",
        ActionContinue => "次へ",
        SoundOn => "サウンド オン",
        SoundOff => "サウンド オフ",
        Volume => "音量 {0}",
        Fullscreen => "フルスクリーン",
        SectorsHeading => "セクター",
        PracticeNote => "練習プレイは旅の進行に影響しません",
        NoTime => "--:--",
        SwiftTarget => "目標タイム {0}",
        BestTime => "ベスト {0}",
        MedalClear => "クリア",
        MedalClean => "ノーミス",
        MedalSwift => "スピード",
        MedalClearHow => "セクターをクリア",
        MedalCleanHow => "ライフを失わない",
        MedalSwiftHow => "目標タイム内にクリア",
        PlaySector => "セクター {0} をプレイ",
        ClearPreviousFirst => "前のセクターをクリアしてください",
        Score => "スコア",
        Lives => "ライフ",
        SectorNumber => "セクター {0}",
        PracticeNumber => "練習 {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0}・セクター {1}",
        Paused => "一時停止中",
        RetrySector => "セクターをリトライ",
        MainMenu => "メインメニュー",
        RetryNote => "リトライはチェックポイントから再開します",
        JourneyComplete => "旅の完了",
        OneMoreOrbit => "もう一周？",
        StatPoints => "ポイント",
        ProgressSaved => "進行状況はセーブされています",
        SectorClear => "セクタークリア",
        StatTime => "タイム",
        StatBonus => "ボーナス",
        StatBestChain => "最大チェイン",
        ExtraLife => "章クリア・ライフ +1",
        NextSector => "次のセクター",
        BackToSectors => "セクター選択へ",
        SaveFailed => "進行状況をセーブできませんでした",
        PerfTitle => "パフォーマンス / CPU",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "暁",
            Chapter::BlueHour => "ブルーアワー",
            Chapter::Afterlight => "黄昏",
        },
        PowerName(p) => match p {
            Power::Wide => "ワイド",
            Power::Slow => "スロー",
            Power::Multi => "マルチボール",
            Power::Anchor => "アンカー",
            Power::Phase => "フェイズ",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1}・{2}"),
        ContinueJourney => Some("続ける"),
        ClearPreviousFirst => Some("ロック中"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "夜明けの光",
    "サテライト",
    "スリップストリーム",
    "共鳴",
    "プリズム",
    "クロスフェード",
    "引き潮",
    "月の出",
    "残光",
    "視差",
    "超新星",
    "帰還",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} ワイドと {icon:slow} スロー：落ちてくるカプセルをキャッチ",
    "{icon:anchor} アンカー：ボールを受け止め、狙って放つ",
    "琥珀のコア：爆発は隣接する4つに届く",
    "隣り合うコアが連鎖を伝える",
    "{icon:multi} マルチボール：3つのボールで1つの突破口を",
    "2本のリレーラインの間に道を開こう",
    "装甲の奥にあるポケットへ切り込め",
    "空いた中心の周りをリレーに沿って進め",
    "{icon:phase} フェイズ：跳ね返らずにブロックへ3回接触",
    "外殻を貫き、内側のルートに点火せよ",
    "他のボールが飛ぶ間に戻りをキャッチ",
    "最後の一周：すべての突破口を生かせ",
];
