//! Japanese. Polite plain style for notes, terse imperatives for tips;
//! full-width punctuation (：・？) and a space between Japanese and Latin.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "宇宙を打ち砕け",
        ContinueJourney => "旅を続ける",
        NewJourney => "新しい旅",
        SectorSelect => "セクター選択",
        ContinueDetail => "{0}・{1}",
        StatMedals => "メダル",
        StatBest => "ベスト",
        ActionServe => "サーブ",
        ActionRelease => "リリース",
        ActionSelect => "決定",
        ActionResume => "再開",
        ActionBack => "戻る",
        Fullscreen => "フルスクリーン",
        SectorsHeading => "セクター",
        PracticeNote => "練習は旅の進行に影響しません",
        MedalClear => "クリア",
        MedalClean => "ノーミス",
        MedalSwift => "スピード",
        PlaySector => "セクター {0} をプレイ",
        UnlockHint => "セクター {0} をクリアで解放",
        Plus => "+{0}",
        ReadyEyebrow => "{0}・セクター {1}",
        Paused => "一時停止中",
        RetrySector => "セクターをリトライ",
        MainMenu => "メインメニュー",
        JourneyComplete => "旅の完了",
        OneMoreOrbit => "もう一周？",
        StatPoints => "ポイント",
        SectorClear => "セクタークリア",
        StatTime => "タイム",
        StatBonus => "ボーナス",
        StatChain => "チェイン",
        ExtraLife => "章クリア・ライフ +1",
        NextSector => "次のセクター",
        BackToSectors => "セクター選択へ",
        SaveFailed => "進行状況をセーブできませんでした",
        PerfTitle => "パフォーマンス / CPU",
        HelpResume => "中断したところから再開します",
        HelpRetry => "セクターのチェックポイントからやり直します",
        HelpMainMenu => "旅の進行はセーブされています",
        HelpSectors => "開放済みのセクターを練習できます",
        HelpNewJourney => "セクター 01 から再スタート・メダルは残ります",
        Settings => "設定",
        HelpSettings => "サウンド・画面・言語",
        SettingSound => "サウンド",
        SettingVolume => "音量",
        SettingDisplay => "画面",
        SettingLanguage => "言語",
        DisplayWindow => "ウインドウ",
        LanguageSystem => "システム",
        ActionAdjust => "調整",
        SettingEffects => "エフェクト",
        SettingContrast => "コントラスト",
        LookStandard => "標準",
        EffectsReduced => "控えめ",
        ContrastHigh => "高",
        KeySpace => "スペース",
        KeyEsc => "Esc",
        SectorsOf => "{0} / {1} セクター",
        TargetBest => "{0}・ベスト {1}",
        LifeGained => "ライフ +1",
        PresenceMenus => "メニュー画面",
        PresenceJourney => "セクター {0}・{1}",
        PresencePractice => "セクター {0}・{1} を練習中",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "暁",
            Chapter::Morning => "朝",
            Chapter::Zenith => "天頂",
            Chapter::GoldenHour => "ゴールデンアワー",
            Chapter::Afterlight => "黄昏",
            Chapter::BlueHour => "ブルーアワー",
            Chapter::Eclipse => "日食",
            Chapter::Aurora => "オーロラ",
        },
        PowerName(p) => match p {
            Power::Wide => "ワイド",
            Power::Slow => "スロー",
            Power::Multi => "マルチボール",
            Power::Anchor => "アンカー",
            Power::Phase => "フェイズ",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("続ける"),
        UnlockHint => Some("ロック中"),
        RetrySector => Some("リトライ"),
        MainMenu => Some("メニュー"),
        NewJourney => Some("新規"),
        SectorSelect => Some("セクター"),
        NextSector => Some("次へ"),
        BackToSectors => Some("セクター"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("再開"),
        PlaySector => Some("プレイ {0}"),
        Settings => Some("設定"),
        ActionServe => Some("サーブ"),
        ActionRelease => Some("リリース"),
        ActionSelect => Some("決定"),
        ActionBack => Some("戻る"),
        ActionAdjust => Some("調整"),
        StatBest => Some("ベスト"),
        StatMedals => Some("メダル"),
        SectorsHeading => Some("セクター"),
        SaveFailed => Some("セーブ失敗"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("スペース"),
        HelpResume => Some("ゲームに戻ります"),
        HelpRetry => Some("チェックポイントから"),
        HelpMainMenu => Some("セーブ済み"),
        HelpSectors => Some("セクターを練習"),
        HelpNewJourney => Some("セクター 01 から"),
        HelpSettings => Some("サウンド・画面"),
        SettingSound => Some("サウンド"),
        SettingVolume => Some("音量"),
        SettingDisplay => Some("画面"),
        SettingLanguage => Some("言語"),
        DisplayWindow => Some("ウインドウ"),
        Fullscreen => Some("全画面"),
        LanguageSystem => Some("システム"),
        ExtraLife => Some("ライフ +1"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("セクター {1}"),
        SettingEffects => Some("効果"),
        SettingContrast => Some("コントラスト"),
        LookStandard => Some("標準"),
        EffectsReduced => Some("控えめ"),
        ContrastHigh => Some("高"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "夜明けの光",
    "漂流",
    "地平線",
    "微光",
    "ヒバリ",
    "灯籠",
    "潮",
    "日の出",
    "サテライト",
    "露点",
    "絞り",
    "回廊",
    "要石",
    "日時計",
    "ピンホール",
    "風配図",
    "スリップストリーム",
    "フィラメント",
    "子午線",
    "カスケード",
    "クロスフェード",
    "つづら折り",
    "至点",
    "共鳴",
    "プリズム",
    "ハニカム",
    "波しぶき",
    "引き潮",
    "収穫",
    "万華鏡",
    "タペストリー",
    "長い影",
    "残光",
    "蛹",
    "ジオード",
    "視差",
    "城塞",
    "オウムガイ",
    "晩祷",
    "超新星",
    "月の出",
    "薄暮",
    "灯火",
    "蛍",
    "灯台",
    "ノクターン",
    "ディープフィールド",
    "星座",
    "半影",
    "メトロノーム",
    "コロナ",
    "朔望",
    "パルサー",
    "シャッター",
    "本影",
    "皆既",
    "太陽風",
    "北極光",
    "リボン",
    "極夜",
    "大聖堂",
    "きらめき",
    "特異点",
    "帰還",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "夜明け",
    "漂流",
    "地平線",
    "微光",
    "ヒバリ",
    "灯籠",
    "潮",
    "日の出",
    "サテライト",
    "露点",
    "絞り",
    "回廊",
    "要石",
    "日時計",
    "ピンホール",
    "風配図",
    "スリップ",
    "フィラメント",
    "子午線",
    "カスケード",
    "クロス",
    "つづら折り",
    "至点",
    "共鳴",
    "プリズム",
    "ハニカム",
    "波しぶき",
    "引き潮",
    "収穫",
    "万華鏡",
    "タペストリー",
    "長影",
    "残光",
    "蛹",
    "ジオード",
    "視差",
    "城塞",
    "オウムガイ",
    "晩祷",
    "超新星",
    "月の出",
    "薄暮",
    "灯火",
    "蛍",
    "灯台",
    "ノクターン",
    "ディープ",
    "星座",
    "半影",
    "メトロノーム",
    "コロナ",
    "朔望",
    "パルサー",
    "シャッター",
    "本影",
    "皆既",
    "太陽風",
    "北極光",
    "リボン",
    "極夜",
    "大聖堂",
    "きらめき",
    "特異点",
    "帰還",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} ワイド：落ちてくるカプセルをキャッチ",
    "{icon:slow} スロー：取るとボールが落ち着く",
    "操作：パドルの端でボールを大きく飛ばせ",
    "点在する火花：一つずつ追い詰めろ",
    "開いた両翼からボールを上へ",
    "灯籠を下から一つずつ片づけよう",
    "うねりに乗れ：横の壁で跳ね返せ",
    "太陽を下から一列ずつ削れ",
    "{icon:anchor} アンカー：ボールを受け止め、狙って放つ",
    "装甲ブロックは2回で割れる：縁に注意",
    "{icon:anchor} 壁の隙間を狙い撃て",
    "入口は一つ：ボールを中庭へ",
    "要石を崩せば、アーチが開く",
    "角度を読め：影の一つ一つが一打",
    "{icon:anchor} 細いピンホール：保持、狙って、放て",
    "どの方角も中心へ続く",
    "琥珀のコア：爆発は隣接する4つに届く",
    "フィラメントはどこに触れても両側へ燃える",
    "子午線に沿って場を二分しよう",
    "カスケードはどちらの端からでも",
    "2本のリレーラインの間に道を開こう",
    "3本のリレーライン：それぞれ一発で決めろ",
    "リングは丸ごと燃える：縁までの道を見つけよう",
    "隣り合うコアが連鎖を伝える",
    "{icon:multi} マルチボール：3つのボールで1つの突破口を",
    "すべてのセルにコア：割って開けろ",
    "しぶきが舞う：3つのボールを解き放て",
    "装甲の奥にあるポケットへ切り込め",
    "満杯の場：{icon:multi} マルチボールで一掃",
    "鏡だらけ：片側を割り、次に双子を割れ",
    "糸を一本引けば織物がほどける",
    "床を突き破り、長い導火線に火をつけろ",
    "{icon:phase} フェイズ：跳ね返らずにブロックへ3回接触",
    "{icon:phase} フェイズ：外殻をすり抜けてコアへ",
    "ジオードを割れば、結晶が輝き出す",
    "外殻を貫き、内側のルートに点火せよ",
    "ゲートから入るか、{icon:phase} フェイズで壁を抜けろ",
    "渦を描いて進め：外側の渦が先に灯る",
    "3つの鐘：それぞれを下から鳴らせ",
    "他のボールが飛ぶ間に戻りをキャッチ",
    "空いた中心の周りをリレーに沿って進め",
    "光が去っていく：今のうちに場を覚えろ",
    "闇の中ではボールとパドルが光を運ぶ",
    "蛍：コアは暗闇でも光る",
    "パドルの光で海岸を照らせ",
    "ボールが増えれば光も増える：{icon:multi} マルチボール",
    "ディープフィールド：かすかな点はすべてブロック",
    "星をつなげ：明るいものがコア",
    "ゲートは拍に合わせて薄れる：隙間を待て",
    "カチ、コチ：ゲートが時を刻む",
    "コロナは拍に合わせて開く：内側を打て",
    "幽霊ゲートは爆発を受け流す：火花のタイミングを計れ",
    "パルサー：速い拍、速い手",
    "シャッターは一瞬だけ開く：備えよ",
    "半分は影の中：ゲート側が拍を刻む",
    "月が実体のうちに太陽へ点火せよ",
    "風は一方向：コアまで乗っていけ",
    "光のカーテン：{icon:multi} マルチボールで払え",
    "リボンはそれぞれゲートに結ばれている：両半分を断て",
    "長い夜：持っている光を頼りに狙え",
    "扉から入り、バラ窓へ上がれ",
    "すべてが同時に：コアに注意",
    "ゲートが固くなる瞬間にリングを打て",
    "最後の一周：すべての突破口を生かせ",
];
