//! Japanese. Polite plain style for notes, terse imperatives for tips;
//! full-width punctuation (：・？) and a space between Japanese and Latin.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "宇宙を打ち砕け",
        ContinueJourney => "旅を続ける",
        NewJourney => "新しい旅",
        SectorSelect => "セクター選択",
        ContinueDetail => "{0}・{1}",
        StatMedals => "メダル",
        StatBest => "ベスト",
        ActionServe => "サーブ",
        ActionRelease => "リリース",
        ActionSelect => "決定",
        ActionResume => "再開",
        ActionBack => "戻る",
        Fullscreen => "フルスクリーン",
        SectorsHeading => "セクター",
        PracticeNote => "練習は旅の進行に影響しません",
        MedalClear => "クリア",
        MedalClean => "ノーミス",
        MedalSwift => "スピード",
        PlaySector => "セクター {0} をプレイ",
        UnlockHint => "セクター {0} をクリアで解放",
        Plus => "+{0}",
        ReadyEyebrow => "{0}・セクター {1}",
        Paused => "一時停止中",
        RetrySector => "セクターをリトライ",
        MainMenu => "メインメニュー",
        JourneyComplete => "旅の完了",
        OneMoreOrbit => "もう一周？",
        StatPoints => "ポイント",
        SectorClear => "セクタークリア",
        StatTime => "タイム",
        StatBonus => "ボーナス",
        StatChain => "チェイン",
        ExtraLife => "章クリア・ライフ +1",
        NextSector => "次のセクター",
        BackToSectors => "セクター選択へ",
        SaveFailed => "進行状況をセーブできませんでした",
        PerfTitle => "パフォーマンス / CPU",
        HelpResume => "中断したところから再開します",
        HelpRetry => "セクターのチェックポイントからやり直します",
        HelpMainMenu => "旅の進行はセーブされています",
        HelpSectors => "開放済みのセクターを練習できます",
        HelpNewJourney => "セクター 01 から再スタート・メダルは残ります",
        Settings => "設定",
        HelpSettings => "サウンド・画面・言語",
        SettingSound => "サウンド",
        SettingVolume => "音量",
        SettingDisplay => "画面",
        SettingLanguage => "言語",
        DisplayWindow => "ウインドウ",
        LanguageSystem => "システム",
        ActionAdjust => "調整",
        KeySpace => "スペース",
        KeyEsc => "Esc",
        SectorsOf => "{0} / {1} セクター",
        TargetBest => "{0}・ベスト {1}",
        LifeGained => "ライフ +1",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "暁",
            Chapter::BlueHour => "ブルーアワー",
            Chapter::Afterlight => "黄昏",
        },
        PowerName(p) => match p {
            Power::Wide => "ワイド",
            Power::Slow => "スロー",
            Power::Multi => "マルチボール",
            Power::Anchor => "アンカー",
            Power::Phase => "フェイズ",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("続ける"),
        UnlockHint => Some("ロック中"),
        RetrySector => Some("リトライ"),
        MainMenu => Some("メニュー"),
        NewJourney => Some("新規"),
        SectorSelect => Some("セクター"),
        NextSector => Some("次へ"),
        BackToSectors => Some("セクター"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "夜明けの光",
    "サテライト",
    "スリップストリーム",
    "共鳴",
    "プリズム",
    "クロスフェード",
    "引き潮",
    "月の出",
    "残光",
    "視差",
    "超新星",
    "帰還",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} ワイドと {icon:slow} スロー：落ちてくるカプセルをキャッチ",
    "{icon:anchor} アンカー：ボールを受け止め、狙って放つ",
    "琥珀のコア：爆発は隣接する4つに届く",
    "隣り合うコアが連鎖を伝える",
    "{icon:multi} マルチボール：3つのボールで1つの突破口を",
    "2本のリレーラインの間に道を開こう",
    "装甲の奥にあるポケットへ切り込め",
    "空いた中心の周りをリレーに沿って進め",
    "{icon:phase} フェイズ：跳ね返らずにブロックへ3回接触",
    "外殻を貫き、内側のルートに点火せよ",
    "他のボールが飛ぶ間に戻りをキャッチ",
    "最後の一周：すべての突破口を生かせ",
];
