//! Korean. Polite *-세요* imperatives; ASCII colons and question marks,
//! as Korean sets them.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "우주를 부숴라",
        ContinueJourney => "여정 계속하기",
        NewJourney => "새 여정",
        SectorSelect => "섹터 선택",
        ContinueDetail => "{0} · {1}",
        StatMedals => "메달",
        StatBest => "최고 점수",
        ActionServe => "서브",
        ActionRelease => "놓기",
        ActionSelect => "선택",
        ActionResume => "재개",
        ActionBack => "뒤로",
        Fullscreen => "전체 화면",
        SectorsHeading => "섹터",
        PracticeNote => "연습은 여정에 영향을 주지 않습니다",
        MedalClear => "클리어",
        MedalClean => "무결점",
        MedalSwift => "신속",
        PlaySector => "섹터 {0} 플레이",
        UnlockHint => "섹터 {0} 완료 시 잠금 해제",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · 섹터 {1}",
        Paused => "일시정지",
        RetrySector => "섹터 재시도",
        MainMenu => "메인 메뉴",
        JourneyComplete => "여정 완료",
        OneMoreOrbit => "한 바퀴 더?",
        StatPoints => "점수",
        SectorClear => "섹터 클리어",
        StatTime => "시간",
        StatBonus => "보너스",
        StatChain => "연쇄",
        ExtraLife => "챕터 완료 · 생명 +1",
        NextSector => "다음 섹터",
        BackToSectors => "섹터로 돌아가기",
        SaveFailed => "진행 상황을 저장하지 못했습니다",
        PerfTitle => "성능 / CPU",
        HelpResume => "멈춘 곳부터 이어서 합니다",
        HelpRetry => "섹터 체크포인트부터 다시 시작합니다",
        HelpMainMenu => "여정이 저장되어 있습니다",
        HelpSectors => "열린 섹터를 연습합니다",
        HelpNewJourney => "섹터 01부터 다시 시작 · 메달은 유지됩니다",
        Settings => "설정",
        HelpSettings => "사운드, 화면, 언어",
        SettingSound => "사운드",
        SettingVolume => "볼륨",
        SettingDisplay => "화면",
        SettingLanguage => "언어",
        DisplayWindow => "창 모드",
        LanguageSystem => "시스템",
        ActionAdjust => "조정",
        SettingEffects => "효과",
        SettingContrast => "대비",
        LookStandard => "표준",
        EffectsReduced => "줄임",
        ContrastHigh => "높음",
        KeySpace => "스페이스",
        KeyEsc => "Esc",
        SectorsOf => "{1}개 섹터 중 {0}개",
        TargetBest => "{0} · 최고 {1}",
        LifeGained => "생명 +1",
        PresenceMenus => "메뉴 화면",
        PresenceJourney => "섹터 {0} · {1}",
        PresencePractice => "섹터 {0} · {1} 연습 중",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "새벽",
            Chapter::BlueHour => "블루 아워",
            Chapter::Afterlight => "황혼",
        },
        PowerName(p) => match p {
            Power::Wide => "와이드",
            Power::Slow => "슬로우",
            Power::Multi => "멀티볼",
            Power::Anchor => "앵커",
            Power::Phase => "페이즈",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("계속"),
        UnlockHint => Some("잠김"),
        RetrySector => Some("재시도"),
        MainMenu => Some("메뉴"),
        NewJourney => Some("새로"),
        SectorSelect => Some("섹터"),
        NextSector => Some("다음"),
        BackToSectors => Some("섹터"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("재개"),
        PlaySector => Some("플레이 {0}"),
        Settings => Some("설정"),
        ActionServe => Some("서브"),
        ActionRelease => Some("놓기"),
        ActionSelect => Some("선택"),
        ActionBack => Some("뒤로"),
        ActionAdjust => Some("조정"),
        StatBest => Some("최고"),
        StatMedals => Some("메달"),
        SectorsHeading => Some("섹터"),
        SaveFailed => Some("저장 실패"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("스페이스"),
        HelpResume => Some("게임으로 돌아갑니다"),
        HelpRetry => Some("체크포인트부터"),
        HelpMainMenu => Some("여정 저장됨"),
        HelpSectors => Some("섹터 연습"),
        HelpNewJourney => Some("섹터 01부터"),
        HelpSettings => Some("사운드, 화면"),
        SettingSound => Some("사운드"),
        SettingVolume => Some("볼륨"),
        SettingDisplay => Some("화면"),
        SettingLanguage => Some("언어"),
        DisplayWindow => Some("창"),
        Fullscreen => Some("전체"),
        LanguageSystem => Some("시스템"),
        ExtraLife => Some("생명 +1"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("섹터 {1}"),
        SettingEffects => Some("효과"),
        SettingContrast => Some("대비"),
        LookStandard => Some("표준"),
        EffectsReduced => Some("줄임"),
        ContrastHigh => Some("높음"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "첫 빛",
    "위성",
    "슬립스트림",
    "공명",
    "프리즘",
    "크로스페이드",
    "역류",
    "월출",
    "잔광",
    "시차",
    "초신성",
    "귀환",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "첫 빛",
    "위성",
    "슬립",
    "공명",
    "프리즘",
    "크로스",
    "역류",
    "월출",
    "잔광",
    "시차",
    "초신성",
    "귀환",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} 와이드와 {icon:slow} 슬로우: 떨어지는 캡슐을 잡으세요",
    "{icon:anchor} 앵커: 공을 잡고, 조준한 뒤 놓으세요",
    "호박색 코어: 폭발이 인접한 네 칸에 닿습니다",
    "이웃한 코어가 연쇄 반응을 이어 갑니다",
    "{icon:multi} 멀티볼: 세 개의 공, 하나의 틈",
    "두 릴레이 라인 사이로 길을 여세요",
    "장갑 뒤의 빈 공간으로 파고드세요",
    "빈 중앙을 따라 릴레이를 쫓으세요",
    "{icon:phase} 페이즈: 튕기지 않고 벽돌에 세 번 접촉",
    "외피를 뚫고 안쪽 경로에 불을 붙이세요",
    "다른 공이 날아가는 동안 돌아오는 공을 잡으세요",
    "마지막 한 바퀴: 모든 틈을 살리세요",
];
