//! Korean. Polite *-세요* imperatives; ASCII colons and question marks,
//! as Korean sets them.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "우주를 부숴라",
        ContinueJourney => "여정 계속하기",
        NewJourney => "새 여정",
        SectorSelect => "섹터 선택",
        ContinueDetail => "{0} · {1}",
        StatMedals => "메달",
        StatBest => "최고 점수",
        ActionServe => "서브",
        ActionRelease => "놓기",
        ActionSelect => "선택",
        ActionResume => "재개",
        ActionBack => "뒤로",
        Fullscreen => "전체 화면",
        SectorsHeading => "섹터",
        PracticeNote => "연습은 여정에 영향을 주지 않습니다",
        MedalClear => "클리어",
        MedalClean => "무결점",
        MedalSwift => "신속",
        PlaySector => "섹터 {0} 플레이",
        UnlockHint => "섹터 {0} 완료 시 잠금 해제",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · 섹터 {1}",
        Paused => "일시정지",
        RetrySector => "섹터 재시도",
        MainMenu => "메인 메뉴",
        JourneyComplete => "여정 완료",
        OneMoreOrbit => "한 바퀴 더?",
        StatPoints => "점수",
        SectorClear => "섹터 클리어",
        StatTime => "시간",
        StatBonus => "보너스",
        StatChain => "연쇄",
        ExtraLife => "챕터 완료 · 생명 +1",
        NextSector => "다음 섹터",
        BackToSectors => "섹터로 돌아가기",
        SaveFailed => "진행 상황을 저장하지 못했습니다",
        PerfTitle => "성능 / CPU",
        HelpResume => "멈춘 곳부터 이어서 합니다",
        HelpRetry => "섹터 체크포인트부터 다시 시작합니다",
        HelpMainMenu => "여정이 저장되어 있습니다",
        HelpSectors => "열린 섹터를 연습합니다",
        HelpNewJourney => "섹터 01부터 다시 시작 · 메달은 유지됩니다",
        Settings => "설정",
        HelpSettings => "사운드, 화면, 언어",
        SettingSound => "사운드",
        SettingVolume => "볼륨",
        SettingDisplay => "화면",
        SettingLanguage => "언어",
        DisplayWindow => "창 모드",
        LanguageSystem => "시스템",
        ActionAdjust => "조정",
        SettingEffects => "효과",
        SettingContrast => "대비",
        LookStandard => "표준",
        EffectsReduced => "줄임",
        ContrastHigh => "높음",
        KeySpace => "스페이스",
        KeyEsc => "Esc",
        SectorsOf => "{1}개 섹터 중 {0}개",
        TargetBest => "{0} · 최고 {1}",
        LifeGained => "생명 +1",
        PresenceMenus => "메뉴 화면",
        PresenceJourney => "섹터 {0} · {1}",
        PresencePractice => "섹터 {0} · {1} 연습 중",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "새벽",
            Chapter::Morning => "아침",
            Chapter::Zenith => "천정",
            Chapter::GoldenHour => "골든 아워",
            Chapter::Afterlight => "황혼",
            Chapter::BlueHour => "블루 아워",
            Chapter::Eclipse => "일식",
            Chapter::Aurora => "오로라",
        },
        PowerName(p) => match p {
            Power::Wide => "와이드",
            Power::Slow => "슬로우",
            Power::Multi => "멀티볼",
            Power::Anchor => "앵커",
            Power::Phase => "페이즈",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("계속"),
        UnlockHint => Some("잠김"),
        RetrySector => Some("재시도"),
        MainMenu => Some("메뉴"),
        NewJourney => Some("새로"),
        SectorSelect => Some("섹터"),
        NextSector => Some("다음"),
        BackToSectors => Some("섹터"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("재개"),
        PlaySector => Some("플레이 {0}"),
        Settings => Some("설정"),
        ActionServe => Some("서브"),
        ActionRelease => Some("놓기"),
        ActionSelect => Some("선택"),
        ActionBack => Some("뒤로"),
        ActionAdjust => Some("조정"),
        StatBest => Some("최고"),
        StatMedals => Some("메달"),
        SectorsHeading => Some("섹터"),
        SaveFailed => Some("저장 실패"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("스페이스"),
        HelpResume => Some("게임으로 돌아갑니다"),
        HelpRetry => Some("체크포인트부터"),
        HelpMainMenu => Some("여정 저장됨"),
        HelpSectors => Some("섹터 연습"),
        HelpNewJourney => Some("섹터 01부터"),
        HelpSettings => Some("사운드, 화면"),
        SettingSound => Some("사운드"),
        SettingVolume => Some("볼륨"),
        SettingDisplay => Some("화면"),
        SettingLanguage => Some("언어"),
        DisplayWindow => Some("창"),
        Fullscreen => Some("전체"),
        LanguageSystem => Some("시스템"),
        ExtraLife => Some("생명 +1"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("섹터 {1}"),
        SettingEffects => Some("효과"),
        SettingContrast => Some("대비"),
        LookStandard => Some("표준"),
        EffectsReduced => Some("줄임"),
        ContrastHigh => Some("높음"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "첫 빛",
    "표류",
    "지평선",
    "미광",
    "종달새",
    "초롱",
    "조수",
    "일출",
    "위성",
    "이슬점",
    "조리개",
    "회랑",
    "쐐기돌",
    "해시계",
    "바늘구멍",
    "바람장미",
    "슬립스트림",
    "필라멘트",
    "자오선",
    "캐스케이드",
    "크로스페이드",
    "굽이길",
    "지점",
    "공명",
    "프리즘",
    "벌집",
    "물보라",
    "역류",
    "수확",
    "만화경",
    "태피스트리",
    "긴 그림자",
    "잔광",
    "번데기",
    "정동",
    "시차",
    "요새",
    "앵무조개",
    "만종",
    "초신성",
    "월출",
    "땅거미",
    "램프 불빛",
    "반딧불이",
    "등대",
    "녹턴",
    "딥 필드",
    "별자리",
    "반그림자",
    "메트로놈",
    "코로나",
    "삭망",
    "펄서",
    "셔터",
    "본그림자",
    "개기식",
    "태양풍",
    "북극광",
    "리본",
    "극야",
    "대성당",
    "일렁임",
    "특이점",
    "귀환",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "첫 빛",
    "표류",
    "지평선",
    "미광",
    "종달새",
    "초롱",
    "조수",
    "일출",
    "위성",
    "이슬점",
    "조리개",
    "회랑",
    "쐐기돌",
    "해시계",
    "바늘구멍",
    "바람장미",
    "슬립",
    "필라멘트",
    "자오선",
    "캐스케이드",
    "크로스",
    "굽이길",
    "지점",
    "공명",
    "프리즘",
    "벌집",
    "물보라",
    "역류",
    "수확",
    "만화경",
    "태피스트리",
    "긴 그림자",
    "잔광",
    "번데기",
    "정동",
    "시차",
    "요새",
    "앵무조개",
    "만종",
    "초신성",
    "월출",
    "땅거미",
    "램프빛",
    "반딧불",
    "등대",
    "녹턴",
    "딥 필드",
    "별자리",
    "반그림자",
    "메트로놈",
    "코로나",
    "삭망",
    "펄서",
    "셔터",
    "본그림자",
    "개기식",
    "태양풍",
    "북극광",
    "리본",
    "극야",
    "대성당",
    "일렁임",
    "특이점",
    "귀환",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} 와이드: 떨어지는 캡슐을 잡으세요",
    "{icon:slow} 슬로우: 잡으면 공이 느려집니다",
    "조종: 패들 가장자리가 공을 넓게 보냅니다",
    "외딴 불꽃: 하나씩 쫓아가세요",
    "열린 날개 쪽으로 공을 올려 보내세요",
    "초롱을 아래에서 하나씩 치우세요",
    "물결을 타세요: 옆 벽에 맞혀 튕기세요",
    "태양을 아래에서 한 줄씩 깎아 내세요",
    "{icon:anchor} 앵커: 공을 잡고, 조준한 뒤 놓으세요",
    "장갑 벽돌은 두 번 맞아야 합니다: 가장자리를 보세요",
    "{icon:anchor} 벽의 틈을 향해 조준하세요",
    "문은 하나뿐: 공을 안뜰로 보내세요",
    "쐐기돌을 빼면 아치가 열립니다",
    "각도를 읽으세요: 그림자 하나가 샷 하나입니다",
    "{icon:anchor} 좁은 바늘구멍 하나: 잡고, 조준하고, 놓으세요",
    "어느 방위든 중심으로 이어집니다",
    "호박색 코어: 폭발이 인접한 네 칸에 닿습니다",
    "필라멘트는 어디를 건드려도 양쪽으로 탑니다",
    "자오선을 따라 필드를 나누세요",
    "캐스케이드는 어느 쪽 끝에서든 시작하세요",
    "두 릴레이 라인 사이로 길을 여세요",
    "릴레이 라인 셋: 라인마다 깔끔한 한 방",
    "고리는 통째로 탑니다: 가장자리로 가는 길을 찾으세요",
    "이웃한 코어가 연쇄 반응을 이어 갑니다",
    "{icon:multi} 멀티볼: 세 개의 공, 하나의 틈",
    "칸마다 코어가 있습니다: 모두 깨뜨리세요",
    "물보라가 사방에: 공 세 개를 풀어 놓으세요",
    "장갑 뒤의 빈 공간으로 파고드세요",
    "꽉 찬 필드: {icon:multi} 멀티볼로 빠르게 쓸어 내세요",
    "사방이 거울: 한쪽을 깨고 나서 쌍둥이를 깨세요",
    "실 한 가닥을 당기면 직물이 풀립니다",
    "바닥을 뚫고 긴 도화선에 불을 붙이세요",
    "{icon:phase} 페이즈: 튕기지 않고 벽돌에 세 번 접촉",
    "{icon:phase} 페이즈: 외피를 지나 코어까지 스며듭니다",
    "정동을 깨면 결정이 빛납니다",
    "외피를 뚫고 안쪽 경로에 불을 붙이세요",
    "게이트로 들어가거나 {icon:phase} 페이즈로 벽을 통과하세요",
    "나선으로 파고드세요: 바깥 고리부터 불이 붙습니다",
    "종 세 개: 아래에서 하나씩 울리세요",
    "다른 공이 날아가는 동안 돌아오는 공을 잡으세요",
    "빈 중앙을 따라 릴레이를 쫓으세요",
    "빛이 사라지고 있습니다: 있을 때 필드를 익히세요",
    "어둠 속에서는 공과 패들이 빛을 지닙니다",
    "반딧불: 코어는 어둠 속에서도 빛납니다",
    "패들의 빛으로 해안을 훑으세요",
    "공이 많을수록 빛도 늘어납니다: {icon:multi} 멀티볼",
    "딥 필드: 희미한 점마다 벽돌입니다",
    "별을 이으세요: 밝은 별이 코어입니다",
    "게이트가 박자에 맞춰 흐려집니다: 틈을 기다리세요",
    "똑딱: 게이트가 박자를 맞춥니다",
    "코로나는 박자에 맞춰 열립니다: 안쪽을 치세요",
    "유령 게이트는 폭발을 흘려보냅니다: 불꽃의 타이밍을 맞추세요",
    "펄서: 빠른 박자, 빠른 손",
    "셔터는 잠깐만 열립니다: 준비하세요",
    "절반은 그림자 속: 게이트 쪽이 박자를 맞춥니다",
    "달이 단단할 때 태양에 불을 붙이세요",
    "바람은 한 방향으로 붑니다: 타고 코어까지 가세요",
    "빛의 장막: {icon:multi} 멀티볼로 쓸어 내세요",
    "리본마다 게이트에 묶여 있습니다: 양쪽 반을 모두 끊으세요",
    "긴 밤: 지닌 빛을 보고 조준하세요",
    "문으로 들어가 장미창까지 오르세요",
    "모든 것이 동시에: 코어를 살피세요",
    "게이트가 단단해질 때 고리를 치세요",
    "마지막 한 바퀴: 모든 틈을 살리세요",
];
