//! Korean. Polite *-세요* imperatives; ASCII colons and question marks,
//! as Korean sets them.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "우주를 부숴라",
        ContinueJourney => "여정 계속하기",
        NewJourney => "새 여정",
        SectorSelect => "섹터 선택",
        ContinueDetail => "섹터 {0} · {1} · {2}",
        StatSectors => "섹터",
        StatMedals => "메달",
        StatBest => "최고 점수",
        Fraction => "{0} / {1}",
        KeysMove => "마우스 또는 방향키로 이동",
        KeysServe => "스페이스 또는 클릭으로 서브",
        KeysPause => "Esc로 일시정지",
        KeysRelease => "클릭 또는 스페이스로 놓기",
        KeysBrowse => "방향키로 탐색",
        KeysPlay => "Enter로 플레이",
        KeysBack => "Esc로 돌아가기",
        KeysContinue => "Enter 또는 클릭으로 계속",
        PadMove => "스틱 또는 방향 패드로 이동",
        PadBrowse => "방향 패드로 탐색",
        ActionServe => "서브",
        ActionPause => "일시정지",
        ActionRelease => "놓기",
        ActionSelect => "선택",
        ActionResume => "재개",
        ActionRetry => "재시도",
        ActionPlay => "플레이",
        ActionBack => "뒤로",
        ActionContinue => "계속",
        SoundOn => "사운드 켬",
        SoundOff => "사운드 끔",
        Volume => "볼륨 {0}",
        Fullscreen => "전체 화면",
        SectorsHeading => "섹터",
        PracticeNote => "연습 플레이는 여정에 영향을 주지 않습니다",
        NoTime => "--:--",
        SwiftTarget => "목표 시간 {0}",
        BestTime => "최고 기록 {0}",
        MedalClear => "클리어",
        MedalClean => "무결점",
        MedalSwift => "신속",
        MedalClearHow => "섹터 완료",
        MedalCleanHow => "생명을 잃지 않기",
        MedalSwiftHow => "목표 시간 안에 완료",
        PlaySector => "섹터 {0} 플레이",
        ClearPreviousFirst => "이전 섹터를 먼저 완료하세요",
        Score => "점수",
        Lives => "생명",
        SectorNumber => "섹터 {0}",
        PracticeNumber => "연습 {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · 섹터 {1}",
        Paused => "일시정지",
        RetrySector => "섹터 재시도",
        MainMenu => "메인 메뉴",
        RetryNote => "재시도하면 체크포인트부터 다시 시작합니다",
        JourneyComplete => "여정 완료",
        OneMoreOrbit => "한 바퀴 더?",
        StatPoints => "점수",
        ProgressSaved => "진행 상황이 저장되었습니다",
        SectorClear => "섹터 클리어",
        StatTime => "시간",
        StatBonus => "보너스",
        StatBestChain => "최고 연쇄",
        ExtraLife => "챕터 완료 · 추가 생명",
        NextSector => "다음 섹터",
        BackToSectors => "섹터로 돌아가기",
        SaveFailed => "진행 상황을 저장하지 못했습니다",
        PerfTitle => "성능 / CPU",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "새벽",
            Chapter::BlueHour => "블루 아워",
            Chapter::Afterlight => "황혼",
        },
        PowerName(p) => match p {
            Power::Wide => "와이드",
            Power::Slow => "슬로우",
            Power::Multi => "멀티볼",
            Power::Anchor => "앵커",
            Power::Phase => "페이즈",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1} · {2}"),
        ContinueJourney => Some("계속"),
        ClearPreviousFirst => Some("잠김"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "첫 빛",
    "위성",
    "슬립스트림",
    "공명",
    "프리즘",
    "크로스페이드",
    "역류",
    "월출",
    "잔광",
    "시차",
    "초신성",
    "귀환",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} 와이드와 {icon:slow} 슬로우: 떨어지는 캡슐을 잡으세요",
    "{icon:anchor} 앵커: 공을 잡고, 조준한 뒤 놓으세요",
    "호박색 코어: 폭발이 인접한 네 칸에 닿습니다",
    "이웃한 코어가 연쇄 반응을 이어 갑니다",
    "{icon:multi} 멀티볼: 세 개의 공, 하나의 틈",
    "두 릴레이 라인 사이로 길을 여세요",
    "장갑 뒤의 빈 공간으로 파고드세요",
    "빈 중앙을 따라 릴레이를 쫓으세요",
    "{icon:phase} 페이즈: 튕기지 않고 벽돌에 세 번 접촉",
    "외피를 뚫고 안쪽 경로에 불을 붙이세요",
    "다른 공이 날아가는 동안 돌아오는 공을 잡으세요",
    "마지막 한 바퀴: 모든 틈을 살리세요",
];
