//! Norwegian Bokmål. Informal *du*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Knus kosmos",
        ContinueJourney => "Fortsett reisen",
        NewJourney => "Ny reise",
        SectorSelect => "Velg sektor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALJER",
        StatBest => "REKORD",
        ActionServe => "Serve",
        ActionRelease => "Slipp",
        ActionSelect => "Velg",
        ActionResume => "Gjenoppta",
        ActionBack => "Tilbake",
        Fullscreen => "Fullskjerm",
        SectorsHeading => "Sektorer",
        PracticeNote => "Trening endrer aldri reisen din",
        MedalClear => "KLART",
        MedalClean => "FEILFRI",
        MedalSwift => "RASK",
        PlaySector => "Spill sektor {0}",
        UnlockHint => "Fullfør sektor {0} for å låse opp",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pause",
        RetrySector => "Prøv sektoren igjen",
        MainMenu => "Hovedmeny",
        JourneyComplete => "Reisen er fullført",
        OneMoreOrbit => "Én bane til?",
        StatPoints => "POENG",
        SectorClear => "Sektor klart",
        StatTime => "TID",
        StatBonus => "BONUS",
        StatChain => "KJEDE",
        ExtraLife => "Kapittel fullført · +1 liv",
        NextSector => "Neste sektor",
        BackToSectors => "Tilbake til sektorer",
        SaveFailed => "Fremgangen kunne ikke lagres",
        PerfTitle => "Ytelse / CPU",
        HelpResume => "Fortsett der du slapp",
        HelpRetry => "Start på nytt fra sektorens sjekkpunkt",
        HelpMainMenu => "Reisen din er lagret",
        HelpSectors => "Tren i en åpen sektor",
        HelpNewJourney => "På nytt fra sektor 01 · medaljene beholdes",
        Settings => "Innstillinger",
        HelpSettings => "Lyd, skjerm, språk",
        SettingSound => "Lyd",
        SettingVolume => "Volum",
        SettingDisplay => "Skjerm",
        SettingLanguage => "Språk",
        DisplayWindow => "Vindu",
        LanguageSystem => "System",
        ActionAdjust => "Juster",
        SettingEffects => "Effekter",
        SettingContrast => "Kontrast",
        LookStandard => "Standard",
        EffectsReduced => "Redusert",
        ContrastHigh => "Høy",
        KeySpace => "Mellomrom",
        KeyEsc => "Esc",
        SectorsOf => "{0} av {1} sektorer",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 liv",
        PresenceMenus => "I menyene",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Trener sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAGGRY",
            Chapter::Morning => "MORGEN",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "GYLNE TIME",
            Chapter::Afterlight => "ETTERLYS",
            Chapter::BlueHour => "BLÅTIMEN",
            Chapter::Eclipse => "FORMØRKELSE",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "BRED",
            Power::Slow => "SAKTE",
            Power::Multi => "MULTIBALL",
            Power::Anchor => "ANKER",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Fortsett"),
        UnlockHint => Some("Låst"),
        RetrySector => Some("Prøv igjen"),
        MainMenu => Some("Meny"),
        NewJourney => Some("Ny"),
        SectorSelect => Some("Sektorer"),
        NextSector => Some("Neste"),
        BackToSectors => Some("Sektorer"),
        Settings => Some("Valg"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Fortsett"),
        PlaySector => Some("Spill {0}"),
        ActionServe => Some("Serve"),
        ActionRelease => Some("Slipp"),
        ActionSelect => Some("Velg"),
        ActionBack => Some("Tilbake"),
        ActionAdjust => Some("Juster"),
        SettingEffects => Some("Effekter"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Færre"),
        ContrastHigh => Some("Høy"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDALJER"),
        SectorsHeading => Some("Sektorer"),
        SaveFailed => Some("Ikke lagret"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Mellomrom"),
        HelpResume => Some("Tilbake til spillet"),
        HelpRetry => Some("Fra sjekkpunktet"),
        HelpMainMenu => Some("Reisen er lagret"),
        HelpSectors => Some("Tren sektorer"),
        HelpNewJourney => Some("Fra sektor 01"),
        HelpSettings => Some("Lyd, skjerm"),
        SettingSound => Some("Lyd"),
        SettingVolume => Some("Volum"),
        SettingDisplay => Some("Skjerm"),
        SettingLanguage => Some("Språk"),
        DisplayWindow => Some("Vindu"),
        Fullscreen => Some("Full"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 liv"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Fullført"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Første lys",
    "Drift",
    "Horisont",
    "Glimt",
    "Lerke",
    "Lykter",
    "Tidevann",
    "Soloppgang",
    "Satellitter",
    "Duggpunkt",
    "Blenderåpning",
    "Kloster",
    "Sluttstein",
    "Solur",
    "Nålehull",
    "Vindrose",
    "Slipstrøm",
    "Glødetråd",
    "Meridian",
    "Kaskade",
    "Overtoning",
    "Serpentin",
    "Solverv",
    "Resonans",
    "Prisme",
    "Vokskake",
    "Skumsprut",
    "Understrøm",
    "Innhøsting",
    "Kaleidoskop",
    "Gobelin",
    "Lange skygger",
    "Etterglød",
    "Puppe",
    "Geode",
    "Parallakse",
    "Citadell",
    "Nautilus",
    "Aftensang",
    "Supernova",
    "Måneoppgang",
    "Skumring",
    "Lampelys",
    "Ildfluer",
    "Fyrtårn",
    "Nocturne",
    "Dypfelt",
    "Stjernebilde",
    "Halvskygge",
    "Metronom",
    "Korona",
    "Syzygi",
    "Pulsar",
    "Lukker",
    "Umbra",
    "Totalitet",
    "Solvind",
    "Nordlys",
    "Bånd",
    "Polarnatt",
    "Katedral",
    "Skimmer",
    "Singularitet",
    "Hjemkomst",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Første lys",
    "Drift",
    "Horisont",
    "Glimt",
    "Lerke",
    "Lykter",
    "Tidevann",
    "Sol",
    "Satellitter",
    "Duggpunkt",
    "Blender",
    "Kloster",
    "Sluttstein",
    "Solur",
    "Nålehull",
    "Vindrose",
    "Slipstrøm",
    "Tråd",
    "Meridian",
    "Kaskade",
    "Overtoning",
    "Serpentin",
    "Solverv",
    "Resonans",
    "Prisme",
    "Voks",
    "Skumsprut",
    "Understrøm",
    "Høst",
    "Kaleido",
    "Gobelin",
    "Skygger",
    "Etterglød",
    "Puppe",
    "Geode",
    "Parallakse",
    "Citadell",
    "Nautilus",
    "Aftensang",
    "Supernova",
    "Måne",
    "Skumring",
    "Lampelys",
    "Ildfluer",
    "Fyrtårn",
    "Nocturne",
    "Dypfelt",
    "Stjerner",
    "Halvskygge",
    "Metronom",
    "Korona",
    "Syzygi",
    "Pulsar",
    "Lukker",
    "Umbra",
    "Totalitet",
    "Solvind",
    "Nordlys",
    "Bånd",
    "Polarnatt",
    "Katedral",
    "Skimmer",
    "Singularitet",
    "Hjemkomst",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Bred: fang den fallende kapselen",
    "{icon:slow} Sakte: fang den, så roer ballen seg",
    "Styr: kantene på racketen sender ballen bredt",
    "Enslige gnister: jag hver eneste",
    "Send ballen opp langs de åpne vingene",
    "Rydd hver lykt nedenfra",
    "Ri på dønningen: spill mot sideveggene",
    "Hugg solen bort nedenfra, rad for rad",
    "{icon:anchor} Anker: fang ballen, sikt og slipp den",
    "Pansrede klosser tåler to treff: se opp for kantene",
    "{icon:anchor} Sikt gjennom åpningen i muren",
    "Bare én dør: send ballen inn i gårdsplassen",
    "Slå ut sluttsteinen, så åpner buen seg",
    "Les vinklene: hver skygge er et skudd",
    "{icon:anchor} Ett smalt nålehull: hold, sikt, slipp",
    "Hvert himmelstrøk fører til hjertet",
    "Ravkjerner: hver eksplosjon når de fire naboene",
    "Berør glødetråden hvor som helst: den brenner begge veier",
    "Del banen langs meridianen",
    "Start kaskaden i begge ender",
    "Åpne en vei gjennom de to relélinjene",
    "Tre relélinjer: ett rent skudd hver",
    "Ringen brenner hel: finn en vei til kanten",
    "Nabokjerner fører reaksjonen videre",
    "{icon:multi} Multiball: tre baller, én åpning",
    "En kjerne i hver celle: knekk dem",
    "Skum overalt: slipp løs tre baller",
    "Bryt inn i lommene bak panseret",
    "Full bane: {icon:multi} Multiball rydder den raskt",
    "Speil overalt: bryt den ene siden, så tvillingen",
    "Trekk i én tråd, så går veven opp",
    "Bryt gjennom gulvet og tenn den lange lunta",
    "{icon:phase} Fase: tre klosstreff uten å sprette",
    "{icon:phase} Fase glir gjennom skallet til kjernen",
    "Knekk en geode, så tennes krystallene",
    "Gjennombryt skallet, og tenn så den indre ruten",
    "Inn gjennom porten, eller gjennom muren med {icon:phase} Fase",
    "Spiral innover: den ytterste viklingen tennes først",
    "Tre klokker: ring hver nedenfra",
    "Fang en returball mens de andre fortsetter",
    "Følg reléet rundt den åpne midten",
    "Lyset forsvinner: lær banen mens du kan",
    "I mørket bærer ballen og racketen lyset",
    "Ildfluer: kjernene gløder selv i mørket",
    "Sveip racketens lys over kysten",
    "Flere baller, mer lys: {icon:multi} Multiball",
    "Dypfelt: hver svake prikk er en kloss",
    "Bind sammen stjernene: de lyse er kjerner",
    "Porter blekner i takt: vent på åpningen",
    "Tikk, takk: portene holder takten",
    "Koronaen åpner seg i takt: treff innenfor",
    "En spøkelsesport rister av seg en eksplosjon: time gnisten",
    "En pulsar: raske slag, raske hender",
    "Lukkeren åpner seg et øyeblikk: vær klar",
    "Halvt i skygge: portsiden holder takten",
    "Tenn solen mens månen er fast",
    "Vinden blåser én vei: ri med den til kjernene",
    "Lysgardiner: sveip dem bort med {icon:multi} Multiball",
    "Hvert bånd er festet til en port: kutt begge halvdelene",
    "Den lange natten: sikt etter lyset du bærer",
    "Inn gjennom dørene, opp til rosevinduet",
    "Alt på én gang: hold øye med kjernene",
    "Treff ringen når portene blir faste",
    "En siste bane: få hver åpning til å telle",
];
