//! Norwegian Bokmål. Informal *du*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Knus kosmos",
        ContinueJourney => "Fortsett reisen",
        NewJourney => "Ny reise",
        SectorSelect => "Velg sektor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALJER",
        StatBest => "REKORD",
        ActionServe => "Serve",
        ActionRelease => "Slipp",
        ActionSelect => "Velg",
        ActionResume => "Gjenoppta",
        ActionBack => "Tilbake",
        Fullscreen => "Fullskjerm",
        SectorsHeading => "Sektorer",
        PracticeNote => "Trening endrer aldri reisen din",
        MedalClear => "KLART",
        MedalClean => "FEILFRI",
        MedalSwift => "RASK",
        PlaySector => "Spill sektor {0}",
        UnlockHint => "Fullfør sektor {0} for å låse opp",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pause",
        RetrySector => "Prøv sektoren igjen",
        MainMenu => "Hovedmeny",
        JourneyComplete => "Reisen er fullført",
        OneMoreOrbit => "Én bane til?",
        StatPoints => "POENG",
        SectorClear => "Sektor klart",
        StatTime => "TID",
        StatBonus => "BONUS",
        StatChain => "KJEDE",
        ExtraLife => "Kapittel fullført · +1 liv",
        NextSector => "Neste sektor",
        BackToSectors => "Tilbake til sektorer",
        SaveFailed => "Fremgangen kunne ikke lagres",
        PerfTitle => "Ytelse / CPU",
        HelpResume => "Fortsett der du slapp",
        HelpRetry => "Start på nytt fra sektorens sjekkpunkt",
        HelpMainMenu => "Reisen din er lagret",
        HelpSectors => "Tren i en åpen sektor",
        HelpNewJourney => "På nytt fra sektor 01 · medaljene beholdes",
        Settings => "Innstillinger",
        HelpSettings => "Lyd, skjerm, språk",
        SettingSound => "Lyd",
        SettingVolume => "Volum",
        SettingDisplay => "Skjerm",
        SettingLanguage => "Språk",
        DisplayWindow => "Vindu",
        LanguageSystem => "System",
        ActionAdjust => "Juster",
        KeySpace => "Mellomrom",
        KeyEsc => "Esc",
        SectorsOf => "{0} av {1} sektorer",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 liv",
        PresenceMenus => "I menyene",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Trener sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAGGRY",
            Chapter::BlueHour => "BLÅTIMEN",
            Chapter::Afterlight => "ETTERLYS",
        },
        PowerName(p) => match p {
            Power::Wide => "BRED",
            Power::Slow => "SAKTE",
            Power::Multi => "MULTIBALL",
            Power::Anchor => "ANKER",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Fortsett"),
        UnlockHint => Some("Låst"),
        RetrySector => Some("Prøv igjen"),
        MainMenu => Some("Meny"),
        NewJourney => Some("Ny"),
        SectorSelect => Some("Sektorer"),
        NextSector => Some("Neste"),
        BackToSectors => Some("Sektorer"),
        Settings => Some("Valg"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Fortsett"),
        PlaySector => Some("Spill {0}"),
        ActionServe => Some("Serve"),
        ActionRelease => Some("Slipp"),
        ActionSelect => Some("Velg"),
        ActionBack => Some("Tilbake"),
        ActionAdjust => Some("Juster"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDALJER"),
        SectorsHeading => Some("Sektorer"),
        SaveFailed => Some("Ikke lagret"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Mellomrom"),
        HelpResume => Some("Tilbake til spillet"),
        HelpRetry => Some("Fra sjekkpunktet"),
        HelpMainMenu => Some("Reisen er lagret"),
        HelpSectors => Some("Tren sektorer"),
        HelpNewJourney => Some("Fra sektor 01"),
        HelpSettings => Some("Lyd, skjerm"),
        SettingSound => Some("Lyd"),
        SettingVolume => Some("Volum"),
        SettingDisplay => Some("Skjerm"),
        SettingLanguage => Some("Språk"),
        DisplayWindow => Some("Vindu"),
        Fullscreen => Some("Full"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 liv"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Fullført"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Første lys",
    "Satellitter",
    "Slipstrøm",
    "Resonans",
    "Prisme",
    "Overtoning",
    "Understrøm",
    "Måneoppgang",
    "Etterglød",
    "Parallakse",
    "Supernova",
    "Hjemkomst",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Første lys",
    "Satellitter",
    "Slipstrøm",
    "Resonans",
    "Prisme",
    "Overtoning",
    "Understrøm",
    "Måne",
    "Etterglød",
    "Parallakse",
    "Supernova",
    "Hjemkomst",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Bred og {icon:slow} Sakte: fang kapslene som faller",
    "{icon:anchor} Anker: fang ballen, sikt og slipp den",
    "Ravkjerner: hver eksplosjon når de fire naboene",
    "Nabokjerner fører reaksjonen videre",
    "{icon:multi} Multiball: tre baller, én åpning",
    "Åpne en vei gjennom de to relélinjene",
    "Bryt inn i lommene bak panseret",
    "Følg reléet rundt den åpne midten",
    "{icon:phase} Fase: tre klosstreff uten å sprette",
    "Gjennombryt skallet, og tenn så den indre ruten",
    "Fang en returball mens de andre fortsetter",
    "En siste bane: få hver åpning til å telle",
];
