//! Dutch. Informal *je*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Breek de kosmos",
        ContinueJourney => "Reis voortzetten",
        NewJourney => "Nieuwe reis",
        SectorSelect => "Sector kiezen",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDAILLES",
        StatBest => "RECORD",
        ActionServe => "Serveren",
        ActionRelease => "Loslaten",
        ActionSelect => "Kiezen",
        ActionResume => "Hervatten",
        ActionBack => "Terug",
        Fullscreen => "Volledig scherm",
        SectorsHeading => "Sectoren",
        PracticeNote => "Oefenrondes veranderen je reis nooit",
        MedalClear => "GEHAALD",
        MedalClean => "FOUTLOOS",
        MedalSwift => "SNEL",
        PlaySector => "Sector {0} spelen",
        UnlockHint => "Voltooi sector {0} om te ontgrendelen",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTOR {1}",
        Paused => "Gepauzeerd",
        RetrySector => "Sector opnieuw",
        MainMenu => "Hoofdmenu",
        JourneyComplete => "Reis voltooid",
        OneMoreOrbit => "Nog één baan?",
        StatPoints => "PUNTEN",
        SectorClear => "Sector gehaald",
        StatTime => "TIJD",
        StatBonus => "BONUS",
        StatChain => "KETTING",
        ExtraLife => "Hoofdstuk voltooid · +1 leven",
        NextSector => "Volgende sector",
        BackToSectors => "Terug naar sectoren",
        SaveFailed => "Voortgang kon niet worden opgeslagen",
        PerfTitle => "Prestaties / CPU",
        HelpResume => "Ga verder waar je was",
        HelpRetry => "Opnieuw vanaf het checkpoint van de sector",
        HelpMainMenu => "Je reis is opgeslagen",
        HelpSectors => "Oefen in elke open sector",
        HelpNewJourney => "Opnieuw vanaf sector 01 · medailles blijven",
        Settings => "Instellingen",
        HelpSettings => "Geluid, scherm, taal",
        SettingSound => "Geluid",
        SettingVolume => "Volume",
        SettingDisplay => "Scherm",
        SettingLanguage => "Taal",
        DisplayWindow => "Venster",
        LanguageSystem => "Systeem",
        ActionAdjust => "Aanpassen",
        SettingEffects => "Effecten",
        SettingContrast => "Contrast",
        LookStandard => "Standaard",
        EffectsReduced => "Beperkt",
        ContrastHigh => "Hoog",
        KeySpace => "Spatie",
        KeyEsc => "Esc",
        SectorsOf => "{0} van {1} sectoren",
        TargetBest => "{0} · record {1}",
        LifeGained => "+1 leven",
        PresenceMenus => "In de menu’s",
        PresenceJourney => "Sector {0} · {1}",
        PresencePractice => "Oefent sector {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAGERAAD",
            Chapter::Morning => "OCHTEND",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "GOUDEN UUR",
            Chapter::Afterlight => "SCHEMERING",
            Chapter::BlueHour => "BLAUWE UUR",
            Chapter::Eclipse => "ECLIPS",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "BREED",
            Power::Slow => "TRAAG",
            Power::Multi => "MULTIBAL",
            Power::Anchor => "ANKER",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Verder"),
        UnlockHint => Some("Op slot"),
        RetrySector => Some("Opnieuw"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nieuw"),
        SectorSelect => Some("Sectoren"),
        NextSector => Some("Volgende"),
        BackToSectors => Some("Sectoren"),
        Settings => Some("Opties"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Verder"),
        PlaySector => Some("Speel {0}"),
        ActionServe => Some("Serveren"),
        ActionRelease => Some("Los"),
        ActionSelect => Some("Kiezen"),
        ActionBack => Some("Terug"),
        ActionAdjust => Some("Wijzig"),
        SettingEffects => Some("Effecten"),
        SettingContrast => Some("Contrast"),
        LookStandard => Some("Normaal"),
        EffectsReduced => Some("Minder"),
        ContrastHigh => Some("Hoog"),
        StatBest => Some("RECORD"),
        StatMedals => Some("MEDAILLES"),
        SectorsHeading => Some("Sectoren"),
        SaveFailed => Some("Niet opgeslagen"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spatie"),
        HelpResume => Some("Terug naar het spel"),
        HelpRetry => Some("Vanaf het checkpoint"),
        HelpMainMenu => Some("Reis opgeslagen"),
        HelpSectors => Some("Oefen sectoren"),
        HelpNewJourney => Some("Vanaf sector 01"),
        HelpSettings => Some("Geluid, scherm"),
        SettingSound => Some("Geluid"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Scherm"),
        SettingLanguage => Some("Taal"),
        DisplayWindow => Some("Venster"),
        Fullscreen => Some("Volledig"),
        LanguageSystem => Some("Systeem"),
        ExtraLife => Some("+1 leven"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SECTOR {1}"),
        JourneyComplete => Some("Voltooid"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Eerste licht",
    "Drijven",
    "Horizon",
    "Glinster",
    "Leeuwerik",
    "Lantaarns",
    "Getijde",
    "Zonsopgang",
    "Satellieten",
    "Dauwpunt",
    "Opening",
    "Klooster",
    "Sluitsteen",
    "Zonnewijzer",
    "Speldengat",
    "Windroos",
    "Zuigstroom",
    "Gloeidraad",
    "Meridiaan",
    "Cascade",
    "Overvloeier",
    "Haarspeldbocht",
    "Zonnewende",
    "Resonantie",
    "Prisma",
    "Honingraat",
    "Schuimspray",
    "Onderstroom",
    "Oogst",
    "Caleidoscoop",
    "Wandtapijt",
    "Lange schaduwen",
    "Avondgloed",
    "Cocon",
    "Geode",
    "Parallax",
    "Citadel",
    "Nautilus",
    "Vespers",
    "Supernova",
    "Maansopkomst",
    "Schemeruur",
    "Lamplicht",
    "Vuurvliegjes",
    "Vuurtoren",
    "Nocturne",
    "Diepveld",
    "Sterrenbeeld",
    "Halfschaduw",
    "Metronoom",
    "Corona",
    "Syzygie",
    "Pulsar",
    "Sluiter",
    "Umbra",
    "Totaliteit",
    "Zonnewind",
    "Noorderlicht",
    "Linten",
    "Poolnacht",
    "Kathedraal",
    "Geflonker",
    "Singulariteit",
    "Thuiskomst",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Eerste licht",
    "Drijven",
    "Horizon",
    "Glinster",
    "Leeuwerik",
    "Lantaarns",
    "Getijde",
    "Zon",
    "Satellieten",
    "Dauwpunt",
    "Opening",
    "Klooster",
    "Sluitsteen",
    "Zonnewijzer",
    "Speldengat",
    "Windroos",
    "Zuigstroom",
    "Draad",
    "Meridiaan",
    "Cascade",
    "Overvloeier",
    "Haarspeld",
    "Zonnewende",
    "Resonantie",
    "Prisma",
    "Raat",
    "Spray",
    "Onderstroom",
    "Oogst",
    "Caleido",
    "Tapijt",
    "Schaduwen",
    "Avondgloed",
    "Cocon",
    "Geode",
    "Parallax",
    "Citadel",
    "Nautilus",
    "Vespers",
    "Supernova",
    "Maan",
    "Schemeruur",
    "Lamplicht",
    "Vuurvliegjes",
    "Vuurtoren",
    "Nocturne",
    "Diepveld",
    "Sterren",
    "Halfschaduw",
    "Metronoom",
    "Corona",
    "Syzygie",
    "Pulsar",
    "Sluiter",
    "Umbra",
    "Totaliteit",
    "Zonnewind",
    "Noorderlicht",
    "Linten",
    "Poolnacht",
    "Kathedraal",
    "Geflonker",
    "Singulariteit",
    "Thuiskomst",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Breed: vang de vallende capsule",
    "{icon:slow} Traag: vang hem en de bal wordt rustiger",
    "Stuur: de randen van het batje sturen de bal opzij",
    "Losse vonken: jaag op elke vonk",
    "Stuur de bal omhoog langs de open vleugels",
    "Ruim elke lantaarn van onderaf op",
    "Rijd op de deining: kaats af op de zijmuren",
    "Hak de zon van onderaf weg, rij na rij",
    "{icon:anchor} Anker: vang de bal, richt en laat hem los",
    "Gepantserde stenen vragen twee treffers: let op de randen",
    "{icon:anchor} Richt door de opening in de muur",
    "Eén deur: stuur de bal de binnenplaats in",
    "Sla de sluitsteen weg en de boog staat open",
    "Lees de hoeken: elke schaduw is een schot",
    "{icon:anchor} Eén smal gaatje: vasthouden, richten, loslaten",
    "Elke windstreek leidt naar het hart",
    "Amberkernen: elke explosie raakt de vier buren",
    "Raak de gloeidraad overal aan: hij brandt twee kanten op",
    "Splits het veld langs de meridiaan",
    "Start de cascade aan een van beide uiteinden",
    "Open een route door de twee relaislijnen",
    "Drie relaislijnen: één zuiver schot per lijn",
    "De ring brandt in zijn geheel: vind een weg naar de rand",
    "Naburige kernen dragen de reactie verder",
    "{icon:multi} Multibal: drie ballen, één opening",
    "Een kern in elke cel: kraak ze open",
    "Spray overal: laat drie ballen los",
    "Breek door naar de holtes achter het pantser",
    "Vol veld: {icon:multi} Multibal ruimt het snel op",
    "Overal spiegels: breek één kant, dan zijn tweeling",
    "Trek aan één draad en het weefsel raakt los",
    "Breek door de vloer en steek de lange lont aan",
    "{icon:phase} Fase: drie steentreffers zonder te stuiteren",
    "{icon:phase} Fase glipt door de schil naar de kern",
    "Kraak een geode en de kristallen lichten op",
    "Doorboor de schil en ontsteek dan de binnenste route",
    "Via de poort naar binnen, of door de muur met {icon:phase} Fase",
    "Spiraal naar binnen: de buitenste winding licht eerst op",
    "Drie klokken: luid elk van onderaf",
    "Vang een terugkerende bal terwijl de andere doorgaan",
    "Volg het relais rond het open midden",
    "Het licht verdwijnt: leer het veld zolang het kan",
    "In het donker dragen je bal en batje het licht",
    "Vuurvliegjes: de kernen gloeien zelfs in het donker",
    "Veeg het licht van het batje over de kust",
    "Meer ballen, meer licht: {icon:multi} Multibal",
    "Diepveld: elke vage stip is een steen",
    "Verbind de sterren: de heldere zijn kernen",
    "Poorten vervagen op de maat: wacht op de opening",
    "Tik, tak: de poorten houden de tijd",
    "De corona opent op de maat: raak binnenin",
    "Een spookpoort schudt een explosie af: timing is alles",
    "Een pulsar: snelle slagen, snelle handen",
    "De sluiter gaat even open: wees klaar",
    "Half in de schaduw: de poortkant houdt de maat",
    "Ontsteek de zon terwijl de maan vast is",
    "De wind waait één kant op: rijd mee naar de kernen",
    "Gordijnen van licht: veeg ze op met {icon:multi} Multibal",
    "Elk lint hangt aan een poort: knip beide helften door",
    "De lange nacht: richt op het licht dat je draagt",
    "Door de deuren naar binnen, omhoog naar het roosvenster",
    "Alles tegelijk: let op de kernen",
    "Raak de ring als de poorten vast worden",
    "Een laatste baan: laat elke opening tellen",
];
