//! Dutch. Informal *je*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Breek de kosmos",
        ContinueJourney => "Reis voortzetten",
        NewJourney => "Nieuwe reis",
        SectorSelect => "Sector kiezen",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDAILLES",
        StatBest => "RECORD",
        ActionServe => "Serveren",
        ActionRelease => "Loslaten",
        ActionSelect => "Kiezen",
        ActionResume => "Hervatten",
        ActionBack => "Terug",
        Fullscreen => "Volledig scherm",
        SectorsHeading => "Sectoren",
        PracticeNote => "Oefenrondes veranderen je reis nooit",
        MedalClear => "GEHAALD",
        MedalClean => "FOUTLOOS",
        MedalSwift => "SNEL",
        PlaySector => "Sector {0} spelen",
        UnlockHint => "Voltooi sector {0} om te ontgrendelen",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTOR {1}",
        Paused => "Gepauzeerd",
        RetrySector => "Sector opnieuw",
        MainMenu => "Hoofdmenu",
        JourneyComplete => "Reis voltooid",
        OneMoreOrbit => "Nog één baan?",
        StatPoints => "PUNTEN",
        SectorClear => "Sector gehaald",
        StatTime => "TIJD",
        StatBonus => "BONUS",
        StatChain => "KETTING",
        ExtraLife => "Hoofdstuk voltooid · +1 leven",
        NextSector => "Volgende sector",
        BackToSectors => "Terug naar sectoren",
        SaveFailed => "Voortgang kon niet worden opgeslagen",
        PerfTitle => "Prestaties / CPU",
        HelpResume => "Ga verder waar je was",
        HelpRetry => "Opnieuw vanaf het checkpoint van de sector",
        HelpMainMenu => "Je reis is opgeslagen",
        HelpSectors => "Oefen in elke open sector",
        HelpNewJourney => "Opnieuw vanaf sector 01 · medailles blijven",
        Settings => "Instellingen",
        HelpSettings => "Geluid, scherm, taal",
        SettingSound => "Geluid",
        SettingVolume => "Volume",
        SettingDisplay => "Scherm",
        SettingLanguage => "Taal",
        DisplayWindow => "Venster",
        LanguageSystem => "Systeem",
        ActionAdjust => "Aanpassen",
        SettingEffects => "Effecten",
        SettingContrast => "Contrast",
        LookStandard => "Standaard",
        EffectsReduced => "Beperkt",
        ContrastHigh => "Hoog",
        KeySpace => "Spatie",
        KeyEsc => "Esc",
        SectorsOf => "{0} van {1} sectoren",
        TargetBest => "{0} · record {1}",
        LifeGained => "+1 leven",
        PresenceMenus => "In de menu’s",
        PresenceJourney => "Sector {0} · {1}",
        PresencePractice => "Oefent sector {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "DAGERAAD",
            Chapter::BlueHour => "BLAUWE UUR",
            Chapter::Afterlight => "SCHEMERING",
        },
        PowerName(p) => match p {
            Power::Wide => "BREED",
            Power::Slow => "TRAAG",
            Power::Multi => "MULTIBAL",
            Power::Anchor => "ANKER",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Verder"),
        UnlockHint => Some("Op slot"),
        RetrySector => Some("Opnieuw"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nieuw"),
        SectorSelect => Some("Sectoren"),
        NextSector => Some("Volgende"),
        BackToSectors => Some("Sectoren"),
        Settings => Some("Opties"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Verder"),
        PlaySector => Some("Speel {0}"),
        ActionServe => Some("Serveren"),
        ActionRelease => Some("Los"),
        ActionSelect => Some("Kiezen"),
        ActionBack => Some("Terug"),
        ActionAdjust => Some("Wijzig"),
        SettingEffects => Some("Effecten"),
        SettingContrast => Some("Contrast"),
        LookStandard => Some("Normaal"),
        EffectsReduced => Some("Minder"),
        ContrastHigh => Some("Hoog"),
        StatBest => Some("RECORD"),
        StatMedals => Some("MEDAILLES"),
        SectorsHeading => Some("Sectoren"),
        SaveFailed => Some("Niet opgeslagen"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spatie"),
        HelpResume => Some("Terug naar het spel"),
        HelpRetry => Some("Vanaf het checkpoint"),
        HelpMainMenu => Some("Reis opgeslagen"),
        HelpSectors => Some("Oefen sectoren"),
        HelpNewJourney => Some("Vanaf sector 01"),
        HelpSettings => Some("Geluid, scherm"),
        SettingSound => Some("Geluid"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Scherm"),
        SettingLanguage => Some("Taal"),
        DisplayWindow => Some("Venster"),
        Fullscreen => Some("Volledig"),
        LanguageSystem => Some("Systeem"),
        ExtraLife => Some("+1 leven"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SECTOR {1}"),
        JourneyComplete => Some("Voltooid"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Eerste licht",
    "Satellieten",
    "Zuigstroom",
    "Resonantie",
    "Prisma",
    "Overvloeier",
    "Onderstroom",
    "Maansopkomst",
    "Avondgloed",
    "Parallax",
    "Supernova",
    "Thuiskomst",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Eerste licht",
    "Satellieten",
    "Zuigstroom",
    "Resonantie",
    "Prisma",
    "Overvloeier",
    "Onderstroom",
    "Maan",
    "Avondgloed",
    "Parallax",
    "Supernova",
    "Thuiskomst",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Breed en {icon:slow} Traag: vang de vallende capsules",
    "{icon:anchor} Anker: vang de bal, richt en laat hem los",
    "Amberkernen: elke explosie raakt de vier buren",
    "Naburige kernen dragen de reactie verder",
    "{icon:multi} Multibal: drie ballen, één opening",
    "Open een route door de twee relaislijnen",
    "Breek door naar de holtes achter het pantser",
    "Volg het relais rond het open midden",
    "{icon:phase} Fase: drie steentreffers zonder te stuiteren",
    "Doorboor de schil en ontsteek dan de binnenste route",
    "Vang een terugkerende bal terwijl de andere doorgaan",
    "Een laatste baan: laat elke opening tellen",
];
