//! Polish. Hints put the action first ("Ruch: mysz lub strzałki"), which
//! keeps them short without an infinitive clause; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Rozbij kosmos",
        ContinueJourney => "Kontynuuj podróż",
        NewJourney => "Nowa podróż",
        SectorSelect => "Wybór sektora",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALE",
        StatBest => "REKORD",
        ActionServe => "Start",
        ActionRelease => "Zwolnij",
        ActionSelect => "Wybierz",
        ActionResume => "Wznów",
        ActionBack => "Wstecz",
        Fullscreen => "Pełny ekran",
        SectorsHeading => "Sektory",
        PracticeNote => "Trening nigdy nie zmienia twojej podróży",
        MedalClear => "UKOŃCZONO",
        MedalClean => "BEZ STRAT",
        MedalSwift => "SZYBKO",
        PlaySector => "Graj: sektor {0}",
        UnlockHint => "Ukończ sektor {0}, aby odblokować",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pauza",
        RetrySector => "Powtórz sektor",
        MainMenu => "Menu główne",
        JourneyComplete => "Podróż ukończona",
        OneMoreOrbit => "Jeszcze jedna orbita?",
        StatPoints => "PUNKTY",
        SectorClear => "Sektor ukończony",
        StatTime => "CZAS",
        StatBonus => "PREMIA",
        StatChain => "SERIA",
        ExtraLife => "Rozdział ukończony · +1 życie",
        NextSector => "Następny sektor",
        BackToSectors => "Powrót do sektorów",
        SaveFailed => "Nie udało się zapisać postępów",
        PerfTitle => "Wydajność / CPU",
        HelpResume => "Graj dalej od tego miejsca",
        HelpRetry => "Zacznij od punktu kontrolnego sektora",
        HelpMainMenu => "Twoja podróż jest zapisana",
        HelpSectors => "Ćwicz w dowolnym otwartym sektorze",
        HelpNewJourney => "Zacznij od sektora 01 · medale zostają",
        Settings => "Ustawienia",
        HelpSettings => "Dźwięk, ekran, język",
        SettingSound => "Dźwięk",
        SettingVolume => "Głośność",
        SettingDisplay => "Ekran",
        SettingLanguage => "Język",
        DisplayWindow => "Okno",
        LanguageSystem => "Systemowy",
        ActionAdjust => "Zmień",
        SettingEffects => "Efekty",
        SettingContrast => "Kontrast",
        LookStandard => "Standard",
        EffectsReduced => "Ograniczone",
        ContrastHigh => "Wysoki",
        KeySpace => "Spacja",
        KeyEsc => "Esc",
        SectorsOf => "{0} z {1} sektorów",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 życie",
        PresenceMenus => "W menu",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Trening: sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ŚWIT",
            Chapter::Morning => "PORANEK",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "ZŁOTA GODZINA",
            Chapter::Afterlight => "ZMIERZCH",
            Chapter::BlueHour => "NIEBIESKA GODZINA",
            Chapter::Eclipse => "ZAĆMIENIE",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "POSZERZENIE",
            Power::Slow => "SPOWOLNIENIE",
            Power::Multi => "MULTIPIŁKA",
            Power::Anchor => "KOTWICA",
            Power::Phase => "FAZA",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Kontynuuj"),
        UnlockHint => Some("Zablokowany"),
        RetrySector => Some("Powtórz"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nowa"),
        SectorSelect => Some("Sektory"),
        NextSector => Some("Dalej"),
        BackToSectors => Some("Sektory"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Wznów"),
        PlaySector => Some("Graj {0}"),
        Settings => Some("Opcje"),
        ActionServe => Some("Start"),
        ActionRelease => Some("Zwolnij"),
        ActionSelect => Some("Wybierz"),
        ActionBack => Some("Wstecz"),
        ActionAdjust => Some("Zmień"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDALE"),
        SectorsHeading => Some("Sektory"),
        SaveFailed => Some("Nie zapisano"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spacja"),
        HelpResume => Some("Wróć do gry"),
        HelpRetry => Some("Od punktu kontrolnego"),
        HelpMainMenu => Some("Podróż zapisana"),
        HelpSectors => Some("Ćwicz sektory"),
        HelpNewJourney => Some("Od sektora 01"),
        HelpSettings => Some("Dźwięk, ekran"),
        SettingSound => Some("Dźwięk"),
        SettingVolume => Some("Głośność"),
        SettingDisplay => Some("Ekran"),
        SettingLanguage => Some("Język"),
        DisplayWindow => Some("Okno"),
        Fullscreen => Some("Pełny"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 życie"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        SettingEffects => Some("Efekty"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Norma"),
        EffectsReduced => Some("Mniej"),
        ContrastHigh => Some("Wysoki"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Pierwsze światło",
    "Dryf",
    "Horyzont",
    "Przebłysk",
    "Skowronek",
    "Lampiony",
    "Przypływ",
    "Wschód słońca",
    "Satelity",
    "Punkt rosy",
    "Apertura",
    "Krużganek",
    "Zwornik",
    "Zegar słoneczny",
    "Otworek",
    "Róża wiatrów",
    "Strumień",
    "Włókno",
    "Południk",
    "Kaskada",
    "Przenikanie",
    "Serpentyny",
    "Przesilenie",
    "Rezonans",
    "Pryzmat",
    "Plaster miodu",
    "Morska piana",
    "Prąd wsteczny",
    "Żniwa",
    "Kalejdoskop",
    "Gobelin",
    "Długie cienie",
    "Poświata",
    "Poczwarka",
    "Geoda",
    "Paralaksa",
    "Cytadela",
    "Nautilus",
    "Nieszpory",
    "Supernowa",
    "Wschód księżyca",
    "Szarówka",
    "Blask lampy",
    "Świetliki",
    "Latarnia morska",
    "Nokturn",
    "Głębokie pole",
    "Gwiazdozbiór",
    "Półcień",
    "Metronom",
    "Korona",
    "Syzygia",
    "Pulsar",
    "Migawka",
    "Umbra",
    "Totalność",
    "Wiatr słoneczny",
    "Zorza polarna",
    "Wstęgi",
    "Noc polarna",
    "Katedra",
    "Migotanie",
    "Osobliwość",
    "Powrót",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Pierwsze światło",
    "Dryf",
    "Horyzont",
    "Przebłysk",
    "Skowronek",
    "Lampiony",
    "Przypływ",
    "Słońce",
    "Satelity",
    "Rosa",
    "Apertura",
    "Krużganek",
    "Zwornik",
    "Zegar",
    "Otworek",
    "Róża",
    "Strumień",
    "Włókno",
    "Południk",
    "Kaskada",
    "Przenikanie",
    "Serpentyny",
    "Przesilenie",
    "Rezonans",
    "Pryzmat",
    "Plaster",
    "Piana",
    "Prąd",
    "Żniwa",
    "Kalejdo",
    "Gobelin",
    "Cienie",
    "Poświata",
    "Poczwarka",
    "Geoda",
    "Paralaksa",
    "Cytadela",
    "Nautilus",
    "Nieszpory",
    "Supernowa",
    "Księżyc",
    "Szarówka",
    "Lampa",
    "Świetliki",
    "Latarnia",
    "Nokturn",
    "Głębia",
    "Gwiazdy",
    "Półcień",
    "Metronom",
    "Korona",
    "Syzygia",
    "Pulsar",
    "Migawka",
    "Umbra",
    "Totalność",
    "Wiatr",
    "Zorza",
    "Wstęgi",
    "Noc polarna",
    "Katedra",
    "Migotanie",
    "Osobliwość",
    "Powrót",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Poszerzenie: złap spadającą kapsułę",
    "{icon:slow} Spowolnienie: złap ją, a piłka zwolni",
    "Kieruj: krawędzie paletki wysyłają piłkę szeroko",
    "Samotne iskry: ścigaj każdą",
    "Wyślij piłkę w górę otwartymi skrzydłami",
    "Oczyść każdy lampion od dołu",
    "Płyń na fali: odbijaj od bocznych ścian",
    "Skuwaj słońce od dołu, rząd po rzędzie",
    "{icon:anchor} Kotwica: złap piłkę, wyceluj i ją wypuść",
    "Opancerzone cegły wytrzymują dwa trafienia: uważaj na brzegi",
    "{icon:anchor} Celuj przez lukę w murze",
    "Tylko jedne drzwi: wyślij piłkę na dziedziniec",
    "Wybij zwornik, a łuk się otworzy",
    "Czytaj kąty: każdy cień to strzał",
    "{icon:anchor} Jeden wąski otworek: przytrzymaj, wyceluj, puść",
    "Każda strona świata prowadzi do serca",
    "Bursztynowe rdzenie: każdy wybuch sięga czterech sąsiadów",
    "Dotknij włókna w dowolnym miejscu: pali się w obie strony",
    "Podziel pole wzdłuż południka",
    "Zacznij kaskadę z któregokolwiek końca",
    "Otwórz drogę przez dwie linie przekaźników",
    "Trzy linie przekaźników: po jednym czystym strzale",
    "Pierścień płonie cały: znajdź drogę do jego brzegu",
    "Sąsiednie rdzenie przenoszą reakcję",
    "{icon:multi} Multipiłka: trzy piłki, jedna luka",
    "Rdzeń w każdej komórce: rozbij je",
    "Piana wszędzie: wypuść trzy piłki",
    "Przebij się do kieszeni za pancerzem",
    "Pełne pole: {icon:multi} Multipiłka szybko je oczyści",
    "Wszędzie lustra: rozbij jedną stronę, potem jej bliźniaczkę",
    "Pociągnij za jedną nić, a tkanina się rozpruje",
    "Przebij podłogę i podpal długi lont",
    "{icon:phase} Faza: trzy trafienia w cegły bez odbicia",
    "{icon:phase} Faza przenika przez skorupę do rdzenia",
    "Rozłup geodę, a jej kryształy rozbłysną",
    "Przebij pancerz, potem odpal wewnętrzną trasę",
    "Wejdź bramą albo przez mur z {icon:phase} Fazą",
    "Spiralą do środka: zewnętrzny zwój zapala się pierwszy",
    "Trzy dzwony: uderz w każdy od dołu",
    "Złap piłkę, gdy pozostałe wciąż lecą",
    "Podążaj za przekaźnikiem wokół pustego środka",
    "Światło gaśnie: poznaj pole, póki możesz",
    "W ciemności piłka i paletka niosą światło",
    "Świetliki: rdzenie świecą nawet w ciemności",
    "Omiataj wybrzeże światłem paletki",
    "Więcej piłek, więcej światła: {icon:multi} Multipiłka",
    "Głębokie pole: każda blada plamka to cegła",
    "Połącz gwiazdy: jasne to rdzenie",
    "Bramy gasną w rytmie: poczekaj na lukę",
    "Tik-tak: bramy odmierzają czas",
    "Korona otwiera się w rytmie: uderz do środka",
    "Brama-widmo strząsa wybuch: wyczuj moment iskry",
    "Pulsar: szybkie uderzenia, szybkie ręce",
    "Migawka otwiera się na chwilę: bądź gotów",
    "W połowie w cieniu: strona z bramami trzyma rytm",
    "Rozpal słońce, gdy księżyc jest twardy",
    "Wiatr wieje w jedną stronę: płyń z nim do rdzeni",
    "Kurtyny światła: zmiataj je {icon:multi} Multipiłką",
    "Każda wstęga jest przywiązana do bramy: przetnij obie połowy",
    "Długa noc: celuj według światła, które niesiesz",
    "Wejdź drzwiami i wspinaj się do rozety",
    "Wszystko naraz: pilnuj rdzeni",
    "Uderz w pierścień, gdy bramy stwardnieją",
    "Ostatnia orbita: niech każda luka się liczy",
];
