//! Polish. Hints put the action first ("Ruch: mysz lub strzałki"), which
//! keeps them short without an infinitive clause; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Rozbij kosmos",
        ContinueJourney => "Kontynuuj podróż",
        NewJourney => "Nowa podróż",
        SectorSelect => "Wybór sektora",
        ContinueDetail => "Sektor {0} · {1} · {2}",
        StatSectors => "SEKTORY",
        StatMedals => "MEDALE",
        StatBest => "REKORD",
        Fraction => "{0} / {1}",
        KeysMove => "Ruch: mysz lub strzałki",
        KeysServe => "Start: spacja lub kliknięcie",
        KeysPause => "Pauza: Esc",
        KeysRelease => "Zwolnij: kliknięcie lub spacja",
        KeysBrowse => "Wybór: strzałki",
        KeysPlay => "Graj: Enter",
        KeysBack => "Powrót: Esc",
        KeysContinue => "Dalej: Enter lub kliknięcie",
        PadMove => "Ruch: gałka lub krzyżak",
        PadBrowse => "Wybór: krzyżak",
        ActionServe => "Start",
        ActionPause => "Pauza",
        ActionRelease => "Zwolnij",
        ActionSelect => "Wybierz",
        ActionResume => "Wznów",
        ActionRetry => "Ponów",
        ActionPlay => "Graj",
        ActionBack => "Wstecz",
        ActionContinue => "Dalej",
        SoundOn => "Dźwięk wł.",
        SoundOff => "Dźwięk wył.",
        Volume => "Głośność {0}",
        Fullscreen => "Pełny ekran",
        SectorsHeading => "Sektory",
        PracticeNote => "Treningi nigdy nie zmieniają twojej podróży",
        MedalClear => "UKOŃCZONO",
        MedalClean => "BEZ STRAT",
        MedalSwift => "SZYBKO",
        MedalClearHow => "Ukończ sektor",
        MedalCleanHow => "Nie trać żyć",
        PlaySector => "Graj: sektor {0}",
        SwiftWithin => "Ukończ w czasie {0}",
        UnlockHint => "Ukończ sektor {0}, aby odblokować",
        Score => "WYNIK",
        Lives => "ŻYCIA",
        SectorNumber => "SEKTOR {0}",
        PracticeNumber => "TRENING {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pauza",
        RetrySector => "Powtórz sektor",
        MainMenu => "Menu główne",
        RetryNote => "Powtórka zaczyna od punktu kontrolnego",
        JourneyComplete => "Podróż ukończona",
        OneMoreOrbit => "Jeszcze jedna orbita?",
        StatPoints => "PUNKTY",
        ProgressSaved => "Twoje postępy są zapisane",
        SectorClear => "Sektor ukończony",
        StatTime => "CZAS",
        StatBonus => "PREMIA",
        StatBestChain => "MAKS. SERIA",
        ExtraLife => "Rozdział ukończony · dodatkowe życie",
        NextSector => "Następny sektor",
        BackToSectors => "Powrót do sektorów",
        SaveFailed => "Nie udało się zapisać postępów",
        PerfTitle => "Wydajność / CPU",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ŚWIT",
            Chapter::BlueHour => "NIEBIESKA GODZINA",
            Chapter::Afterlight => "ZMIERZCH",
        },
        PowerName(p) => match p {
            Power::Wide => "Poszerzenie",
            Power::Slow => "Spowolnienie",
            Power::Multi => "Multipiłka",
            Power::Anchor => "Kotwica",
            Power::Phase => "Faza",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1} · {2}"),
        ContinueJourney => Some("Kontynuuj"),
        SwiftWithin => Some("Do {0}"),
        UnlockHint => Some("Zablokowany"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Pierwsze światło",
    "Satelity",
    "Strumień",
    "Rezonans",
    "Pryzmat",
    "Przenikanie",
    "Prąd wsteczny",
    "Wschód księżyca",
    "Poświata",
    "Paralaksa",
    "Supernowa",
    "Powrót",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Poszerzenie i {icon:slow} Spowolnienie: łap spadające kapsuły",
    "{icon:anchor} Kotwica: złap piłkę, wyceluj i ją wypuść",
    "Bursztynowe rdzenie: każdy wybuch sięga czterech sąsiadów",
    "Sąsiednie rdzenie przenoszą reakcję",
    "{icon:multi} Multipiłka: trzy piłki, jedna luka",
    "Otwórz drogę przez dwie linie przekaźników",
    "Przebij się do kieszeni za pancerzem",
    "Podążaj za przekaźnikiem wokół pustego środka",
    "{icon:phase} Faza: trzy trafienia w cegły bez odbicia",
    "Przebij pancerz, potem odpal wewnętrzną trasę",
    "Złap piłkę, gdy pozostałe wciąż lecą",
    "Ostatnia orbita: niech każda luka się liczy",
];
