//! Polish. Hints put the action first ("Ruch: mysz lub strzałki"), which
//! keeps them short without an infinitive clause; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Rozbij kosmos",
        ContinueJourney => "Kontynuuj podróż",
        NewJourney => "Nowa podróż",
        SectorSelect => "Wybór sektora",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALE",
        StatBest => "REKORD",
        ActionServe => "Start",
        ActionRelease => "Zwolnij",
        ActionSelect => "Wybierz",
        ActionResume => "Wznów",
        ActionBack => "Wstecz",
        Fullscreen => "Pełny ekran",
        SectorsHeading => "Sektory",
        PracticeNote => "Trening nigdy nie zmienia twojej podróży",
        MedalClear => "UKOŃCZONO",
        MedalClean => "BEZ STRAT",
        MedalSwift => "SZYBKO",
        PlaySector => "Graj: sektor {0}",
        UnlockHint => "Ukończ sektor {0}, aby odblokować",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pauza",
        RetrySector => "Powtórz sektor",
        MainMenu => "Menu główne",
        JourneyComplete => "Podróż ukończona",
        OneMoreOrbit => "Jeszcze jedna orbita?",
        StatPoints => "PUNKTY",
        SectorClear => "Sektor ukończony",
        StatTime => "CZAS",
        StatBonus => "PREMIA",
        StatChain => "SERIA",
        ExtraLife => "Rozdział ukończony · +1 życie",
        NextSector => "Następny sektor",
        BackToSectors => "Powrót do sektorów",
        SaveFailed => "Nie udało się zapisać postępów",
        PerfTitle => "Wydajność / CPU",
        HelpResume => "Graj dalej od tego miejsca",
        HelpRetry => "Zacznij od punktu kontrolnego sektora",
        HelpMainMenu => "Twoja podróż jest zapisana",
        HelpSectors => "Ćwicz w dowolnym otwartym sektorze",
        HelpNewJourney => "Zacznij od sektora 01 · medale zostają",
        Settings => "Ustawienia",
        HelpSettings => "Dźwięk, ekran, język",
        SettingSound => "Dźwięk",
        SettingVolume => "Głośność",
        SettingDisplay => "Ekran",
        SettingLanguage => "Język",
        DisplayWindow => "Okno",
        LanguageSystem => "Systemowy",
        ActionAdjust => "Zmień",
        KeySpace => "Spacja",
        KeyEsc => "Esc",
        SectorsOf => "{0} z {1} sektorów",
        TargetBest => "{0} · rekord {1}",
        LifeGained => "+1 życie",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ŚWIT",
            Chapter::BlueHour => "NIEBIESKA GODZINA",
            Chapter::Afterlight => "ZMIERZCH",
        },
        PowerName(p) => match p {
            Power::Wide => "POSZERZENIE",
            Power::Slow => "SPOWOLNIENIE",
            Power::Multi => "MULTIPIŁKA",
            Power::Anchor => "KOTWICA",
            Power::Phase => "FAZA",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Kontynuuj"),
        UnlockHint => Some("Zablokowany"),
        RetrySector => Some("Powtórz"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nowa"),
        SectorSelect => Some("Sektory"),
        NextSector => Some("Dalej"),
        BackToSectors => Some("Sektory"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Pierwsze światło",
    "Satelity",
    "Strumień",
    "Rezonans",
    "Pryzmat",
    "Przenikanie",
    "Prąd wsteczny",
    "Wschód księżyca",
    "Poświata",
    "Paralaksa",
    "Supernowa",
    "Powrót",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Poszerzenie i {icon:slow} Spowolnienie: łap spadające kapsuły",
    "{icon:anchor} Kotwica: złap piłkę, wyceluj i ją wypuść",
    "Bursztynowe rdzenie: każdy wybuch sięga czterech sąsiadów",
    "Sąsiednie rdzenie przenoszą reakcję",
    "{icon:multi} Multipiłka: trzy piłki, jedna luka",
    "Otwórz drogę przez dwie linie przekaźników",
    "Przebij się do kieszeni za pancerzem",
    "Podążaj za przekaźnikiem wokół pustego środka",
    "{icon:phase} Faza: trzy trafienia w cegły bez odbicia",
    "Przebij pancerz, potem odpal wewnętrzną trasę",
    "Złap piłkę, gdy pozostałe wciąż lecą",
    "Ostatnia orbita: niech każda luka się liczy",
];
