//! Brazilian Portuguese. Informal *você*; labels in capitals with accents
//! kept (BÔNUS).
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Quebre o cosmos",
        ContinueJourney => "Continuar jornada",
        NewJourney => "Nova jornada",
        SectorSelect => "Escolher setor",
        ContinueDetail => "Setor {0} · {1} · {2}",
        StatSectors => "SETORES",
        StatMedals => "MEDALHAS",
        StatBest => "RECORDE",
        Fraction => "{0} / {1}",
        KeysMove => "Mouse ou setas para mover",
        KeysServe => "Espaço ou clique para lançar",
        KeysPause => "Esc para pausar",
        KeysRelease => "Clique ou Espaço para soltar",
        KeysBrowse => "Setas para navegar",
        KeysPlay => "Enter para jogar",
        KeysBack => "Esc para voltar",
        PadMove => "Analógico ou direcional para mover",
        PadBrowse => "Direcional para navegar",
        ActionServe => "Lançar",
        ActionPause => "Pausar",
        ActionRelease => "Soltar",
        ActionSelect => "Selecionar",
        ActionResume => "Retomar",
        ActionPlay => "Jogar",
        ActionBack => "Voltar",
        SoundOn => "Som ligado",
        SoundOff => "Som desligado",
        Volume => "Volume {0}",
        Fullscreen => "Tela cheia",
        SectorsHeading => "Setores",
        PracticeNote => "Treinos nunca alteram sua jornada",
        MedalClear => "CONCLUÍDO",
        MedalClean => "IMPECÁVEL",
        MedalSwift => "VELOZ",
        MedalClearHow => "Conclua o setor",
        MedalCleanHow => "Não perca vidas",
        PlaySector => "Jogar setor {0}",
        SwiftWithin => "Conclua em até {0}",
        UnlockHint => "Conclua o setor {0} para desbloquear",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SETOR {1}",
        Paused => "Pausado",
        RetrySector => "Repetir setor",
        MainMenu => "Menu principal",
        JourneyComplete => "Jornada concluída",
        OneMoreOrbit => "Mais uma órbita?",
        StatPoints => "PONTOS",
        SectorClear => "Setor concluído",
        StatTime => "TEMPO",
        StatBonus => "BÔNUS",
        StatChain => "COMBO",
        ExtraLife => "Capítulo concluído · +1 vida",
        NextSector => "Próximo setor",
        BackToSectors => "Voltar aos setores",
        SaveFailed => "Não foi possível salvar o progresso",
        PerfTitle => "Desempenho / CPU",
        HelpResume => "Continue de onde parou",
        HelpRetry => "Recomeça do ponto de controle do setor",
        HelpMainMenu => "Sua jornada está salva",
        HelpSectors => "Treine em qualquer setor aberto",
        HelpNewJourney => "Recomeça no setor 01 · as medalhas ficam",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ALVORADA",
            Chapter::BlueHour => "HORA AZUL",
            Chapter::Afterlight => "CREPÚSCULO",
        },
        PowerName(p) => match p {
            Power::Wide => "Largo",
            Power::Slow => "Lento",
            Power::Multi => "Multibola",
            Power::Anchor => "Âncora",
            Power::Phase => "Fase",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1} · {2}"),
        ContinueJourney => Some("Continuar"),
        SwiftWithin => Some("Até {0}"),
        UnlockHint => Some("Bloqueado"),
        RetrySector => Some("Repetir"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nova"),
        SectorSelect => Some("Setores"),
        NextSector => Some("Próximo"),
        BackToSectors => Some("Setores"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Primeira luz",
    "Satélites",
    "Esteira",
    "Ressonância",
    "Prisma",
    "Transição",
    "Ressaca",
    "Nascer da lua",
    "Arrebol",
    "Paralaxe",
    "Supernova",
    "Regresso",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Largo e {icon:slow} Lento: pegue as cápsulas que caem",
    "{icon:anchor} Âncora: pegue a bola, mire e depois solte",
    "Núcleos âmbar: cada explosão atinge seus quatro vizinhos",
    "Núcleos vizinhos propagam a reação",
    "{icon:multi} Multibola: três bolas, uma abertura",
    "Abra caminho pelas duas linhas de relés",
    "Invada os bolsões atrás da blindagem",
    "Siga o relé ao redor do centro aberto",
    "{icon:phase} Fase: três contatos com tijolos sem quicar",
    "Perfure a casca e depois acenda a rota interna",
    "Pegue uma bola enquanto as outras continuam",
    "Uma última órbita: faça cada abertura valer",
];
