//! Brazilian Portuguese. Informal *você*; labels in capitals with accents
//! kept (BÔNUS).
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Quebre o cosmos",
        ContinueJourney => "Continuar jornada",
        NewJourney => "Nova jornada",
        SectorSelect => "Escolher setor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALHAS",
        StatBest => "RECORDE",
        ActionServe => "Lançar",
        ActionRelease => "Soltar",
        ActionSelect => "Selecionar",
        ActionResume => "Retomar",
        ActionBack => "Voltar",
        Fullscreen => "Tela cheia",
        SectorsHeading => "Setores",
        PracticeNote => "Treinar nunca altera sua jornada",
        MedalClear => "CONCLUÍDO",
        MedalClean => "IMPECÁVEL",
        MedalSwift => "VELOZ",
        PlaySector => "Jogar setor {0}",
        UnlockHint => "Conclua o setor {0} para desbloquear",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SETOR {1}",
        Paused => "Pausado",
        RetrySector => "Repetir setor",
        MainMenu => "Menu principal",
        JourneyComplete => "Jornada concluída",
        OneMoreOrbit => "Mais uma órbita?",
        StatPoints => "PONTOS",
        SectorClear => "Setor concluído",
        StatTime => "TEMPO",
        StatBonus => "BÔNUS",
        StatChain => "COMBO",
        ExtraLife => "Capítulo concluído · +1 vida",
        NextSector => "Próximo setor",
        BackToSectors => "Voltar aos setores",
        SaveFailed => "Não foi possível salvar o progresso",
        PerfTitle => "Desempenho / CPU",
        HelpResume => "Continue de onde parou",
        HelpRetry => "Recomeça do ponto de controle do setor",
        HelpMainMenu => "Sua jornada está salva",
        HelpSectors => "Treine em qualquer setor aberto",
        HelpNewJourney => "Recomeça no setor 01 · as medalhas ficam",
        Settings => "Configurações",
        HelpSettings => "Som, tela, idioma",
        SettingSound => "Som",
        SettingVolume => "Volume",
        SettingDisplay => "Tela",
        SettingLanguage => "Idioma",
        DisplayWindow => "Janela",
        LanguageSystem => "Sistema",
        ActionAdjust => "Ajustar",
        SettingEffects => "Efeitos",
        SettingContrast => "Contraste",
        LookStandard => "Padrão",
        EffectsReduced => "Reduzidos",
        ContrastHigh => "Alto",
        KeySpace => "Espaço",
        KeyEsc => "Esc",
        SectorsOf => "{0} de {1} setores",
        TargetBest => "{0} · recorde {1}",
        LifeGained => "+1 vida",
        PresenceMenus => "Nos menus",
        PresenceJourney => "Setor {0} · {1}",
        PresencePractice => "Treinando o setor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ALVORADA",
            Chapter::Morning => "MANHÃ",
            Chapter::Zenith => "ZÊNITE",
            Chapter::GoldenHour => "HORA DOURADA",
            Chapter::Afterlight => "CREPÚSCULO",
            Chapter::BlueHour => "HORA AZUL",
            Chapter::Eclipse => "ECLIPSE",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "LARGO",
            Power::Slow => "LENTO",
            Power::Multi => "MULTIBOLA",
            Power::Anchor => "ÂNCORA",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continuar"),
        UnlockHint => Some("Bloqueado"),
        RetrySector => Some("Repetir"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nova"),
        SectorSelect => Some("Setores"),
        NextSector => Some("Próximo"),
        BackToSectors => Some("Setores"),
        Settings => Some("Opções"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Retomar"),
        PlaySector => Some("Jogar {0}"),
        ActionServe => Some("Lançar"),
        ActionRelease => Some("Soltar"),
        ActionSelect => Some("Escolher"),
        ActionBack => Some("Voltar"),
        ActionAdjust => Some("Ajustar"),
        StatBest => Some("RECORDE"),
        StatMedals => Some("MEDALHAS"),
        SectorsHeading => Some("Setores"),
        SaveFailed => Some("Não salvo"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Espaço"),
        HelpResume => Some("Voltar ao jogo"),
        HelpRetry => Some("Do ponto de controle"),
        HelpMainMenu => Some("Jornada salva"),
        HelpSectors => Some("Treinar setores"),
        HelpNewJourney => Some("Do setor 01"),
        HelpSettings => Some("Som, tela"),
        SettingSound => Some("Som"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Tela"),
        SettingLanguage => Some("Idioma"),
        DisplayWindow => Some("Janela"),
        Fullscreen => Some("Cheia"),
        LanguageSystem => Some("Sistema"),
        ExtraLife => Some("+1 vida"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SETOR {1}"),
        SettingEffects => Some("Efeitos"),
        SettingContrast => Some("Contraste"),
        LookStandard => Some("Padrão"),
        EffectsReduced => Some("Menos"),
        ContrastHigh => Some("Alto"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Primeira luz",
    "Deriva",
    "Horizonte",
    "Lampejo",
    "Cotovia",
    "Lanternas",
    "Maré",
    "Nascer do sol",
    "Satélites",
    "Ponto de orvalho",
    "Abertura",
    "Claustro",
    "Pedra angular",
    "Relógio de sol",
    "Estenopo",
    "Rosa dos ventos",
    "Esteira",
    "Filamento",
    "Meridiano",
    "Cascata",
    "Transição",
    "Zigue-zague",
    "Solstício",
    "Ressonância",
    "Prisma",
    "Favo",
    "Borrifo",
    "Ressaca",
    "Colheita",
    "Caleidoscópio",
    "Tapeçaria",
    "Sombras longas",
    "Arrebol",
    "Crisálida",
    "Geodo",
    "Paralaxe",
    "Cidadela",
    "Nautilus",
    "Vésperas",
    "Supernova",
    "Nascer da lua",
    "Lusco-fusco",
    "Luz de lampião",
    "Vaga-lumes",
    "Farol",
    "Noturno",
    "Campo profundo",
    "Constelação",
    "Penumbra",
    "Metrônomo",
    "Coroa solar",
    "Sizígia",
    "Pulsar",
    "Obturador",
    "Umbra",
    "Totalidade",
    "Vento solar",
    "Borealis",
    "Fitas",
    "Noite polar",
    "Catedral",
    "Cintilação",
    "Singularidade",
    "Regresso",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Primeira luz",
    "Deriva",
    "Horizonte",
    "Lampejo",
    "Cotovia",
    "Lanternas",
    "Maré",
    "Sol",
    "Satélites",
    "Orvalho",
    "Abertura",
    "Claustro",
    "Pedra",
    "Relógio",
    "Estenopo",
    "Rosa",
    "Esteira",
    "Filamento",
    "Meridiano",
    "Cascata",
    "Transição",
    "Zigue-zague",
    "Solstício",
    "Ressonância",
    "Prisma",
    "Favo",
    "Borrifo",
    "Ressaca",
    "Colheita",
    "Caleido",
    "Tapeçaria",
    "Sombras",
    "Arrebol",
    "Crisálida",
    "Geodo",
    "Paralaxe",
    "Cidadela",
    "Nautilus",
    "Vésperas",
    "Supernova",
    "Lua",
    "Lusco",
    "Lampião",
    "Vaga-lumes",
    "Farol",
    "Noturno",
    "Campo profundo",
    "Estrelas",
    "Penumbra",
    "Metrônomo",
    "Coroa",
    "Sizígia",
    "Pulsar",
    "Obturador",
    "Umbra",
    "Totalidade",
    "Vento",
    "Borealis",
    "Fitas",
    "Noite polar",
    "Catedral",
    "Cintilação",
    "Singularidade",
    "Regresso",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Largo: pegue a cápsula que cai",
    "{icon:slow} Lento: pegue-a e a bola desacelera",
    "Conduza: as bordas da raquete mandam a bola para os lados",
    "Faíscas solitárias: persiga cada uma",
    "Mande a bola pelas alas abertas",
    "Limpe cada lanterna por baixo",
    "Surfe a maré: rebata nas paredes laterais",
    "Lasque o sol por baixo, fileira por fileira",
    "{icon:anchor} Âncora: pegue a bola, mire e depois solte",
    "Tijolos blindados levam dois golpes: cuidado com as bordas",
    "{icon:anchor} Mire pela fresta na parede",
    "Só uma porta: mande a bola para o pátio",
    "Derrube a pedra angular e o arco se abre",
    "Leia os ângulos: cada sombra é uma tacada",
    "{icon:anchor} Um único estenopo estreito: segure, mire, solte",
    "Cada ponto cardeal leva ao coração",
    "Núcleos âmbar: cada explosão atinge seus quatro vizinhos",
    "Toque o filamento em qualquer ponto: ele queima nos dois sentidos",
    "Divida o campo pelo meridiano",
    "Comece a cascata por qualquer uma das pontas",
    "Abra caminho pelas duas linhas de relés",
    "Três linhas de relé: uma tacada limpa em cada",
    "O anel queima inteiro: ache um caminho até a borda",
    "Núcleos vizinhos propagam a reação",
    "{icon:multi} Multibola: três bolas, uma abertura",
    "Um núcleo em cada célula: abra todas",
    "Borrifos por toda parte: solte três bolas",
    "Invada os bolsões atrás da blindagem",
    "Campo cheio: {icon:multi} Multibola limpa rápido",
    "Espelhos por toda parte: quebre um lado, depois o gêmeo",
    "Puxe um fio e a trama se desfaz",
    "Rompa o piso e acenda o pavio longo",
    "{icon:phase} Fase: três contatos com tijolos sem quicar",
    "{icon:phase} Fase atravessa a casca até o núcleo",
    "Abra um geodo e seus cristais se acendem",
    "Perfure a casca e depois acenda a rota interna",
    "Entre pelo portal, ou pela parede com {icon:phase} Fase",
    "Em espiral: a volta externa acende primeiro",
    "Três sinos: toque cada um por baixo",
    "Pegue uma bola enquanto as outras continuam",
    "Siga o relé ao redor do centro aberto",
    "A luz está indo embora: aprenda o campo enquanto pode",
    "No escuro, sua bola e sua raquete levam a luz",
    "Vaga-lumes: os núcleos brilham até no escuro",
    "Varra a costa com a luz da raquete",
    "Mais bolas, mais luz: {icon:multi} Multibola",
    "Campo profundo: cada pontinho fraco é um tijolo",
    "Una as estrelas: as brilhantes são núcleos",
    "Portais somem no compasso: espere a brecha",
    "Tique, taque: os portais marcam o tempo",
    "A coroa abre no compasso: acerte dentro",
    "Um portal fantasma ignora a explosão: acerte a faísca na hora",
    "Um pulsar: batidas rápidas, mãos rápidas",
    "O obturador abre por um instante: fique pronto",
    "Metade na sombra: o lado dos portais marca o tempo",
    "Acenda o sol enquanto a lua está sólida",
    "O vento corre num só sentido: surfe até os núcleos",
    "Cortinas de luz: varra com {icon:multi} Multibola",
    "Cada fita prende a um portal: corte as duas metades",
    "A longa noite: mire pela luz que você carrega",
    "Entre pelas portas, suba até o rosetão",
    "Tudo ao mesmo tempo: vigie os núcleos",
    "Acerte o anel quando os portais ficarem sólidos",
    "Uma última órbita: faça cada abertura valer",
];
