//! European Portuguese. Informal *tu*, as Portuguese games address
//! players; Portugal's spelling and words (ecrã, rato, guardar). Labels in
//! capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Destrói o cosmos",
        ContinueJourney => "Continuar viagem",
        NewJourney => "Nova viagem",
        SectorSelect => "Escolher setor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALHAS",
        StatBest => "RECORDE",
        ActionServe => "Lançar",
        ActionRelease => "Soltar",
        ActionSelect => "Selecionar",
        ActionResume => "Retomar",
        ActionBack => "Voltar",
        Fullscreen => "Ecrã inteiro",
        SectorsHeading => "Setores",
        PracticeNote => "Os treinos nunca alteram a tua viagem",
        MedalClear => "CONCLUÍDO",
        MedalClean => "IMPECÁVEL",
        MedalSwift => "VELOZ",
        PlaySector => "Jogar setor {0}",
        UnlockHint => "Conclui o setor {0} para desbloquear",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SETOR {1}",
        Paused => "Em pausa",
        RetrySector => "Repetir setor",
        MainMenu => "Menu principal",
        JourneyComplete => "Viagem concluída",
        OneMoreOrbit => "Mais uma órbita?",
        StatPoints => "PONTOS",
        SectorClear => "Setor concluído",
        StatTime => "TEMPO",
        StatBonus => "BÓNUS",
        StatChain => "COMBO",
        ExtraLife => "Capítulo concluído · +1 vida",
        NextSector => "Setor seguinte",
        BackToSectors => "Voltar aos setores",
        SaveFailed => "Não foi possível guardar o progresso",
        PerfTitle => "Desempenho / CPU",
        HelpResume => "Continua onde paraste",
        HelpRetry => "Recomeça no ponto de controlo do setor",
        HelpMainMenu => "A tua viagem está guardada",
        HelpSectors => "Treina em qualquer setor aberto",
        HelpNewJourney => "Recomeça no setor 01 · as medalhas ficam",
        Settings => "Definições",
        HelpSettings => "Som, ecrã, idioma",
        SettingSound => "Som",
        SettingVolume => "Volume",
        SettingDisplay => "Ecrã",
        SettingLanguage => "Idioma",
        DisplayWindow => "Janela",
        LanguageSystem => "Sistema",
        ActionAdjust => "Ajustar",
        SettingEffects => "Efeitos",
        SettingContrast => "Contraste",
        LookStandard => "Padrão",
        EffectsReduced => "Reduzidos",
        ContrastHigh => "Alto",
        KeySpace => "Espaço",
        KeyEsc => "Esc",
        SectorsOf => "{0} de {1} setores",
        TargetBest => "{0} · recorde {1}",
        LifeGained => "+1 vida",
        PresenceMenus => "Nos menus",
        PresenceJourney => "Setor {0} · {1}",
        PresencePractice => "A treinar o setor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ALVORADA",
            Chapter::Morning => "MANHÃ",
            Chapter::Zenith => "ZÉNITE",
            Chapter::GoldenHour => "HORA DOURADA",
            Chapter::Afterlight => "CREPÚSCULO",
            Chapter::BlueHour => "HORA AZUL",
            Chapter::Eclipse => "ECLIPSE",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "LARGO",
            Power::Slow => "LENTO",
            Power::Multi => "MULTIBOLA",
            Power::Anchor => "ÂNCORA",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continuar"),
        UnlockHint => Some("Bloqueado"),
        RetrySector => Some("Repetir"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nova"),
        SectorSelect => Some("Setores"),
        NextSector => Some("Seguinte"),
        BackToSectors => Some("Setores"),
        Settings => Some("Opções"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Retomar"),
        PlaySector => Some("Jogar {0}"),
        ActionServe => Some("Lançar"),
        ActionRelease => Some("Soltar"),
        ActionSelect => Some("Escolher"),
        ActionBack => Some("Voltar"),
        ActionAdjust => Some("Ajustar"),
        SettingEffects => Some("Efeitos"),
        SettingContrast => Some("Contraste"),
        LookStandard => Some("Padrão"),
        EffectsReduced => Some("Menos"),
        ContrastHigh => Some("Alto"),
        StatBest => Some("RECORDE"),
        StatMedals => Some("MEDALHAS"),
        SectorsHeading => Some("Setores"),
        SaveFailed => Some("Não guardado"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Espaço"),
        HelpResume => Some("Voltar ao jogo"),
        HelpRetry => Some("Do ponto de controlo"),
        HelpMainMenu => Some("Viagem guardada"),
        HelpSectors => Some("Treinar setores"),
        HelpNewJourney => Some("Do setor 01"),
        HelpSettings => Some("Som, ecrã"),
        SettingSound => Some("Som"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Ecrã"),
        SettingLanguage => Some("Idioma"),
        DisplayWindow => Some("Janela"),
        Fullscreen => Some("Inteiro"),
        LanguageSystem => Some("Sistema"),
        ExtraLife => Some("+1 vida"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SETOR {1}"),
        JourneyComplete => Some("Concluída"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Primeira luz",
    "Deriva",
    "Horizonte",
    "Lampejo",
    "Cotovia",
    "Lanternas",
    "Maré",
    "Nascer do sol",
    "Satélites",
    "Ponto de orvalho",
    "Abertura",
    "Claustro",
    "Pedra angular",
    "Relógio de sol",
    "Estenopo",
    "Rosa dos ventos",
    "Esteira",
    "Filamento",
    "Meridiano",
    "Cascata",
    "Transição",
    "Ziguezague",
    "Solstício",
    "Ressonância",
    "Prisma",
    "Favo",
    "Salpico",
    "Ressaca",
    "Colheita",
    "Caleidoscópio",
    "Tapeçaria",
    "Sombras longas",
    "Arrebol",
    "Crisálida",
    "Geodo",
    "Paralaxe",
    "Cidadela",
    "Nautilus",
    "Vésperas",
    "Supernova",
    "Nascer da lua",
    "Lusco-fusco",
    "Luz de candeeiro",
    "Pirilampos",
    "Farol",
    "Noturno",
    "Campo profundo",
    "Constelação",
    "Penumbra",
    "Metrónomo",
    "Coroa solar",
    "Sizígia",
    "Pulsar",
    "Obturador",
    "Umbra",
    "Totalidade",
    "Vento solar",
    "Borealis",
    "Fitas",
    "Noite polar",
    "Catedral",
    "Cintilação",
    "Singularidade",
    "Regresso",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Primeira luz",
    "Deriva",
    "Horizonte",
    "Lampejo",
    "Cotovia",
    "Lanternas",
    "Maré",
    "Sol",
    "Satélites",
    "Orvalho",
    "Abertura",
    "Claustro",
    "Pedra",
    "Relógio",
    "Estenopo",
    "Rosa",
    "Esteira",
    "Filamento",
    "Meridiano",
    "Cascata",
    "Transição",
    "Ziguezague",
    "Solstício",
    "Ressonância",
    "Prisma",
    "Favo",
    "Salpico",
    "Ressaca",
    "Colheita",
    "Caleido",
    "Tapeçaria",
    "Sombras",
    "Arrebol",
    "Crisálida",
    "Geodo",
    "Paralaxe",
    "Cidadela",
    "Nautilus",
    "Vésperas",
    "Supernova",
    "Lua",
    "Lusco",
    "Candeeiro",
    "Pirilampos",
    "Farol",
    "Noturno",
    "Campo profundo",
    "Estrelas",
    "Penumbra",
    "Metrónomo",
    "Coroa",
    "Sizígia",
    "Pulsar",
    "Obturador",
    "Umbra",
    "Totalidade",
    "Vento",
    "Borealis",
    "Fitas",
    "Noite polar",
    "Catedral",
    "Cintilação",
    "Singularidade",
    "Regresso",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Largo: apanha a cápsula que cai",
    "{icon:slow} Lento: apanha-a e a bola abranda",
    "Conduz: as pontas da raquete mandam a bola para os lados",
    "Faíscas solitárias: persegue cada uma",
    "Manda a bola pelas alas abertas",
    "Limpa cada lanterna por baixo",
    "Surfa a maré: ressalta nas paredes laterais",
    "Lasca o sol por baixo, fila a fila",
    "{icon:anchor} Âncora: apanha a bola, aponta e depois solta-a",
    "Tijolos blindados levam dois toques: atenção às bordas",
    "{icon:anchor} Aponta pela fresta na parede",
    "Só uma porta: manda a bola para o pátio",
    "Deita abaixo a pedra angular e o arco abre-se",
    "Lê os ângulos: cada sombra é uma tacada",
    "{icon:anchor} Um único estenopo estreito: segura, aponta, solta",
    "Cada ponto cardeal leva ao coração",
    "Núcleos âmbar: cada explosão atinge os quatro vizinhos",
    "Toca no filamento em qualquer ponto: arde nos dois sentidos",
    "Divide o campo pelo meridiano",
    "Começa a cascata por qualquer uma das pontas",
    "Abre caminho pelas duas linhas de relés",
    "Três linhas de relés: uma tacada limpa em cada",
    "O anel arde inteiro: encontra um caminho até à borda",
    "Núcleos vizinhos propagam a reação",
    "{icon:multi} Multibola: três bolas, uma abertura",
    "Um núcleo em cada célula: abre-as todas",
    "Salpicos por todo o lado: solta três bolas",
    "Entra nas bolsas atrás da blindagem",
    "Campo cheio: {icon:multi} Multibola limpa-o depressa",
    "Espelhos por todo o lado: parte um lado e depois o gémeo",
    "Puxa um fio e a trama desfaz-se",
    "Rompe o chão e acende o rastilho longo",
    "{icon:phase} Fase: três contactos com tijolos sem ressaltar",
    "{icon:phase} Fase atravessa a casca até ao núcleo",
    "Abre um geodo e os seus cristais acendem-se",
    "Perfura a carapaça e depois acende a rota interior",
    "Entra pelo portal, ou pela parede com {icon:phase} Fase",
    "Em espiral: a volta exterior acende primeiro",
    "Três sinos: toca em cada um por baixo",
    "Apanha uma bola enquanto as outras continuam",
    "Segue o relé à volta do centro aberto",
    "A luz está a partir: aprende o campo enquanto podes",
    "No escuro, a tua bola e a tua raquete levam a luz",
    "Pirilampos: os núcleos brilham até no escuro",
    "Varre a costa com a luz da raquete",
    "Mais bolas, mais luz: {icon:multi} Multibola",
    "Campo profundo: cada pontinho fraco é um tijolo",
    "Une as estrelas: as brilhantes são núcleos",
    "Os portais esbatem-se ao compasso: espera pela brecha",
    "Tique, taque: os portais marcam o tempo",
    "A coroa abre ao compasso: acerta lá dentro",
    "Um portal fantasma ignora a explosão: acerta a faísca a tempo",
    "Um pulsar: batidas rápidas, mãos rápidas",
    "O obturador abre por um instante: fica a postos",
    "Metade na sombra: o lado dos portais marca o tempo",
    "Acende o sol enquanto a lua está sólida",
    "O vento corre num só sentido: segue-o até aos núcleos",
    "Cortinas de luz: varre-as com {icon:multi} Multibola",
    "Cada fita prende-se a um portal: corta as duas metades",
    "A longa noite: aponta pela luz que levas",
    "Entra pelas portas e sobe até ao rosetão",
    "Tudo ao mesmo tempo: vigia os núcleos",
    "Acerta no anel quando os portais ficarem sólidos",
    "Uma última órbita: faz cada abertura valer",
];
