//! European Portuguese. Informal *tu*, as Portuguese games address
//! players; Portugal's spelling and words (ecrã, rato, guardar). Labels in
//! capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Destrói o cosmos",
        ContinueJourney => "Continuar viagem",
        NewJourney => "Nova viagem",
        SectorSelect => "Escolher setor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALHAS",
        StatBest => "RECORDE",
        ActionServe => "Lançar",
        ActionRelease => "Soltar",
        ActionSelect => "Selecionar",
        ActionResume => "Retomar",
        ActionBack => "Voltar",
        Fullscreen => "Ecrã inteiro",
        SectorsHeading => "Setores",
        PracticeNote => "Os treinos nunca alteram a tua viagem",
        MedalClear => "CONCLUÍDO",
        MedalClean => "IMPECÁVEL",
        MedalSwift => "VELOZ",
        PlaySector => "Jogar setor {0}",
        UnlockHint => "Conclui o setor {0} para desbloquear",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SETOR {1}",
        Paused => "Em pausa",
        RetrySector => "Repetir setor",
        MainMenu => "Menu principal",
        JourneyComplete => "Viagem concluída",
        OneMoreOrbit => "Mais uma órbita?",
        StatPoints => "PONTOS",
        SectorClear => "Setor concluído",
        StatTime => "TEMPO",
        StatBonus => "BÓNUS",
        StatChain => "COMBO",
        ExtraLife => "Capítulo concluído · +1 vida",
        NextSector => "Setor seguinte",
        BackToSectors => "Voltar aos setores",
        SaveFailed => "Não foi possível guardar o progresso",
        PerfTitle => "Desempenho / CPU",
        HelpResume => "Continua onde paraste",
        HelpRetry => "Recomeça no ponto de controlo do setor",
        HelpMainMenu => "A tua viagem está guardada",
        HelpSectors => "Treina em qualquer setor aberto",
        HelpNewJourney => "Recomeça no setor 01 · as medalhas ficam",
        Settings => "Definições",
        HelpSettings => "Som, ecrã, idioma",
        SettingSound => "Som",
        SettingVolume => "Volume",
        SettingDisplay => "Ecrã",
        SettingLanguage => "Idioma",
        DisplayWindow => "Janela",
        LanguageSystem => "Sistema",
        ActionAdjust => "Ajustar",
        SettingEffects => "Efeitos",
        SettingContrast => "Contraste",
        LookStandard => "Padrão",
        EffectsReduced => "Reduzidos",
        ContrastHigh => "Alto",
        KeySpace => "Espaço",
        KeyEsc => "Esc",
        SectorsOf => "{0} de {1} setores",
        TargetBest => "{0} · recorde {1}",
        LifeGained => "+1 vida",
        PresenceMenus => "Nos menus",
        PresenceJourney => "Setor {0} · {1}",
        PresencePractice => "A treinar o setor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ALVORADA",
            Chapter::BlueHour => "HORA AZUL",
            Chapter::Afterlight => "CREPÚSCULO",
        },
        PowerName(p) => match p {
            Power::Wide => "LARGO",
            Power::Slow => "LENTO",
            Power::Multi => "MULTIBOLA",
            Power::Anchor => "ÂNCORA",
            Power::Phase => "FASE",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continuar"),
        UnlockHint => Some("Bloqueado"),
        RetrySector => Some("Repetir"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Nova"),
        SectorSelect => Some("Setores"),
        NextSector => Some("Seguinte"),
        BackToSectors => Some("Setores"),
        Settings => Some("Opções"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Retomar"),
        PlaySector => Some("Jogar {0}"),
        ActionServe => Some("Lançar"),
        ActionRelease => Some("Soltar"),
        ActionSelect => Some("Escolher"),
        ActionBack => Some("Voltar"),
        ActionAdjust => Some("Ajustar"),
        SettingEffects => Some("Efeitos"),
        SettingContrast => Some("Contraste"),
        LookStandard => Some("Padrão"),
        EffectsReduced => Some("Menos"),
        ContrastHigh => Some("Alto"),
        StatBest => Some("RECORDE"),
        StatMedals => Some("MEDALHAS"),
        SectorsHeading => Some("Setores"),
        SaveFailed => Some("Não guardado"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Espaço"),
        HelpResume => Some("Voltar ao jogo"),
        HelpRetry => Some("Do ponto de controlo"),
        HelpMainMenu => Some("Viagem guardada"),
        HelpSectors => Some("Treinar setores"),
        HelpNewJourney => Some("Do setor 01"),
        HelpSettings => Some("Som, ecrã"),
        SettingSound => Some("Som"),
        SettingVolume => Some("Volume"),
        SettingDisplay => Some("Ecrã"),
        SettingLanguage => Some("Idioma"),
        DisplayWindow => Some("Janela"),
        Fullscreen => Some("Inteiro"),
        LanguageSystem => Some("Sistema"),
        ExtraLife => Some("+1 vida"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SETOR {1}"),
        JourneyComplete => Some("Concluída"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Primeira luz",
    "Satélites",
    "Esteira",
    "Ressonância",
    "Prisma",
    "Transição",
    "Ressaca",
    "Nascer da lua",
    "Arrebol",
    "Paralaxe",
    "Supernova",
    "Regresso",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Primeira luz",
    "Satélites",
    "Esteira",
    "Ressonância",
    "Prisma",
    "Transição",
    "Ressaca",
    "Lua",
    "Arrebol",
    "Paralaxe",
    "Supernova",
    "Regresso",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Largo e {icon:slow} Lento: apanha as cápsulas que caem",
    "{icon:anchor} Âncora: apanha a bola, aponta e depois solta-a",
    "Núcleos âmbar: cada explosão atinge os quatro vizinhos",
    "Núcleos vizinhos propagam a reação",
    "{icon:multi} Multibola: três bolas, uma abertura",
    "Abre caminho pelas duas linhas de relés",
    "Entra nas bolsas atrás da blindagem",
    "Segue o relé à volta do centro aberto",
    "{icon:phase} Fase: três contactos com tijolos sem ressaltar",
    "Perfura a carapaça e depois acende a rota interior",
    "Apanha uma bola enquanto as outras continuam",
    "Uma última órbita: faz cada abertura valer",
];
