//! Romanian. Informal *tu*; ș and ț with comma below; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Sparge cosmosul",
        ContinueJourney => "Continuă călătoria",
        NewJourney => "Călătorie nouă",
        SectorSelect => "Alege sectorul",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALII",
        StatBest => "RECORD",
        ActionServe => "Lansează",
        ActionRelease => "Eliberează",
        ActionSelect => "Alege",
        ActionResume => "Reia",
        ActionBack => "Înapoi",
        Fullscreen => "Ecran complet",
        SectorsHeading => "Sectoare",
        PracticeNote => "Antrenamentul nu îți schimbă niciodată călătoria",
        MedalClear => "TRECUT",
        MedalClean => "IMPECABIL",
        MedalSwift => "RAPID",
        PlaySector => "Joacă sectorul {0}",
        UnlockHint => "Termină sectorul {0} pentru deblocare",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTORUL {1}",
        Paused => "Pauză",
        RetrySector => "Reia sectorul",
        MainMenu => "Meniu principal",
        JourneyComplete => "Călătorie încheiată",
        OneMoreOrbit => "Încă o orbită?",
        StatPoints => "PUNCTE",
        SectorClear => "Sector trecut",
        StatTime => "TIMP",
        StatBonus => "BONUS",
        StatChain => "LANȚ",
        ExtraLife => "Capitol încheiat · +1 viață",
        NextSector => "Sectorul următor",
        BackToSectors => "Înapoi la sectoare",
        SaveFailed => "Progresul nu a putut fi salvat",
        PerfTitle => "Performanță / CPU",
        HelpResume => "Continuă de unde ai rămas",
        HelpRetry => "Reia de la punctul de control al sectorului",
        HelpMainMenu => "Călătoria ta e salvată",
        HelpSectors => "Exersează în orice sector deschis",
        HelpNewJourney => "Din nou de la sectorul 01 · medaliile rămân",
        Settings => "Setări",
        HelpSettings => "Sunet, ecran, limbă",
        SettingSound => "Sunet",
        SettingVolume => "Volum",
        SettingDisplay => "Ecran",
        SettingLanguage => "Limbă",
        DisplayWindow => "Fereastră",
        LanguageSystem => "Sistem",
        ActionAdjust => "Ajustează",
        KeySpace => "Spațiu",
        KeyEsc => "Esc",
        SectorsOf => "{0} din {1} sectoare",
        TargetBest => "{0} · record {1}",
        LifeGained => "+1 viață",
        PresenceMenus => "În meniuri",
        PresenceJourney => "Sectorul {0} · {1}",
        PresencePractice => "Se antrenează în sectorul {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ZORI",
            Chapter::BlueHour => "ORA ALBASTRĂ",
            Chapter::Afterlight => "AMURG",
        },
        PowerName(p) => match p {
            Power::Wide => "LAT",
            Power::Slow => "LENT",
            Power::Multi => "MULTIMINGE",
            Power::Anchor => "ANCORĂ",
            Power::Phase => "FAZĂ",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continuă"),
        UnlockHint => Some("Blocat"),
        RetrySector => Some("Reia"),
        MainMenu => Some("Meniu"),
        NewJourney => Some("Nouă"),
        SectorSelect => Some("Sectoare"),
        NextSector => Some("Următorul"),
        BackToSectors => Some("Sectoare"),
        Settings => Some("Setări"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Reia"),
        PlaySector => Some("Joacă {0}"),
        ActionServe => Some("Lansează"),
        ActionRelease => Some("Lasă"),
        ActionSelect => Some("Alege"),
        ActionBack => Some("Înapoi"),
        ActionAdjust => Some("Ajustează"),
        StatBest => Some("RECORD"),
        StatMedals => Some("MEDALII"),
        SectorsHeading => Some("Sectoare"),
        SaveFailed => Some("Nesalvat"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spațiu"),
        HelpResume => Some("Înapoi în joc"),
        HelpRetry => Some("De la punctul de control"),
        HelpMainMenu => Some("Călătorie salvată"),
        HelpSectors => Some("Exersează"),
        HelpNewJourney => Some("De la sectorul 01"),
        HelpSettings => Some("Sunet, ecran"),
        SettingSound => Some("Sunet"),
        SettingVolume => Some("Volum"),
        SettingDisplay => Some("Ecran"),
        SettingLanguage => Some("Limbă"),
        DisplayWindow => Some("Fereastră"),
        Fullscreen => Some("Complet"),
        LanguageSystem => Some("Sistem"),
        ExtraLife => Some("+1 viață"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SECTORUL {1}"),
        JourneyComplete => Some("Încheiată"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Prima lumină",
    "Sateliți",
    "Siaj",
    "Rezonanță",
    "Prismă",
    "Fondu",
    "Curent de fund",
    "Răsărit de lună",
    "Licăr de apus",
    "Paralaxă",
    "Supernovă",
    "Întoarcere acasă",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Prima lumină",
    "Sateliți",
    "Siaj",
    "Rezonanță",
    "Prismă",
    "Fondu",
    "Curent",
    "Lună",
    "Licăr",
    "Paralaxă",
    "Supernovă",
    "Întoarcere",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Lat și {icon:slow} Lent: prinde capsulele care cad",
    "{icon:anchor} Ancoră: prinde mingea, țintește, apoi elibereaz-o",
    "Nuclee de chihlimbar: fiecare explozie atinge cei patru vecini",
    "Nucleele vecine duc reacția mai departe",
    "{icon:multi} Multiminge: trei mingi, o singură deschidere",
    "Deschide un drum prin cele două linii de relee",
    "Pătrunde în buzunarele din spatele blindajului",
    "Urmează releul în jurul centrului deschis",
    "{icon:phase} Fază: trei atingeri de cărămizi fără ricoșeu",
    "Străpunge carcasa, apoi aprinde traseul interior",
    "Prinde o minge care revine în timp ce celelalte zboară",
    "O ultimă orbită: fă ca fiecare deschidere să conteze",
];
