//! Romanian. Informal *tu*; ș and ț with comma below; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Sparge cosmosul",
        ContinueJourney => "Continuă călătoria",
        NewJourney => "Călătorie nouă",
        SectorSelect => "Alege sectorul",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALII",
        StatBest => "RECORD",
        ActionServe => "Lansează",
        ActionRelease => "Eliberează",
        ActionSelect => "Alege",
        ActionResume => "Reia",
        ActionBack => "Înapoi",
        Fullscreen => "Ecran complet",
        SectorsHeading => "Sectoare",
        PracticeNote => "Antrenamentul nu îți schimbă niciodată călătoria",
        MedalClear => "TRECUT",
        MedalClean => "IMPECABIL",
        MedalSwift => "RAPID",
        PlaySector => "Joacă sectorul {0}",
        UnlockHint => "Termină sectorul {0} pentru deblocare",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SECTORUL {1}",
        Paused => "Pauză",
        RetrySector => "Reia sectorul",
        MainMenu => "Meniu principal",
        JourneyComplete => "Călătorie încheiată",
        OneMoreOrbit => "Încă o orbită?",
        StatPoints => "PUNCTE",
        SectorClear => "Sector trecut",
        StatTime => "TIMP",
        StatBonus => "BONUS",
        StatChain => "LANȚ",
        ExtraLife => "Capitol încheiat · +1 viață",
        NextSector => "Sectorul următor",
        BackToSectors => "Înapoi la sectoare",
        SaveFailed => "Progresul nu a putut fi salvat",
        PerfTitle => "Performanță / CPU",
        HelpResume => "Continuă de unde ai rămas",
        HelpRetry => "Reia de la punctul de control al sectorului",
        HelpMainMenu => "Călătoria ta e salvată",
        HelpSectors => "Exersează în orice sector deschis",
        HelpNewJourney => "Din nou de la sectorul 01 · medaliile rămân",
        Settings => "Setări",
        HelpSettings => "Sunet, ecran, limbă",
        SettingSound => "Sunet",
        SettingVolume => "Volum",
        SettingDisplay => "Ecran",
        SettingLanguage => "Limbă",
        DisplayWindow => "Fereastră",
        LanguageSystem => "Sistem",
        ActionAdjust => "Ajustează",
        SettingEffects => "Efecte",
        SettingContrast => "Contrast",
        LookStandard => "Standard",
        EffectsReduced => "Reduse",
        ContrastHigh => "Ridicat",
        KeySpace => "Spațiu",
        KeyEsc => "Esc",
        SectorsOf => "{0} din {1} sectoare",
        TargetBest => "{0} · record {1}",
        LifeGained => "+1 viață",
        PresenceMenus => "În meniuri",
        PresenceJourney => "Sectorul {0} · {1}",
        PresencePractice => "Se antrenează în sectorul {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ZORI",
            Chapter::Morning => "DIMINEAȚĂ",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "ORA DE AUR",
            Chapter::Afterlight => "AMURG",
            Chapter::BlueHour => "ORA ALBASTRĂ",
            Chapter::Eclipse => "ECLIPSĂ",
            Chapter::Aurora => "AURORĂ",
        },
        PowerName(p) => match p {
            Power::Wide => "LAT",
            Power::Slow => "LENT",
            Power::Multi => "MULTIMINGE",
            Power::Anchor => "ANCORĂ",
            Power::Phase => "FAZĂ",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Continuă"),
        UnlockHint => Some("Blocat"),
        RetrySector => Some("Reia"),
        MainMenu => Some("Meniu"),
        NewJourney => Some("Nouă"),
        SectorSelect => Some("Sectoare"),
        NextSector => Some("Următorul"),
        BackToSectors => Some("Sectoare"),
        Settings => Some("Setări"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Reia"),
        PlaySector => Some("Joacă {0}"),
        ActionServe => Some("Lansează"),
        ActionRelease => Some("Lasă"),
        ActionSelect => Some("Alege"),
        ActionBack => Some("Înapoi"),
        ActionAdjust => Some("Ajustează"),
        SettingEffects => Some("Efecte"),
        SettingContrast => Some("Contrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Puține"),
        ContrastHigh => Some("Ridicat"),
        StatBest => Some("RECORD"),
        StatMedals => Some("MEDALII"),
        SectorsHeading => Some("Sectoare"),
        SaveFailed => Some("Nesalvat"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Spațiu"),
        HelpResume => Some("Înapoi în joc"),
        HelpRetry => Some("De la punctul de control"),
        HelpMainMenu => Some("Călătorie salvată"),
        HelpSectors => Some("Exersează"),
        HelpNewJourney => Some("De la sectorul 01"),
        HelpSettings => Some("Sunet, ecran"),
        SettingSound => Some("Sunet"),
        SettingVolume => Some("Volum"),
        SettingDisplay => Some("Ecran"),
        SettingLanguage => Some("Limbă"),
        DisplayWindow => Some("Fereastră"),
        Fullscreen => Some("Complet"),
        LanguageSystem => Some("Sistem"),
        ExtraLife => Some("+1 viață"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SECTORUL {1}"),
        JourneyComplete => Some("Încheiată"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Prima lumină",
    "Plutire",
    "Orizont",
    "Sclipire",
    "Ciocârlie",
    "Felinare",
    "Maree",
    "Răsărit de soare",
    "Sateliți",
    "Punct de rouă",
    "Diafragmă",
    "Claustru",
    "Cheia de boltă",
    "Ceas solar",
    "Cameră obscură",
    "Roza vânturilor",
    "Siaj",
    "Filament",
    "Meridian",
    "Cascadă",
    "Fondu",
    "Serpentine",
    "Solstițiu",
    "Rezonanță",
    "Prismă",
    "Fagure",
    "Stropi de mare",
    "Curent de fund",
    "Recoltă",
    "Caleidoscop",
    "Tapiserie",
    "Umbre lungi",
    "Licăr de apus",
    "Crisalidă",
    "Geodă",
    "Paralaxă",
    "Citadelă",
    "Nautilus",
    "Vecernie",
    "Supernovă",
    "Răsărit de lună",
    "Înserare",
    "Lumină de lampă",
    "Licurici",
    "Far",
    "Nocturnă",
    "Câmp adânc",
    "Constelație",
    "Penumbră",
    "Metronom",
    "Coroană solară",
    "Sizigie",
    "Pulsar",
    "Obturator",
    "Umbră",
    "Totalitate",
    "Vânt solar",
    "Boreală",
    "Panglici",
    "Noapte polară",
    "Catedrală",
    "Sclipici",
    "Singularitate",
    "Întoarcere acasă",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Prima lumină",
    "Plutire",
    "Orizont",
    "Sclipire",
    "Ciocârlie",
    "Felinare",
    "Maree",
    "Soare",
    "Sateliți",
    "Rouă",
    "Diafragmă",
    "Claustru",
    "Cheie",
    "Ceas",
    "Obscură",
    "Roza",
    "Siaj",
    "Filament",
    "Meridian",
    "Cascadă",
    "Fondu",
    "Serpentine",
    "Solstițiu",
    "Rezonanță",
    "Prismă",
    "Fagure",
    "Stropi",
    "Curent",
    "Recoltă",
    "Caleido",
    "Tapiserie",
    "Umbre",
    "Licăr",
    "Crisalidă",
    "Geodă",
    "Paralaxă",
    "Citadelă",
    "Nautilus",
    "Vecernie",
    "Supernovă",
    "Lună",
    "Înserare",
    "Lampă",
    "Licurici",
    "Far",
    "Nocturnă",
    "Adânc",
    "Stele",
    "Penumbră",
    "Metronom",
    "Coroană",
    "Sizigie",
    "Pulsar",
    "Obturator",
    "Umbră",
    "Totalitate",
    "Vânt",
    "Boreală",
    "Panglici",
    "Noapte polară",
    "Catedrală",
    "Sclipici",
    "Singularitate",
    "Întoarcere",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Lat: prinde capsula care cade",
    "{icon:slow} Lent: prinde-o și mingea se liniștește",
    "Condu: marginile paletei trimit mingea larg",
    "Scântei singure: urmărește-le pe fiecare",
    "Trimite mingea în sus pe aripile deschise",
    "Curăță fiecare felinar de jos",
    "Călărește valul: ricoșează din pereții laterali",
    "Cioplește soarele de jos, rând cu rând",
    "{icon:anchor} Ancoră: prinde mingea, țintește, apoi elibereaz-o",
    "Cărămizile blindate rezistă două lovituri: ai grijă la margini",
    "{icon:anchor} Țintește prin spărtura din zid",
    "O singură ușă: trimite mingea în curte",
    "Dărâmă cheia de boltă și arcul se deschide",
    "Citește unghiurile: fiecare umbră e o lovitură",
    "{icon:anchor} Un singur orificiu îngust: ține, țintește, eliberează",
    "Fiecare punct cardinal duce la inimă",
    "Nuclee de chihlimbar: fiecare explozie atinge cei patru vecini",
    "Atinge filamentul oriunde: arde în ambele sensuri",
    "Împarte terenul pe meridian",
    "Pornește cascada de la oricare capăt",
    "Deschide un drum prin cele două linii de relee",
    "Trei linii de relee: câte o lovitură curată",
    "Inelul arde întreg: găsește un drum până la margine",
    "Nucleele vecine duc reacția mai departe",
    "{icon:multi} Multiminge: trei mingi, o singură deschidere",
    "Un nucleu în fiecare celulă: sparge-le",
    "Stropi peste tot: eliberează trei mingi",
    "Pătrunde în buzunarele din spatele blindajului",
    "Teren plin: {icon:multi} Multiminge îl curăță repede",
    "Oglinzi peste tot: sparge o parte, apoi geamăna ei",
    "Trage de un fir și țesătura se desface",
    "Sparge podeaua și aprinde fitilul lung",
    "{icon:phase} Fază: trei atingeri de cărămizi fără ricoșeu",
    "{icon:phase} Faza trece prin carcasă până la nucleu",
    "Sparge o geodă și cristalele ei se aprind",
    "Străpunge carcasa, apoi aprinde traseul interior",
    "Intră pe poartă sau prin zid cu {icon:phase} Faza",
    "În spirală spre interior: spira exterioară se aprinde prima",
    "Trei clopote: sună-le pe fiecare de jos",
    "Prinde o minge care revine în timp ce celelalte zboară",
    "Urmează releul în jurul centrului deschis",
    "Lumina se stinge: învață terenul cât poți",
    "În întuneric, mingea și paleta duc lumina",
    "Licurici: nucleele strălucesc chiar și în întuneric",
    "Mătură coasta cu lumina paletei",
    "Mai multe mingi, mai multă lumină: {icon:multi} Multiminge",
    "Câmp adânc: fiecare punct slab e o cărămidă",
    "Unește stelele: cele strălucitoare sunt nuclee",
    "Porțile pălesc pe ritm: așteaptă deschiderea",
    "Tic-tac: porțile țin timpul",
    "Coroana se deschide pe ritm: lovește înăuntru",
    "O poartă fantomă ignoră explozia: potrivește scânteia",
    "Un pulsar: bătăi rapide, mâini rapide",
    "Obturatorul se deschide o clipă: fii gata",
    "Pe jumătate în umbră: partea cu porți ține ritmul",
    "Aprinde soarele cât timp luna e solidă",
    "Vântul bate într-o singură direcție: călărește-l până la nuclee",
    "Perdele de lumină: mătură-le cu {icon:multi} Multiminge",
    "Fiecare panglică e legată de o poartă: taie ambele jumătăți",
    "Noaptea lungă: ghidează-te după lumina pe care o porți",
    "Intră pe uși, urcă la rozetă",
    "Toate deodată: urmărește nucleele",
    "Lovește inelul când porțile devin solide",
    "O ultimă orbită: fă ca fiecare deschidere să conteze",
];
