//! Russian. Formal *вы*, as Russian game UI usually addresses players;
//! hints read "key — action" with an em dash, the idiomatic short form.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Разбей космос",
        ContinueJourney => "Продолжить путь",
        NewJourney => "Новый путь",
        SectorSelect => "Выбор сектора",
        ContinueDetail => "Сектор {0} · {1} · {2}",
        StatSectors => "СЕКТОРЫ",
        StatMedals => "МЕДАЛИ",
        StatBest => "РЕКОРД",
        Fraction => "{0} / {1}",
        KeysMove => "Мышь или стрелки — движение",
        KeysServe => "Пробел или щелчок — запуск",
        KeysPause => "Esc — пауза",
        KeysRelease => "Щелчок или пробел — отпустить",
        KeysBrowse => "Стрелки — выбор",
        KeysPlay => "Enter — играть",
        KeysBack => "Esc — назад",
        PadMove => "Стик или крестовина — движение",
        PadBrowse => "Крестовина — выбор",
        ActionServe => "Запуск",
        ActionPause => "Пауза",
        ActionRelease => "Отпустить",
        ActionSelect => "Выбрать",
        ActionResume => "Продолжить",
        ActionPlay => "Играть",
        ActionBack => "Назад",
        Fullscreen => "Полный экран",
        SectorsHeading => "Секторы",
        PracticeNote => "Тренировки не влияют на ваш путь",
        MedalClear => "ПРОЙДЕН",
        MedalClean => "БЕЗ ПОТЕРЬ",
        MedalSwift => "БЫСТРО",
        MedalClearHow => "Пройдите сектор",
        MedalCleanHow => "Не теряйте жизней",
        PlaySector => "Играть: сектор {0}",
        SwiftWithin => "Пройдите за {0}",
        UnlockHint => "Пройдите сектор {0}, чтобы открыть",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · СЕКТОР {1}",
        Paused => "Пауза",
        RetrySector => "Сектор заново",
        MainMenu => "Главное меню",
        JourneyComplete => "Путь пройден",
        OneMoreOrbit => "Ещё одна орбита?",
        StatPoints => "ОЧКИ",
        SectorClear => "Сектор пройден",
        StatTime => "ВРЕМЯ",
        StatBonus => "БОНУС",
        StatChain => "СЕРИЯ",
        ExtraLife => "Глава пройдена · +1 жизнь",
        NextSector => "Следующий сектор",
        BackToSectors => "К секторам",
        SaveFailed => "Не удалось сохранить прогресс",
        PerfTitle => "Производительность / ЦП",
        HelpResume => "Продолжить с того же места",
        HelpRetry => "Начать заново с контрольной точки сектора",
        HelpMainMenu => "Ваш путь сохранён",
        HelpSectors => "Тренируйтесь в любом открытом секторе",
        HelpNewJourney => "Заново с сектора 01 · медали сохранятся",
        Settings => "Настройки",
        HelpSettings => "Звук, экран, язык",
        SettingSound => "Звук",
        SettingVolume => "Громкость",
        SettingDisplay => "Экран",
        SettingLanguage => "Язык",
        DisplayWindow => "Окно",
        LanguageSystem => "Системный",
        ActionAdjust => "Изменить",
        KeySpace => "Пробел",
        KeyEsc => "Esc",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "РАССВЕТ",
            Chapter::BlueHour => "СИНИЙ ЧАС",
            Chapter::Afterlight => "СУМЕРКИ",
        },
        PowerName(p) => match p {
            Power::Wide => "Ширина",
            Power::Slow => "Замедление",
            Power::Multi => "Мультимяч",
            Power::Anchor => "Якорь",
            Power::Phase => "Фаза",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{1} · {2}"),
        ContinueJourney => Some("Продолжить"),
        SwiftWithin => Some("За {0}"),
        UnlockHint => Some("Закрыт"),
        RetrySector => Some("Заново"),
        MainMenu => Some("Меню"),
        NewJourney => Some("Заново"),
        SectorSelect => Some("Секторы"),
        NextSector => Some("Дальше"),
        BackToSectors => Some("Секторы"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Первый свет",
    "Спутники",
    "Попутный поток",
    "Резонанс",
    "Призма",
    "Наплыв",
    "Течение",
    "Восход луны",
    "Послесвечение",
    "Параллакс",
    "Сверхновая",
    "Возвращение",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Ширина и {icon:slow} Замедление: ловите падающие капсулы",
    "{icon:anchor} Якорь: поймайте мяч, прицельтесь и отпустите",
    "Янтарные ядра: каждый взрыв задевает четырёх соседей",
    "Соседние ядра передают реакцию дальше",
    "{icon:multi} Мультимяч: три мяча, один проход",
    "Откройте путь через две линии реле",
    "Пробейтесь в карманы за бронёй",
    "Следуйте за реле вокруг открытого центра",
    "{icon:phase} Фаза: три касания кирпичей без отскока",
    "Пробейте оболочку, затем подожгите внутренний путь",
    "Поймайте мяч, пока остальные летят",
    "Последняя орбита: пусть каждый проход считается",
];
