//! Russian. Formal *вы*, as Russian game UI usually addresses players;
//! hints read "key — action" with an em dash, the idiomatic short form.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Разбей космос",
        ContinueJourney => "Продолжить путь",
        NewJourney => "Новый путь",
        SectorSelect => "Выбор сектора",
        SavedAt => "Сохранено в секторе {0} · {1}",
        JourneyIntro => "Двенадцать секторов в трёх главах",
        StatSectors => "СЕКТОРЫ",
        StatMedals => "МЕДАЛИ",
        StatBest => "РЕКОРД",
        Fraction => "{0} / {1}",
        KeysMove => "Мышь или стрелки — движение",
        KeysServe => "Пробел или щелчок — запуск",
        KeysPause => "Esc — пауза",
        KeysRelease => "Щелчок или пробел — отпустить",
        KeysBrowse => "Стрелки — выбор",
        KeysPlay => "Enter — играть",
        KeysBack => "Esc — назад",
        KeysContinue => "Enter или щелчок — далее",
        PadMove => "Стик или крестовина — движение",
        PadBrowse => "Крестовина — выбор",
        ActionServe => "Запуск",
        ActionPause => "Пауза",
        ActionRelease => "Отпустить",
        ActionSelect => "Выбрать",
        ActionResume => "Продолжить",
        ActionRetry => "Заново",
        ActionPlay => "Играть",
        ActionBack => "Назад",
        ActionContinue => "Далее",
        SoundOn => "Звук вкл.",
        SoundOff => "Звук выкл.",
        Volume => "Громкость {0}",
        Fullscreen => "Полный экран",
        SectorsHeading => "Секторы",
        PracticeNote => "Тренировки не влияют на ваш путь",
        NoTime => "--:--",
        SwiftTarget => "Целевое время {0}",
        BestTime => "Лучшее {0}",
        MedalClear => "ПРОЙДЕН",
        MedalClean => "БЕЗ ПОТЕРЬ",
        MedalSwift => "БЫСТРО",
        MedalClearHow => "Пройдите сектор",
        MedalCleanHow => "Не теряйте жизней",
        MedalSwiftHow => "Уложитесь в целевое время",
        PlaySector => "Играть: сектор {0}",
        ClearPreviousFirst => "Сначала пройдите предыдущий сектор",
        Score => "ОЧКИ",
        Lives => "ЖИЗНИ",
        SectorNumber => "СЕКТОР {0}",
        PracticeNumber => "ТРЕНИРОВКА {0}",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · СЕКТОР {1}",
        Paused => "Пауза",
        RetrySector => "Сектор заново",
        MainMenu => "Главное меню",
        RetryNote => "Повтор начнётся с контрольной точки",
        JourneyComplete => "Путь пройден",
        OneMoreOrbit => "Ещё одна орбита?",
        StatPoints => "ОЧКИ",
        ProgressSaved => "Ваш прогресс сохранён",
        SectorClear => "Сектор пройден",
        StatTime => "ВРЕМЯ",
        StatBonus => "БОНУС",
        StatBestChain => "МАКС. СЕРИЯ",
        ExtraLife => "Глава пройдена · дополнительная жизнь",
        NextSector => "Следующий сектор",
        BackToSectors => "К секторам",
        SaveFailed => "Не удалось сохранить прогресс",
        PerfTitle => "Производительность / ЦП",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "РАССВЕТ",
            Chapter::BlueHour => "СИНИЙ ЧАС",
            Chapter::Afterlight => "СУМЕРКИ",
        },
        PowerName(p) => match p {
            Power::Wide => "Ширина",
            Power::Slow => "Замедление",
            Power::Multi => "Мультимяч",
            Power::Anchor => "Якорь",
            Power::Phase => "Фаза",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueJourney => Some("Продолжить"),
        ClearPreviousFirst => Some("Закрыт"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Первый свет",
    "Спутники",
    "Попутный поток",
    "Резонанс",
    "Призма",
    "Наплыв",
    "Течение",
    "Восход луны",
    "Послесвечение",
    "Параллакс",
    "Сверхновая",
    "Возвращение",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Ширина и {icon:slow} Замедление: ловите падающие капсулы",
    "{icon:anchor} Якорь: поймайте мяч, прицельтесь и отпустите",
    "Янтарные ядра: каждый взрыв задевает четырёх соседей",
    "Соседние ядра передают реакцию дальше",
    "{icon:multi} Мультимяч: три мяча, один проход",
    "Откройте путь через две линии реле",
    "Пробейтесь в карманы за бронёй",
    "Следуйте за реле вокруг открытого центра",
    "{icon:phase} Фаза: три касания кирпичей без отскока",
    "Пробейте оболочку, затем подожгите внутренний путь",
    "Поймайте мяч, пока остальные летят",
    "Последняя орбита: пусть каждый проход считается",
];
