//! Swedish. Informal *du*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Krossa kosmos",
        ContinueJourney => "Fortsätt resan",
        NewJourney => "Ny resa",
        SectorSelect => "Välj sektor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALJER",
        StatBest => "REKORD",
        ActionServe => "Serva",
        ActionRelease => "Släpp",
        ActionSelect => "Välj",
        ActionResume => "Återuppta",
        ActionBack => "Tillbaka",
        Fullscreen => "Helskärm",
        SectorsHeading => "Sektorer",
        PracticeNote => "Träning ändrar aldrig din resa",
        MedalClear => "KLARAD",
        MedalClean => "FELFRI",
        MedalSwift => "SNABB",
        PlaySector => "Spela sektor {0}",
        UnlockHint => "Klara sektor {0} för att låsa upp",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pausat",
        RetrySector => "Försök sektorn igen",
        MainMenu => "Huvudmeny",
        JourneyComplete => "Resan är klar",
        OneMoreOrbit => "En bana till?",
        StatPoints => "POÄNG",
        SectorClear => "Sektorn klarad",
        StatTime => "TID",
        StatBonus => "BONUS",
        StatChain => "KEDJA",
        ExtraLife => "Kapitlet klart · +1 liv",
        NextSector => "Nästa sektor",
        BackToSectors => "Tillbaka till sektorer",
        SaveFailed => "Framstegen kunde inte sparas",
        PerfTitle => "Prestanda / CPU",
        HelpResume => "Fortsätt där du slutade",
        HelpRetry => "Börja om från sektorns kontrollpunkt",
        HelpMainMenu => "Din resa är sparad",
        HelpSectors => "Träna på valfri öppen sektor",
        HelpNewJourney => "Om från sektor 01 · medaljerna finns kvar",
        Settings => "Inställningar",
        HelpSettings => "Ljud, skärm, språk",
        SettingSound => "Ljud",
        SettingVolume => "Volym",
        SettingDisplay => "Skärm",
        SettingLanguage => "Språk",
        DisplayWindow => "Fönster",
        LanguageSystem => "System",
        ActionAdjust => "Justera",
        SettingEffects => "Effekter",
        SettingContrast => "Kontrast",
        LookStandard => "Standard",
        EffectsReduced => "Minskade",
        ContrastHigh => "Hög",
        KeySpace => "Mellanslag",
        KeyEsc => "Esc",
        SectorsOf => "{0} av {1} sektorer",
        TargetBest => "{0} · bäst {1}",
        LifeGained => "+1 liv",
        PresenceMenus => "I menyerna",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Tränar sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "GRYNING",
            Chapter::Morning => "MORGON",
            Chapter::Zenith => "ZENIT",
            Chapter::GoldenHour => "GYLLENE TIMMEN",
            Chapter::Afterlight => "SKYMNING",
            Chapter::BlueHour => "BLÅ TIMMEN",
            Chapter::Eclipse => "FÖRMÖRKELSE",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "BRED",
            Power::Slow => "LÅNGSAM",
            Power::Multi => "MULTIBOLL",
            Power::Anchor => "ANKARE",
            Power::Phase => "FAS",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Fortsätt"),
        UnlockHint => Some("Låst"),
        RetrySector => Some("Försök igen"),
        MainMenu => Some("Meny"),
        NewJourney => Some("Ny"),
        SectorSelect => Some("Sektorer"),
        NextSector => Some("Nästa"),
        BackToSectors => Some("Sektorer"),
        Settings => Some("Val"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Fortsätt"),
        PlaySector => Some("Spela {0}"),
        ActionServe => Some("Serva"),
        ActionRelease => Some("Släpp"),
        ActionSelect => Some("Välj"),
        ActionBack => Some("Tillbaka"),
        ActionAdjust => Some("Justera"),
        SettingEffects => Some("Effekter"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Färre"),
        ContrastHigh => Some("Hög"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDALJER"),
        SectorsHeading => Some("Sektorer"),
        SaveFailed => Some("Inte sparat"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Mellanslag"),
        HelpResume => Some("Tillbaka till spelet"),
        HelpRetry => Some("Från kontrollpunkten"),
        HelpMainMenu => Some("Resan är sparad"),
        HelpSectors => Some("Träna sektorer"),
        HelpNewJourney => Some("Från sektor 01"),
        HelpSettings => Some("Ljud, skärm"),
        SettingSound => Some("Ljud"),
        SettingVolume => Some("Volym"),
        SettingDisplay => Some("Skärm"),
        SettingLanguage => Some("Språk"),
        DisplayWindow => Some("Fönster"),
        Fullscreen => Some("Hel"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 liv"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Klar"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Första ljuset",
    "Drift",
    "Horisont",
    "Glimt",
    "Lärka",
    "Lyktor",
    "Tidvatten",
    "Soluppgång",
    "Satelliter",
    "Daggpunkt",
    "Bländare",
    "Kloster",
    "Slutsten",
    "Solur",
    "Nålhål",
    "Vindros",
    "Slipström",
    "Glödtråd",
    "Meridian",
    "Kaskad",
    "Övertoning",
    "Serpentin",
    "Solstånd",
    "Resonans",
    "Prisma",
    "Vaxkaka",
    "Skumsprut",
    "Underström",
    "Skörd",
    "Kalejdoskop",
    "Gobeläng",
    "Långa skuggor",
    "Efterglöd",
    "Puppa",
    "Geod",
    "Parallax",
    "Citadell",
    "Nautilus",
    "Aftonsång",
    "Supernova",
    "Månuppgång",
    "Skymningsljus",
    "Lampsken",
    "Eldflugor",
    "Fyr",
    "Nattstycke",
    "Djupfält",
    "Stjärnbild",
    "Halvskugga",
    "Metronom",
    "Korona",
    "Syzygi",
    "Pulsar",
    "Slutare",
    "Umbra",
    "Totalitet",
    "Solvind",
    "Norrsken",
    "Band",
    "Polarnatt",
    "Katedral",
    "Skimmer",
    "Singularitet",
    "Hemkomst",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Första ljuset",
    "Drift",
    "Horisont",
    "Glimt",
    "Lärka",
    "Lyktor",
    "Tidvatten",
    "Sol",
    "Satelliter",
    "Daggpunkt",
    "Bländare",
    "Kloster",
    "Slutsten",
    "Solur",
    "Nålhål",
    "Vindros",
    "Slipström",
    "Tråd",
    "Meridian",
    "Kaskad",
    "Övertoning",
    "Serpentin",
    "Solstånd",
    "Resonans",
    "Prisma",
    "Kaka",
    "Skumsprut",
    "Underström",
    "Skörd",
    "Kalejdo",
    "Gobeläng",
    "Skuggor",
    "Efterglöd",
    "Puppa",
    "Geod",
    "Parallax",
    "Citadell",
    "Nautilus",
    "Aftonsång",
    "Supernova",
    "Månuppgång",
    "Skymning",
    "Lampsken",
    "Eldflugor",
    "Fyr",
    "Nattstycke",
    "Djupfält",
    "Stjärnor",
    "Halvskugga",
    "Metronom",
    "Korona",
    "Syzygi",
    "Pulsar",
    "Slutare",
    "Umbra",
    "Totalitet",
    "Solvind",
    "Norrsken",
    "Band",
    "Polarnatt",
    "Katedral",
    "Skimmer",
    "Singularitet",
    "Hemkomst",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Bred: fånga den fallande kapseln",
    "{icon:slow} Långsam: fånga den så lugnar bollen sig",
    "Styr: rackets kanter skickar bollen brett",
    "Ensamma gnistor: jaga var och en",
    "Skicka bollen upp längs de öppna flyglarna",
    "Rensa varje lykta underifrån",
    "Rid på dyningen: studsa mot sidoväggarna",
    "Hacka bort solen underifrån, rad för rad",
    "{icon:anchor} Ankare: fånga bollen, sikta och släpp den",
    "Pansrade klossar tål två träffar: se upp för kanterna",
    "{icon:anchor} Sikta genom hålet i muren",
    "Bara en dörr: skicka bollen in på gården",
    "Slå ut slutstenen så öppnas bågen",
    "Läs vinklarna: varje skugga är ett skott",
    "{icon:anchor} Ett smalt nålhål: håll, sikta, släpp",
    "Varje väderstreck leder till hjärtat",
    "Bärnstenskärnor: varje explosion når fyra grannar",
    "Rör glödtråden var som helst: den brinner åt båda håll",
    "Dela banan längs meridianen",
    "Starta kaskaden i någon av ändarna",
    "Öppna en väg genom de två relälinjerna",
    "Tre relälinjer: ett rent skott var",
    "Ringen brinner hel: hitta en väg till kanten",
    "Närliggande kärnor för reaktionen vidare",
    "{icon:multi} Multiboll: tre bollar, en öppning",
    "En kärna i varje cell: knäck dem",
    "Skum överallt: släpp loss tre bollar",
    "Bryt in i fickorna bakom pansaret",
    "Full bana: {icon:multi} Multiboll rensar den snabbt",
    "Speglar överallt: bryt ena sidan, sedan tvillingen",
    "Dra i en tråd så lossnar vävnaden",
    "Bryt igenom golvet och tänd den långa stubinen",
    "{icon:phase} Fas: tre klosskontakter utan studs",
    "{icon:phase} Fas glider genom skalet till kärnan",
    "Knäck en geod så tänds dess kristaller",
    "Genomborra skalet och tänd sedan den inre rutten",
    "In genom porten, eller genom muren med {icon:phase} Fas",
    "Spiralera inåt: det yttersta varvet tänds först",
    "Tre klockor: ringa i var och en underifrån",
    "Fånga en returboll medan de andra fortsätter",
    "Följ reläet runt den öppna mitten",
    "Ljuset försvinner: lär dig banan medan du kan",
    "I mörkret bär din boll och ditt racket ljuset",
    "Eldflugor: kärnorna glöder även i mörkret",
    "Svep racketets ljus över kusten",
    "Fler bollar, mer ljus: {icon:multi} Multiboll",
    "Djupfält: varje svag prick är en kloss",
    "Förena stjärnorna: de ljusa är kärnor",
    "Portar bleknar i takt: vänta på glappet",
    "Tick, tack: portarna håller takten",
    "Koronan öppnas i takt: träffa innanför",
    "En spökport skakar av sig en explosion: tajma gnistan",
    "En pulsar: snabba slag, snabba händer",
    "Slutaren öppnas ett ögonblick: var redo",
    "Halvt i skugga: portsidan håller takten",
    "Tänd solen medan månen är fast",
    "Vinden blåser åt ett håll: rid med den till kärnorna",
    "Ljusridåer: svep bort dem med {icon:multi} Multiboll",
    "Varje band hänger i en port: klipp båda halvorna",
    "Den långa natten: sikta efter ljuset du bär",
    "In genom dörrarna, upp till rosfönstret",
    "Allt på en gång: håll koll på kärnorna",
    "Träffa ringen när portarna blir fasta",
    "En sista bana: låt varje öppning räknas",
];
