//! Swedish. Informal *du*; labels in capitals.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Krossa kosmos",
        ContinueJourney => "Fortsätt resan",
        NewJourney => "Ny resa",
        SectorSelect => "Välj sektor",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MEDALJER",
        StatBest => "REKORD",
        ActionServe => "Serva",
        ActionRelease => "Släpp",
        ActionSelect => "Välj",
        ActionResume => "Återuppta",
        ActionBack => "Tillbaka",
        Fullscreen => "Helskärm",
        SectorsHeading => "Sektorer",
        PracticeNote => "Träning ändrar aldrig din resa",
        MedalClear => "KLARAD",
        MedalClean => "FELFRI",
        MedalSwift => "SNABB",
        PlaySector => "Spela sektor {0}",
        UnlockHint => "Klara sektor {0} för att låsa upp",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTOR {1}",
        Paused => "Pausat",
        RetrySector => "Försök sektorn igen",
        MainMenu => "Huvudmeny",
        JourneyComplete => "Resan är klar",
        OneMoreOrbit => "En bana till?",
        StatPoints => "POÄNG",
        SectorClear => "Sektorn klarad",
        StatTime => "TID",
        StatBonus => "BONUS",
        StatChain => "KEDJA",
        ExtraLife => "Kapitlet klart · +1 liv",
        NextSector => "Nästa sektor",
        BackToSectors => "Tillbaka till sektorer",
        SaveFailed => "Framstegen kunde inte sparas",
        PerfTitle => "Prestanda / CPU",
        HelpResume => "Fortsätt där du slutade",
        HelpRetry => "Börja om från sektorns kontrollpunkt",
        HelpMainMenu => "Din resa är sparad",
        HelpSectors => "Träna på valfri öppen sektor",
        HelpNewJourney => "Om från sektor 01 · medaljerna finns kvar",
        Settings => "Inställningar",
        HelpSettings => "Ljud, skärm, språk",
        SettingSound => "Ljud",
        SettingVolume => "Volym",
        SettingDisplay => "Skärm",
        SettingLanguage => "Språk",
        DisplayWindow => "Fönster",
        LanguageSystem => "System",
        ActionAdjust => "Justera",
        KeySpace => "Mellanslag",
        KeyEsc => "Esc",
        SectorsOf => "{0} av {1} sektorer",
        TargetBest => "{0} · bäst {1}",
        LifeGained => "+1 liv",
        PresenceMenus => "I menyerna",
        PresenceJourney => "Sektor {0} · {1}",
        PresencePractice => "Tränar sektor {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "GRYNING",
            Chapter::BlueHour => "BLÅ TIMMEN",
            Chapter::Afterlight => "SKYMNING",
        },
        PowerName(p) => match p {
            Power::Wide => "BRED",
            Power::Slow => "LÅNGSAM",
            Power::Multi => "MULTIBOLL",
            Power::Anchor => "ANKARE",
            Power::Phase => "FAS",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Fortsätt"),
        UnlockHint => Some("Låst"),
        RetrySector => Some("Försök igen"),
        MainMenu => Some("Meny"),
        NewJourney => Some("Ny"),
        SectorSelect => Some("Sektorer"),
        NextSector => Some("Nästa"),
        BackToSectors => Some("Sektorer"),
        Settings => Some("Val"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Fortsätt"),
        PlaySector => Some("Spela {0}"),
        ActionServe => Some("Serva"),
        ActionRelease => Some("Släpp"),
        ActionSelect => Some("Välj"),
        ActionBack => Some("Tillbaka"),
        ActionAdjust => Some("Justera"),
        StatBest => Some("REKORD"),
        StatMedals => Some("MEDALJER"),
        SectorsHeading => Some("Sektorer"),
        SaveFailed => Some("Inte sparat"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Mellanslag"),
        HelpResume => Some("Tillbaka till spelet"),
        HelpRetry => Some("Från kontrollpunkten"),
        HelpMainMenu => Some("Resan är sparad"),
        HelpSectors => Some("Träna sektorer"),
        HelpNewJourney => Some("Från sektor 01"),
        HelpSettings => Some("Ljud, skärm"),
        SettingSound => Some("Ljud"),
        SettingVolume => Some("Volym"),
        SettingDisplay => Some("Skärm"),
        SettingLanguage => Some("Språk"),
        DisplayWindow => Some("Fönster"),
        Fullscreen => Some("Hel"),
        LanguageSystem => Some("System"),
        ExtraLife => Some("+1 liv"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTOR {1}"),
        JourneyComplete => Some("Klar"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Första ljuset",
    "Satelliter",
    "Slipström",
    "Resonans",
    "Prisma",
    "Övertoning",
    "Underström",
    "Månuppgång",
    "Efterglöd",
    "Parallax",
    "Supernova",
    "Hemkomst",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Första ljuset",
    "Satelliter",
    "Slipström",
    "Resonans",
    "Prisma",
    "Övertoning",
    "Underström",
    "Månuppgång",
    "Efterglöd",
    "Parallax",
    "Supernova",
    "Hemkomst",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Bred och {icon:slow} Långsam: fånga de fallande kapslarna",
    "{icon:anchor} Ankare: fånga bollen, sikta och släpp den",
    "Bärnstenskärnor: varje explosion når fyra grannar",
    "Närliggande kärnor för reaktionen vidare",
    "{icon:multi} Multiboll: tre bollar, en öppning",
    "Öppna en väg genom de två relälinjerna",
    "Bryt in i fickorna bakom pansaret",
    "Följ reläet runt den öppna mitten",
    "{icon:phase} Fas: tre klosskontakter utan studs",
    "Genomborra skalet och tänd sedan den inre rutten",
    "Fånga en returboll medan de andra fortsätter",
    "En sista bana: låt varje öppning räknas",
];
