//! Thai. Polite neutral register. Thai writes no spaces between words, so
//! U+200B ZERO WIDTH SPACE marks where a line may break; spaces separate
//! phrases. Labels have no case.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "ทำลาย\u{200b}จักรวาล",
        ContinueJourney => "เดินทาง\u{200b}ต่อ",
        NewJourney => "การ\u{200b}เดินทาง\u{200b}ใหม่",
        SectorSelect => "เลือก\u{200b}เซกเตอร์",
        ContinueDetail => "{0} · {1}",
        StatMedals => "เหรียญ",
        StatBest => "สูงสุด",
        ActionServe => "เสิร์ฟ",
        ActionRelease => "ปล่อย",
        ActionSelect => "เลือก",
        ActionResume => "เล่น\u{200b}ต่อ",
        ActionBack => "กลับ",
        Fullscreen => "เต็ม\u{200b}จอ",
        SectorsHeading => "เซกเตอร์",
        PracticeNote => {
            "การ\u{200b}ฝึก\u{200b}ซ้อม\u{200b}ไม่\u{200b}เปลี่ยน\u{200b}การ\u{200b}เดินทาง\u{200b}ของ\u{200b}คุณ"
        }
        MedalClear => "ผ่าน",
        MedalClean => "ไร้\u{200b}ที่\u{200b}ติ",
        MedalSwift => "รวดเร็ว",
        PlaySector => "เล่น\u{200b}เซกเตอร์ {0}",
        UnlockHint => "ผ่าน\u{200b}เซกเตอร์ {0} เพื่อ\u{200b}ปลด\u{200b}ล็อก",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · เซกเตอร์ {1}",
        Paused => "หยุด\u{200b}ชั่วคราว",
        RetrySector => "เล่น\u{200b}เซกเตอร์\u{200b}ใหม่",
        MainMenu => "เมนู\u{200b}หลัก",
        JourneyComplete => "การ\u{200b}เดินทาง\u{200b}สิ้นสุด",
        OneMoreOrbit => "อีก\u{200b}หนึ่ง\u{200b}รอบ?",
        StatPoints => "แต้ม",
        SectorClear => "ผ่าน\u{200b}เซกเตอร์\u{200b}แล้ว",
        StatTime => "เวลา",
        StatBonus => "โบนัส",
        StatChain => "คอมโบ",
        ExtraLife => "จบ\u{200b}บท · +1 ชีวิต",
        NextSector => "เซกเตอร์\u{200b}ถัดไป",
        BackToSectors => "กลับ\u{200b}ไป\u{200b}ที่\u{200b}เซกเตอร์",
        SaveFailed => "บันทึก\u{200b}ความ\u{200b}คืบหน้า\u{200b}ไม่\u{200b}ได้",
        PerfTitle => "ประสิทธิภาพ / CPU",
        HelpResume => "เล่น\u{200b}ต่อ\u{200b}จาก\u{200b}จุด\u{200b}ที่\u{200b}ค้าง\u{200b}ไว้",
        HelpRetry => {
            "เริ่ม\u{200b}ใหม่\u{200b}จาก\u{200b}จุด\u{200b}เช็ก\u{200b}พอยต์\u{200b}ของ\u{200b}เซกเตอร์"
        }
        HelpMainMenu => "บันทึก\u{200b}การ\u{200b}เดินทาง\u{200b}แล้ว",
        HelpSectors => "ฝึก\u{200b}เล่น\u{200b}เซกเตอร์\u{200b}ที่\u{200b}เปิด\u{200b}แล้ว",
        HelpNewJourney => "เริ่ม\u{200b}ใหม่\u{200b}ที่\u{200b}เซกเตอร์ 01 · เหรียญ\u{200b}ยัง\u{200b}อยู่",
        Settings => "การ\u{200b}ตั้ง\u{200b}ค่า",
        HelpSettings => "เสียง การ\u{200b}แสดง\u{200b}ผล ภาษา",
        SettingSound => "เสียง",
        SettingVolume => "ระดับ\u{200b}เสียง",
        SettingDisplay => "การ\u{200b}แสดง\u{200b}ผล",
        SettingLanguage => "ภาษา",
        DisplayWindow => "หน้า\u{200b}ต่าง",
        LanguageSystem => "ตาม\u{200b}ระบบ",
        ActionAdjust => "ปรับ",
        KeySpace => "เว้น\u{200b}วรรค",
        KeyEsc => "Esc",
        SectorsOf => "{0} จาก {1} เซกเตอร์",
        TargetBest => "{0} · ดี\u{200b}ที่\u{200b}สุด {1}",
        LifeGained => "+1 ชีวิต",
        PresenceMenus => "อยู่\u{200b}ใน\u{200b}เมนู",
        PresenceJourney => "เซกเตอร์ {0} · {1}",
        PresencePractice => "กำลัง\u{200b}ฝึก\u{200b}ซ้อม\u{200b}เซกเตอร์ {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "รุ่ง\u{200b}อรุณ",
            Chapter::BlueHour => "บลู\u{200b}อาวร์",
            Chapter::Afterlight => "สนธยา",
        },
        PowerName(p) => match p {
            Power::Wide => "ขยาย",
            Power::Slow => "ช้า",
            Power::Multi => "หลาย\u{200b}ลูก",
            Power::Anchor => "สมอ",
            Power::Phase => "เฟส",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("เล่น\u{200b}ต่อ"),
        UnlockHint => Some("ล็อก"),
        RetrySector => Some("ลอง\u{200b}ใหม่"),
        MainMenu => Some("เมนู"),
        NewJourney => Some("เริ่ม\u{200b}ใหม่"),
        SectorSelect => Some("เซกเตอร์"),
        NextSector => Some("ถัด\u{200b}ไป"),
        BackToSectors => Some("เซกเตอร์"),
        Settings => Some("ตั้ง\u{200b}ค่า"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("เล่น\u{200b}ต่อ"),
        PlaySector => Some("เล่น {0}"),
        ActionServe => Some("เสิร์ฟ"),
        ActionRelease => Some("ปล่อย"),
        ActionSelect => Some("เลือก"),
        ActionBack => Some("กลับ"),
        ActionAdjust => Some("ปรับ"),
        StatBest => Some("สูงสุด"),
        StatMedals => Some("เหรียญ"),
        SectorsHeading => Some("เซกเตอร์"),
        SaveFailed => Some("ไม่\u{200b}ได้\u{200b}บันทึก"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("เว้น\u{200b}วรรค"),
        HelpResume => Some("กลับ\u{200b}ไป\u{200b}เล่น"),
        HelpRetry => Some("จาก\u{200b}จุด\u{200b}เช็ก\u{200b}พอยต์"),
        HelpMainMenu => Some("บันทึก\u{200b}แล้ว"),
        HelpSectors => Some("ฝึก\u{200b}เล่น"),
        HelpNewJourney => Some("จาก\u{200b}เซกเตอร์ 01"),
        HelpSettings => Some("เสียง การ\u{200b}แสดง\u{200b}ผล"),
        SettingSound => Some("เสียง"),
        SettingVolume => Some("เสียง"),
        SettingDisplay => Some("จอ"),
        SettingLanguage => Some("ภาษา"),
        DisplayWindow => Some("หน้า\u{200b}ต่าง"),
        Fullscreen => Some("เต็ม\u{200b}จอ"),
        LanguageSystem => Some("ระบบ"),
        ExtraLife => Some("+1 ชีวิต"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("เซกเตอร์ {1}"),
        JourneyComplete => Some("สิ้นสุด"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "แสง\u{200b}แรก",
    "ดาวเทียม",
    "กระแส\u{200b}ลม",
    "การ\u{200b}สั่น\u{200b}พ้อง",
    "ปริซึม",
    "ครอส\u{200b}เฟด",
    "คลื่น\u{200b}ใต้\u{200b}น้ำ",
    "จันทร์\u{200b}ขึ้น",
    "แสง\u{200b}สนธยา",
    "พารัล\u{200b}แลกซ์",
    "ซูเปอร์\u{200b}โนวา",
    "กลับ\u{200b}บ้าน",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "แสง\u{200b}แรก",
    "ดาวเทียม",
    "กระแส\u{200b}ลม",
    "สั่น\u{200b}พ้อง",
    "ปริซึม",
    "ครอส\u{200b}เฟด",
    "คลื่น",
    "จันทร์\u{200b}ขึ้น",
    "แสง\u{200b}สนธยา",
    "พารัล\u{200b}แลกซ์",
    "ซูเปอร์\u{200b}โนวา",
    "กลับ\u{200b}บ้าน",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} ขยาย และ {icon:slow} ช้า: รับ\u{200b}แคปซูล\u{200b}ที่\u{200b}ตก\u{200b}ลง\u{200b}มา",
    "{icon:anchor} สมอ: รับ\u{200b}ลูก\u{200b}บอล เล็ง แล้ว\u{200b}ปล่อย",
    "แกน\u{200b}อำพัน: ทุก\u{200b}การ\u{200b}ระเบิด\u{200b}ส่ง\u{200b}ผล\u{200b}ถึง\u{200b}สี่\u{200b}ช่อง\u{200b}ข้าง\u{200b}เคียง",
    "แกน\u{200b}ที่\u{200b}อยู่\u{200b}ติด\u{200b}กัน\u{200b}ส่ง\u{200b}ต่อ\u{200b}ปฏิกิริยา",
    "{icon:multi} หลาย\u{200b}ลูก: สาม\u{200b}ลูก หนึ่ง\u{200b}ช่อง\u{200b}ว่าง",
    "เปิด\u{200b}ทาง\u{200b}ผ่าน\u{200b}สอง\u{200b}แนว\u{200b}รีเลย์",
    "ทะลวง\u{200b}เข้า\u{200b}ช่อง\u{200b}หลัง\u{200b}เกราะ",
    "ตาม\u{200b}รีเลย์\u{200b}รอบ\u{200b}ใจ\u{200b}กลาง\u{200b}ที่\u{200b}เปิด\u{200b}โล่ง",
    "{icon:phase} เฟส: ชน\u{200b}อิฐ\u{200b}สาม\u{200b}ครั้ง\u{200b}โดย\u{200b}ไม่\u{200b}เด้ง",
    "เจาะ\u{200b}เปลือก แล้ว\u{200b}จุด\u{200b}ชนวน\u{200b}เส้น\u{200b}ทาง\u{200b}ด้าน\u{200b}ใน",
    "รับ\u{200b}ลูก\u{200b}ที่\u{200b}กลับ\u{200b}มา\u{200b}ขณะ\u{200b}ที่\u{200b}ลูก\u{200b}อื่น\u{200b}ยัง\u{200b}ลอย\u{200b}อยู่",
    "วง\u{200b}โคจร\u{200b}สุด\u{200b}ท้าย: ใช้\u{200b}ทุก\u{200b}ช่อง\u{200b}ว่าง\u{200b}ให้\u{200b}คุ้ม",
];
