//! Turkish. Informal *sen*; hints read "action: keys". Labels in capitals
//! with the dotted capital İ, as Turkish writes them.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Kozmosu parçala",
        ContinueJourney => "Yolculuğa devam et",
        NewJourney => "Yeni yolculuk",
        SectorSelect => "Sektör seçimi",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MADALYALAR",
        StatBest => "REKOR",
        ActionServe => "Servis",
        ActionRelease => "Bırak",
        ActionSelect => "Seç",
        ActionResume => "Devam et",
        ActionBack => "Geri",
        Fullscreen => "Tam ekran",
        SectorsHeading => "Sektörler",
        PracticeNote => "Antrenmanlar yolculuğunu asla değiştirmez",
        MedalClear => "TAMAM",
        MedalClean => "KUSURSUZ",
        MedalSwift => "HIZLI",
        PlaySector => "{0}. sektörü oyna",
        UnlockHint => "Açmak için {0}. sektörü tamamla",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTÖR {1}",
        Paused => "Duraklatıldı",
        RetrySector => "Sektörü tekrarla",
        MainMenu => "Ana menü",
        JourneyComplete => "Yolculuk tamamlandı",
        OneMoreOrbit => "Bir tur daha?",
        StatPoints => "PUAN",
        SectorClear => "Sektör tamamlandı",
        StatTime => "SÜRE",
        StatBonus => "BONUS",
        StatChain => "ZİNCİR",
        ExtraLife => "Bölüm tamamlandı · +1 can",
        NextSector => "Sonraki sektör",
        BackToSectors => "Sektörlere dön",
        SaveFailed => "İlerleme kaydedilemedi",
        PerfTitle => "Performans / CPU",
        HelpResume => "Kaldığın yerden devam et",
        HelpRetry => "Sektörün kontrol noktasından yeniden başla",
        HelpMainMenu => "Yolculuğun kaydedildi",
        HelpSectors => "Açık herhangi bir sektörde antrenman yap",
        HelpNewJourney => "Sektör 01’den yeniden · madalyalar kalır",
        Settings => "Ayarlar",
        HelpSettings => "Ses, ekran, dil",
        SettingSound => "Ses",
        SettingVolume => "Ses düzeyi",
        SettingDisplay => "Ekran",
        SettingLanguage => "Dil",
        DisplayWindow => "Pencere",
        LanguageSystem => "Sistem",
        ActionAdjust => "Ayarla",
        SettingEffects => "Efektler",
        SettingContrast => "Kontrast",
        LookStandard => "Standart",
        EffectsReduced => "Azaltılmış",
        ContrastHigh => "Yüksek",
        KeySpace => "Boşluk",
        KeyEsc => "Esc",
        SectorsOf => "{0}/{1} sektör",
        TargetBest => "{0} · rekor {1}",
        LifeGained => "+1 can",
        PresenceMenus => "Menülerde",
        PresenceJourney => "Sektör {0} · {1}",
        PresencePractice => "Antrenman: {0}. sektör · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ŞAFAK",
            Chapter::BlueHour => "MAVİ SAAT",
            Chapter::Afterlight => "ALACAKARANLIK",
        },
        PowerName(p) => match p {
            Power::Wide => "GENİŞ",
            Power::Slow => "YAVAŞ",
            Power::Multi => "ÇOKLU TOP",
            Power::Anchor => "ÇAPA",
            Power::Phase => "FAZ",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Devam et"),
        UnlockHint => Some("Kilitli"),
        RetrySector => Some("Tekrar"),
        MainMenu => Some("Menü"),
        NewJourney => Some("Yeni"),
        SectorSelect => Some("Sektörler"),
        NextSector => Some("Sonraki"),
        BackToSectors => Some("Sektörler"),
        Settings => Some("Ayarlar"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Devam"),
        PlaySector => Some("{0}. sektör"),
        ActionServe => Some("Servis"),
        ActionRelease => Some("Bırak"),
        ActionSelect => Some("Seç"),
        ActionBack => Some("Geri"),
        ActionAdjust => Some("Ayarla"),
        SettingEffects => Some("Efektler"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Az"),
        ContrastHigh => Some("Yüksek"),
        StatBest => Some("REKOR"),
        StatMedals => Some("MADALYALAR"),
        SectorsHeading => Some("Sektörler"),
        SaveFailed => Some("Kaydedilmedi"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Boşluk"),
        HelpResume => Some("Oyuna dön"),
        HelpRetry => Some("Kontrol noktasından"),
        HelpMainMenu => Some("Kaydedildi"),
        HelpSectors => Some("Antrenman"),
        HelpNewJourney => Some("Sektör 01’den"),
        HelpSettings => Some("Ses, ekran"),
        SettingSound => Some("Ses"),
        SettingVolume => Some("Ses düzeyi"),
        SettingDisplay => Some("Ekran"),
        SettingLanguage => Some("Dil"),
        DisplayWindow => Some("Pencere"),
        Fullscreen => Some("Tam"),
        LanguageSystem => Some("Sistem"),
        ExtraLife => Some("+1 can"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTÖR {1}"),
        JourneyComplete => Some("Tamamlandı"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "İlk Işık",
    "Uydular",
    "Hava Akımı",
    "Rezonans",
    "Prizma",
    "Geçiş",
    "Dip Akıntısı",
    "Ay Doğuşu",
    "Son Işıltı",
    "Paralaks",
    "Süpernova",
    "Eve Dönüş",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "İlk Işık",
    "Uydular",
    "Hava Akımı",
    "Rezonans",
    "Prizma",
    "Geçiş",
    "Akıntı",
    "Ay Doğuşu",
    "Son Işıltı",
    "Paralaks",
    "Süpernova",
    "Eve Dönüş",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Geniş ve {icon:slow} Yavaş: düşen kapsülleri yakala",
    "{icon:anchor} Çapa: topu yakala, nişan al, sonra bırak",
    "Kehribar çekirdekler: her patlama dört komşusuna ulaşır",
    "Komşu çekirdekler tepkimeyi taşır",
    "{icon:multi} Çoklu top: üç top, tek açıklık",
    "İki röle hattı arasından bir yol aç",
    "Zırhın ardındaki ceplere gir",
    "Açık merkezin çevresinde röleyi izle",
    "{icon:phase} Faz: sekmeden üç tuğla teması",
    "Kabuğu del, sonra iç rotayı ateşle",
    "Diğer toplar uçarken dönen bir topu yakala",
    "Son bir yörünge: her açıklığı değerlendir",
];
