//! Turkish. Informal *sen*; hints read "action: keys". Labels in capitals
//! with the dotted capital İ, as Turkish writes them.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Kozmosu parçala",
        ContinueJourney => "Yolculuğa devam et",
        NewJourney => "Yeni yolculuk",
        SectorSelect => "Sektör seçimi",
        ContinueDetail => "{0} · {1}",
        StatMedals => "MADALYALAR",
        StatBest => "REKOR",
        ActionServe => "Servis",
        ActionRelease => "Bırak",
        ActionSelect => "Seç",
        ActionResume => "Devam et",
        ActionBack => "Geri",
        Fullscreen => "Tam ekran",
        SectorsHeading => "Sektörler",
        PracticeNote => "Antrenmanlar yolculuğunu asla değiştirmez",
        MedalClear => "TAMAM",
        MedalClean => "KUSURSUZ",
        MedalSwift => "HIZLI",
        PlaySector => "{0}. sektörü oyna",
        UnlockHint => "Açmak için {0}. sektörü tamamla",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · SEKTÖR {1}",
        Paused => "Duraklatıldı",
        RetrySector => "Sektörü tekrarla",
        MainMenu => "Ana menü",
        JourneyComplete => "Yolculuk tamamlandı",
        OneMoreOrbit => "Bir tur daha?",
        StatPoints => "PUAN",
        SectorClear => "Sektör tamamlandı",
        StatTime => "SÜRE",
        StatBonus => "BONUS",
        StatChain => "ZİNCİR",
        ExtraLife => "Bölüm tamamlandı · +1 can",
        NextSector => "Sonraki sektör",
        BackToSectors => "Sektörlere dön",
        SaveFailed => "İlerleme kaydedilemedi",
        PerfTitle => "Performans / CPU",
        HelpResume => "Kaldığın yerden devam et",
        HelpRetry => "Sektörün kontrol noktasından yeniden başla",
        HelpMainMenu => "Yolculuğun kaydedildi",
        HelpSectors => "Açık herhangi bir sektörde antrenman yap",
        HelpNewJourney => "Sektör 01’den yeniden · madalyalar kalır",
        Settings => "Ayarlar",
        HelpSettings => "Ses, ekran, dil",
        SettingSound => "Ses",
        SettingVolume => "Ses düzeyi",
        SettingDisplay => "Ekran",
        SettingLanguage => "Dil",
        DisplayWindow => "Pencere",
        LanguageSystem => "Sistem",
        ActionAdjust => "Ayarla",
        SettingEffects => "Efektler",
        SettingContrast => "Kontrast",
        LookStandard => "Standart",
        EffectsReduced => "Azaltılmış",
        ContrastHigh => "Yüksek",
        KeySpace => "Boşluk",
        KeyEsc => "Esc",
        SectorsOf => "{0}/{1} sektör",
        TargetBest => "{0} · rekor {1}",
        LifeGained => "+1 can",
        PresenceMenus => "Menülerde",
        PresenceJourney => "Sektör {0} · {1}",
        PresencePractice => "Antrenman: {0}. sektör · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "ŞAFAK",
            Chapter::Morning => "SABAH",
            Chapter::Zenith => "ZENİT",
            Chapter::GoldenHour => "ALTIN SAAT",
            Chapter::Afterlight => "ALACAKARANLIK",
            Chapter::BlueHour => "MAVİ SAAT",
            Chapter::Eclipse => "TUTULMA",
            Chapter::Aurora => "AURORA",
        },
        PowerName(p) => match p {
            Power::Wide => "GENİŞ",
            Power::Slow => "YAVAŞ",
            Power::Multi => "ÇOKLU TOP",
            Power::Anchor => "ÇAPA",
            Power::Phase => "FAZ",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Devam et"),
        UnlockHint => Some("Kilitli"),
        RetrySector => Some("Tekrar"),
        MainMenu => Some("Menü"),
        NewJourney => Some("Yeni"),
        SectorSelect => Some("Sektörler"),
        NextSector => Some("Sonraki"),
        BackToSectors => Some("Sektörler"),
        Settings => Some("Ayarlar"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Devam"),
        PlaySector => Some("{0}. sektör"),
        ActionServe => Some("Servis"),
        ActionRelease => Some("Bırak"),
        ActionSelect => Some("Seç"),
        ActionBack => Some("Geri"),
        ActionAdjust => Some("Ayarla"),
        SettingEffects => Some("Efektler"),
        SettingContrast => Some("Kontrast"),
        LookStandard => Some("Normal"),
        EffectsReduced => Some("Az"),
        ContrastHigh => Some("Yüksek"),
        StatBest => Some("REKOR"),
        StatMedals => Some("MADALYALAR"),
        SectorsHeading => Some("Sektörler"),
        SaveFailed => Some("Kaydedilmedi"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Boşluk"),
        HelpResume => Some("Oyuna dön"),
        HelpRetry => Some("Kontrol noktasından"),
        HelpMainMenu => Some("Kaydedildi"),
        HelpSectors => Some("Antrenman"),
        HelpNewJourney => Some("Sektör 01’den"),
        HelpSettings => Some("Ses, ekran"),
        SettingSound => Some("Ses"),
        SettingVolume => Some("Ses düzeyi"),
        SettingDisplay => Some("Ekran"),
        SettingLanguage => Some("Dil"),
        DisplayWindow => Some("Pencere"),
        Fullscreen => Some("Tam"),
        LanguageSystem => Some("Sistem"),
        ExtraLife => Some("+1 can"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("SEKTÖR {1}"),
        JourneyComplete => Some("Tamamlandı"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "İlk Işık",
    "Sürüklenme",
    "Ufuk",
    "Parıltı",
    "Tarlakuşu",
    "Fenerler",
    "Gelgit",
    "Gün Doğumu",
    "Uydular",
    "Çiğ Noktası",
    "Diyafram",
    "Manastır",
    "Kilit Taşı",
    "Güneş Saati",
    "İğne Deliği",
    "Rüzgârgülü",
    "Hava Akımı",
    "Filaman",
    "Meridyen",
    "Çağlayan",
    "Geçiş",
    "Keskin Viraj",
    "Gündönümü",
    "Rezonans",
    "Prizma",
    "Petek",
    "Deniz Köpüğü",
    "Dip Akıntısı",
    "Hasat",
    "Kaleydoskop",
    "Duvar Halısı",
    "Uzun Gölgeler",
    "Son Işıltı",
    "Koza",
    "Jeod",
    "Paralaks",
    "Hisar",
    "Nautilus",
    "Akşam Ayini",
    "Süpernova",
    "Ay Doğuşu",
    "Akşam Loşluğu",
    "Lamba Işığı",
    "Ateşböcekleri",
    "Deniz Feneri",
    "Noktürn",
    "Derin Alan",
    "Takımyıldız",
    "Yarıgölge",
    "Metronom",
    "Korona",
    "Sizijî",
    "Pulsar",
    "Deklanşör",
    "Umbra",
    "Tam Tutulma",
    "Güneş Rüzgârı",
    "Kuzey Işıkları",
    "Şeritler",
    "Kutup Gecesi",
    "Katedral",
    "Titrek Işık",
    "Tekillik",
    "Eve Dönüş",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "İlk Işık",
    "Sürükle",
    "Ufuk",
    "Parıltı",
    "Tarlakuşu",
    "Fenerler",
    "Gelgit",
    "Gün",
    "Uydular",
    "Çiğ",
    "Diyafram",
    "Manastır",
    "Kilit",
    "Saat",
    "Delik",
    "Rüzgârgülü",
    "Hava Akımı",
    "Filaman",
    "Meridyen",
    "Çağlayan",
    "Geçiş",
    "Viraj",
    "Gündönümü",
    "Rezonans",
    "Prizma",
    "Petek",
    "Köpük",
    "Akıntı",
    "Hasat",
    "Kaleydo",
    "Halı",
    "Gölgeler",
    "Son Işıltı",
    "Koza",
    "Jeod",
    "Paralaks",
    "Hisar",
    "Nautilus",
    "Ayin",
    "Süpernova",
    "Ay Doğuşu",
    "Loşluk",
    "Lamba",
    "Böcekler",
    "Fener",
    "Noktürn",
    "Derinlik",
    "Yıldızlar",
    "Yarıgölge",
    "Metronom",
    "Korona",
    "Sizijî",
    "Pulsar",
    "Deklanşör",
    "Umbra",
    "Tam",
    "Rüzgâr",
    "Kuzey",
    "Şeritler",
    "Kutup Gecesi",
    "Katedral",
    "Titrek",
    "Tekillik",
    "Eve Dönüş",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Geniş: düşen kapsülü yakala",
    "{icon:slow} Yavaş: yakala, top sakinleşsin",
    "Yönlendir: raketin kenarları topu geniş açıyla yollar",
    "Yalnız kıvılcımlar: her birinin peşine düş",
    "Topu açık kanatlardan yukarı yolla",
    "Her feneri aşağıdan temizle",
    "Dalgaya bin: yan duvarlardan sektir",
    "Güneşi aşağıdan oy, sıra sıra",
    "{icon:anchor} Çapa: topu yakala, nişan al, sonra bırak",
    "Zırhlı tuğlalar iki vuruşa dayanır: kenarlara dikkat",
    "{icon:anchor} Duvardaki boşluktan nişan al",
    "Tek bir kapı: topu avluya gönder",
    "Kilit taşını devir, kemer açılsın",
    "Açıları oku: her gölge bir atış",
    "{icon:anchor} Tek bir dar delik: tut, nişan al, bırak",
    "Her yön kalbe çıkar",
    "Kehribar çekirdekler: her patlama dört komşusuna ulaşır",
    "Filamana herhangi bir yerden dokun: iki yöne de yanar",
    "Alanı meridyen boyunca böl",
    "Çağlayanı iki uçtan birinden başlat",
    "İki röle hattı arasından bir yol aç",
    "Üç röle hattı: her biri için tek temiz atış",
    "Halka bütünüyle yanar: kenarına giden bir yol bul",
    "Komşu çekirdekler tepkimeyi taşır",
    "{icon:multi} Çoklu top: üç top, tek açıklık",
    "Her hücrede bir çekirdek: hepsini kır",
    "Her yerde köpük: üç topu serbest bırak",
    "Zırhın ardındaki ceplere gir",
    "Dolu alan: {icon:multi} Çoklu top hızla temizler",
    "Her yerde aynalar: bir tarafı kır, sonra ikizini",
    "Bir ipi çek, dokuma çözülsün",
    "Zemini kır ve uzun fitili tutuştur",
    "{icon:phase} Faz: sekmeden üç tuğla teması",
    "{icon:phase} Faz kabuğun içinden çekirdeğe sızar",
    "Bir jeodu kır, kristalleri aydınlansın",
    "Kabuğu del, sonra iç rotayı ateşle",
    "Kapıdan gir ya da {icon:phase} Faz ile duvarın içinden",
    "Spiralle içeri: dış sarım önce yanar",
    "Üç çan: her birini aşağıdan çal",
    "Diğer toplar uçarken dönen bir topu yakala",
    "Açık merkezin çevresinde röleyi izle",
    "Işık çekiliyor: alanı fırsat varken öğren",
    "Karanlıkta topun ve raketin ışığı taşır",
    "Ateşböcekleri: çekirdekler karanlıkta bile parlar",
    "Raketin ışığını kıyıda gezdir",
    "Daha çok top, daha çok ışık: {icon:multi} Çoklu top",
    "Derin alan: her sönük nokta bir tuğla",
    "Yıldızları birleştir: parlak olanlar çekirdek",
    "Kapılar ritimle solar: boşluğu bekle",
    "Tik, tak: kapılar zamanı tutar",
    "Korona ritimle açılır: içeriye vur",
    "Hayalet kapı patlamayı savuşturur: kıvılcımı zamanla",
    "Bir pulsar: hızlı vuruşlar, hızlı eller",
    "Deklanşör bir anlığına açılır: hazır ol",
    "Yarısı gölgede: kapılı taraf ritmi tutar",
    "Ay katıyken güneşi tutuştur",
    "Rüzgâr tek yöne eser: onunla çekirdeklere süzül",
    "Işık perdeleri: {icon:multi} Çoklu top ile süpür",
    "Her şerit bir kapıya bağlı: iki yarısını da kes",
    "Uzun gece: taşıdığın ışığa göre nişan al",
    "Kapılardan gir, gül pencereye çık",
    "Hepsi bir arada: çekirdeklere dikkat et",
    "Kapılar katılaşırken halkaya vur",
    "Son bir yörünge: her açıklığı değerlendir",
];
