//! Ukrainian. Formal *ви*, as Ukrainian game UI usually addresses players;
//! hints read "keys — action". The apostrophe is U+2019.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Розбий космос",
        ContinueJourney => "Продовжити подорож",
        NewJourney => "Нова подорож",
        SectorSelect => "Вибір сектора",
        ContinueDetail => "{0} · {1}",
        StatMedals => "МЕДАЛІ",
        StatBest => "РЕКОРД",
        ActionServe => "Подача",
        ActionRelease => "Відпустити",
        ActionSelect => "Вибрати",
        ActionResume => "Продовжити",
        ActionBack => "Назад",
        Fullscreen => "Повний екран",
        SectorsHeading => "Сектори",
        PracticeNote => "Тренування не впливають на вашу подорож",
        MedalClear => "ПРОЙДЕНО",
        MedalClean => "БЕЗ ВТРАТ",
        MedalSwift => "ШВИДКО",
        PlaySector => "Грати: сектор {0}",
        UnlockHint => "Пройдіть сектор {0}, щоб відкрити",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · СЕКТОР {1}",
        Paused => "Пауза",
        RetrySector => "Сектор знову",
        MainMenu => "Головне меню",
        JourneyComplete => "Подорож завершено",
        OneMoreOrbit => "Ще одна орбіта?",
        StatPoints => "ОЧКИ",
        SectorClear => "Сектор пройдено",
        StatTime => "ЧАС",
        StatBonus => "БОНУС",
        StatChain => "СЕРІЯ",
        ExtraLife => "Розділ завершено · +1 життя",
        NextSector => "Наступний сектор",
        BackToSectors => "До секторів",
        SaveFailed => "Не вдалося зберегти прогрес",
        PerfTitle => "Продуктивність / ЦП",
        HelpResume => "Продовжте з того ж місця",
        HelpRetry => "Почати знову з контрольної точки сектора",
        HelpMainMenu => "Вашу подорож збережено",
        HelpSectors => "Тренуйтеся в будь-якому відкритому секторі",
        HelpNewJourney => "Знову із сектора 01 · медалі залишаться",
        Settings => "Налаштування",
        HelpSettings => "Звук, екран, мова",
        SettingSound => "Звук",
        SettingVolume => "Гучність",
        SettingDisplay => "Екран",
        SettingLanguage => "Мова",
        DisplayWindow => "Вікно",
        LanguageSystem => "Системна",
        ActionAdjust => "Змінити",
        KeySpace => "Пробіл",
        KeyEsc => "Esc",
        SectorsOf => "{0} з {1} секторів",
        TargetBest => "{0} · рекорд {1}",
        LifeGained => "+1 життя",
        PresenceMenus => "У меню",
        PresenceJourney => "Сектор {0} · {1}",
        PresencePractice => "Тренування: сектор {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "СВІТАНОК",
            Chapter::BlueHour => "СИНЯ ГОДИНА",
            Chapter::Afterlight => "СУТІНКИ",
        },
        PowerName(p) => match p {
            Power::Wide => "ШИРИНА",
            Power::Slow => "СПОВІЛЬНЕННЯ",
            Power::Multi => "МУЛЬТИМ’ЯЧ",
            Power::Anchor => "ЯКІР",
            Power::Phase => "ФАЗА",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Продовжити"),
        UnlockHint => Some("Закрито"),
        RetrySector => Some("Знову"),
        MainMenu => Some("Меню"),
        NewJourney => Some("Нова"),
        SectorSelect => Some("Сектори"),
        NextSector => Some("Далі"),
        BackToSectors => Some("Сектори"),
        Settings => Some("Опції"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Далі"),
        PlaySector => Some("Грати {0}"),
        ActionServe => Some("Подача"),
        ActionRelease => Some("Пуск"),
        ActionSelect => Some("Вибрати"),
        ActionBack => Some("Назад"),
        ActionAdjust => Some("Змінити"),
        StatBest => Some("РЕКОРД"),
        StatMedals => Some("МЕДАЛІ"),
        SectorsHeading => Some("Сектори"),
        SaveFailed => Some("Не збережено"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Пробіл"),
        HelpResume => Some("Назад у гру"),
        HelpRetry => Some("З контрольної точки"),
        HelpMainMenu => Some("Збережено"),
        HelpSectors => Some("Тренування"),
        HelpNewJourney => Some("Із сектора 01"),
        HelpSettings => Some("Звук, екран"),
        SettingSound => Some("Звук"),
        SettingVolume => Some("Гучність"),
        SettingDisplay => Some("Екран"),
        SettingLanguage => Some("Мова"),
        DisplayWindow => Some("Вікно"),
        Fullscreen => Some("Повний"),
        LanguageSystem => Some("Система"),
        ExtraLife => Some("+1 життя"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("СЕКТОР {1}"),
        JourneyComplete => Some("Завершено"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Перше світло",
    "Супутники",
    "Попутний потік",
    "Резонанс",
    "Призма",
    "Перехід",
    "Підводна течія",
    "Схід місяця",
    "Післясвітіння",
    "Паралакс",
    "Наднова",
    "Повернення",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Перше світло",
    "Супутники",
    "Потік",
    "Резонанс",
    "Призма",
    "Перехід",
    "Течія",
    "Місяць",
    "Сяйво",
    "Паралакс",
    "Наднова",
    "Повернення",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Ширина і {icon:slow} Сповільнення: ловіть капсули, що падають",
    "{icon:anchor} Якір: спіймайте м’яч, прицільтеся й відпустіть",
    "Бурштинові ядра: кожен вибух зачіпає чотирьох сусідів",
    "Сусідні ядра передають реакцію далі",
    "{icon:multi} Мультим’яч: три м’ячі, один прохід",
    "Відкрийте шлях крізь дві лінії реле",
    "Пробийтеся в кишені за бронею",
    "Слідуйте за реле навколо відкритого центру",
    "{icon:phase} Фаза: три удари по цеглі без відскоку",
    "Пробийте оболонку, потім підпаліть внутрішній шлях",
    "Спіймайте м’яч, поки інші летять",
    "Остання орбіта: хай кожен прохід важить",
];
