//! Vietnamese. Neutral *bạn*; labels in capitals with their tone marks, all
//! precomposed (NFC).
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Phá tan vũ trụ",
        ContinueJourney => "Tiếp tục hành trình",
        NewJourney => "Hành trình mới",
        SectorSelect => "Chọn khu vực",
        ContinueDetail => "{0} · {1}",
        StatMedals => "HUY CHƯƠNG",
        StatBest => "KỶ LỤC",
        ActionServe => "Phát bóng",
        ActionRelease => "Thả",
        ActionSelect => "Chọn",
        ActionResume => "Tiếp tục",
        ActionBack => "Quay lại",
        Fullscreen => "Toàn màn hình",
        SectorsHeading => "Khu vực",
        PracticeNote => "Chơi luyện tập không ảnh hưởng hành trình của bạn",
        MedalClear => "HOÀN THÀNH",
        MedalClean => "HOÀN HẢO",
        MedalSwift => "THẦN TỐC",
        PlaySector => "Chơi khu vực {0}",
        UnlockHint => "Hoàn thành khu vực {0} để mở khóa",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · KHU VỰC {1}",
        Paused => "Tạm dừng",
        RetrySector => "Chơi lại khu vực",
        MainMenu => "Menu chính",
        JourneyComplete => "Hoàn thành hành trình",
        OneMoreOrbit => "Thêm một vòng nữa?",
        StatPoints => "ĐIỂM",
        SectorClear => "Đã hoàn thành khu vực",
        StatTime => "THỜI GIAN",
        StatBonus => "THƯỞNG",
        StatChain => "CHUỖI",
        ExtraLife => "Hoàn thành chương · +1 mạng",
        NextSector => "Khu vực tiếp theo",
        BackToSectors => "Về danh sách khu vực",
        SaveFailed => "Không thể lưu tiến trình",
        PerfTitle => "Hiệu năng / CPU",
        HelpResume => "Tiếp tục từ chỗ bạn dừng",
        HelpRetry => "Chơi lại từ điểm lưu của khu vực",
        HelpMainMenu => "Hành trình đã được lưu",
        HelpSectors => "Luyện tập ở khu vực đã mở",
        HelpNewJourney => "Lại từ khu vực 01 · giữ huy chương",
        Settings => "Cài đặt",
        HelpSettings => "Âm thanh, hiển thị, ngôn ngữ",
        SettingSound => "Âm thanh",
        SettingVolume => "Âm lượng",
        SettingDisplay => "Hiển thị",
        SettingLanguage => "Ngôn ngữ",
        DisplayWindow => "Cửa sổ",
        LanguageSystem => "Hệ thống",
        ActionAdjust => "Điều chỉnh",
        SettingEffects => "Hiệu ứng",
        SettingContrast => "Độ tương phản",
        LookStandard => "Tiêu chuẩn",
        EffectsReduced => "Giảm bớt",
        ContrastHigh => "Cao",
        KeySpace => "Cách",
        KeyEsc => "Esc",
        SectorsOf => "{0}/{1} khu vực",
        TargetBest => "{0} · kỷ lục {1}",
        LifeGained => "+1 mạng",
        PresenceMenus => "Đang ở menu",
        PresenceJourney => "Khu vực {0} · {1}",
        PresencePractice => "Đang luyện tập khu vực {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "BÌNH MINH",
            Chapter::Morning => "BUỔI SÁNG",
            Chapter::Zenith => "THIÊN ĐỈNH",
            Chapter::GoldenHour => "GIỜ VÀNG",
            Chapter::Afterlight => "HOÀNG HÔN",
            Chapter::BlueHour => "GIỜ XANH",
            Chapter::Eclipse => "NHẬT THỰC",
            Chapter::Aurora => "CỰC QUANG",
        },
        PowerName(p) => match p {
            Power::Wide => "RỘNG",
            Power::Slow => "CHẬM",
            Power::Multi => "ĐA BÓNG",
            Power::Anchor => "NEO",
            Power::Phase => "PHA",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Tiếp tục"),
        UnlockHint => Some("Đã khóa"),
        RetrySector => Some("Chơi lại"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Mới"),
        SectorSelect => Some("Khu vực"),
        NextSector => Some("Tiếp"),
        BackToSectors => Some("Khu vực"),
        Settings => Some("Cài đặt"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Tiếp tục"),
        PlaySector => Some("Chơi {0}"),
        ActionServe => Some("Phát"),
        ActionRelease => Some("Thả"),
        ActionSelect => Some("Chọn"),
        ActionBack => Some("Quay lại"),
        ActionAdjust => Some("Chỉnh"),
        SettingEffects => Some("Hiệu ứng"),
        SettingContrast => Some("Tương phản"),
        LookStandard => Some("Chuẩn"),
        EffectsReduced => Some("Ít"),
        ContrastHigh => Some("Cao"),
        StatBest => Some("KỶ LỤC"),
        StatMedals => Some("HUY HIỆU"),
        SectorsHeading => Some("Khu vực"),
        SaveFailed => Some("Chưa lưu"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Cách"),
        HelpResume => Some("Quay lại chơi"),
        HelpRetry => Some("Từ điểm lưu"),
        HelpMainMenu => Some("Đã lưu"),
        HelpSectors => Some("Luyện tập"),
        HelpNewJourney => Some("Từ khu vực 01"),
        HelpSettings => Some("Âm thanh, hiển thị"),
        SettingSound => Some("Âm thanh"),
        SettingVolume => Some("Âm lượng"),
        SettingDisplay => Some("Hiển thị"),
        SettingLanguage => Some("Ngôn ngữ"),
        DisplayWindow => Some("Cửa sổ"),
        Fullscreen => Some("Toàn màn"),
        LanguageSystem => Some("Hệ thống"),
        ExtraLife => Some("+1 mạng"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("KHU VỰC {1}"),
        JourneyComplete => Some("Hoàn thành"),
        SectorClear => Some("Hoàn thành"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Tia sáng đầu",
    "Trôi dạt",
    "Chân trời",
    "Le lói",
    "Chim sơn ca",
    "Đèn lồng",
    "Thủy triều",
    "Mặt trời mọc",
    "Vệ tinh",
    "Điểm sương",
    "Khẩu độ",
    "Tu viện",
    "Đá đỉnh vòm",
    "Đồng hồ mặt trời",
    "Lỗ kim",
    "Hoa gió",
    "Luồng gió",
    "Dây tóc",
    "Kinh tuyến",
    "Thác",
    "Chuyển cảnh",
    "Ngoằn ngoèo",
    "Chí điểm",
    "Cộng hưởng",
    "Lăng kính",
    "Tổ ong",
    "Bọt sóng",
    "Dòng ngầm",
    "Mùa gặt",
    "Kính vạn hoa",
    "Thảm thêu",
    "Bóng dài",
    "Ánh tà",
    "Nhộng",
    "Geode",
    "Thị sai",
    "Thành trì",
    "Ốc anh vũ",
    "Kinh chiều",
    "Siêu tân tinh",
    "Trăng lên",
    "Chập choạng",
    "Ánh đèn",
    "Đom đóm",
    "Hải đăng",
    "Dạ khúc",
    "Trường sâu",
    "Chòm sao",
    "Bán ảnh",
    "Máy nhịp",
    "Nhật hoa",
    "Syzygy",
    "Sao xung",
    "Cửa chớp",
    "Bóng tối",
    "Toàn phần",
    "Gió mặt trời",
    "Cực quang bắc",
    "Dải lụa",
    "Đêm vùng cực",
    "Thánh đường",
    "Lấp lánh",
    "Điểm kỳ dị",
    "Trở về",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Tia sáng đầu",
    "Trôi",
    "Chân trời",
    "Le lói",
    "Chim sơn ca",
    "Đèn lồng",
    "Thủy triều",
    "Mặt trời",
    "Vệ tinh",
    "Sương",
    "Khẩu độ",
    "Tu viện",
    "Đá đỉnh",
    "Đồng hồ",
    "Lỗ kim",
    "Hoa gió",
    "Luồng gió",
    "Dây tóc",
    "Kinh tuyến",
    "Thác",
    "Chuyển cảnh",
    "Ngoằn ngoèo",
    "Chí điểm",
    "Cộng hưởng",
    "Lăng kính",
    "Tổ ong",
    "Bọt sóng",
    "Dòng ngầm",
    "Mùa gặt",
    "Vạn hoa",
    "Thảm thêu",
    "Bóng dài",
    "Ánh tà",
    "Nhộng",
    "Geode",
    "Thị sai",
    "Thành trì",
    "Anh vũ",
    "Kinh chiều",
    "Siêu tân tinh",
    "Trăng lên",
    "Chập choạng",
    "Ánh đèn",
    "Đom đóm",
    "Hải đăng",
    "Dạ khúc",
    "Trường sâu",
    "Chòm sao",
    "Bán ảnh",
    "Máy nhịp",
    "Nhật hoa",
    "Syzygy",
    "Sao xung",
    "Chớp",
    "Bóng tối",
    "Toàn phần",
    "Gió",
    "Cực quang",
    "Dải lụa",
    "Đêm cực",
    "Thánh đường",
    "Lấp lánh",
    "Điểm kỳ dị",
    "Trở về",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Rộng: bắt viên nang đang rơi",
    "{icon:slow} Chậm: bắt nó và quả bóng sẽ chậm lại",
    "Điều hướng: hai mép thanh đỡ đẩy bóng ra rộng",
    "Những tia lửa lẻ: săn từng tia một",
    "Đưa bóng lên qua hai cánh mở",
    "Dọn từng đèn lồng từ bên dưới",
    "Cưỡi con sóng: đánh dội từ tường hai bên",
    "Đẽo mặt trời từ bên dưới, từng hàng một",
    "{icon:anchor} Neo: bắt bóng, ngắm, rồi thả ra",
    "Gạch bọc giáp chịu hai cú đánh: để ý các mép",
    "{icon:anchor} Ngắm qua khe hở trên tường",
    "Chỉ một cửa: đưa bóng vào sân trong",
    "Phá đá đỉnh vòm và mái vòm sẽ mở ra",
    "Đọc các góc: mỗi bóng đổ là một cú đánh",
    "{icon:anchor} Một lỗ kim hẹp: giữ, ngắm, thả",
    "Mọi hướng la bàn đều dẫn về trung tâm",
    "Lõi hổ phách: mỗi vụ nổ lan tới bốn ô lân cận",
    "Chạm vào dây tóc ở bất kỳ đâu: nó cháy về hai phía",
    "Chia sân theo đường kinh tuyến",
    "Khởi động thác từ một trong hai đầu",
    "Mở đường xuyên qua hai tuyến tiếp sóng",
    "Ba tuyến tiếp sóng: mỗi tuyến một cú đánh gọn",
    "Vòng cháy trọn vẹn: tìm đường tới mép của nó",
    "Các lõi kề nhau truyền tiếp phản ứng",
    "{icon:multi} Đa bóng: ba quả bóng, một lối mở",
    "Mỗi ô một lõi: hãy phá chúng ra",
    "Bọt sóng khắp nơi: thả ba quả bóng",
    "Phá vào các hốc phía sau lớp giáp",
    "Sân đầy: {icon:multi} Đa bóng dọn rất nhanh",
    "Gương khắp nơi: phá một bên, rồi bên song sinh",
    "Kéo một sợi chỉ và tấm thêu sẽ bung ra",
    "Phá xuyên sàn và châm ngòi dài",
    "{icon:phase} Pha: ba lần chạm gạch mà không nảy",
    "{icon:phase} Pha lướt xuyên lớp vỏ tới tận lõi",
    "Bẻ một hốc tinh thể và các tinh thể sẽ sáng lên",
    "Xuyên thủng lớp vỏ, rồi kích nổ tuyến bên trong",
    "Vào qua cổng, hoặc xuyên tường bằng {icon:phase} Pha",
    "Xoắn vào trong: vòng ngoài cùng sáng trước",
    "Ba chiếc chuông: gõ từng chiếc từ bên dưới",
    "Bắt bóng quay về trong khi các bóng khác vẫn bay",
    "Đi theo tuyến tiếp sóng quanh vùng trung tâm trống",
    "Ánh sáng đang tắt: hãy học sân khi còn kịp",
    "Trong bóng tối, bóng và thanh đỡ mang theo ánh sáng",
    "Đom đóm: các lõi vẫn phát sáng trong bóng tối",
    "Quét ánh sáng của thanh đỡ qua bờ biển",
    "Nhiều bóng hơn, nhiều sáng hơn: {icon:multi} Đa bóng",
    "Trường sâu: mỗi đốm mờ là một viên gạch",
    "Nối các vì sao: những ngôi sáng là lõi",
    "Cổng mờ dần theo nhịp: chờ khoảng trống",
    "Tích tắc: các cổng giữ nhịp",
    "Nhật hoa mở theo nhịp: đánh vào trong",
    "Cổng ma gạt vụ nổ đi: canh đúng lúc tia lửa",
    "Một sao xung: nhịp nhanh, tay nhanh",
    "Cửa chớp chỉ mở trong chốc lát: hãy sẵn sàng",
    "Nửa trong bóng tối: phía có cổng giữ nhịp",
    "Đốt mặt trời khi mặt trăng còn đặc",
    "Gió chỉ thổi một hướng: cưỡi nó tới các lõi",
    "Những tấm màn sáng: quét chúng bằng {icon:multi} Đa bóng",
    "Mỗi dải lụa buộc vào một cổng: cắt cả hai nửa",
    "Đêm dài: ngắm theo ánh sáng bạn mang",
    "Vào qua các cửa, lên cửa sổ hoa hồng",
    "Mọi thứ cùng lúc: để ý các lõi",
    "Đánh vào vòng khi các cổng đặc lại",
    "Vòng quỹ đạo cuối: tận dụng mọi lối mở",
];
