//! Vietnamese. Neutral *bạn*; labels in capitals with their tone marks, all
//! precomposed (NFC).
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "Phá tan vũ trụ",
        ContinueJourney => "Tiếp tục hành trình",
        NewJourney => "Hành trình mới",
        SectorSelect => "Chọn khu vực",
        ContinueDetail => "{0} · {1}",
        StatMedals => "HUY CHƯƠNG",
        StatBest => "KỶ LỤC",
        ActionServe => "Phát bóng",
        ActionRelease => "Thả",
        ActionSelect => "Chọn",
        ActionResume => "Tiếp tục",
        ActionBack => "Quay lại",
        Fullscreen => "Toàn màn hình",
        SectorsHeading => "Khu vực",
        PracticeNote => "Chơi luyện tập không ảnh hưởng hành trình của bạn",
        MedalClear => "HOÀN THÀNH",
        MedalClean => "HOÀN HẢO",
        MedalSwift => "THẦN TỐC",
        PlaySector => "Chơi khu vực {0}",
        UnlockHint => "Hoàn thành khu vực {0} để mở khóa",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · KHU VỰC {1}",
        Paused => "Tạm dừng",
        RetrySector => "Chơi lại khu vực",
        MainMenu => "Menu chính",
        JourneyComplete => "Hoàn thành hành trình",
        OneMoreOrbit => "Thêm một vòng nữa?",
        StatPoints => "ĐIỂM",
        SectorClear => "Đã hoàn thành khu vực",
        StatTime => "THỜI GIAN",
        StatBonus => "THƯỞNG",
        StatChain => "CHUỖI",
        ExtraLife => "Hoàn thành chương · +1 mạng",
        NextSector => "Khu vực tiếp theo",
        BackToSectors => "Về danh sách khu vực",
        SaveFailed => "Không thể lưu tiến trình",
        PerfTitle => "Hiệu năng / CPU",
        HelpResume => "Tiếp tục từ chỗ bạn dừng",
        HelpRetry => "Chơi lại từ điểm lưu của khu vực",
        HelpMainMenu => "Hành trình đã được lưu",
        HelpSectors => "Luyện tập ở khu vực đã mở",
        HelpNewJourney => "Lại từ khu vực 01 · giữ huy chương",
        Settings => "Cài đặt",
        HelpSettings => "Âm thanh, hiển thị, ngôn ngữ",
        SettingSound => "Âm thanh",
        SettingVolume => "Âm lượng",
        SettingDisplay => "Hiển thị",
        SettingLanguage => "Ngôn ngữ",
        DisplayWindow => "Cửa sổ",
        LanguageSystem => "Hệ thống",
        ActionAdjust => "Điều chỉnh",
        KeySpace => "Cách",
        KeyEsc => "Esc",
        SectorsOf => "{0}/{1} khu vực",
        TargetBest => "{0} · kỷ lục {1}",
        LifeGained => "+1 mạng",
        PresenceMenus => "Đang ở menu",
        PresenceJourney => "Khu vực {0} · {1}",
        PresencePractice => "Đang luyện tập khu vực {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "BÌNH MINH",
            Chapter::BlueHour => "GIỜ XANH",
            Chapter::Afterlight => "HOÀNG HÔN",
        },
        PowerName(p) => match p {
            Power::Wide => "RỘNG",
            Power::Slow => "CHẬM",
            Power::Multi => "ĐA BÓNG",
            Power::Anchor => "NEO",
            Power::Phase => "PHA",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("Tiếp tục"),
        UnlockHint => Some("Đã khóa"),
        RetrySector => Some("Chơi lại"),
        MainMenu => Some("Menu"),
        NewJourney => Some("Mới"),
        SectorSelect => Some("Khu vực"),
        NextSector => Some("Tiếp"),
        BackToSectors => Some("Khu vực"),
        Settings => Some("Cài đặt"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("Tiếp tục"),
        PlaySector => Some("Chơi {0}"),
        ActionServe => Some("Phát"),
        ActionRelease => Some("Thả"),
        ActionSelect => Some("Chọn"),
        ActionBack => Some("Quay lại"),
        ActionAdjust => Some("Chỉnh"),
        StatBest => Some("KỶ LỤC"),
        StatMedals => Some("HUY HIỆU"),
        SectorsHeading => Some("Khu vực"),
        SaveFailed => Some("Chưa lưu"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("Cách"),
        HelpResume => Some("Quay lại chơi"),
        HelpRetry => Some("Từ điểm lưu"),
        HelpMainMenu => Some("Đã lưu"),
        HelpSectors => Some("Luyện tập"),
        HelpNewJourney => Some("Từ khu vực 01"),
        HelpSettings => Some("Âm thanh, hiển thị"),
        SettingSound => Some("Âm thanh"),
        SettingVolume => Some("Âm lượng"),
        SettingDisplay => Some("Hiển thị"),
        SettingLanguage => Some("Ngôn ngữ"),
        DisplayWindow => Some("Cửa sổ"),
        Fullscreen => Some("Toàn màn"),
        LanguageSystem => Some("Hệ thống"),
        ExtraLife => Some("+1 mạng"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("KHU VỰC {1}"),
        JourneyComplete => Some("Hoàn thành"),
        SectorClear => Some("Hoàn thành"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "Tia sáng đầu",
    "Vệ tinh",
    "Luồng gió",
    "Cộng hưởng",
    "Lăng kính",
    "Chuyển cảnh",
    "Dòng ngầm",
    "Trăng lên",
    "Ánh tà",
    "Thị sai",
    "Siêu tân tinh",
    "Trở về",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "Tia sáng đầu",
    "Vệ tinh",
    "Luồng gió",
    "Cộng hưởng",
    "Lăng kính",
    "Chuyển cảnh",
    "Dòng ngầm",
    "Trăng lên",
    "Ánh tà",
    "Thị sai",
    "Siêu tân tinh",
    "Trở về",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} Rộng và {icon:slow} Chậm: bắt các viên nang rơi xuống",
    "{icon:anchor} Neo: bắt bóng, ngắm, rồi thả ra",
    "Lõi hổ phách: mỗi vụ nổ lan tới bốn ô lân cận",
    "Các lõi kề nhau truyền tiếp phản ứng",
    "{icon:multi} Đa bóng: ba quả bóng, một lối mở",
    "Mở đường xuyên qua hai tuyến tiếp sóng",
    "Phá vào các hốc phía sau lớp giáp",
    "Đi theo tuyến tiếp sóng quanh vùng trung tâm trống",
    "{icon:phase} Pha: ba lần chạm gạch mà không nảy",
    "Xuyên thủng lớp vỏ, rồi kích nổ tuyến bên trong",
    "Bắt bóng quay về trong khi các bóng khác vẫn bay",
    "Vòng quỹ đạo cuối: tận dụng mọi lối mở",
];
