//! Simplified Chinese. Full-width punctuation (：、？); a space separates
//! Chinese from Latin letters and numbers.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "击碎宇宙",
        ContinueJourney => "继续旅程",
        NewJourney => "新的旅程",
        SectorSelect => "选择星区",
        ContinueDetail => "{0} · {1}",
        StatMedals => "奖章",
        StatBest => "最高分",
        ActionServe => "发球",
        ActionRelease => "释放",
        ActionSelect => "选择",
        ActionResume => "继续",
        ActionBack => "返回",
        Fullscreen => "全屏",
        SectorsHeading => "星区",
        PracticeNote => "练习不会影响你的旅程",
        MedalClear => "通关",
        MedalClean => "无损",
        MedalSwift => "神速",
        PlaySector => "开始星区 {0}",
        UnlockHint => "完成星区 {0} 即可解锁",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · 星区 {1}",
        Paused => "已暂停",
        RetrySector => "重试本星区",
        MainMenu => "主菜单",
        JourneyComplete => "旅程完成",
        OneMoreOrbit => "再来一圈？",
        StatPoints => "得分",
        SectorClear => "星区完成",
        StatTime => "时间",
        StatBonus => "奖励",
        StatChain => "连击",
        ExtraLife => "篇章完成 · +1 生命",
        NextSector => "下一星区",
        BackToSectors => "返回星区",
        SaveFailed => "无法保存进度",
        PerfTitle => "性能 / CPU",
        HelpResume => "从暂停处继续",
        HelpRetry => "从本星区检查点重新开始",
        HelpMainMenu => "旅程已保存",
        HelpSectors => "练习任一已开放的星区",
        HelpNewJourney => "从星区 01 重新开始 · 奖章保留",
        Settings => "设置",
        HelpSettings => "声音、显示、语言",
        SettingSound => "声音",
        SettingVolume => "音量",
        SettingDisplay => "显示",
        SettingLanguage => "语言",
        DisplayWindow => "窗口",
        LanguageSystem => "跟随系统",
        ActionAdjust => "调整",
        KeySpace => "空格",
        KeyEsc => "Esc",
        SectorsOf => "{0} / {1} 个星区",
        TargetBest => "{0} · 最佳 {1}",
        LifeGained => "+1 生命",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "破晓",
            Chapter::BlueHour => "蓝调时刻",
            Chapter::Afterlight => "暮光",
        },
        PowerName(p) => match p {
            Power::Wide => "加宽",
            Power::Slow => "减速",
            Power::Multi => "多球",
            Power::Anchor => "锚定",
            Power::Phase => "相位",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("继续"),
        UnlockHint => Some("未解锁"),
        RetrySector => Some("重试"),
        MainMenu => Some("菜单"),
        NewJourney => Some("新旅程"),
        SectorSelect => Some("星区"),
        NextSector => Some("下一个"),
        BackToSectors => Some("星区"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "晨光",
    "卫星",
    "滑流",
    "共振",
    "棱镜",
    "交错",
    "暗流",
    "月出",
    "余晖",
    "视差",
    "超新星",
    "归途",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} 加宽、{icon:slow} 减速：接住下落的胶囊",
    "{icon:anchor} 锚定：接住球，瞄准，然后释放",
    "琥珀核心：每次爆炸波及相邻四块",
    "相邻核心会传递连锁反应",
    "{icon:multi} 多球：三颗球，一个缺口",
    "在两条中继线之间打开通路",
    "攻入装甲后方的空腔",
    "沿着中继线绕过空旷的中心",
    "{icon:phase} 相位：连续三次穿透砖块，无需反弹",
    "击穿外壳，再点燃内部通路",
    "其他球仍在飞行时，接住一颗回球",
    "最后一圈：让每个缺口都有价值",
];
