//! Simplified Chinese. Full-width punctuation (：、？); a space separates
//! Chinese from Latin letters and numbers.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "击碎宇宙",
        ContinueJourney => "继续旅程",
        NewJourney => "新的旅程",
        SectorSelect => "选择星区",
        ContinueDetail => "{0} · {1}",
        StatMedals => "奖章",
        StatBest => "最高分",
        ActionServe => "发球",
        ActionRelease => "释放",
        ActionSelect => "选择",
        ActionResume => "继续",
        ActionBack => "返回",
        Fullscreen => "全屏",
        SectorsHeading => "星区",
        PracticeNote => "练习不会影响你的旅程",
        MedalClear => "通关",
        MedalClean => "无损",
        MedalSwift => "神速",
        PlaySector => "开始星区 {0}",
        UnlockHint => "完成星区 {0} 即可解锁",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · 星区 {1}",
        Paused => "已暂停",
        RetrySector => "重试本星区",
        MainMenu => "主菜单",
        JourneyComplete => "旅程完成",
        OneMoreOrbit => "再来一圈？",
        StatPoints => "得分",
        SectorClear => "星区完成",
        StatTime => "时间",
        StatBonus => "奖励",
        StatChain => "连击",
        ExtraLife => "篇章完成 · +1 生命",
        NextSector => "下一星区",
        BackToSectors => "返回星区",
        SaveFailed => "无法保存进度",
        PerfTitle => "性能 / CPU",
        HelpResume => "从暂停处继续",
        HelpRetry => "从本星区检查点重新开始",
        HelpMainMenu => "旅程已保存",
        HelpSectors => "练习任一已开放的星区",
        HelpNewJourney => "从星区 01 重新开始 · 奖章保留",
        Settings => "设置",
        HelpSettings => "声音、显示、语言",
        SettingSound => "声音",
        SettingVolume => "音量",
        SettingDisplay => "显示",
        SettingLanguage => "语言",
        DisplayWindow => "窗口",
        LanguageSystem => "跟随系统",
        ActionAdjust => "调整",
        SettingEffects => "特效",
        SettingContrast => "对比度",
        LookStandard => "标准",
        EffectsReduced => "减弱",
        ContrastHigh => "高",
        KeySpace => "空格",
        KeyEsc => "Esc",
        SectorsOf => "{0} / {1} 个星区",
        TargetBest => "{0} · 最佳 {1}",
        LifeGained => "+1 生命",
        PresenceMenus => "在菜单中",
        PresenceJourney => "星区 {0} · {1}",
        PresencePractice => "正在练习星区 {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "破晓",
            Chapter::Morning => "清晨",
            Chapter::Zenith => "天顶",
            Chapter::GoldenHour => "黄金时刻",
            Chapter::Afterlight => "暮光",
            Chapter::BlueHour => "蓝调时刻",
            Chapter::Eclipse => "日食",
            Chapter::Aurora => "极光",
        },
        PowerName(p) => match p {
            Power::Wide => "加宽",
            Power::Slow => "减速",
            Power::Multi => "多球",
            Power::Anchor => "锚定",
            Power::Phase => "相位",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("继续"),
        UnlockHint => Some("未解锁"),
        RetrySector => Some("重试"),
        MainMenu => Some("菜单"),
        NewJourney => Some("新旅程"),
        SectorSelect => Some("星区"),
        NextSector => Some("下一个"),
        BackToSectors => Some("星区"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("继续"),
        PlaySector => Some("开始 {0}"),
        Settings => Some("设置"),
        ActionServe => Some("发球"),
        ActionRelease => Some("释放"),
        ActionSelect => Some("选择"),
        ActionBack => Some("返回"),
        ActionAdjust => Some("调整"),
        StatBest => Some("最高"),
        StatMedals => Some("奖章"),
        SectorsHeading => Some("星区"),
        SaveFailed => Some("未保存"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("空格"),
        HelpResume => Some("返回游戏"),
        HelpRetry => Some("从检查点重来"),
        HelpMainMenu => Some("旅程已保存"),
        HelpSectors => Some("练习星区"),
        HelpNewJourney => Some("从星区 01 开始"),
        HelpSettings => Some("声音、显示"),
        SettingSound => Some("声音"),
        SettingVolume => Some("音量"),
        SettingDisplay => Some("显示"),
        SettingLanguage => Some("语言"),
        DisplayWindow => Some("窗口"),
        Fullscreen => Some("全屏"),
        LanguageSystem => Some("系统"),
        ExtraLife => Some("+1 生命"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("星区 {1}"),
        SettingEffects => Some("特效"),
        SettingContrast => Some("对比度"),
        LookStandard => Some("标准"),
        EffectsReduced => Some("减弱"),
        ContrastHigh => Some("高"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "晨光",
    "漂流",
    "地平线",
    "微光",
    "云雀",
    "灯笼",
    "潮水",
    "日出",
    "卫星",
    "露点",
    "光圈",
    "回廊",
    "拱心石",
    "日晷",
    "针孔",
    "风玫瑰",
    "滑流",
    "灯丝",
    "子午线",
    "叠瀑",
    "交错",
    "曲折",
    "至日",
    "共振",
    "棱镜",
    "蜂巢",
    "浪花",
    "暗流",
    "丰收",
    "万花筒",
    "挂毯",
    "长影",
    "余晖",
    "蛹",
    "晶洞",
    "视差",
    "堡垒",
    "鹦鹉螺",
    "晚祷",
    "超新星",
    "月出",
    "薄暮",
    "灯火",
    "萤火",
    "灯塔",
    "夜曲",
    "深空",
    "星座",
    "半影",
    "节拍器",
    "日冕",
    "朔望",
    "脉冲星",
    "快门",
    "本影",
    "全食",
    "太阳风",
    "北极光",
    "飘带",
    "极夜",
    "大教堂",
    "粼光",
    "奇点",
    "归途",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "晨光",
    "漂流",
    "地平线",
    "微光",
    "云雀",
    "灯笼",
    "潮水",
    "日出",
    "卫星",
    "露点",
    "光圈",
    "回廊",
    "拱心石",
    "日晷",
    "针孔",
    "风玫瑰",
    "滑流",
    "灯丝",
    "子午线",
    "叠瀑",
    "交错",
    "曲折",
    "至日",
    "共振",
    "棱镜",
    "蜂巢",
    "浪花",
    "暗流",
    "丰收",
    "万花筒",
    "挂毯",
    "长影",
    "余晖",
    "蛹",
    "晶洞",
    "视差",
    "堡垒",
    "鹦鹉螺",
    "晚祷",
    "超新星",
    "月出",
    "薄暮",
    "灯火",
    "萤火",
    "灯塔",
    "夜曲",
    "深空",
    "星座",
    "半影",
    "节拍器",
    "日冕",
    "朔望",
    "脉冲星",
    "快门",
    "本影",
    "全食",
    "太阳风",
    "北极光",
    "飘带",
    "极夜",
    "大教堂",
    "粼光",
    "奇点",
    "归途",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} 加宽：接住掉落的胶囊",
    "{icon:slow} 减速：接住它，球就会慢下来",
    "操控：挡板边缘会把球打向两侧",
    "零星火花：逐个追击",
    "把球沿敞开的两翼打上去",
    "从下方清除每盏灯笼",
    "顺势而行：借侧墙反弹",
    "从下方一排排凿掉太阳",
    "{icon:anchor} 锚定：接住球，瞄准，然后释放",
    "装甲砖块要打两下：留意边缘",
    "{icon:anchor} 瞄准墙上的缺口",
    "只有一道门：把球送进庭院",
    "打掉拱心石，拱门就开了",
    "看准角度：每道影子都是一次击球",
    "{icon:anchor} 一个窄小的针孔：按住，瞄准，释放",
    "每个方向都通向核心",
    "琥珀核心：每次爆炸波及相邻四块",
    "触碰灯丝任意位置：两端同时燃烧",
    "沿子午线把场地一分为二",
    "从任意一端引爆叠瀑",
    "在两条中继线之间打开通路",
    "三条中继线：各一次干净的击球",
    "圆环整体燃烧：找条路打到边缘",
    "相邻核心会传递连锁反应",
    "{icon:multi} 多球：三颗球，一个缺口",
    "每格一个核心：逐个击破",
    "浪花四溅：放出三颗球",
    "攻入装甲后方的空腔",
    "满场砖块：{icon:multi} 多球清得很快",
    "到处是镜子：先破一侧，再破它的孪生",
    "抽出一根线，织物便散开",
    "击穿地面，点燃长引线",
    "{icon:phase} 相位：连续三次穿透砖块，无需反弹",
    "{icon:phase} 相位：穿过外壳直达核心",
    "敲开晶洞，晶体随即亮起",
    "击穿外壳，再点燃内部通路",
    "从闸门进入，或用 {icon:phase} 相位穿墙而过",
    "螺旋向内：最外圈先亮",
    "三口钟：从下方逐一敲响",
    "其他球仍在飞行时，接住一颗回球",
    "沿着中继线绕过空旷的中心",
    "光在消退：趁还来得及熟悉场地",
    "黑暗中，球和挡板带来光亮",
    "萤火：核心在黑暗中也会发光",
    "用挡板的光扫过海岸",
    "球越多，光越多：{icon:multi} 多球",
    "深空：每个微弱的光点都是砖块",
    "连接星星：明亮的是核心",
    "闸门随节拍淡去：等待空隙",
    "滴答，滴答：闸门在计时",
    "日冕随节拍开启：打进去",
    "幽灵闸门不惧爆炸：抓准火花的时机",
    "脉冲星：节拍急促，手要更快",
    "快门只开片刻：做好准备",
    "一半在阴影中：带闸门的一侧掌控节奏",
    "趁月亮坚实时点燃太阳",
    "风只朝一个方向吹：顺风直达核心",
    "光幕：用 {icon:multi} 多球扫净",
    "每条飘带都系着一道闸门：两半都要剪断",
    "漫长的夜：凭你携带的光瞄准",
    "穿过大门，直上玫瑰窗",
    "万物同时发生：留意核心",
    "闸门变实时，打击圆环",
    "最后一圈：让每个缺口都有价值",
];
