//! Traditional Chinese, as used in Taiwan (滑鼠, 螢幕, 儲存). Full-width
//! punctuation; a space separates Chinese from Latin letters and numbers.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "擊碎宇宙",
        ContinueJourney => "繼續旅程",
        NewJourney => "新的旅程",
        SectorSelect => "選擇星區",
        ContinueDetail => "{0} · {1}",
        StatMedals => "獎章",
        StatBest => "最高分",
        ActionServe => "發球",
        ActionRelease => "釋放",
        ActionSelect => "選擇",
        ActionResume => "繼續",
        ActionBack => "返回",
        Fullscreen => "全螢幕",
        SectorsHeading => "星區",
        PracticeNote => "練習不會影響你的旅程",
        MedalClear => "通關",
        MedalClean => "無損",
        MedalSwift => "神速",
        PlaySector => "開始星區 {0}",
        UnlockHint => "完成星區 {0} 即可解鎖",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · 星區 {1}",
        Paused => "已暫停",
        RetrySector => "重試本星區",
        MainMenu => "主選單",
        JourneyComplete => "旅程完成",
        OneMoreOrbit => "再來一圈？",
        StatPoints => "得分",
        SectorClear => "星區完成",
        StatTime => "時間",
        StatBonus => "獎勵",
        StatChain => "連擊",
        ExtraLife => "篇章完成 · +1 生命",
        NextSector => "下一個星區",
        BackToSectors => "返回星區",
        SaveFailed => "無法儲存進度",
        PerfTitle => "效能 / CPU",
        HelpResume => "從暫停處繼續",
        HelpRetry => "從本星區檢查點重新開始",
        HelpMainMenu => "旅程已儲存",
        HelpSectors => "練習任一已開放的星區",
        HelpNewJourney => "從星區 01 重新開始 · 獎章保留",
        Settings => "設定",
        HelpSettings => "音效、顯示、語言",
        SettingSound => "音效",
        SettingVolume => "音量",
        SettingDisplay => "顯示",
        SettingLanguage => "語言",
        DisplayWindow => "視窗",
        LanguageSystem => "跟隨系統",
        ActionAdjust => "調整",
        SettingEffects => "特效",
        SettingContrast => "對比度",
        LookStandard => "標準",
        EffectsReduced => "減弱",
        ContrastHigh => "高",
        KeySpace => "空白鍵",
        KeyEsc => "Esc",
        SectorsOf => "{0} / {1} 個星區",
        TargetBest => "{0} · 最佳 {1}",
        LifeGained => "+1 生命",
        PresenceMenus => "在選單中",
        PresenceJourney => "星區 {0} · {1}",
        PresencePractice => "正在練習星區 {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "破曉",
            Chapter::Morning => "清晨",
            Chapter::Zenith => "天頂",
            Chapter::GoldenHour => "黃金時刻",
            Chapter::Afterlight => "暮光",
            Chapter::BlueHour => "藍調時刻",
            Chapter::Eclipse => "日蝕",
            Chapter::Aurora => "極光",
        },
        PowerName(p) => match p {
            Power::Wide => "加寬",
            Power::Slow => "減速",
            Power::Multi => "多球",
            Power::Anchor => "錨定",
            Power::Phase => "相位",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("繼續"),
        UnlockHint => Some("未解鎖"),
        RetrySector => Some("重試"),
        MainMenu => Some("選單"),
        NewJourney => Some("新旅程"),
        SectorSelect => Some("星區"),
        NextSector => Some("下一個"),
        BackToSectors => Some("星區"),
        Settings => Some("設定"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("繼續"),
        PlaySector => Some("開始 {0}"),
        ActionServe => Some("發球"),
        ActionRelease => Some("釋放"),
        ActionSelect => Some("選擇"),
        ActionBack => Some("返回"),
        ActionAdjust => Some("調整"),
        SettingEffects => Some("特效"),
        SettingContrast => Some("對比度"),
        LookStandard => Some("標準"),
        EffectsReduced => Some("減弱"),
        ContrastHigh => Some("高"),
        StatBest => Some("最高"),
        StatMedals => Some("獎章"),
        SectorsHeading => Some("星區"),
        SaveFailed => Some("未儲存"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("空白"),
        HelpResume => Some("返回遊戲"),
        HelpRetry => Some("從檢查點重來"),
        HelpMainMenu => Some("旅程已儲存"),
        HelpSectors => Some("練習星區"),
        HelpNewJourney => Some("從星區 01 開始"),
        HelpSettings => Some("音效、顯示"),
        SettingSound => Some("音效"),
        SettingVolume => Some("音量"),
        SettingDisplay => Some("顯示"),
        SettingLanguage => Some("語言"),
        DisplayWindow => Some("視窗"),
        Fullscreen => Some("全螢幕"),
        LanguageSystem => Some("系統"),
        ExtraLife => Some("+1 生命"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("星區 {1}"),
        JourneyComplete => Some("完成"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "晨光",
    "漂流",
    "地平線",
    "微光",
    "雲雀",
    "燈籠",
    "潮水",
    "日出",
    "衛星",
    "露點",
    "光圈",
    "迴廊",
    "拱心石",
    "日晷",
    "針孔",
    "風玫瑰",
    "滑流",
    "燈絲",
    "子午線",
    "疊瀑",
    "交錯",
    "曲折",
    "至日",
    "共振",
    "稜鏡",
    "蜂巢",
    "浪花",
    "暗流",
    "豐收",
    "萬花筒",
    "掛毯",
    "長影",
    "餘暉",
    "蛹",
    "晶洞",
    "視差",
    "堡壘",
    "鸚鵡螺",
    "晚禱",
    "超新星",
    "月出",
    "薄暮",
    "燈火",
    "螢火",
    "燈塔",
    "夜曲",
    "深空",
    "星座",
    "半影",
    "節拍器",
    "日冕",
    "朔望",
    "脈衝星",
    "快門",
    "本影",
    "全蝕",
    "太陽風",
    "北極光",
    "飄帶",
    "極夜",
    "大教堂",
    "粼光",
    "奇點",
    "歸途",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "晨光",
    "漂流",
    "地平線",
    "微光",
    "雲雀",
    "燈籠",
    "潮水",
    "日出",
    "衛星",
    "露點",
    "光圈",
    "迴廊",
    "拱心石",
    "日晷",
    "針孔",
    "風玫瑰",
    "滑流",
    "燈絲",
    "子午線",
    "疊瀑",
    "交錯",
    "曲折",
    "至日",
    "共振",
    "稜鏡",
    "蜂巢",
    "浪花",
    "暗流",
    "豐收",
    "萬花筒",
    "掛毯",
    "長影",
    "餘暉",
    "蛹",
    "晶洞",
    "視差",
    "堡壘",
    "鸚鵡螺",
    "晚禱",
    "超新星",
    "月出",
    "薄暮",
    "燈火",
    "螢火",
    "燈塔",
    "夜曲",
    "深空",
    "星座",
    "半影",
    "節拍器",
    "日冕",
    "朔望",
    "脈衝星",
    "快門",
    "本影",
    "全蝕",
    "太陽風",
    "北極光",
    "飄帶",
    "極夜",
    "大教堂",
    "粼光",
    "奇點",
    "歸途",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} 加寬：接住掉落的膠囊",
    "{icon:slow} 減速：接住它，球就會慢下來",
    "操控：擋板邊緣會把球打向兩側",
    "零星火花：逐個追擊",
    "把球沿敞開的兩翼打上去",
    "從下方清除每盞燈籠",
    "順勢而行：藉側牆反彈",
    "從下方一排排鑿掉太陽",
    "{icon:anchor} 錨定：接住球，瞄準，然後釋放",
    "裝甲磚塊要打兩下：留意邊緣",
    "{icon:anchor} 瞄準牆上的缺口",
    "只有一道門：把球送進庭院",
    "打掉拱心石，拱門就開了",
    "看準角度：每道影子都是一次擊球",
    "{icon:anchor} 一個窄小的針孔：按住，瞄準，釋放",
    "每個方向都通向核心",
    "琥珀核心：每次爆炸會波及相鄰四塊",
    "觸碰燈絲任意位置：兩端同時燃燒",
    "沿子午線把場地一分為二",
    "從任一端引爆疊瀑",
    "在兩條中繼線之間打開通路",
    "三條中繼線：各一次乾淨的擊球",
    "圓環整體燃燒：找條路打到邊緣",
    "相鄰核心會傳遞連鎖反應",
    "{icon:multi} 多球：三顆球，一個缺口",
    "每格一個核心：逐個擊破",
    "浪花四濺：放出三顆球",
    "攻入裝甲後方的空腔",
    "滿場磚塊：{icon:multi} 多球清得很快",
    "到處是鏡子：先破一側，再破它的孿生",
    "抽出一根線，織物便散開",
    "擊穿地面，點燃長引線",
    "{icon:phase} 相位：連續三次穿透磚塊，無需反彈",
    "{icon:phase} 相位：穿過外殼直達核心",
    "敲開晶洞，晶體隨即亮起",
    "擊穿外殼，再點燃內部通路",
    "從閘門進入，或用 {icon:phase} 相位穿牆而過",
    "螺旋向內：最外圈先亮",
    "三口鐘：從下方逐一敲響",
    "其他球仍在飛行時，接住一顆回球",
    "沿著中繼線繞過空曠的中心",
    "光在消退：趁還來得及熟悉場地",
    "黑暗中，球和擋板帶來光亮",
    "螢火：核心在黑暗中也會發光",
    "用擋板的光掃過海岸",
    "球越多，光越多：{icon:multi} 多球",
    "深空：每個微弱的光點都是磚塊",
    "連接星星：明亮的是核心",
    "閘門隨節拍淡去：等待空隙",
    "滴答，滴答：閘門在計時",
    "日冕隨節拍開啟：打進去",
    "幽靈閘門不懼爆炸：抓準火花的時機",
    "脈衝星：節拍急促，手要更快",
    "快門只開片刻：做好準備",
    "一半在陰影中：帶閘門的一側掌控節奏",
    "趁月亮堅實時點燃太陽",
    "風只朝一個方向吹：順風直達核心",
    "光幕：用 {icon:multi} 多球掃淨",
    "每條飄帶都繫著一道閘門：兩半都要剪斷",
    "漫長的夜：憑你攜帶的光瞄準",
    "穿過大門，直上玫瑰窗",
    "萬物同時發生：留意核心",
    "閘門變實時，打擊圓環",
    "最後一圈：讓每個缺口都有價值",
];
