//! Traditional Chinese, as used in Taiwan (滑鼠, 螢幕, 儲存). Full-width
//! punctuation; a space separates Chinese from Latin letters and numbers.
use crate::TextId::{self, *};
use ark::{
    Power,
    sectors::{Chapter, SECTOR_COUNT},
};

pub(super) fn text(id: TextId) -> &'static str {
    match id {
        Tagline => "擊碎宇宙",
        ContinueJourney => "繼續旅程",
        NewJourney => "新的旅程",
        SectorSelect => "選擇星區",
        ContinueDetail => "{0} · {1}",
        StatMedals => "獎章",
        StatBest => "最高分",
        ActionServe => "發球",
        ActionRelease => "釋放",
        ActionSelect => "選擇",
        ActionResume => "繼續",
        ActionBack => "返回",
        Fullscreen => "全螢幕",
        SectorsHeading => "星區",
        PracticeNote => "練習不會影響你的旅程",
        MedalClear => "通關",
        MedalClean => "無損",
        MedalSwift => "神速",
        PlaySector => "開始星區 {0}",
        UnlockHint => "完成星區 {0} 即可解鎖",
        Plus => "+{0}",
        ReadyEyebrow => "{0} · 星區 {1}",
        Paused => "已暫停",
        RetrySector => "重試本星區",
        MainMenu => "主選單",
        JourneyComplete => "旅程完成",
        OneMoreOrbit => "再來一圈？",
        StatPoints => "得分",
        SectorClear => "星區完成",
        StatTime => "時間",
        StatBonus => "獎勵",
        StatChain => "連擊",
        ExtraLife => "篇章完成 · +1 生命",
        NextSector => "下一個星區",
        BackToSectors => "返回星區",
        SaveFailed => "無法儲存進度",
        PerfTitle => "效能 / CPU",
        HelpResume => "從暫停處繼續",
        HelpRetry => "從本星區檢查點重新開始",
        HelpMainMenu => "旅程已儲存",
        HelpSectors => "練習任一已開放的星區",
        HelpNewJourney => "從星區 01 重新開始 · 獎章保留",
        Settings => "設定",
        HelpSettings => "音效、顯示、語言",
        SettingSound => "音效",
        SettingVolume => "音量",
        SettingDisplay => "顯示",
        SettingLanguage => "語言",
        DisplayWindow => "視窗",
        LanguageSystem => "跟隨系統",
        ActionAdjust => "調整",
        SettingEffects => "特效",
        SettingContrast => "對比度",
        LookStandard => "標準",
        EffectsReduced => "減弱",
        ContrastHigh => "高",
        KeySpace => "空白鍵",
        KeyEsc => "Esc",
        SectorsOf => "{0} / {1} 個星區",
        TargetBest => "{0} · 最佳 {1}",
        LifeGained => "+1 生命",
        PresenceMenus => "在選單中",
        PresenceJourney => "星區 {0} · {1}",
        PresencePractice => "正在練習星區 {0} · {1}",
        SectorName(s) => NAMES[s.index()],
        SectorTip(s) => TIPS[s.index()],
        ChapterName(c) => match c {
            Chapter::Daybreak => "破曉",
            Chapter::BlueHour => "藍調時刻",
            Chapter::Afterlight => "暮光",
        },
        PowerName(p) => match p {
            Power::Wide => "加寬",
            Power::Slow => "減速",
            Power::Multi => "多球",
            Power::Anchor => "錨定",
            Power::Phase => "相位",
        },
    }
}

pub(super) fn short(id: TextId) -> Option<&'static str> {
    match id {
        ContinueDetail => Some("{0}"),
        ContinueJourney => Some("繼續"),
        UnlockHint => Some("未解鎖"),
        RetrySector => Some("重試"),
        MainMenu => Some("選單"),
        NewJourney => Some("新旅程"),
        SectorSelect => Some("星區"),
        NextSector => Some("下一個"),
        BackToSectors => Some("星區"),
        Settings => Some("設定"),
        SectorsOf => Some("{0}/{1}"),
        TargetBest => Some("{0}"),
        LifeGained => Some("+1"),
        ActionResume => Some("繼續"),
        PlaySector => Some("開始 {0}"),
        ActionServe => Some("發球"),
        ActionRelease => Some("釋放"),
        ActionSelect => Some("選擇"),
        ActionBack => Some("返回"),
        ActionAdjust => Some("調整"),
        SettingEffects => Some("特效"),
        SettingContrast => Some("對比度"),
        LookStandard => Some("標準"),
        EffectsReduced => Some("減弱"),
        ContrastHigh => Some("高"),
        StatBest => Some("最高"),
        StatMedals => Some("獎章"),
        SectorsHeading => Some("星區"),
        SaveFailed => Some("未儲存"),
        KeyEsc => Some("Esc"),
        KeySpace => Some("空白"),
        HelpResume => Some("返回遊戲"),
        HelpRetry => Some("從檢查點重來"),
        HelpMainMenu => Some("旅程已儲存"),
        HelpSectors => Some("練習星區"),
        HelpNewJourney => Some("從星區 01 開始"),
        HelpSettings => Some("音效、顯示"),
        SettingSound => Some("音效"),
        SettingVolume => Some("音量"),
        SettingDisplay => Some("顯示"),
        SettingLanguage => Some("語言"),
        DisplayWindow => Some("視窗"),
        Fullscreen => Some("全螢幕"),
        LanguageSystem => Some("系統"),
        ExtraLife => Some("+1 生命"),
        SectorName(s) => Some(SHORT_NAMES[s.index()]),
        ReadyEyebrow => Some("星區 {1}"),
        JourneyComplete => Some("完成"),
        _ => None,
    }
}

const NAMES: [&str; SECTOR_COUNT] = [
    "晨光",
    "衛星",
    "滑流",
    "共振",
    "稜鏡",
    "交錯",
    "暗流",
    "月出",
    "餘暉",
    "視差",
    "超新星",
    "歸途",
];

/// Sector names for narrow places: the band and a Compact page.
const SHORT_NAMES: [&str; SECTOR_COUNT] = [
    "晨光",
    "衛星",
    "滑流",
    "共振",
    "稜鏡",
    "交錯",
    "暗流",
    "月出",
    "餘暉",
    "視差",
    "超新星",
    "歸途",
];

const TIPS: [&str; SECTOR_COUNT] = [
    "{icon:wide} 加寬、{icon:slow} 減速：接住落下的膠囊",
    "{icon:anchor} 錨定：接住球，瞄準，然後釋放",
    "琥珀核心：每次爆炸會波及相鄰四塊",
    "相鄰核心會傳遞連鎖反應",
    "{icon:multi} 多球：三顆球，一個缺口",
    "在兩條中繼線之間打開通路",
    "攻入裝甲後方的空腔",
    "沿著中繼線繞過空曠的中心",
    "{icon:phase} 相位：連續三次穿透磚塊，無需反彈",
    "擊穿外殼，再點燃內部通路",
    "其他球仍在飛行時，接住一顆回球",
    "最後一圈：讓每個缺口都有價值",
];
